### ISSUE TITLE
Dataset names not uppercased in zowe-install-xmem.sh

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1009]
**Describe the bug**
The script `zowe-install-xmem.sh` does not fold lowercase letters to uppercase.  Lowercase is tolerated in TSO commands, so the user could reasonably expect uppercasing in a DSN where this is required, but the script does not do this, so lowercase persists which gives a JCL error.

**To Reproduce**
`scripts/utils: >zowe-install-xmem.sh zoe.smpe zoe.ZIS.SZISLOAD zoe.zis.sissamp`
```
XXSTEPLIB  DD   DSNAME=zoe.ZIS.SZISLOAD,DISP=SHR       
XXPARMLIB  DD   DSNAME=zoe.smpe.SZWESAMP,DISP=SHR      
```

**Expected behavior**
All DSN text to be uppercased.

**Additional context**
Workaround:  Use all-uppercase in the parameters of `zowe-install-xmem.sh`

**Comment by Joe-Winchester** [comment]
Sounds like a good catch to fix @John-A-Davies   Are you able to work on this for 1.9 and create a PR ?  Tks
