### ISSUE TITLE
Zowe instance directory has no proper group ownership set

### ISSUE THREAD

**Issue by kiril-ibm** [zowe/zowe-install-packaging#1012]
It has to set newly created instance directory group ownership to ZWEADMIN

**Comment by kiril-ibm** [comment]
Any ETA on fixing that ?

**Comment by stevenhorsman** [comment]
@kiril-ibm - can we get more details please. What is going wrong?

**Comment by kiril-ibm** [comment]
1) Install Zowe
2) Check zowe-instance-dir ownership (OMVS in mycase)
3) As a result I am not able to start Zowe
4) Execute chgrp -R ZWEADMIN zowe-instance-dir
5) Zowe can be started

**Comment by stevenhorsman** [comment]
Thanks for the quick response. Can you do an ls -al on the instance-dir after install please? The script that creates it does a chmod -R 777 so I don't understand the 
>As a result I am not able to start Zowe bit

**Comment by kiril-ibm** [comment]
The issue looks fixed in ​1.8.0-staging-484-202002031746​39 . I am removing my workaround for now and will test it fully
