### ISSUE TITLE
install requires ZWESVUSR & ZWEADMIN to exist

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1014]
**Describe the bug**

zowe-install.sh expects that userid ZWESVUSR and ZWEADMIN are pre-defined. Install on any system but a primed one has issues because of this. 
Install has to be userid-agnostic. The only requirements it can demand are permits for the user doing the install. The need for knowledge about specific userid / group name does not arise until configuration time. You can't expect customer to find the ZWESECUR jcl somewhere in the install files and run it before the install is done.

Also, install expects that this ID/GID will own the Zowe install. This can NOT be mandated. Many sites use fixed userids, with elevated permits, for install, and those IDs own the install, all other have read/execute. 
Install removes read for other, which breaks all these customers. Product installs are expected to be 755. Security-sensitive stuff can get restricted permits and special owners, but this happens during customization.

**To Reproduce**
invoke zowe-install.sh

FSUM6541 id: invalid user name: "ZWESVUSR"                                                                                                                    
  Unable to display the group of userid ZWESVUSR                                                                                                              
  Run ZWESECUR jcl job to create the zowe userid ZWESVUSR.                                                                                                    
FSUM6541 id: invalid user name: "ZWESVUSR"                                                                                                                    
  userid ZWESVUSR is not a member of group ZWEADMIN                                                                                                           
  Run ZWESECUR jcl job to create the zowe userid ZWESVUSR in group ZWEADMIN.                                                                                  
FSUM6185 chgrp: group "ZWEADMIN" is unknown                                                                                                                   
  The current user does not have sufficient authority to change the group of /bld/zowe/bld/stage.                                                             
  A user who is part of group ZWEADMIN must run 'chgrp -R ZWEADMIN /bld/zowe/bld/stage'.                                                                      

**Expected behavior**

line 184-214 in zowe-install sh do not belong int he install script
# Verify that zowe userid and group exist   
...
#Give all directories -rw+x permission so they can be listed, ...
...
# If this step fails it is likely because the user running this script
...

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stevenhorsman** [comment]
So the behaviour that is *supposed* to happen is:
During the install:
- if ZWESVUSR & ZWEADMIN exist:
    - if the installing user is a member of ZWEADMIN:
          - We chgrp the runtime folder to ZWEADMIN and all is well
    - else (installing user isn't in ZWEADMIN):
          - We can't chgrp, so prompt the user to find someone who is a member to do it
- else if they don't exist:
   - we don't try and chgrp, but prompt the user to run ZWESECUR, then run the chgrp

@OnnoVdT - it sounds like this hasn't been implemented (or tested) properly, but does this flow work from your perspective, or have we missed something

**Comment by OnnoVdT** [comment]
In a nutshell, No, I don't think this will work.

SMPE and pax install should end up with the same result, and SMPE does not offer a way to do this querying and prompting. That would become manual steps documetned in the program directory (in the hope folks read that part).
SMPE will attempt to become UID 0 and just unpax the files holding the Zowe directories. Even though we technically can, we can not tell SMPE to restore the file ownership, as we do not know which UID/GID the customer will use for ZWESVUSR/ZWEADMIN. So everything SMPE lays down ends up being owned by UID 0 (or the UID of the installer if the UID 0 switch was not successful).

I think now that if we can get through issue https://github.com/zowe/zowe-install-packaging/issues/1015 (zlux requiring restricted permissions 550) there is no need to do all this mumbo-jumbo, and things can be installed as 755, without caring for actual owner/group. 

And to reiterate, many shops use a fixed, UID 0, userid for install work that is expected to own everything.

**Comment by OnnoVdT** [comment]
related to https://github.com/zowe/zowe-install-packaging/issues/1020 (Add user and group parameters to install/setup scripts )

**Comment by Joe-Winchester** [comment]
@OnnoVdT - If the install script doesn't do any chmod or chgrp, then when ZWESVSVR runs we will likely get unable to read, unable to stat, ... errors because the user ID of the ZWESVSVR task is unable to get at the USS files and folders.   Would you rather that we let this happen and provide doc help for how to fix and diagnose this rather than attempt any chmod or chgrp ?     Also for the keystore_directory which holds the public key we wanted to ensure its permissions were not too open, and I know the cross memory server makes some permission checks to ensure USS permissions on certain folders aren't too wide open otherwise it exits.

**Comment by OnnoVdT** [comment]
If the ***install*** is done with 755 for everything, owner, group, and everybody else can read & execute/list, so there is no need to chown/chgrp. 
The keystore directory is a different story, that one should indeed be tied down, which is one of the reasons this is not a install task but a customization task. There is no problem with something created during customization to have a custom permission mask.
For ZSS, it requires that users have permit to RACF profile ZWES.IS, so permits are tied to a userid. There is no reason to verify whether somebody without that permit can read/execute the code that attempts to talk to ZSS. 
Remember, anyone can install, so anyone can get a copy of that code where they are not locked out. And we have the source out in the open, so anybody can create their own version of the code, with or without alterations.
