### ISSUE TITLE
zowe-install.sh removes write permit for owner, breaking apply of service

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1015]
**Describe the bug**

zowe-install.sh removes owner write permits for some of the files it installs. This implies that future product service must be applied by a UID 0 userid or it will fail due to lack of permits.

**To Reproduce**
edit zowe-install.sh 
go to line 216
chmod -R 550 ${ZOWE_ROOT_DIR}/components/app-server/share/zlux-app-server/defaults

**Expected behavior**

Product install is supposed to lay things down with 755. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stevenhorsman** [comment]
Hey Onno, I share your concerns about this, but we've been told in the past that zlux won't start without certain locked down permissions. When I asked how this related to updates I was told that we could chmod first, or (the policy I took for convenience updates) to move the existing runtime as a backup. I'm assuming that these strategies won't work for SMP/E, so I guess we'll need to experiment with removing the o+w restriction after 1.8 is out and see what any side effects are. Does that sound reasonable?

**Comment by OnnoVdT** [comment]
sounds reasonable. I put it on FEb 4 to keep it on the radar

**Comment by OnnoVdT** [comment]
Note that SMPE lays everything down with 755, there is no 550.

**Comment by OnnoVdT** [comment]
FYI. I tried SMPE build with the chmod 755 line at the end of smpe-install.sh commented out, and the build fails. The split logic is designed to move parts from the installed product to the staging directories for the different pax files, and that fails when the owner lacks write permit. Move is used to avoid complex exclusion logic required for copy.
If we cannot get rid of the chmod 550 in zowe-install.sh we will have to add it to smpe-split.sh (which I rather avoid).

**Comment by stevenhorsman** [comment]
This should have been addressed in #1028
