### ISSUE TITLE
zowe-install.sh continues after copy failure

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1016]
**Describe the bug**

stderr of install shows 
cp: /bld/zowe/bld/extract/zowe-1.8.0/scripts/configure/.: EDC5129I No such file or directory. (errno2=0x0594003D)                                             

but install claims it completed successfully. 

**To Reproduce**

**Expected behavior**

Install should fail on any error or we can't trust our own build.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stevenhorsman** [comment]
Looks like the configure directory was deleted without the associated code

**Comment by stevenhorsman** [comment]
Should be addressed in #1021 - the configure directory was deleted, but not the code that cp'd it
