### ISSUE TITLE
don't do pax per component in SMPE build

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1017]
*Customer content*

**Is your feature request related to a problem? Please describe.**

smpe-split.sh was updated to create a pax file per component, plus additional pax files for large api-mediation jars. In the past, most explorers were bundled in a single pax.

**Describe the solution you'd like**

By creating a pax file per component, even the small ones, we no longer know beforehand how much pax files smpe-split.sh will create. So when a new component is added, we now require that SMPMCS.txt is updated as well to avoid a build failure (pax not defined in MCS). 
If we go back to the old scheme of creating a separate pax for the big files and keep all the rest of the components together, we can add small to reasonably sized components without SMPMCS changes.
I propose a pax for
- components/app-server (31%)
- 1 per large components/api-mediation/...jar (16%,15%,14%,16%)
- 1 per api (9%,9%)
- all other files (+/-3%)
(8 in total)

**Describe alternatives you've considered**

**Additional context**

ZWEPAX01 has 125701632 bytes (119.0 MB, 148.0 CYL), 31.0% of max PTF size
components/app-server
ZWEPAX02 has 4193280 bytes (3.0 MB, 3.0 CYL), 1.0% of max PTF size
components/explorer-jes
ZWEPAX03 has 4161024 bytes (3.0 MB, 3.0 CYL), 1.0% of max PTF size
components/explorer-mvs
ZWEPAX04 has 4257792 bytes (4.0 MB, 5.0 CYL), 1.0% of max PTF size
components/explorer-uss
ZWEPAX05 has 37868544 bytes (36.0 MB, 45.0 CYL), 9.0% of max PTF size
components/files-api
ZWEPAX06 has 36191232 bytes (34.0 MB, 42.0 CYL), 9.0% of max PTF size
components/jobs-api
ZWEPAX07 has 66221568 bytes (63.0 MB, 78.0 CYL), 16.0% of max PTF size
components/api-mediation/api-catalog-services.jar
ZWEPAX08 has 62705664 bytes (59.0 MB, 73.0 CYL), 15.0% of max PTF size
components/api-mediation/discoverable-client.jar
ZWEPAX09 has 57770496 bytes (55.0 MB, 68.0 CYL), 14.0% of max PTF size
components/api-mediation/discovery-service.jar
ZWEPAX10 has 66931200 bytes (63.0 MB, 78.0 CYL), 16.0% of max PTF size
components/api-mediation/gateway-service.jar
ZWEPAX11 has 1387008 bytes (1.0 MB, 1.0 CYL), 1.0% of max PTF size
bin
components
manifest.json
scripts

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by OnnoVdT** [comment]
@stevenhorsman If we decide to implement this then it MUST be done before we ship or first drop to Shopz for validation. Once that happens no SMPE structure changes (new or removed members/pax files) are allowed anymore.

**Comment by stevenhorsman** [comment]
Hey Onno, it looks like I've messed up here - I saw that before the componentisation was done (and the components were in the top level folder) they were all called out and separated, so I tried to continue that, but it seems like we need the hard-codedness, so I think your proposal sounds the best plan.

**Comment by stevenhorsman** [comment]
@OnnoVdT I've created a new milestone for the shopz validation (4th Feb), can this be planned for that, or does it need to be in 1.8?

**Comment by OnnoVdT** [comment]
moved it to feb 4, I didn't know about that one and picked 1.8 to make sure it got your attention

**Comment by OnnoVdT** [comment]
Steven, I already did the update to the split script in PR https://github.com/zowe/zowe-install-packaging/pull/1025 so I can test Shopz compatibility locally with something that is close to the Feb 4 release.
