### ISSUE TITLE
Review all our uses of opercmd and update the docs accordingly

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#1026]
We currently have a bunch of commands (including zowe-start.sh) that utilise opercmd.
This has a dependency on SDSF, which we can't rely on, so we need to review all uses and either remove them, or document alternatives.

**Comment by Tam-Lin** [comment]
Could I suggest using the zoau opercmd instead?  It doesn't rely on SDSF.

**Comment by Shobhajayanna** [comment]
Can we add it in Zowe docs as a requirement for zowe installation?

**Comment by 1000TurquoisePogs** [comment]
Closing in favor of duplicates https://github.com/zowe/zowe-install-packaging/issues/3704 and https://github.com/zowe/zowe-install-packaging/issues/3477
