### ISSUE TITLE
Output results of component validate.sh scripts to STDERR for easy identification

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#1030]
When looking through logs if can be hard to find which lines are causing problems with components being able to launch.

**Describe the solution you'd like**
For components that are using the validate.sh scripts have a way that they can write lines to STDERR so that we can tell users to check STDERR for component launch problems

**Comment by stevenhorsman** [comment]
Apparently I implemented this 16 days ago: https://github.com/zowe/zowe-install-packaging/commit/33e6d076b76adaeb3a17bddf3e8cab630c531ebc#diff-905ad0cb5615e161023ceefe9a36d1b4
