### ISSUE TITLE
TSS & multi-user address spaces

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1039]
*Customer content*

**Is your feature request related to a problem? Please describe.**

The Top Secret specialists added this block to ZWESECUR
```
If any of these started tasks are multiusers address spaces
a TSS FACILITY needs to be defined and assigned to the started
and should not be using the STC FACILITY . The all acids signing
on to the started tasks will need to be authorized to the
FACILITY.

Create FACILITY example:
In the TSSPARMS add the following lines to create
the new FACILITY.

FACILITY(USER11=NAME=ZOWE)
FACILITY(ZOWE=MODE=FAIL)
FACILITY(ZOWE=RES)

To assign the FACILITY to the started task issue the following
command:

TSS ADD(started_task_acid) MASTFAC(ZOWE)

To authorize a user to signon to the FACILITY, issues the
following command.

TSS ADD(user_acid) FAC(ZOWE)
```

Since Zowe server and ZMEM server (ZSS) has BPX.SERVER permit to impersonate a user, I think both qualify to what is defind in this block. 

**Describe the solution you'd like**

If TSS specialists agree with this conclusion, the sample commands should be updated so that the setup described here is the default.

**Describe alternatives you've considered**

Leave ZWESECUR as is (just move the block out of dataset protection and into the started task section)

**Additional context**

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by vit-tomica** [comment]
I think this block just adds an additional security that TSS provides for multi-user address spaces. So access to the multi-user address space (zowe) can be controlled for individual userids. The block also describes to add a new facility by a manual change to a TSS parm file. If that's the case then I think the block should be removed from ZWESECUR completely and added to documentation.
I'll check with TSS experts.

**Comment by stevenhorsman** [comment]
@vit-tomica - Did you hear back from the TSS experts? Is there anything we need to do for this issue?

**Comment by vit-tomica** [comment]
@stevenhorsman not yet (a reminder sent on Monday). I've made some research regarding this. 
I think the original Onno's concern is not valid anymore as it was clarified that xmem server that runs under ZWESIUSR doesn't not do impersonation and so it's not multi-user address space. So this applies only to ZWESVUSR as ZSS runs under the ZWESVUSR userid. 

I believe the command block should be deleted from the ZWESECUR and moved somewhere in Zowe desktop configuration doc section as a Top Secret specific setup. 
A new TSS FACILITY can be defined dynamically but such change to TSS can be temporary. Moreover, the command syntax and description in the block indicates manual effort. More details [here](https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/security/ca-top-secret-for-z-os/16-0/using/protecting-facilities/how-to-perform-facility-matrix-table-administration.html#concept.dita_5f62bf0075b62247803308ce33669e195125160c_DetermineWheretoStoreFacilityMatrixEntries)

**Comment by stevenhorsman** [comment]
Discussed on scrum - I think we reached agreement that it should be moved out into documentation. Need to understand if it is optional, mandatory, or just recommendation

**Comment by vit-tomica** [comment]
Answer from a TSS expert:
"Creating a FACILITY and attaching it to the acid that brings up a multi user address space is something that needs to be done not just for ZWESECUR but for any address space where multiple users will be signing on like CICS, TCPIP, FTP, DATACOM, DB2, etc…"

+ knowledge base article
https://ca-broadcom.wolkenservicedesk.com/external/article?articleId=27209&_ga=2.250598402.565039485.1580747450-236160232.1576001374

**Comment by vit-tomica** [comment]
Fixed.
