### ISSUE TITLE
Check zss can UPDATE BPX.SERVER+BPX.DAEMON

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1048]
*Customer content*

-- for discussion --

**Is your feature request related to a problem? Please describe.**
When the File Editor is used, it requires that zss, which runs under ZWESVSTC, have access to BPX.DAEMON and BPX.SERVER.  The File Editor is one of the few apps that requires such access.  The ZWESECUR job should set ZWESVUSR with UPDATE access to those BPX.* profiles.  

**Describe the solution you'd like**
A File Editor test that verifies this access.

**Describe alternatives you've considered**
Merely verify that the SAF access is correct.

**Additional context**

These SAF setttings were done incorrectly initially (now fixed).  

*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** zss user,  
**I want** to edit a file 
**so that** I am sure I can access BPX profiles

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by 1000TurquoisePogs** [comment]
Accomplished
