### ISSUE TITLE
Zowe STCs don't have sub-component IDs in their names

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1049]
**Describe the bug**
The STC names of the Zowe server should contain an ID for sub-component, as per this list
```
A subcomponent will be one of the following values:
• AC - API ML Catalog
• AD - API ML Discovery Service
```
... etc

But this is not true in recent builds.  (Estimated last seen OK around 15 Jan)

**To Reproduce**
1. Install zowe with all defaults
2. start zowe
3. view active jobs in SDSF

**Expected behavior**
All STCs should have the 2-letter ID of its component

**Screenshots**
Here is the result of a build on or before 28 Jan:
```
SDSF DA S0W1     S0W1     PAG  0  CPU/L    13/***      LINE 1-18 (18) 
COMMAND INPUT ===>                                            SCROLL =
NP   JOBNAME  StepName ProcStep JobID    Owner    C Pos DP Real Paging
     ZWE1SV   ZWE1SV   ZOWESTEP STC03210 ZWESVUSR   LO  FF  335   0.00
     ZWE1SV1  *OMVSEX           STC03217 ZWESVUSR   LO  FF  25T   0.00
     ZWE1SV1  STEP1             STC03176 ZWESVUSR   LO  FF  465   0.00
     ZWE1SV2  STEP1             STC03218 ZWESVUSR   LO  FF 2454   0.00
     ZWE1SV2  STEP1             STC03219 ZWESVUSR   LO  FF  31T   0.00
     ZWE1SV2  *OMVSEX           STC03215 ZWESVUSR   LO  FF  25T   0.00
     ZWE1SV3  *OMVSEX           STC03212 ZWESVUSR   LO  FF  24T   0.00
     ZWE1SV3  *OMVSEX           STC03097 ZWESVUSR   LO  FF  37T   0.00
     ZWE1SV3  STEP1             STC03141 ZWESVUSR   LO  FF  516   0.00
     ZWE1SV4  STEP1             STC03177 ZWESVUSR   LO  FF  449   0.00
     ZWE1SV4  *OMVSEX           STC03220 ZWESVUSR   LO  FF 2506   0.00
     ZWE1SV5  *OMVSEX           STC03089 ZWESVUSR   IN  F6  73T   0.00
     ZWE1SV6  *OMVSEX           STC03138 ZWESVUSR   IN  F6  79T   0.00
     ZWE1SV6  *OMVSEX           STC03211 ZWESVUSR   IN  F6  67T   0.00
     ZWE1SV7  STEP1             STC03214 ZWESVUSR   IN  F6 3292   0.00
     ZWE1SV7  *OMVSEX           STC03088 ZWESVUSR   IN  F6  66T   0.00
     ZWE1SV7  *OMVSEX           STC03213 ZWESVUSR   IN  F6  66T   0.00
     ZWE1SV8  STEP1             STC03216 ZWESVUSR   LO  FF 2541   0.00
```
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
None.

**Comment by John-A-Davies** [comment]
Build `zowe-smpe-1.8.0-staging-463-20200128112852` had this problem.

**Comment by Joe-Winchester** [comment]
For successful assignment of the address space name the user ID ZWESVUSR needs to have BPX.JOBNAME READ access
```
SETROPTS CLASSACT(FACILITY) RACLIST(FACILITY)
PERMIT BPX.JOBNAME CLASS(FACILITY) ID(ZWESVUSR) ACCESS(READ)
SETROPTS RACLIST(FACILITY) REFRESH
```
https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#prerequisites

This should be added to ZWESECUR

**Comment by stevenhorsman** [comment]
Note - the ui components are missing the BPX_JOBNAME command - https://github.com/zowe/zlux/issues/393 raised to cover this

**Comment by John-A-Davies** [comment]
@vit-tomica 
TOPSECRET and ACF2 will need these changes too, and also the undo of them, in ZWENOSEC.

**Comment by vit-tomica** [comment]
The BPX.JOBNAME READ access has already been added for TSS and ACF2 in the ZWESECUR jcl as well.

Regarding ZWENOSEC, I opened a new issue https://github.com/zowe/zowe-install-packaging/issues/1112. The ZWENOSEC needs to be updated with TSS and ACF2 commands completely.

I think this issue can be closed then.
