### ISSUE TITLE
Provide a docker container that for Zowe that can connect to a z/OS zss and z/OSMF

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#1057]
*Customer content*

**Is your feature request related to a problem? Please describe.**
Extenders have asked for the ability to have a docker container distribution of Zowe that can run off z/OS.  This could then be run on ZCX, or a laptop, or anywhere else supporting docker images.

**Describe the solution you'd like**
Provide a way that Zowe on z/OS can be started so that just zss and cross memory are active.
Provide a docker image that can be installed and run on a machine that has docker, including ZCX on ao mainframe, with the ability to connect to the z/OS components of Zowe runtime stack (zss and z/OSMF).

**Additional context**
This allows for tailor fit pricing and other cost benefits of running workload off z/OS, as well as a way for developers to test the volatile part of Zowe (APIML, Web Desktop, ...) away from z/OS

---

**Comment by 1000TurquoisePogs** [comment]
Is this needed since https://github.com/zowe/zowe-install-packaging/issues/793 exists?

**Comment by jackjia-ibm** [comment]
The containerization work is progressed in 2 threads:
- tech preview with single Docker image
- the coming Kubernetes and docker-compose support based on per-component images.
Think we can merge into #793 with detail implementation tasks.
