### ISSUE TITLE
zowe-install.sh should prime the environment on startup

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1059]
*Customer content*

**Is your feature request related to a problem? Please describe.**

At startup, zowe-isntall.sh does not tailor its environment, which means we rely on whatever was active when we were called.

**Describe the solution you'd like**

Do some basic setup to ensure we can rely on some things.
```
export _EDC_ADD_ERRNO2=1                        # show details on error
unset ENV             # just in case, as it can cause unexpected output
umask 0022                                       # similar to chmod 755
```
**Describe alternatives you've considered**

**Additional context**

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by stevenhorsman** [comment]
@OnnoVdT - I guess that unmask is just for zowe-install.sh, but are the other 2 applicable to the create instance directory and run-zowe scripts?

**Comment by OnnoVdT** [comment]
I would say umask also applies to create instance dir, since we are creating a new path. 
For errno and env, I feel it's good practice to add them to any script. Getting some details when there is an error is worth gold when it happens. And the env envvar has bitten me a few times in the past (it can point to a script that does an echo, and then that echo is in the output of each new shell that is started, a real pain when you're parsing its output in a pipe).
