### ISSUE TITLE
Add Zowe Hands-On Tutorial to zowe.org

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#108]

**Comment by Tbr00ksy** [comment]
[Zowe MTM Hand-on Tutorial v2.pptx](https://github.com/zowe/zowe-install-packaging/files/2484857/Zowe.MTM.Hand-on.Tutorial.v2.pptx)
Hi Jack, I'm posting the reviewed copy here for your convenience.

**Comment by nannanli** [comment]
@Tbr00ksy Hi Tim, just a quick question about this new tutorial link. 

The Zowe doc site also contain some tutorials. At first I thought that all tutorials are now moved to this Z Ecosystem site but by reading more in the deck, I found this tutorial is limited in use scenario: 
- It's for people who don't have their own z/OS instance but want to try to extend Zowe
- It's only for Zowe Web UI, not including CLI

Therefore, I'm wondering if we should make these two points clear for the new button to be added on the community site. I'd propose we add a lead in sentence before the button. Your thought? 
<img width="711" alt="screenshot_20181017113208" src="https://user-images.githubusercontent.com/14340789/47060519-82238900-d200-11e8-8c38-dad795c34e42.png">

**Comment by Tbr00ksy** [comment]
@nannanli Thank you for that feedback! I agree with your assessment. @jackjia-ibm could we incorporate Ashley's recommendation above please?

**Comment by jackjia-ibm** [comment]
Thanks @nannanli for the input. The extra lead sentences were added.

@Tbr00ksy please review and let me know if the updates are good or not. Thanks.

**Comment by Tbr00ksy** [comment]
@jackjia-ibm the Download page and FAQ page looks good. We need to add the beta disclaimer back to the home page under the download button to match the download page.
Homepage:
<img width="960" alt="screen shot 2018-10-17 at 9 48 00 am" src="https://user-images.githubusercontent.com/36775778/47090876-c6f3f380-d1f1-11e8-9a8e-d7aa1839c554.png">

Needs to match Download page:
<img width="1015" alt="screen shot 2018-10-17 at 9 48 41 am" src="https://user-images.githubusercontent.com/36775778/47090923-df640e00-d1f1-11e8-87a3-f780a426576c.png">

**Comment by jackjia-ibm** [comment]
Thanks @Tbr00ksy for the remind. This is updated.

**Comment by jackjia-ibm** [comment]
@Tbr00ksy I will close this issue for now. Please let me know any time if you find issues. Thank you.
