### ISSUE TITLE
zLUX requires certain levels of node

### ISSUE THREAD

**Issue by jthyssenrocket** [zowe/zowe-install-packaging#1098]
zLUX requires certain levels of Node.

Examples:
6.14.3 does not work
6.17.0 works
8.16.0 works
8.16.1 does not work
8.16.2 works

The installation script should verify that the version of node installed is supported

**Comment by stevenhorsman** [comment]
Issue moved to [zowe/zlux #397](https://github.com/zowe/zlux/issues/397) via [**ZenHub**](https://www.zenhub.com/)

**Comment by stevenhorsman** [comment]
This issue is to update the validation script in the app-server component, so move to the appropriate repo
