### ISSUE TITLE
apiml_cm.sh script documentation and tests

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-install-packaging#1108]
The `apiml_cm.sh` script has been moved to the `bin/` directory in this repository.

The tests are still in the original repository: https://github.com/zowe/api-layer/blob/master/scripts/apiml_cm.test.js

The API ML documentation points to the original location:
https://docs.zowe.org/stable/extend/extend-apiml/api-mediation-security.html#running-on-localhost

Is there a plan to migrate the tests and update the documentation?

**Comment by vit-tomica** [comment]
@plavjanik we've just checked that there is mocha test environment in the https://github.com/zowe/zowe-install-test/tree/master/test repo where the test could fit. The apiml_cm.sh is currently tested as part of the integration test [here](https://github.com/zowe/zowe-install-test/blob/25ed41380417c0072017455ce12e0442f0fee626/scripts/install-zowe.sh#L527) 

We will update the documentation link and try to migrate the apiml_cm test into the zowe-install-test repo.
Thanks!
