### ISSUE TITLE
zowe-configure-instance.sh - Errors in sed

### ISSUE THREAD

**Issue by ehrocha** [zowe/zowe-install-packaging#1124]
**Describe the bug**
instance.env file does not get created 

**To Reproduce**
1. Install Zowe 1.8 SMPE Version
2. Run bin/zowe-configure-instance.sh -c /var/zowe/1.8.0
3. See error : sed: FSUM7296 newline or end of file found in pattern

**Expected behavior**
File instance.env gets populated.

**Screenshots**
/var/usr/lpp/zowe >bin/zowe-configure-instance.sh -c /var/zowe/1.8.0
Creating zowe instance in /var/zowe/1.8.0
Checking existing /var/zowe/1.8.0/instance.env for updated properties
sed: FSUM7296 newline or end of file found in pattern
Missing properties that will be appended to /var/zowe/1.8.0/instance.env:

Properties added, please review these before starting zowe.
Configure instance completed. Please now review the properties in /var/zowe/1.8.0/instance.env to check they are correct.
To start Zowe run the script /var/zowe/1.8.0/bin/zowe-start.sh
   (or in SDSF directly issue the command /S ZWESVSTC,INSTANCE='/var/zowe/1.8.0')
To stop Zowe run the script /var/zowe/1.8.0/bin/zowe-stop.sh
  (or in SDSF directly the command /C ZWESVSTC)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 2.3

**Additional context**
Running under z/OS 2.4

**Comment by stevenhorsman** [comment]
Hi Eduardo - normally when we see `FSUM7296 newline or end of file found in pattern` it is as a result of a code-page issue. In the latest 1.9 release (release candidate due any day now), we've done some work to try and fix that issue, so we might have to ask to you to either try the nightly build, or hang on and test 1.9 to see if the changes have helped, or hindered.

**Comment by ehrocha** [comment]
I will wait for the 1.9 release to test again. Thank you.

**Comment by ehrocha** [comment]
I have tried the latest nightly : zowe-smpe-1.9.0-staging-540-20200221051814.zip 

Same issue
USER:/var/usr/lpp/zowe >bin/zowe-configure-instance.sh -c /var/zowe/zowe190;
Creating zowe instance in /var/zowe/zowe190
sed: FSUM7296 newline or end of file found in pattern
Configure instance completed. Please now review the properties in /var/zowe/zowe190/instance.env to check they are correct.
To start Zowe run the script /var/zowe/zowe190/bin/zowe-start.sh
   (or in SDSF directly issue the command /S ZWESVSTC,INSTANCE='/var/zowe/zowe190')
To stop Zowe run the script /var/zowe/zowe190/bin/zowe-stop.sh
  (or in SDSF directly the command /C ZWESVSTC)

**Comment by stevenhorsman** [comment]
Ok, I think I'm going to need some more information to try and work out what is going wrong. I've created a gist: https://gist.github.com/stevenhorsman/0c9cd24fbf6cad6df7488e8b71029a94 with an updated check_existing_instance_for_updates() function adding some debug. If you could run that and send us the output that would be very helpful.

**Comment by ehrocha** [comment]
Steve, in order to run that , I will need to re run the installation scripts then I would replace the provided file with the one on Zowe's filesystem and then run the file ?

**Comment by stevenhorsman** [comment]
Hey Eduardo, you don't have to re-install zowe, you can just update your zowe-configure-instance.sh with the updates in the gist and then re-run /var/usr/lpp/zowe/bin/zowe-configure-instance.sh -c /var/zowe/zowe190

**Comment by vit-tomica** [comment]
Hi @stevenhorsman, I've got this one, too. I added echo's to the code 
```
check_existing_instance_for_updates() {
echo "discovered port is ${ZOWE_ZOSMF_PORT}"
```
```
create_new_instance() {
  echo "discovered port is ${ZOWE_ZOSMF_PORT}"
```
getting the output:
```
Creating zowe instance in /a/tomvi02/moi2/instance-sed-bug
discovered port is 20015
01443
Checking existing /a/tomvi02/moi2/instance-sed-bug/instance.env for updated properties
sed: FSUM7296 newline or end of file found in pattern
```
I can workaround it by explicitly setting the zosmf port:
` ZOWE_ZOSMF_PORT=xxx bin/zowe-configure-instance.sh -c ...`

**Comment by vit-tomica** [comment]
We have a customer with this issue and the workaround worked for him as well. Looks like a problem in the zowe-init.sh script that does the zosmf port discovery?

**Comment by stevenhorsman** [comment]
Hey @vit-tomica - thanks for getting extra info on this. Just to clarify - the behaviour you are seeing is that the ZOWE_ZOSMF_PORT is coming back from zowe-init.sh with a new line in the property?
Have you any idea what has changed in your config - is it a 2.4 system or anything new? It looks like the zosmf code in zowe-init.sh hasn't updated for 17 months :S
What output do you get when you run `netstat -b -E IZUSVR1`

**Comment by vit-tomica** [comment]
Yes @stevenhorsman, there is a new line in the ZOWE_ZOSMF_PORT property.
The output of the command from the affected LPAR is 
```
MVS TCP/IP NETSTAT CS V2R4       TCPIP Name: TCPIP32         07:33:55
03/06/2020          MVS TCP/IP Real Time Network Monitor
User Id  BytesOut             BytesIn              LPort State
-------  --------             -------              ----- -----
IZUSVR1  00000000000000000000 00000000000000000000 20015 Listen
  Foreign Socket: ::..0
IZUSVR1  00000000000000000000 00000000000000000000 01443 Listen
  Foreign Socket: ::..0
Connections displayed: 2
```
It looks fine on a different LPAR:
```
MVS TCP/IP NETSTAT CS V2R4       TCPIP Name: TCPIP31         07:34:26
03/06/2020          MVS TCP/IP Real Time Network Monitor
User Id  BytesOut             BytesIn              LPort State
-------  --------             -------              ----- -----
IZUSVR1  00000000000000000000 00000000000000000000 01444 Listen
  Foreign Socket: ::..0
Connections displayed: 1
``` 

I recall I saw this problem some time ago but forgot about it :(
I have no idea what the 20015 port is for. I'll try to find out.

**Comment by vit-tomica** [comment]
@stevenhorsman 
I found something out. I can see messages in the zosmf joblog on the affected LPAR:
```
.WARNING . RMI TCP Accept-0: accept loop for ServerSocket.addr=0.0.0.0/0.0.0.0,localport=20015. throws                             
The server sockets created using the LocalRMIServerSocketFactory only accept connections from clients running on the host where the host where the RMI remote objects have been exported.
```
After a little bit of googling:
e.g. https://support.tibco.com/s/article/Tibco-KnowledgeArticle-Article-37737

The messages can be removed by modifying /etc/hosts according to the article. I wonder whether also the 20015 port will disappear together with the messages.
When I compare the beginning of the /etc/hosts file of the affected LPAR and the ok LPAR, there is a difference that matches to what the article says how to resolve it:
```
TOMVI02:/a/tomvi02: >cat /CA32/etc/hosts
127.0.0.1 localhost # ca32
...
```
```
TOMVI02:/a/tomvi02: >cat /CA31/etc/hosts
127.0.0.1 localhost usilca31.ca.com usilca31
...
```

**Comment by stevenhorsman** [comment]
Thanks for the info - I'm not sure how we can fix up zowe-init.sh to work around this.
So far I can only think of either error-ing if we find 2 ports, or just picking one and outputting a warning, but it depends if there is any ordering, or pattern we can trust. I think we'll need to leave this item open for now.

**Comment by vit-tomica** [comment]
Yes, additionally to error-ing, we could print both ports and instruct a user to pick the correct one and export it using ZOWE_ZOSMF_PORT variable before re-running the script?

**Comment by ehrocha** [comment]
Hi, That is exactly what I was about to post, I am having the exact same problem as @vit-tomica ...  I am on z/OS 2.4 and I am getting 2 ports for z/OSMF as well. I believe the second port to be ZERT , I have disabled it in IZUPRM00 and now z/OSMF is only listening in the ssl port as expected.

**Comment by ehrocha** [comment]
One other thing about ZERT, I re-enabled it and now it gor another random port, I looked at the configuration for z/OSMF and there is no option to set ZERT's port, so It will get a random one..

**Comment by stevenhorsman** [comment]
I've added code into 1.13 to this so that if we get multiple matches we try to hit the endpoint and check them, or fall back to prompting the user if we can't do this.
