### ISSUE TITLE
Allow TN3270 host to be specified during installation configuration

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zowe-install-packaging#1125]
*Customer content*

**Describe the solution you'd like**
Allow specification of the TN3270 host during installation of Zowe.

**Additional context**
The TN3270 host is set by default to 'localhost' in 
> workspace/app-server/ZLUX/pluginStorage/org.zowe.terminal.tn3270/sessions/_defaultTN3270.json

during installation of Zowe 1.8.0., and requires us to change it after installation to some other host.
Installation configuration of Zowe allows specification of the TN3270 port in 'instance.env' via

> ZOWE_ZLUX_TELNET_PORT

In Zowe 1.6.0 (and 1.4.0) we also could specify the host during installation configuration. We would appreciate it if we could specify it (again) during installation configuration to overrule the default of 'localhost' i.s.o. manually changing the generated _defaultNT3270.json.

**Comment by 1000TurquoisePogs** [comment]
In 1.8, install & configure have been separated. The configuration which you used to do in 1.6 and 1.4 is covered within the instance.env file, but I see that the host is not an option there.

The solution could be to add host as another option, such as ZOWE_ZLUX_TELNET_HOST
Would that work for you?

Another option is just to make the terminal app have a save button for recalling your exact preferences.

**Comment by FreekCornelis** [comment]
You are right, I confused installation and configuration in 1.8.0, I meant the latter. 
I prefer to be able to set ZOWE_ZLUX_TELNET_HOST during configuration via instance.env. That way, users are not required to find out what the correct host would be and to save that themselves.

**Comment by 1000TurquoisePogs** [comment]
Please take a look at my new draft PR, hopefully it will be in soon.
