### ISSUE TITLE
apiml_cm.sh depends on openssl which is not documented

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1129]
**Describe the bug**

zowe-setup-certificates.sh reports
openssl: trust_zosmf 10: /shr/usr/lpp/zowe/bin/apiml_cm.sh 516: FSUM7351 not found

**To Reproduce**
1. run bin/zowe-setup-certificates.sh -p zowe-setup-certificates.env

**Expected behavior**

Document that openssl is needed/used. If not critical then test for existance before using it. If it is critical then end right there with non-zero RC so automated processes can pick up on the failure.

**Additional context**

`bin/apiml_cm.sh:385:      cat ${entry} | openssl x509 -sha1 -noout -fingerprint -subject >&5`

**Comment by vit-tomica** [comment]
Fixed.
