### ISSUE TITLE
apiml_cm.sh error parsing zOSMF certificate

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1131]
**Describe the bug**

apiml_cm.sh function get_service_certificate_form_url fails to parse zOSMF certificate
```
Exception in thread "main" javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is: 
	java.security.cert.CertPathValidatorException: The certificate issued by CN=ROOT CA - IBM MVS SYSPROG, OU=RTP labs, O=IBM, L=Raleigh, ST=NC, C=US is not trusted; internal cause is: 
	java.security.cert.CertPathValidatorException: Certificate chaining error
```

However, the server and CA cert are trusted, so I'm not sure what Java is tripping over.

**Expected behavior**

properly parse certificate chain

I cannot give you my server and CA cert, but I can run a diagnostic tool if needed.

[certificate_config_2020-02-21-13-16-32.log.txt](https://github.com/zowe/zowe-install-packaging/files/4237733/certificate_config_2020-02-21-13-16-32.log.txt)
[zowe-setup-certificates.env.txt](https://github.com/zowe/zowe-install-packaging/files/4237734/zowe-setup-certificates.env.txt)
[listchain.txt](https://github.com/zowe/zowe-install-packaging/files/4237735/listchain.txt)

**Comment by vit-tomica** [comment]
Fixed.
