### ISSUE TITLE
zowe-setup-certificates.sh ends with rc 0 on error

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1132]
**Describe the bug**

Even though there were errors and things were not completed as requested (trusting zOSMF), zowe-setup-certificates.sh still ended with RC 0. This trips up automated scenarios.

**To Reproduce**
1. run zowe-setup-certificates.sh in such a way that `apiml_cm.sh --action trust-zosmf ` fails

**Expected behavior**

End with non-zero RC on any error.

**Comment by vit-tomica** [comment]
@OnnoVdT @stevenhorsman 
Currently, if the "apiml_cm.sh --action trust-zosmf" command fails it is tolerated and warning messages are printed, encouraging a user to rerun the command manually to set up trust with zosmf. Zowe can be started anyway. 
I'm thinking whether we want to change that while fixing this issue. That means, if "--action trust-zosmf" fails then we interrupt the zowe-setup-certificates.sh script and we ask a user to rerun the script again until the trust with zosmf is set. Zowe can't be started until the trust with zosmf is established.
Any suggestion?

Relevant code snippet 
https://github.com/zowe/zowe-install-packaging/blob/8a2f16518581780d23db86f39536e9b5b5b25db6/bin/zowe-setup-certificates.sh#L144-L149

**Comment by OnnoVdT** [comment]
Since the code only runs when requested (`if [[ "${VERIFY_CERTIFICATES}" == "true" ]]; then`), I feel that any failure should result in failure of the whole script.

**Comment by Joe-Winchester** [comment]
I agree that we should not return rc=0 if the verify is true and it fails, we should echo that we suggest they re-run with verify set to false.  I'm not in favor of a script interruption that needs input (i.e. a "do you want to proceed with verify=false" step as that can bork automation .

**Comment by vit-tomica** [comment]
Fixed.
