### ISSUE TITLE
ZWESVSTC continues startup without write to instance dir

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1135]
**Describe the bug**

if ZWESVUSR lacks write permit to isntande dir it issues this message
`Error 0: Directory '/VM30094/var/zowe' does not have write access`
but continues to start, with tons of errors following.

**To Reproduce**
1. remove write permit from $instancedir for ZWESVUSR
2. start ZWESVSTC
3. check started task output

**Expected behavior**

Immediately halt on such a critical issue

**Additional context**

**Comment by stevenhorsman** [comment]
Hi Onno, thanks for raising the problem. There is currently a check and you should have an error for this ins STDERR. It was also coded to immediately exit, but I was requested to disable exit on error behaviour by default in case of false positives, so run-zowe.sh needs to be run with the -v option to trigger this behaviour. Maybe we should review this decision, or consider severity of errors, but it's not a fix I think can be made without a wider discussion once people are back from Share.

**Comment by stevenhorsman** [comment]
As part of the refactor changes that Jack has been working on this should be a hard-stop in the code again.
