### ISSUE TITLE
Unable to deploy an extension using install-app.sh

### ISSUE THREAD

**Issue by kiril-ibm** [zowe/zowe-install-packaging#1141]
Zowe: 1.9.0-RC1
It happens due to incorrect write permissions set on certain directories.
Directories ${instanceDir}/logs and ${instanceDir}/workspace/app-server has to be writable by ZWEADMIN.

IBMUSER:/opt/zowe/zowe-instance-dir>ls -la workspace
total 176
drwxrwx--x   9 ZWESVUSR ZWEADMIN    8192 Feb 25 12:19 .
drwxrwxr-x   5 IBMUSER  ZWEADMIN    8192 Feb 25 12:19 ..
-rw-r--r--   1 ZWESVUSR ZWEADMIN    2571 Feb 25 12:19 active_configuration.cfg
drwxr-xr-x   3 ZWESVUSR ZWEADMIN    8192 Feb 25 12:19 api-catalog
drwxrwx--x   3 ZWESVUSR ZWEADMIN    8192 Feb 25 12:20 api-mediation
drwxr-x---   8 ZWESVUSR ZWEADMIN    8192 Feb 25 12:19 app-server
drwxrwx--x   2 ZWESVUSR ZWEADMIN       0 Feb 25 12:19 backups
drwxr-xr-x   3 ZWESVUSR ZWEADMIN    8192 Feb 25 12:19 explorer-jes
drwxr-xr-x   3 ZWESVUSR ZWEADMIN    8192 Feb 25 12:19 explorer-mvs
drwxr-xr-x   3 ZWESVUSR ZWEADMIN    8192 Feb 25 12:19 explorer-uss
-rwxr-xr-x   1 ZWESVUSR ZWEADMIN   10765 Feb 25 12:19 manifest.json

IBMUSER:/opt/zowe/zowe-instance-dir>ls -la logs
total 272
drwxrwxrwx   2 IBMUSER  ZWEADMIN    8192 Feb 25 12:20 .
drwxrwxr-x   5 IBMUSER  ZWEADMIN    8192 Feb 25 12:19 ..
-rw-r--r--   1 ZWESVUSR ZWEADMIN   85003 Feb 25 12:21 appServer-2020-02-25-17-20.log
-rw-r--r--   1 IBMUSER  ZWEADMIN    1070 Feb 25 12:19 configure-2020-02-25-12-19-04.log
-rw-r--r--   1 ZWESVUSR ZWEADMIN     883 Feb 25 12:20 install-app.log
-rw-r--r--   1 ZWESVUSR ZWEADMIN    4982 Feb 25 12:20 zssServer-2020-02-25-17-20.log

**Comment by 1000TurquoisePogs** [comment]
If I create a new instance, the group that owns the files is the primary group of my user:
```
 ./zowe-configure-instance.sh -c /u/tsspg/zowe/inst/2
(tsspg) TSSPG@RS28:/proj/mvd/sandboxes/zowe-release-1.9.0/bin> ls ~/zowe/inst/2
total 48
                    drwxr-xr-x        4 TSSPG    TSUSER      8192 Feb 25 13:50 bin
t IBM-1047    T=on  -rwxr-xr-x  --s-  1 TSSPG    TSUSER      1898 Feb 25 13:50 instance.env
                    drwxrwxrwx        2 TSSPG    TSUSER      8192 Feb 25 13:50 logs
```

But, you can specify the -g parameter to specify a different group:

```
./zowe-configure-instance.sh -c /u/tsspg/zowe/inst/3 -g MVDUSER
 ls ~/zowe/inst/3/
total 48
                    drwxr-xr-x        4 TSSPG    MVDUSER     8192 Feb 25 13:51 bin
t IBM-1047    T=on  -rwxr-xr-x  --s-  1 TSSPG    MVDUSER     1898 Feb 25 13:51 instance.env
                    drwxrwxrwx        2 TSSPG    MVDUSER     8192 Feb 25 13:51 logs
```

**Comment by kiril-ibm** [comment]
@1000TurquoisePogs Can you paste the same for your logs and workspace/app-server directories ? (with -g and without it)

**Comment by 1000TurquoisePogs** [comment]
If I install an app in the one with the primary default group
```
 ./install-app.sh ~/plugins/app-gen
 ls ~/zowe/inst/3/
total 64
                    drwxr-xr-x        4 TSSPG    MVDUSER     8192 Feb 25 13:51 bin
t IBM-1047    T=on  -rwxr-xr-x  --s-  1 TSSPG    MVDUSER     1898 Feb 25 13:51 instance.env
                    drwxrwxrwx        2 TSSPG    MVDUSER     8192 Feb 25 13:53 logs
                    drwxrwx---        3 TSSPG    MVDUSER     8192 Feb 25 13:53 workspace
(tsspg) TSSPG@RS28:~/zowe/inst/3/bin> ls ~/zowe/inst/3/workspace/
total 16
                    drwxrwx---        8 TSSPG    MVDUSER     8192 Feb 25 13:53 app-server
(tsspg) TSSPG@RS28:~/zowe/inst/3/bin> ls ~/zowe/inst/3/logs
total 32
t IBM-1047    T=on  -rw-r--r--  --s-  1 TSSPG    MVDUSER      945 Feb 25 13:51 configure-2020-02-25-13-51-00.log
- untagged    T=off -rw-rw-r--  --s-  1 TSSPG    MVDUSER      780 Feb 25 13:53 install-app.log
```

But, if I use the one with custom specified group:

```
 ./install-app.sh ~/plugins/app-gen
 ls ~/zowe/inst/2/
total 64
                    drwxr-xr-x        4 TSSPG    TSUSER      8192 Feb 25 13:50 bin
t IBM-1047    T=on  -rwxr-xr-x  --s-  1 TSSPG    TSUSER      1898 Feb 25 13:50 instance.env
                    drwxrwxrwx        2 TSSPG    TSUSER      8192 Feb 25 13:55 logs
                    drwxrwx---        3 TSSPG    TSUSER      8192 Feb 25 13:55 workspace
(tsspg) TSSPG@RS28:~/zowe/inst/2/bin> ls ~/zowe/inst/2/workspace/
total 16
                    drwxrwx---        8 TSSPG    TSUSER      8192 Feb 25 13:55 app-server
(tsspg) TSSPG@RS28:~/zowe/inst/2/bin> ls ~/zowe/inst/2/logs
total 32
t IBM-1047    T=on  -rw-r--r--  --s-  1 TSSPG    TSUSER       945 Feb 25 13:50 configure-2020-02-25-13-50-28.log
- untagged    T=off -rw-rw-r--  --s-  1 TSSPG    TSUSER       774 Feb 25 13:55 install-app.log
```

So it seems like the directory group is applied to new files within. But, all the files that get created have write permission for the group on my system.

Do you have a `umask` set? Mine is `umask 0002`, and I am not sure if this has an effect. The workspace creation script writes with 770 mixed with your umask:  https://github.com/zowe/zlux-app-server/blob/master/lib/initInstance.js#L21

But the app installation that makes content in `workspace/app-server/plugins` uses 660, https://github.com/zowe/zlux-server-framework/blob/master/utils/install-app.js#L27
Both scripts are supposed to give write support to the user & group, but one utilizes umask. We may want to make either both or neither use umask, but umask may be the difference between your system and mine,

**Comment by kiril-ibm** [comment]
my umask is 0022

**Comment by 1000TurquoisePogs** [comment]
OK, I think that is the important difference.
If you run `umask -S` it will tell you the meaning of the numbers.
0002:
u=rwx,g=rwx,o=rx
0022:
u=rwx,g=rx,o=rx

So, group files could be created without write permission, which causes problems later.
Probably, we want to ensure at least u=rw and g=rw, overriding umask except for others. I need to ask what others are doing in the rest of the Zowe scripts so that it is consistent.

**Comment by 1000TurquoisePogs** [comment]
I tried setting `umask 0022` but it did not prevent me from adding a plugin.
It would probably prevent someone else from my group from adding a plugin, though. So umask could be used to limit if these config items only work for 1 user or a whole group

**Comment by kiril-ibm** [comment]
fixed
