### ISSUE TITLE
Zowe server fails to start if validate-zosmf-host-and-port hangs

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1165]
**Describe the bug**
ZWESVSTC starts but only one STC starts, and its STDOUT does not get past msgs 
```
Appending JAVA_HOME/bin to the PATH...  
Appending NODE_HOME/bin to the PATH...  
```
in STDOUT.  This is because the script `${ROOT_DIR}/scripts/utils/validate-zosmf-host-and-port.sh` does not return control.  This script is called in 3 places, where I have to comment the calls out for Zowe to complete its startup.  

**To Reproduce**
1. Download `zowe-smpe-1.9.0-install-ptf-4-20200226113422`
2. Install it on zD&T system
3. Configure it
4. Run `zowe-start.sh`

**Expected behavior**
STDOUT begins like this, and has more than 2 lines.  All 18 STCs start up.
```
Appending JAVA_HOME/bin to the PATH...                                                                                             
Appending NODE_HOME/bin to the PATH...                                                                                             
Verifying node exists                                                                                                              
/Z23B/usr/lpp/IBM/cnj/IBM/node-v6.14.4-os390-s390x/bin/node is /Z23B/usr/lpp/IBM/cnj/IBM/node-v6.14.4-os390-s390x/bin/node         
Running app-server plugin installer. Log=/u/tstradm/zowe/instance4/logs/install-app.log                                            
utils_path=/S0W1/tmp/usr/lpp/zowe/components/app-server/share/zlux-server-framework/utils                                          
app_path=/u/tstradm/zowe/instance4/workspace/api-catalog                                                                           
json_path=/u/tstradm/zowe/instance4/workspace/app-server/serverConfig/server.json                                                  
```

**Additional context**
z/OS was IPL-ed 4 days ago.  ZWE1SV jobs prior to IPL did not have this problem.

**Comment by John-A-Davies** [comment]
@stevenhorsman I want to find out what's wrong with my environment in case users encounter the same problem.

**Comment by stevenhorsman** [comment]
@John-A-Davies, can you try adding a timeout to the request please?
Modify zosmfHttpRequest.js to add `timeout: 10000` to the options

**Comment by John-A-Davies** [comment]
Invocations are here
``` 
/usr/lpp/zowe/components: >ls */bin/validate.sh

api-mediation/bin/validate.sh  
files-api/bin/validate.sh      
jobs-api/bin/validate.sh
```

**Comment by stevenhorsman** [comment]
John's said: "I just used Firefox to verify that 10443/zosmf hangs". So this means that the z/OS MF server is not set up correctly on this system. If would be nice if Zowe handled it better, but this is a problem with the system.
