### ISSUE TITLE
ZWESECUR - IKJ56600I UNRECOVERABLE COMMAND SYSTEM ERROR

### ISSUE THREAD

**Issue by vit-tomica** [zowe/zowe-install-packaging#1168]
**Describe the bug**
If I specify the HLQ variable that consists of more qualifiers, so that length exceeds 8 chars, e.g.
USERID.SMPE.AZWE001:

https://github.com/zowe/zowe-install-packaging/blob/a580b3e5d5e6dc48ecd8a0fb9f993e13adaddb3a/files/jcl/ZWESECUR.jcl#L101

then the ZWESECUR jcl fails with the error "IKJ56600I UNRECOVERABLE COMMAND SYSTEM ERROR" here:

https://github.com/zowe/zowe-install-packaging/blob/63560a2d6daebf05a53c4964e725dd2ec79975bf/files/jcl/ZWESECUR.jcl#L306

**To Reproduce**

see above

**Expected behavior**

**Comment by dkelosky** [comment]
FYI, I am still getting this issue in Zowe V3 ` UNRECOVERABLE COMMAND SYSTEM ERROR`.

I had `HLQ=DKELOSKY.PSWI.AZWE003.T` which perhaps was generated via z/OSMF Workflow?

**Comment by dkelosky** [comment]
As a workaround, I needed to split this line in `DKELOSKY.PSWI.AZWE003.T.SZWESAMP(ZWESECUR)`:
```
  ADDSD  '&HLQ..*.**' UACC(READ) -  
    DATA('Zowe')                    
```
