### ISSUE TITLE
More option for TN3270 for the instance.env configuration's file

### ISSUE THREAD

**Issue by yann-59** [zowe/zowe-install-packaging#1176]
With the latest zowe's version, we discover the instance.env configuration's file which was usefull.
For the moment, we can only fix the port number and security type for the TN3270.
Is it possible to had more option like :
Host ? Default is localhost ... we don't bind our telnet on LocalHost
Terminal model? Default is Model 2 .. most of ou developer used Model 5
Codepage ? Default is 1047 ... we used the later 297 
With this file, we don't have to redo the configruation on each install.

**Comment by stevenhorsman** [comment]
Related to https://github.com/zowe/zowe-install-packaging/issues/1125. @NolanRogers - I think this is content that the Web UI squad will need to provide guidance on.

**Comment by NolanRogers** [comment]
Thanks @stevenhorsman, I'll pass this on to the the scrum team.
CC @timgerstel, @sakeerthy @1000TurquoisePogs @struga0258 @DivergentEuropeans @NakulManchanda @jordanCain @DNikolaevAtRocket @ifakhrutdinov

**Comment by 1000TurquoisePogs** [comment]
Please take a look at my new draft PR, hopefully it will be in soon.

**Comment by yann-59** [comment]
It look's like to be good ... we will be impatient to have this new feature in the configuration file.
