### ISSUE TITLE
Create plugin installation test based on Ansible playbook

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1199]
**Is your feature request related to a problem? Please describe.**

We need to create a new installation test case which will automatically install a plugin and verify it.

**Describe the solution you'd like**

- Create new Ansible playbook to install plugin.
- Create new installation test case which will install and verify plugin.
- The test case should call the Ansible playbook to perform plugin installation and validate with the method defined by the plugin.

**For this stage, we will install and test the sample api/plugin.**

#### Acceptance Criteria

- There should be a new Ansible playbook which allows others to consume and install any plugin.
- There should be a new option show in install test Jenkins job to allow the user to run  a plugin installation test.
- The test should generate similar test report like others installation test.

**Comment by jackjia-ibm** [comment]
**Stage 1**: create `scripts/zowe-install-extension.sh` which supports these parameters:

- `-e|--extension`: file path and name of the extension package
- `-r|--runtime-dir`: path to zowe runtime directory
- `-i|--instance-dir`: path to zowe instance directory
- `-d|--target-dir`: optional, default value is `<zowe-runtime-dir>/extensions`

Below parameters will be removed in future stages:

- `-t|--type`: value of `component` or `desktop-plugin`.

Example:
```
./zowe-install-extension.sh \
  -e /path/to/sample-node-api.pax \
  -t /path/to/my/extensions-runtime-dir \
  -r /var/zowe/runtime \
  -d /var/zowe/instance-dir \
  -t component
```

`type=component` can be used to install `sample-node-api`
`type=desktop-plugin` can be used to install `sample-trial-app`.

The behaviors for component installation:

- unpax the package and put into target folder
- validate the package if it has `/bin` folder and lifecycle scripts. Currently `start.sh` is required.
- modify instance-dir `instance.env` to `EXTERNAL_COMPONENTS`

The behaviors for desktop plugin installation:

- unpax the package and put into target folder
- validate the package if it has `pluginDefinition.json`.
- call `${INSTANCE_DIR}/bin/install-app.sh ${COMPONENT_DIR}` to install plugin.

**Stage 2**: modify sample repositories to define and include `manifest.json` into final package.
https://github.com/zowe/sample-node-api
https://github.com/zowe/sample-trial-app

TBD.

**Comment by jackjia-ibm** [comment]
fyi @Joe-Winchester @stevenhorsman you may be interested in. For stage 1, there are no changes on the packaging format. Just try to support the installation from open source side.

**Comment by JadinLuong** [comment]
@jackjia-ibm, I've created a PR for the script required for stage 1. I'm open to all the feedback and changes you think is necessary for the script.

**Comment by MarkAckert** [comment]
This work depends on #1692, PR #1671 to gather feedback.

**Comment by jackjia-ibm** [comment]
Information related to ZIS plugin, will need more investigation on the potential works be related.

Irek gave me this but I haven't had time to try it yet https://github.com/ifakhrutdinov/zss-sample-plugin
ifakhrutdinov/zss-sample-plugin
the idea is we were going to make an automated test about installing & running it
a ZIS plugin without a ZSS plugin is kind of useless. ZIS is used to get interesting data, and ZSS is used to send that data somewhere else
So, that repo has both

**Comment by jackjia-ibm** [comment]
Thanks Jadin. I think the current manifests we put into samples look good, we may need to go back to change something. We need to revisit stage 1 with these changes:

- change `-e|--extension` to `-o|--component` and support these packaging format:
  * **pax**: we will use `pax -ppx -rf <pax-file-name>` to extract
  * **zip**: we will use `jar xf <jar-file-name>` to extract
  * **tar**: we will use `pax -z tar -xf <tar-file-name>` to extract
  * **<directory>**: we don't need to extract, instead we will create symbolic link into `-d|--target-dir`.
- change `-d|--target-dir` default value. If the user defined `-i|--instance-dir`, then try to load the instance environment variables and find definition of `ZWE_EXTENSION_DIR`. If this is not defined, then default to `/usr/lpp/zowe-ext`.
- remove `-n|--name` and `-t|--type` options.
  * if the package has manifest, then we will read manifest to get those information.
  * if the package doesn't have manifest, we simply extract the content into target extension directory.
- the supported manifest file names are: manifest.yaml, manifest.yml, manifest.json.
- split script into 2:
  * **zowe-install-component.sh**: this script will simply lay down the files into target directory, and then read manifest and rename the laid down folder to match the name defined in manifest. Also it should check if there is `commands.install` entry. If yes, the script will switch to the component root directory and run the script defined in `commands.install`. It supports these parameters:
    - `-o|--component`: required, file path and name of the extension package
    - `-d|--target-dir`: optional, default value is `/usr/lpp/zowe-ext`.
    - `-i|--instance-dir`: optional, path to zowe instance directory. If this value is specified, this script will call `zowe-configure-component.sh` automatically.
  * **zowe-configure-component.sh**: this script will run the component `commands.configureInstance` entry defined in manifest. If the component has `desktopPlugins[].path` defined, then run `install-app.sh` on this plugin. Once this is done, the script will change add the component id into `EXTERNAL_COMPONENTS` if it has `commands.start` entry defined. It supports these parameters:
    - `-o|--component`: required. the component ID
    - `-d|--target-dir`: optional, default value is `/usr/lpp/zowe-ext`.
    - `-i|--instance-dir`: required, path to zowe instance directory. This is where we update `instance.env` `EXTERNAL_COMPONENTS` value.
- all build-in zowe components will be installed and configured in 2 steps, 3rd extensions can have option to install/configure with one command
- Pending:
  * yaml parser
  * template parser
  * call `${INSTALL_DIR}/scripts/tag-files.sh` if the package is in zip/tar format. We may need to read from manifest entry.

Check the Manifest proposal uploaded here: https://github.com/zowe/zowe-install-packaging/issues/1692#issuecomment-709645869

**Comment by JadinLuong** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create plugin installation test based on Ansible playbook](https://trello.com/c/wi8DaIRS/27-create-plugin-installation-test-based-on-ansible-playbook)

**Comment by jackjia-ibm** [comment]
Had implemented all items defined.
