### ISSUE TITLE
apiml_cm.sh

### ISSUE THREAD

**Issue by ilkinabdullayev** [zowe/zowe-install-packaging#1213]
**Reported by:** [Dan Kelosky](https://github.com/dkelosky)
**Transferred from:** `api-layer`

## Content
These [instructions ](https://github.com/zowe/api-layer/blob/master/keystore/README.md#self-signed-certificate) show to use the `new-self-signed-service`.  It looks like this and other commands are not documented in the help:

```
$ ./apiml_cm.sh
APIML Certificate Management
usage: apiml_cm.sh --action <action>

  <action> action to be done:
     - setup - setups APIML certificate management
     - new-service-csr - creates CSR for new service to be signed by external CA
     - new-service - adds new service signed by local CA or external CA
     - trust - adds a public certificate of a service to APIML truststore
     - trust-zosmf - adds public certificates from z/OSMF keyring to APIML truststore
     - clean - removes files created by setup
     - jwt-keygen - generates and exports JWT key pair
```

## Discussion
https://github.com/zowe/api-layer/issues/414

**Comment by 1000TurquoisePogs** [comment]
Replaced with zwe init certificate and its documentation.
