### ISSUE TITLE
Define zowe version in an independent file instead of as build parameter

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#122]
Ideally zowe version should be defined only once.

**Comment by 1000TurquoisePogs** [comment]
App plugins that constitute the "zlux" framework are versioned together, and probably this version should match the zowe version. We do it by replacing a string: https://github.com/zowe/zlux-app-manager/blob/master/virtual-desktop/pluginDefinition.json#L4
With recent fixes, the Zowe Desktop now shows the version number from here, so people can get an idea of what version of Zowe they are using.

**Comment by jackjia-ibm** [comment]
Thanks @1000TurquoisePogs! That's good information which I didn't know.

**Comment by jackjia-ibm** [comment]
Changes have been merged with PR https://github.com/zowe/zowe-install-packaging/pull/133
