### ISSUE TITLE
Have a message written to the MVS console when all of the Zowe components have successfully started

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#1248]
**Is your feature request related to a problem? Please describe.**
When Zowe starts customers have asked for the ability to see message(s) in the log to indicate that the components have successfully started and also that all of Zowe's address spaces are available.

**Additional context**
Related to https://github.com/zowe/zlux/issues/355#event-3204982153

**Comment by OnnoVdT** [comment]
tip: shell scripts can write a console messge by piping to /dev/console
`echo test > /dev/console ` results in
`BPXF024I (ONNO) test`

**Comment by F-LEMANER** [comment]
Hello,
On MVS (z/OS) )latform, we use automation software to start/stop/survey adress spaces.
We need a ZWExxxI "ZOWE successfully initialized" message to trap

**Comment by Joe-Winchester** [comment]
> Hello,
> On MVS (z/OS) )latform, we use automation software to start/stop/survey adress spaces.
> We need a ZWExxxI "ZOWE successfully initialized" message to trap

@F-LEMANER - yes this is the scenarios we've heard from others to get a message when all of the Zowe address spaces are settled down their init processes.  @ifakhrutdinov I believe you've started to look at this a little where the cross memory server can be the orchestrator and monitor of the address spaces ?

**Comment by ifakhrutdinov** [comment]
@Joe-Winchester, @F-LEMANER, yes, there is a new project which is going to solve this and other issues (handling of modify commands, address space cancellation, etc).

**Comment by 1000TurquoisePogs** [comment]
Completed in v2 by the `zowe.sysMessages` array of message IDs to be duplicated into syslog.
