### ISSUE TITLE
disk storage leak from tomcat /tmp files

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1252]
**Describe the bug**
Every run of the zowe server STC produces directories like this
```
tmp/tomcat.2912774408755830734.41552/work/Tomcat/localhost/apicatalog
```

**To Reproduce**
1. start zowe

**Expected behavior**
No files should be left over when zowe ends

**Additional context**
https://stackoverflow.com/questions/27865189/tomcat-server-creating-directories-in-tmp

One workaround might be to clean up these directories when zowe starts.

**Comment by stevenhorsman** [comment]
John - from your stackoverflow link it looks like a base directory needs to be set in the API catalog?

**Comment by stevenhorsman** [comment]
Issue moved to [zowe/api-layer zowe/zowe-install-packaging#3098](https://github.com/zowe/zowe-install-packaging/issues/3098) via [**ZenHub**](https://www.zenhub.com/)
