### ISSUE TITLE
zowe-check-prereqs.sh is not shipped in SMP/E

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1255]
**Describe the bug**
The script `zowe-check-prereqs.sh` is not shipped in the SMP/E package.  
It is shipped in the convenience build, in the `install` directory.

**To Reproduce**
1. install zowe using only SMP/E
4. The script is not there

**Expected behavior**
This script should be available from SMP/E, as it's intended to be run before the install.  

**Additional context**
The doc does not describe when and how to run `zowe-check-prereqs.sh`, only that it's been enhanced.

**Comment by stevenhorsman** [comment]
Dup of #1069
