### ISSUE TITLE
Issues in validate-port-available.sh

### ISSUE THREAD

**Issue by jthyssenrocket** [zowe/zowe-install-packaging#1265]
Occassionally when I started Zowe 1.9 I get error messages like: 

Error 0: Port 7654 is already in use by process  

However, port 7654 was not in use, but by coincidence another task had the same four digits in the second column ("Conn") of onetstat, so you'll get a match on the grep. 

What about using:
MATCHES=`onetstat -P $PORT | grep -c $PORT`

Also, any reason why line 15 uses onestat and line 18 netstat?

**Comment by stevenhorsman** [comment]
@jthyssenrocket - thanks for raising the issue and the fix suggestion - I've raised #1266 to fix this, to hopefully it should be in the next release

**Comment by stevenhorsman** [comment]
This PR made the release candidate for 1.11 which is being tested now
