### ISSUE TITLE
Allow specification of tn3270 connection type

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#127]
The terminal has a capability to use TLS instead of plain telnet, and is controlled here: https://github.com/zowe/tn3270-ng2/blob/master/_defaultTN3270.json#L5 where "tls" is the other option.
This should be exposed in the installer so that users can choose their port, but also their security preference.

**Comment by Joe-Winchester** [comment]
Solution:
current zowe-install.yaml is:
```# Ports for the TN3270 and the VT terminal to connect to
terminals:
  sshPort=22
  telnetPort=23
```
Change this to be
``` 
  sshPort=22
  3270Port=23
# security=tls 
```
Modifh the install script zowe-zlux-configure-ports.sh so that is security= tag is specified then this goes into the _defaultTN3270.json file and is used in the security / type argument.

```{
  "host": "localhost",
  "port": 23,
  "security": {
    "type": "telnet"
  }
}```
