### ISSUE TITLE
Allow configuration of address binding of HTTP/S

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#128]
A group interested in Zowe was concerned about being able to use it with its current IP binding behavior.
Here's a summary of their reasoning for why they'd like Zowe to support configuration of having the individual servers binding to specific IPs instead of all (0.0.0.0) as is the current behavior.

As heavy users of Dynamic VIPAs, they have an aversion to software tasks using INADDR_ANY binding when opening listening sockets. This has a number of advantages – the main ones being:

                It helps with application portability.
                It helps us identify traffic easier. If a task is using the primary interface within TCPIP, identifying traffic is harder (although not impossible I know!)
                It makes life incredibly difficult on systems that are connected to multiple networks (like dev and test systems).
                INADDR_ANY Binds mean that the application port is accessible on other IP Addresses that are reserved for use by other applications. 
                Scalability and reliability – we can use the same ports for multiple applications.

**Comment by 1000TurquoisePogs** [comment]
zlux implementation task here https://github.com/zowe/zlux-proxy-server/issues/20

**Comment by Joe-Winchester** [comment]
@1000TurquoisePogs - we currently have a mix of ZOWE_HOST_NAME and ZOWE_IP_ADDRESS that we detect at install time and burn into various configuration files for servers.  
The ZOWE_HOST_NAME doesn't always map correctly so we are thinking of changing all of our installer to use just the IP address that we detect using hostname -c and host {hostname}.  Is that what you're wanting the install to do differently ?
