### ISSUE TITLE
zowe-install-proc.sh should exit with code non-zero if zowe-copy-to-JES.sh failed

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1284]
**Describe the bug**

If zowe-copy-to-JES.sh script failed with exit code non-zero, the zowe-install-proc.sh should also exit with a non-zero value. Exit with zero gives the automation false positive of the script execution.

**To Reproduce**

1. After Zowe is installed, run command `./zowe-install-proc.sh "IBMUSER.ZWE" "NONEXISTS.PROCLIB"`.
2. The log shows:

```
  rc: 0
  stderr: |-
    Shared connection to *** closed.
  stdout: |-
    <zowe-copy-to-JES.sh>
    Check name of ZWESVSTC PROC
    Copied IBMUSER.ZWE.SZWESAMP(ZWESVSTC) into IBMUSER.zowetemp.instproc.SZWESAMP.proclib(ZWESVSTC)
    Unable to list target PROCLIB dataset NONEXISTS.PROCLIB
    exit 12
    </zowe-copy-to-JES.sh>
```

`rc: 0` means `zowe-install-proc.sh` exits with 0, but zowe-copy-to-JES.sh exits with 12.

**Expected behavior**

`zowe-install-proc.sh` should exit with non-zero if `zowe-copy-to-JES.sh` fails.

**Comment by jackjia-ibm** [comment]
@stevenhorsman sorry for adding more info to this issue. Please let me know if we want a new issue related to the below.

I found a test failed on copying ZWESECURE.jcl to SZWESAMP and the zowe-install.sh saying everything is ok.  Here are the related logs:

zowe-install.sh stdout:

```
---------------------------------------------------------------------
    Log file created: /ZOWE/tmp/logs/zowe-install-2020-04-****-12-48-01.log
    Beginning install of Zowe 1.10.0 into directory  /ZOWE/staging/zowe
    cp: /ZOWE/zowe-installs/extracted/zowe-1.10.0/files/jcl/ZWESECUR.jcl: EDC5129I No such file or directory. (errno2=0x053B006C)
    Zowe 1.10.0 runtime install completed into
      directory  /ZOWE/staging/zowe
      datasets   ZOWEAD3.ZWE.SZWESAMP  and  ZOWEAD3.ZWE.SZWEAUTH
    The install script zowe-install.sh does not need to be re-run as it completed successfully
    ---------------------------------------------------------------------
    zowe-install.sh completed. In order to use Zowe:
     - 1-time only: Setup the security defintions by submitting 'ZOWEAD3.ZWE.SZWESAMP(ZWESECUR)'
```

zowe-install.sh log shows:

```
zowe-install-MVS.sh ZWESECUR.jcl not staged in /ZOWE/zowe-installs/extracted/zowe-1.10.0/temp_2020-04-****/zowe-install-MVS/SAMPLIB, RC=1
```

I think it worth to show warnings or even fail the installation if ZWESECURE is not copied successfully. But I will leave it to you to decide if this is a warning or critical error.

**Comment by stevenhorsman** [comment]
Hey Jack - I created #1298 just because the issue for this had already been merged, so wanted to have it a bit cleaner.
