### ISSUE TITLE
Change installer according zlux http port removal

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#129]
Related to pull request of https://github.com/zowe/zlux-example-server/pull/20.

The installer should be updated for the removal of zLux http port.

**Comment by Joe-Winchester** [comment]
@1000TurquoisePogs and @rpenny125  - the installer picks up .yaml parameters and then updates zluxserver.json.  If there is no http port should we detect this and remove the http: { ... } lines from the zluxserver.json ?
 
```  "node": {
    "https": {
      "port": 25007,
      //pfx (string), keys, certificates, certificateAuthorities, and certificateRevocationLists are all valid here.
      "keys": ["../deploy/product/ZLUX/serverConfig/server.key"],
      "certificates": ["../deploy/product/ZLUX/serverConfig/server.cert"]
    },
    "http": {
      "port": 25006
    },```

**Comment by hogstrom** [comment]
Shouldn't we not have any http services by default ?  Is there a reason to have any?

**Comment by 1000TurquoisePogs** [comment]
I will commit https://github.com/zowe/zlux-example-server/pull/20 as soon as the installer would be ready to accommodate the absence of the "http" block. Just let me know. I could do it just after 0.9.4 to kick-start the process.

**Comment by 1000TurquoisePogs** [comment]
I believe this is done now.
