### ISSUE TITLE
"-l " logging option fails in running Ansible for zowe pax installation 

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zowe-install-packaging#1311]
When running ansible to install pax zowe build, an error occurred for complaining "-l " option:

**To Reproduce**
1. run ansible playbook"
ansible-playbook -l tvt4188 install.yml --extra-vars  "zowe_build_url=https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/nightly/zowe-1.10.0-staging-672-20200421071610.pax" -v 
2. errors:
TASK [zos : Check if work_dir_remote has a value] *************************************************************************
Thursday 23 April 2020  08:38:56 -0700 (0:00:00.406)       0:05:28.850 ******** 
skipping: [tvt4188] => changed=false 
  skip_reason: Conditional result was False

TASK [zos : Run ./zowe-install.sh from /opt/zowe/ansible/extracted/zowe-1.10.0/install] ***********************************
Thursday 23 April 2020  08:38:56 -0700 (0:00:00.043)       0:05:28.894 ******** 
fatal: [tvt4188]: FAILED! => changed=true 
  msg: non-zero return code
  rc: 1
  stderr: |-
    Shared connection to tvt4188.svl.ibm.com closed.
  stderr_lines: <omitted>
  stdout: |-
    FSUMA930 ./zowe-install.sh: Unknown option -l
    Invalid option: -?
  stdout_lines: <omitted>

PLAY RECAP ****************************************************************************************************************
tvt4188                    : ok=50   changed=40   unreachable=0    failed=1    skipped=75   rescued=0    ignored=6   

**Expected behavior**
Successful install.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version RHEL7.7

**Comment by stevenhorsman** [comment]
@raymondyanli - You were running the latest tests against an old build, so they aren't compatible. Now we've had a green nightly build you shouldn't see this problem anymore
