### ISSUE TITLE
Ansible installation can't enable zowe server ports

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zowe-install-packaging#1312]
**Describe the bug**
Not able to assign port number for certain zowe services when running ansibe to install zowe build for FMID package.

**To Reproduce**
1. run ansible install:
ansible-playbook -l tvt4188 install-fmid.yml -v --extra-vars  "zowe_build_url=https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/1.9.0/zowe-smpe-package-1.9.0.zip"

2. errors:
TASK [start : Wait for being able to login to API Catelog] ****************************************************************
Thursday 23 April 2020  08:11:07 -0700 (0:00:25.663)       0:19:45.742 ******** 
FAILED - RETRYING: Wait for being able to login to API Catelog (360 retries left).
FAILED - RETRYING: Wait for being able to login to API Catelog (359 retries left).
FAILED - RETRYING: Wait for being able to login to API Catelog (358 retries left).
FAILED - RETRYING: Wait for being able to login to API Catelog (357 retries left).
FAILED - RETRYING: Wait for being able to login to API Catelog (356 retries left).
ok: [tvt4188 -> localhost] => changed=false 
  attempts: 6
  censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'

PLAY RECAP ****************************************************************************************************************
tvt4188                    : ok=155  changed=88   unreachable=0    failed=0    skipped=134  rescued=0    ignored=9  

**Expected behavior**
A clear installation 

**Desktop (please complete the following information):**
 - OS: Linux
 - Version RHEL7.7

**Comment by stevenhorsman** [comment]
@raymondyanli - I don't know what the issue you are trying to raise here is - you can see from https://wash.zowe.org:8443/job/zowe-install-test/job/staging/147/ that this works in Jenkins, so it looks like the problem is with your tvt4188 set-up

**Comment by raymondyanli** [comment]
@stevenhorsman Yeahh, I can see it works on your Jenkins jobs.... I ran 1.11.0-RC1 today, I am still getting errors ...

TASK [start : Wait for Jobs API port 8545 to be available] **************************************************************************
Wednesday 29 April 2020  08:39:29 -0700 (0:02:39.742)       0:12:03.508 ******* 
FAILED - RETRYING: Wait for Jobs API port 8545 to be available (360 retries left).
FAILED - RETRYING: Wait for Jobs API port 8545 to be available (359 retries left).
FAILED - RETRYING: Wait for Jobs API port 8545 to be available (358 retries left).
FAILED - RETRYING: Wait for Jobs API port 8545 to be available (357 retries left).

eventually, it will fail in the end.... I will see if I can find some weird things from server side.

**Comment by raymondyanli** [comment]
This problem still happened to see...

ansible-playbook playbooks/install.yml -i playbooks/hosts -l vm30051 --extra-vars zowe_build_url=https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/1.11.0-RC1/zowe-1.11.0-RC1.PAX

FAILED - RETRYING: Wait for Desktop port 8544 to be available (3 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (2 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (1 retries left).
fatal: [vm30051 -> localhost]: FAILED! => {"attempts": 360, "changed": false, "content": "", "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "https://vm30051.svl.ibm.com:8544"}

**Comment by jackjia-ibm** [comment]
@raymondyanli will need to check the Zowe job log and see why 8544 port (Zowe desktop) is not started. If you see this failure again, could you post the whole zowe job log and see if we can find any clue there.

**Comment by raymondyanli** [comment]
@jackjia-ibm 
Here are the zowe install logs (on tvt6080):
[zowe-setup-certificates-2020-05-06-11-57-36.log](https://github.com/zowe/zowe-install-packaging/files/4593455/zowe-setup-certificates-2020-05-06-11-57-36.log)
[zowe-install-2020-05-06-11-56-49.log](https://github.com/zowe/zowe-install-packaging/files/4593456/zowe-install-2020-05-06-11-56-49.log)
[zowe-install-proc-2020-05-06-11-57-32.log](https://github.com/zowe/zowe-install-packaging/files/4593457/zowe-install-proc-2020-05-06-11-57-32.log)
[zowe-install-xmem-2020-05-06-11-57-33.log](https://github.com/zowe/zowe-install-packaging/files/4593458/zowe-install-xmem-2020-05-06-11-57-33.log)

**Comment by jackjia-ibm** [comment]
Thanks @raymondyanli, could you find the Zowe job ZWE1SV log? Install log might be helpful, I will take a look.

**Comment by jackjia-ibm** [comment]
Also just to double check, if you are testing v1.11.0 or v1.11.0-RC1, you should use playbooks from https://github.com/zowe/zowe-install-packaging/tree/v1.11.0, not staging branch. The staging branch had moved over for next release. If you are testing nightly build, you should use the playbooks in staging branch.

**Comment by jackjia-ibm** [comment]
@raymondyanli are we ok to close this issue?

**Comment by raymondyanli** [comment]
closed since it works fine.
