### ISSUE TITLE
Document changes to zowe-setup-certificates.sh for SSO

### ISSUE THREAD

**Issue by timgerstel** [zowe/zowe-install-packaging#1318]
**Describe the bug**

zowe-setup-certificates.sh will need re-running during the upgrade process. This requirement is due to the automatic setup of SSO, requiring users to input new values in zowe-setup-certificates.env. This doc will be a requirement for the following pull request: https://github.com/zowe/zowe-install-packaging/pull/1291

**Comment by stevenhorsman** [comment]
Issue moved to [zowe/docs-site #1162](https://github.com/zowe/docs-site/issues/1162) via [**ZenHub**](https://www.zenhub.com/)
