### ISSUE TITLE
"javac: FSUM7351 not found" when running ansible install zowe

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zowe-install-packaging#1327]
**Describe the bug**

**To Reproduce**
1. Run ansible install on host tvt6019.svl.ibm.com:
ansible-playbook install.yml -i hosts -l tvt6019 --extra-vars  "zowe_build_url=https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/1.11.0-RC1/zowe-1.11.0-RC1.pax" 

2. Error message shows:
task path: /opt/zowe/zowe-install-packaging/playbooks/roles/common/tasks/upload_essentials.yml:32
<tvt6019.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: ibmuser
<tvt6019.svl.ibm.com> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'User="ibmuser"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/e98f6e0849 -tt tvt6019.svl.ibm.com 'touch ~/.profile && . ~/.profile  && export ZOWE_IP_ADDRESS=9.30.242.85 && cd "/opt/zowe/ansible" && javac MD5Checksum.java'
<tvt6019.svl.ibm.com> (127, 'javac: FSUM7351 not found\r\n', 'Shared connection to tvt6019.svl.ibm.com closed.\r\n')
<tvt6019.svl.ibm.com> Failed to connect to the host via ssh: Shared connection to tvt6019.svl.ibm.com closed.
fatal: [tvt6019]: FAILED! => {
    "changed": true, 
    "msg": "non-zero return code", 
    "rc": 127, 
    "stderr": "Shared connection to tvt6019.svl.ibm.com closed.\r\n", 
    "stderr_lines": [
        "Shared connection to tvt6019.svl.ibm.com closed."
    ], 
    "stdout": "javac: FSUM7351 not found\r\n", 
    "stdout_lines": [
        "javac: FSUM7351 not found"
    ]
}

3. Verified java is available and javac MD5Checksum.java works locally on tvt6019
[root@zeusCent1 zowe-install-packaging]# ssh ibmuser@tvt6019.svl.ibm.com
IBMUSER:/u/ibmuser>cd "/opt/zowe/ansible" && javac MD5Checksum.java 

IBMUSER:/opt/zowe/ansible>ls -l /opt/zowe/ansible
total 32
-rw-r--r--   1 IBMUSER  OMVS        1549 May  1 12:26 MD5Checksum.class
-rwxr-xr-x   1 IBMUSER  OMVS        1417 Apr 29 16:54 MD5Checksum.java

**Expected behavior**
A clear installation

**Desktop (please complete the following information):**
 - OS: RHEL7

**Comment by jackjia-ibm** [comment]
@raymondyanli the latest version requires $JAVA_HOME/bin been added to $PATH environment variable. Will this work for you if you add java bin to the PATH?

**Comment by raymondyanli** [comment]
Thanks. it works.
