### ISSUE TITLE
Ansible install SMPE PTF build fails

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zowe-install-packaging#1340]
**Describe the bug**

**To Reproduce**
1. Run ansible playbook for installing PTF, but run into problems
ansible-playbook playbooks/install-ptf.yml -i playbooks/hosts -l vm30051 --extra-vars zowe_build_url=https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/1.11.0-RC1/zowe-smpe-package-1.11.0-RC1.zip

2. Error message:
TASK [configure : Check if zowe_xmem_stc_name has a value] ************************************************************************************************************
fatal: [vm30051]: FAILED! => {"changed": false, "msg": "Cannot find cross memory server"}

PLAY RECAP ************************************************************************************************************************************************************
vm30051                    : ok=40   changed=21   unreachable=0    failed=1    skipped=66   rescued=0    ignored=3   

3. Run PTF on tvt4188:
ansible-playbook playbooks/install-ptf.yml -i playbooks/hosts -l tvt4188 --extra-vars zowe_build_url=https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/1.11.0-RC1/zowe-smpe-package-1.11.0-RC1.zip 

4. Error message:
                          ", "", "------------------------------- JES2:JESYSMSG -------------------------------", "", " ICH70001I IBMUSER  LAST ACCESS AT 13:26:14 ON TUESDAY, MAY 5, 2020", " IEFA111I Z0PTFUCL IS USING THE FOLLOWING JOB RELATED SETTINGS:", "          SWA=BELOW,TIOT SIZE=32K,DSENQSHR=DISALLOW,GDGBIAS=JOB", " IEFA107I Z0PTFUCL UCLIN SMPCSI - DATA SET ZOE.SMPE.CSI NOT FOUND", " IEF272I Z0PTFUCL UCLIN - STEP WAS NOT EXECUTED.", " IEF373I STEP/UCLIN   /START 2020126.1326", " IEF032I STEP/UCLIN   /STOP  2020126.1326 ", "         CPU:     0 HR  00 MIN  00.00 SEC    SRB:     0 HR  00 MIN  00.00 SEC    ", "         VIRT:     0K  SYS:     0K  EXT:        0K  SYS:        0K", "         ATB- REAL:                  1032K  SLOTS:                     0K", "              VIRT- ALLOC:      11M SHRD:       0M", " IEF375I  JOB/Z0PTFUCL/START 2020126.1326", " IEF033I  JOB/Z0PTFUCL/STOP  2020126.1326 ", "         CPU:     0 HR  00 MIN  00.00 SEC    SRB:     0 HR  00 MIN  00.00 SEC    ", "", "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<", "", "install-SMPE-SYSMOD.sh ====================== content end ========================", "install-SMPE-SYSMOD.sh ERROR: no return code for jobid 09341 PID=83886260", "install-SMPE-SYSMOD.sh DISPLAY JOB output was:", "TVT4188   2020126  13:26:18.93             ISF031I CONSOLE MYCONS ACTIVATED", "TVT4188   2020126  13:26:18.93            -$DJ09341,CC", "TVT4188   2020126  13:26:18.93  JOB09341   $HASP890 JOB(Z0PTFUCL)  CC=(JCLERROR)", "ISF754I Command 'SET CONSOLE MYCONS' generated from associated variable ISFCONS.", "ISF776I Processing started for action 1 of 1.", "ISF769I System command issued, command text: $DJ09341,CC.", "ISF766I Request completed, status: COMMAND ISSUED.", "install-SMPE-SYSMOD.sh ERROR: SMP/E JOB Z0PTFUCL failed"]}

PLAY RECAP ************************************************************************************************************************************************************
tvt4188                    : ok=135  changed=67   unreachable=0    failed=1    skipped=107  rescued=0    ignored=12  

**Expected behavior**
successful installation.

**Desktop (please complete the following information):**
 - OS: RHEL 7 (run playbook) 
 - ZOS: 2.4 (vm30051)

**Comment by stevenhorsman** [comment]
This was due to ptf-buckets not being updated and since has been resolved. Please look at https://openmainframeproject.slack.com/archives/CC9QW5NJE/p1588665621017600 for more info

**Comment by jackjia-ibm** [comment]
@raymondyanli I didn't see the full log, but the error message `ERROR: SMP/E JOB Z0PTFUCL failed` indicates that could be some failures related to allocating new data sets. We will need to check the Z0PTFUCL job failure why it fails. Usually this job log should be displayed in the whole Ansible job output.

**Comment by raymondyanli** [comment]
@jackjia-ibm 
Here is the ansible output log.
[ptf-install-tvt4188.log](https://github.com/zowe/zowe-install-packaging/files/4593400/ptf-install-tvt4188.log)

**Comment by raymondyanli** [comment]
seems I can't reopen it, I will open a new issue then.

**Comment by jackjia-ibm** [comment]
@raymondyanli I re-opened this issue. After read the log, I think your CSI is not clean after FMID is installed. The log shows your PTF installation failed at `Z3RECEIV` stage, and the failure is `GIM38601E ** SYSMOD UO01942 WAS NOT RECEIVED BECAUSE IT HAS ALREADY BEEN RECEIVED.`. This means you may have run PTF installation on the server already and didn't REJECT the last installation, or do a fully clean installation.

I would like to suggest you run a clean `install-fmid`, then run `install-ptf` and let me know it passes the RECEIVE step.

**Comment by jackjia-ibm** [comment]
BTW, the log you attached shows different error comparing to your original post. The original post was failed at Z0PTFUCL step, and the log you posted shows Z0PTFUCL passed, but failed at Z3RECEIV step. I think you may have fixed the Z0PTFUCL step issue (which I don't know what caused the failure).

**Comment by raymondyanli** [comment]
@jackjia-ibm 
I ran fmid first on vm30051 here:
ansible-playbook playbooks/install-fmid.yml -i playbooks/hosts -l vm30051 --extra-vars  "zowe_build_url=https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/1.9.0/zowe-smpe-package-1.9.0.zip"

and it can't get 8544 port for free...

FAILED - RETRYING: Wait for Desktop port 8544 to be available (10 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (9 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (8 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (7 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (6 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (5 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (4 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (3 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (2 retries left).
FAILED - RETRYING: Wait for Desktop port 8544 to be available (1 retries left).
fatal: [vm30051 -> localhost]: FAILED! => {"attempts": 360, "changed": false, "content": "", "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "https://vm30051.svl.ibm.com:8544"}

PLAY RECAP *********************************************************************************************************************************************
vm30051                    : ok=143  changed=87   unreachable=0    failed=1    skipped=132  rescued=0    ignored=9

**Comment by jackjia-ibm** [comment]
@raymondyanli can you provide the Zowe job log after you install FMID? Thanks.

**Comment by jackjia-ibm** [comment]
@raymondyanli Are we ok to close this issue?

**Comment by raymondyanli** [comment]
closed since it works fine now.
