### ISSUE TITLE
Install nightly PAX build fail in ansible tvt6080

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zowe-install-packaging#1346]
**Describe the bug**

**To Reproduce**
1. ansible-playbook playbooks/install.yml -i playbooks/hosts -l tvt6080 --extra-vars  "zowe_build_url=https://zowe.jfrog.io/zowe/libs-release-local/org/zowe/nightly/zowe-1.11.0-staging-723-20200507071630.pax 

2. See errors in log files

**Expected behavior**
Installation ok
[zowe-setup-certificates-2020-05-07-17-02-43.log](https://github.com/zowe/zowe-install-packaging/files/4595832/zowe-setup-certificates-2020-05-07-17-02-43.log)
[pax-tvt6080.log](https://github.com/zowe/zowe-install-packaging/files/4595833/pax-tvt6080.log)
[zowe-install-2020-05-07-17-02-06.log](https://github.com/zowe/zowe-install-packaging/files/4595834/zowe-install-2020-05-07-17-02-06.log)
[zowe-install-proc-2020-05-07-17-02-27.log](https://github.com/zowe/zowe-install-packaging/files/4595835/zowe-install-proc-2020-05-07-17-02-27.log)
[zowe-install-xmem-2020-05-07-17-02-30.log](https://github.com/zowe/zowe-install-packaging/files/4595836/zowe-install-xmem-2020-05-07-17-02-30.log)

**Comment by raymondyanli** [comment]
@jackjia-ibm 
I will run pax and smpe separately, open new issue here individually. 
I will clean up the old issues.

**Comment by jackjia-ibm** [comment]
@raymondyanli This is the error Sean talked about at https://openmainframeproject.slack.com/archives/CC9QW5NJE/p1588783448020300?thread_ts=1588753201.019900&cid=CC9QW5NJE. It doesn't fail on our test server which hostname/dns is configured properly. It caused issues on other systems, especially internal systems which local dns is not configured.

```
Sean Grady(opens in new tab)  1 day ago
@Steven Horsman @Jack T. Jia there's a regression here, not sure when it started, but post-1.11.0
1. the keystore script fails to recognize my systems hostname (has been this way FOREVER, we have some missing dns/host configuration probably)
2. keystore script therefore defaults to the IP i gave
3. apiml_cm.sh does something that requires a hostname, not an ip, and therefore fails.

Sean Grady(opens in new tab)  1 day ago
Log file created: /u/me/zowe/logs/zowe-setup-certificates-2020-05-06-12-41-30.log
Loading default variables from /u/me/zowe/test/722/bin/zowe-setup-certificates.env file.
Loading /u/me/zowe-setup-certificates.env file and overriding default variables.
warning : ping mylpar.rocketsoftware.com did not match stated IP address 192.168.1.100
    Defaulting hostname to value of ZOWE_IP_ADDRESS 192.168.1.100
  ZOWE_IP_ADDRESS    variable value=192.168.1.100
  ZOWE_EXPLORER_HOST variable value=192.168.1.100
Creating certificates and keystores... STARTED
apiml_cm.sh --action setup has failed. See /u/me/zowe/logs/zowe-setup-certificates-2020-05-06-12-41-30.log for more details

Sean Grady(opens in new tab)  1 day ago
`Calling keytool -gencert -v -infile /u/me/zowe/test/722/keystore/localhost/localhost.keystore.csr -outfile /u/me/zowe/test/722/keystore/localhost/localhost.keystore_signed.cer -keystore /u/me/zowe/test/722/keystore/local_ca/loc\
alca.keystore.p12 -alias localca -keypass local_ca_password -storepass local_ca_password -storetype PKCS12 -ext SAN=dns:192.168.1.100,ip:192.168.1.100,dns:localhost.localdomain,dns:localhost,ip:127.0.0.1 -ext KeyUsage:critical=keyEnciph\
erment,digitalSignature,nonRepudiation,dataEncipherment -ext ExtendedKeyUsage=clientAuth,serverAuth -rfc -validity 3650
keytool error (likely untranslated): java.lang.RuntimeException: java.io.IOException: DNSName components must begin with a letter`

Steven Horsman(opens in new tab)  1 day ago
@JohnDavies @Joe Winchester - I’m guessing this is caused by https://github.com/zowe/zowe-install-packaging/pull/1323 ? (edited) 

Sean Grady(opens in new tab)  1 day ago
i think the same

Sean Grady(opens in new tab)  1 day ago
i'm assuming the fix is just to not have apiml_cm use that ip, but to keep using the hostname

Sean Grady(opens in new tab)  1 day ago
it's a strange configuration that we have because i can actually reach the hostname that i use in my browser, but however we do a sanity check on the hostname has never worked, pre-1.0

Sean Grady(opens in new tab)  1 day ago
always printed a warning which i would ignore without consequence

Sean Grady(opens in new tab)  1 day ago
to fix THAT issue, let me DM you the output, i think its a sed ipv6 thing.
```

I believe we don't have a resolution at this time yet, but will track the fix.

**Comment by raymondyanli** [comment]
It seems the problem is still there. please see the log files.
[zowe-setup-certificates-2020-05-13-10-11-32.log](https://github.com/zowe/zowe-install-packaging/files/4622564/zowe-setup-certificates-2020-05-13-10-11-32.log)
[pax-tvt6019.log](https://github.com/zowe/zowe-install-packaging/files/4622565/pax-tvt6019.log)

**Comment by raymondyanli** [comment]
Hostname issue can be solved by adding variable in playbook.
