### ISSUE TITLE
ASSIZEMAX needs to be set 

### ISSUE THREAD

**Issue by xwu0226** [zowe/zowe-install-packaging#1354]
*Customer content*
While configuring Zowe certificate, you got JVMJ9VM015W message showing that the JVM could not get enough memory to continue process. We need to configure omvs user address space size (ASSIZEMAX) to big enough for JAVA to run. This change needs user logoff/logon.

This needs to be documented somewhere in Zowe installation guide.

**Comment by stevenhorsman** [comment]
Issue moved to [zowe/docs-site #1205](https://github.com/zowe/docs-site/issues/1205) via [**ZenHub**](https://www.zenhub.com/)
