### ISSUE TITLE
/etc/hosts need to set properly for APIML to work

### ISSUE THREAD

**Issue by xwu0226** [zowe/zowe-install-packaging#1355]
*Customer content*

"After creating /etc/hosts we noticed that APIML was not working. and we had the following messages in the system: EZZ3111I Unknown host 'STLABE7'   Error 255: ZOWE_EXPLORER_HOST Error: /zowev110/usr/lpp/zowe/bin/internal/run-zowe.sh 124: FSUM7351 not found Error: getaddrinfo ENOTFOUND STLABE7 . ...  Need to add the line ""9.30.132.107  STLABE7  STLABE7.svl.ibm.com "" to /etc/hosts and  did some changes in instance.env and zowe-setup-certificates.env related to hostname, then reran zowe-setup-certificates.sh"

Documentation needs to be updated.

**Comment by stevenhorsman** [comment]
Issue moved to [zowe/docs-site #1204](https://github.com/zowe/docs-site/issues/1204) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Joe-Winchester** [comment]
@xwu0226 - can you paste in the etc/hosts file you have please ?  It looks as though you added  
```
9.30.132.107 STLABE7 STLABE7.svl.ibm.com
```
which is specific to your host name.  
Are you operating behind a firewall where the hostname STLABE7.svl.ibm.com isn't addressable from your z/OS machine (so it's not actually a reachable host name externally) and that what you're doing is effectively swopping the host name to the IP address ?  If so then the way we might want to get customers to do this is that in the instance.env file the ZOWE_EXPLORER_HOST is set to the IP address,  and also the reachable external IP name should be set into the zowe-create-certificates.env file.
