### ISSUE TITLE
Documentation suggestion for SZWESAMP(ZWESECUR)

### ISSUE THREAD

**Issue by xwu0226** [zowe/zowe-install-packaging#1357]
**Describe the bug**
In SZWESAMP(ZWESECUR)

ZWESECUR sample should have a line with CONNECT for normal user IDs as it does for administrative user IDs for clarity.

**Comment by stevenhorsman** [comment]
Issue moved to [zowe/docs-site #1202](https://github.com/zowe/docs-site/issues/1202) via [**ZenHub**](https://www.zenhub.com/)
