### ISSUE TITLE
Document error in for ZWESISTC

### ISSUE THREAD

**Issue by xwu0226** [zowe/zowe-install-packaging#1359]
**Describe the bug**

Section: Installing and configuring the Zowe cross memory server (ZWESISTC), Step 1: Copy the cross memory PROCLIB and load library, 1b. Should be Proc not Prob

**Comment by stevenhorsman** [comment]
Issue moved to [zowe/docs-site #1200](https://github.com/zowe/docs-site/issues/1200) via [**ZenHub**](https://www.zenhub.com/)
