### ISSUE TITLE
ZWESECUR should PERMIT READ to AUXUSER to ZWES.IS

### ISSUE THREAD

**Issue by jthyssenrocket** [zowe/zowe-install-packaging#1361]
The manual https://docs.zowe.org/stable/user-guide/configure-xmem-server.html#step-4-configure-saf states that 

> "It is recommended that you also grant READ access to the STC user under which the ZWESASTC started task runs which is ZWESIUSR."

This is actually a requirement, so the security job ZWESECUR be updated to permit READ to AUXUSER:

```
000266 /* permit Zowe main server to use XMEM cross memory server       
000267   RLIST   FACILITY ZWES.IS ALL                                   
000268   RDEFINE FACILITY ZWES.IS UACC(NONE)                            
000269   PERMIT ZWES.IS CLASS(FACILITY) ACCESS(READ) ID(&ZOWEUSER.)     
000270   PERMIT ZWES.IS CLASS(FACILITY) ACCESS(READ) ID(&AUXUSER.)
```

**Comment by jthyssenrocket** [comment]
Without the READ in place you may see error messages like 

xxxxnnnnE Init step 'startup' failed - parent CMS communication RC = 33
ZWES0063E User module failure - init function RC = 162

in the ZIS AUX address space (ZWESASTC)

**Comment by 1000TurquoisePogs** [comment]
I see this in the current v2 one, so closing this.
