### ISSUE TITLE
Use an internal as well as external hostname and IP address

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1364]
*Customer content*

**Is your feature request related to a problem? Please describe.**
Referring to the problems in issue #1279 and #1350, zowe configuration needs to determine hostname and IP address, but on some systems, e.g. ZD&T, these values differ between the internal and external TCP/IP domains.  These are not interchangeable.  In some cases of zowe the internal value is required, and for others, the external value.  In particular, the ZD&T internal hostname S0W1.DAL-EBIS.IHOST.COM can't be resolved externally, so we had changed zowe-init.sh to replace that by the external IP address.  However, the certificate creation tool requires a non-numeric hostname, so this fails. 

**Describe the solution you'd like**
Rather than have a single environment variable for hostname, have separate variables for the internal and external ones, and the same for the IP address.

**Describe alternatives you've considered**
For alternative solutions or features we considered, see issue #1279.  

**Additional context**
https://github.com/zowe/zowe-install-packaging/issues/1279#issuecomment-626771663
---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** installer,
**I want** to configure Zowe on systems where the TCP/IP domains differ between internal and external views
**so that** the configuration is correct inside and out, and the certificates are correctly created.

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by stevenhorsman** [comment]
I think this issue should be covered by #1762

**Comment by jackjia-ibm** [comment]
Few changes we had I believe can support to close this issue:

- with #2049, we have confirmed usage of `ZWE_EXTERNAL_HOSTS` vs `ZOWE_EXPLORER_HOST` (internal). Also if the user uses YAML configuration, he will have full control on how many `zowe.externalDomains` and `haInstances.[ha-instance].host` as internal domain.
- with #2049, user can define `COMPONENT_LEVEL_CERTIFICATES` to create as many certificates as they need, can be used for internal communication, etc.
- zowe-setup-certificates.env supports multiple domain names with `HOSTNAME` variables.
