### ISSUE TITLE
Enable Keyring test

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1398]
After keyring feature is ready, we need extend test case to test the keyring functionality.

- Other than using `zowe-setup-certificates.sh`, change the playbook to allow use keyring configuration JCL to setup certificates in keyring, and the following services should be configured to use keyring.
- The user should have ability to choose what kind of certificates to use: java keystore in USS or keyring.

**Comment by jandadav** [comment]
@jackjia-ibm Great news, is there a plan to include this into nightly?

**Comment by stevenhorsman** [comment]
Duplicated in #1535
