### ISSUE TITLE
Atlas messages.log Unable to acquire TCCL store lock for MVS explorer

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#141]
Problem:
]
com.ibm.ws.container.service.state.StateChangeException: java.lang.IllegalStateException: 
Unable to acquire TCCL store lock
in messages.log

Solution
Update installer so
-Dcom.ibm.ws.classloading.tcclLockWaitTimeMillis=300000
is added to the jvm.options file in /explorer-server/wlp/usr/servers/Atlas/
using the same technique that updates the server.env file

This will need to be done the same way that the server.env and other Liberty files are appended to, during the install as part of the zowe-install-liberty-server.sh file, using a template file.

**Comment by John-A-Davies** [comment]
Already done via a clashing PR from @Joe-Winchester.
