### ISSUE TITLE
In the node checking script write a warning/info message related to node support

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#1410]
**Is your feature request related to a problem? Please describe.**
Zowe checks node on startup,  and validates that the version is a supported on (6, 8 (excluding 8.16.1), and so forth.
Each node release has an end of support timeframe, for example node 6 goes out of support September

**Describe the solution you'd like**
In the node validation script log warning messages if the node release being used is close to end of support, and also messages if the node release is out of support.  
This could check the date of the system against a known set of end of support releases, info on approaching 6 months,  warning approaching 3 months, and warning in CAP LETTERS if the node release is past support (which isn't an error per-say - Zowe will still launch - but it isn't necessarily supported.

**Comment by DivergentEuropeans** [comment]
PR: https://github.com/zowe/zowe-install-packaging/pull/1442/files

**Comment by DivergentEuropeans** [comment]
@Joe-Winchester Can you close this issue? For some reason, I cannot in this ZenHub page
