### ISSUE TITLE
server.json productDir not updated on Runtime install change

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#1434]
I think this is the same problem as #1245, just in a different file.

To Reproduce
- Install 2 Zowe versions, such as A and B
- Run zowe-configure-instance.sh on A
- Change that instance to point to ROOT_DIR of B
- Run the instance
the productDir field in <instance>/workspace/app-server/serverConfig/server.json still points to install A

**Comment by 1000TurquoisePogs** [comment]
Not used in v2.
