### ISSUE TITLE
Remove ZOWE_HOST_NAME from installer and replace with ZOWE_IPADDRESS 

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#144]
Problem:
The installer tries to detect ZOWE_HOST_NAME and use this in various places (the index.html pages of the Atlas explorers in MVD).  
We have run into problems where customers don't have this DNS mapper.

Solution:
Replace with ZOWE_IPADDRESS.  This is also detected during the install and used for the API mediation layer, so it's more consistent as well if we switch over entirely to IPADDRESS

**Comment by patbossman** [comment]
We need to make sure we're splitting config and operational directories from binaries/static code.  We have over a thousand z/OS on z/VM instances.  So we want the binaries in a read only, and be able to update the config for all of the instances.  Updating hostname and IPs would be a key piece of that.

**Comment by John-A-Davies** [comment]
ZOWE_HOST_NAME has already been replaced globally by ZOWE_IPADDRESS in this repo.  I move to close it.

**Comment by Joe-Winchester** [comment]
@John-A-Davies - we still have the environment variable ZOWE_EXPLORER_HOST used by the installer that causes problems on boxes where it doesn't map (i.e. ZD&T in the cloud).  We should replace this with ZOWE_IPADDRESS so I'd like to keep this open and put it into 0.9.5 as an open issue.

**Comment by John-A-Davies** [comment]
Yes, 4 scripts still use ZOWE_EXPLORER_HOST.
