### ISSUE TITLE
Packaging Distribution and Management Hill

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#1440]
Hills:
**As a z/OS System Programmer I can manage extensions to Zowe in a reliable, repeatable and consistent manner across conformant offerings, through download, install, configure into an existing Zowe instance, auditability of which extensions are active, upgrade, uninstall

As a z/OS conformant extension I can package my offering in a way that z/OS system programmers can download and install/extend/configure their existing Zowe instances in a consistent way.**

Notes:
There are a number of issues with the current version of Zowe that make it quite coupled and not very flexible. This will cause challenges going forward when thinking about HA, hybridisation/containerisation of Zowe and adoption by extenders.

[Extending Zowe Lifecycle.pptx](https://github.com/zowe/zowe-install-packaging/files/4787461/Extending.Zowe.Lifecycle.pptx)

**Comment by 1000TurquoisePogs** [comment]
![package management edit](https://user-images.githubusercontent.com/30730276/91869756-3f2bfc80-ec44-11ea-9fa5-a16baf02a693.png)

Here's an edit I made to clarify package manager metadata versus zowe metadata, from today's call.

**Comment by 1000TurquoisePogs** [comment]
an example of how you may package code so that runtime structure is not disturbed from latest experiments:
https://github.com/zowe/zlux-build/blob/staging/conda/README.md

**Comment by 1000TurquoisePogs** [comment]
Implemented in v2
