### ISSUE TITLE
Validate zowe-support.sh works as expected

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1456]
*Customer content*

**Is your feature request related to a problem? Please describe.**
There is no test for validating if zowe-support.sh works as expected. 

**Describe the solution you'd like**
`zowe-install-test` should do this.

**Describe alternatives you've considered**
none.

**Additional context**
`zowe-support.sh` now also invokes `zowe-verify-authenticity.sh`, so we need to check what the customer will
experience when they run `zowe-support.sh` .

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** customer or L2,  
**I want** to ensure that  `zowe-support.sh` collects the right data, including `zowe-verify-authenticity.sh` 
**so that** I have the info I need to determine the cause of a problem.

*Details/notes*  
Invoke this in sanity test.

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by Martin-Zeithaml** [comment]
Closing as V1 is out of support.
