### ISSUE TITLE
Research - Discuss performance test suite requirements with component squads

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#1464]
- Non-HA
- HA

- What existing performance tests do component squads have?
- Which endpoints and features are the interested in performance testing
- Do components want to test separately (i.e. without other components running)
- What pre-reqs do squads have for their tests?
   * Do they need mock / dummy backend services

- Do they want "real-world" testing - not a single endpoint, but multiple endpoints or features in parallel?

- This issue covers all components - CLI, App Framework, APIML, Explorer APIs

**Comment by NakulManchanda** [comment]
Hi,
This can be good start for **web ui squad**

James shared this potential list which can be good start from web ui squad for performance testing
[web ui- performance test suite.xlsx](https://github.com/zowe/zowe-install-packaging/files/4833369/web.ui-.performance.test.suite.xlsx)

Let us know if we need to provide more info. 
We will upload again with modifications if required.

FYI @1000TurquoisePogs  @struga0258 @jackjia-ibm @MarkAckert

**Comment by jackjia-ibm** [comment]
As part of this work, we are thinking to setup a meeting in architecture call to:

- introduce why we are designing this performance test framework,
- introduce the purpose of each parts of the test framework,
- explain what to expect,
- demo what we currently have so far,
- briefly introduce how we can prepare test suites / test cases (this is undergoing work in Sprint 1),
- take feedbacks.

Will make this happen in Sprint 1.

fyi @jandadav @jalel01 @1000TurquoisePogs @struga0258

**Comment by jackjia-ibm** [comment]
From David of APIML squad: https://github.com/zowe/zowe-install-packaging/issues/617#issuecomment-658050696

**Comment by jackjia-ibm** [comment]
From Jordan represents Explorer APIs/UIs: https://github.com/zowe/zowe-install-packaging/issues/617#issuecomment-668669360

**Comment by jackjia-ibm** [comment]
So far Melissa had collected all requirements from apiml/desktop/explorer api squads.
