### ISSUE TITLE
High Availability - Research user expectations

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#1468]
As part of understanding how Zowe should achieve high availability, we should first understand customer expectations in speaking of it. 

We should:
* Gather more detailed user feedback and requirements for high availability
* Engage with SME's within our companies for expertise and guidance
* Ask for Sysplex training from SME :-) 

Checkpoints:
* Can we schedule the SME training and guidance in Zowe Architecture calls?

Output:
* A clearly defined scope for what high availability means for Zowe. This scope includes the qualities of High Availability to target (i.e., reliability, scalability, disaster recovery) as well as some deployment attributes (sysplex, multi-sysplex, container+sysplex, etc.).
* This scope should be communicated with the community so that we have a shared knowledge when working on HA. 
* Present results to the team on a Zowe Architecture call

**Comment by MarkAckert** [comment]
Education session for sysplex will be after sprint 1, likely sprint 2

**Comment by 1000TurquoisePogs** [comment]
@John-A-Davies noted that people may be ok with a much easier level of uptime-protection... not quite high availability but pretty good: have a monitor program which records the process IDs of each component of zowe, and if a process stops in a way that is considered abnormal, then the monitor could restart that by going through the standard configure.sh, start.sh component scripts.
This would be at effectively no-cost to system resources, and would keep uptime better than without.

**Comment by jackjia-ibm** [comment]
@1000TurquoisePogs thanks for the information. yes this is in scope of research and mainly covered by https://github.com/zowe/zowe-install-packaging/issues/1472. Looking forward to discuss in Architecture call to find out what's the best way to achieve this. Is Eureka in better place to solve this issue, or the ZLaunch which Irek is working on, or some other solutions like the nanny process mentioned here.

**Comment by jackjia-ibm** [comment]
The slide to kick off the discussion at Jul 7, 2020: [2020PI3 - high availability.pdf](https://github.com/zowe/zowe-install-packaging/files/4910230/2020PI3.-.high.availability.pdf)

Many comments are added to https://github.com/zowe/zowe-install-packaging/issues/1467. Thanks for all who shared their ideas.

Recordings can be found at https://github.com/zowe/community/blob/master/Project%20Management/Architecture%20Call/Archtecture_Call.md

**Comment by jackjia-ibm** [comment]
The first drop of [Zowe-HA-Draft.docx](https://github.com/zowe/zowe-install-packaging/files/4919166/Zowe-HA-Draft.docx)

**Comment by jackjia-ibm** [comment]
The second version of [Zowe-HA-Draft.docx](https://github.com/zowe/zowe-install-packaging/files/4967431/Zowe-HA-Draft.docx).

Comparing to the first version, we:

- A clear definition of Caching API
- Added Limitation section to explain how Zowe HA is limited, either running it on single LPAR, or component functionality.

**Comment by jackjia-ibm** [comment]
We have pretty good understanding of what HA means for Zowe and started to work on the draft. The publish of draft will continue on https://github.com/zowe/zowe-install-packaging/issues/1477.
