### ISSUE TITLE
High Availability Research: Zowe App Framework

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#1469]
What is required for Zowe App Framework to begin considering High Availability? High Availability here refers to scope defined in #1468 . 

* App Framework is currently stateful
    - What does the path to HA look like?
    - Will persisting stateful data in shared storage enable HA?
*  What about App Framework plugins?
    - Do these need to be highly available as well?
* Websockets?

**Comment by jackjia-ibm** [comment]
After many discussion, I think we have good shape to move to next PI. We will do more validations when some implementations are in place.
