### ISSUE TITLE
High Availability Research: APIML

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#1470]
What is required for Zowe APIML  to begin considering High Availability? High Availability here refers to scope defined in #1468 . 

* How multiple gateways should be implemented to support DDVIPA for load balancing? Do we assign each instance a different port?
    - What about static config YAML ? dynamic is preferred for dynamic registration, but static is convenient?
* JWT token - will use z/OSMF JWT if available, if not, APIML wraps LTPA in JWT [using certificate store]
* Certificate store is the stateful aspect of current APIML authentication
* How do the different microservices reach HA? What are their requirements?
* How do we start multiple Eureka services and gateway to make sure APIML is always online, how this will affect components registration.
* These are the 2 import components of APIML trio (Catalog can tolerate failure)
* Eureka can run multiple instances to reach HA
* Gateway HA?
* Websockets?

**Comment by jalel01** [comment]
@MarkAckert Thank you for opening the issue. We agreed with @jordanCain that the API ML Squad will work with you to understand what the API ML needs to do to support HA.

**Comment by jackjia-ibm** [comment]
More discussion on starting multiple instances of Gateway and Discovery service on August 6 call.

Run multiple instances of Gateway seems more straightforward and they will be automatically registered to Discovery Service. We need more testing on multiple instances of Discovery Service.

Items related to multiple Gateway we need to resolve:
- Is that possible to let Gateway prioritized to direct traffic to components located in same LPAR.

David had been doing some testing and recorded here: https://github.com/jandadav/eureka-cluster.

Items related to multiple Discovery Service we need to resolve:
- start multiple in same LPAR:
  * we may not be able to use same hostname, this may create requirement on LPAR configuration
  * is it possible to start multiple with same hostname (maybe different port)
  * can we start multiple on same port with port sharing,
  * start multiple on different port
- start multiple on different LPARs and how they communicate and be aware of each other
- if we start multiple on same port and use port sharing, will this affect health check
- evaluate risk / consequences of component without health check
- is dynamic registration mandatory for health check
- is there simple way to minimize the changes on component to enable dynamic registration.
- (more?)

**Comment by jordanCain** [comment]
1.  Successfully started two discovery services on the same hostname with different ports
- Gateway and catalog would be configured to know about one discovery service and upon checking the registered services of both discovery services they matched showing they were able to replicate.
2. Start discovery service using port sharing (PENDING)
3. Two discovery services running and killing one 
- Have gateway and catalog registered to discovery service that is not killed, no issues
- Have gateway and catalog registered to discovery service that *is* killed, no issues, existing discovery service was able to replicate the services to itself
- Restart killed discovery service, as soon as `ZWEAM000I Discovery Service has been started` message was seen the existing running discovery service was already showing the restarted discovery service on the eureka home page under registered instances 
- Killing both discovery services - Any registered services still worked through the gateway.
- Killed discovery services still show up on the gateway home page `2 Discovery Service instances are running`

**Comment by jackjia-ibm** [comment]
Extra info from Petr P.: https://github.com/zowe/api-layer/blob/master/docs/local-configuration.md#running-multiple-instances-of-eureka-locally

**Comment by jackjia-ibm** [comment]
Nayer worked on experiment 3 and the result shows even with static registration, Gateway can still be able to avoid failed instance and point to the working instance. Based on Jakub's insights, Gateway will try the next available instance shows in Discovery Service instance list, and avoid go back to the failed instance in 2 minutes.

This eases the requirement to switching to dynamic registration, so we can pause the experiment 4 and 5. We will come back to investigate dynamic registration when we want to work on scalability.

**Comment by jackjia-ibm** [comment]
For experiment 6, David did quick test and confirmed we can have multiple static definition files with same serviceId. All the instances defined in the various files can be recognized by Discovery Service.

**Comment by jackjia-ibm** [comment]
We may not cover all the tests we want, but I think we have a good shape to move to next PI. We will identify more tests and validation works after some implementations are in place. Thanks for all the inputs.
