### ISSUE TITLE
High Availability Research: Extender Services

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#1471]
As a Zowe extender, I would also like to make my service highly available. 

* Can Zowe provide some lifecycle management to make extender services highly available "for free"?
* If not, can Zowe provide guidance and/or conformance criteria for high availability?

**Comment by jackjia-ibm** [comment]
@jordanCain this should be the topic related to explorer API and UI components.

**Comment by jackjia-ibm** [comment]
With the HA draft https://github.com/zowe/zowe-install-packaging/issues/1477, extensions should inherit HA feature built-in of Zowe.

This is also related to standardized packaging format to properly define extension metadata, related to https://github.com/zowe/zowe-install-packaging/issues/1440 and https://github.com/zowe/zowe-install-packaging/issues/1249.

Further implementation works will be handled by other issues defined under `High Availability` label.
