### ISSUE TITLE
opercmd insufficient permission when trying to get iplinfo in zowe-api-mediation-configure.sh

### ISSUE THREAD

**Issue by jordanCain** [zowe/zowe-install-packaging#148]
When trying to get the iplinfo to get zos version during the configuration of zosmf behind the mediation layer I get 
```
/u/jcain/zowe-0.9.4/install/..//scripts/opercmd: /u/jcain/zowe-0.9.4/install/..//scripts/zowe-api-mediation-configure.sh 88: .: ./zowe-install.sh 95: FSUM9209 cannot execute: reason code = ef076015: EDC5111I Permission denied.
```

The file at fault here is /scripts/zowe-api-mediation-configure.sh at line 88

Further on in the install the opercmd is able to run successfully and copy the proclib into USER.PROCLIB.
I also verified my user has sufficient authority to run the opercmd script to get D IPLINFO

**Comment by John-A-Davies** [comment]
This is because opercmd does not have execute permission when it's laid down by un-PAX.

**Comment by jackjia-ibm** [comment]
I believe this is not an issue anymore. Please re-open if it still is.
