### ISSUE TITLE
APPLY step fails on low disk space

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1480]
**Describe the bug**
The SMP/E job Z4APPLY failed on Marist with
```
GIM24200E ** SYSTEM ABEND B37 OCCURRED WITH A REASON CODE OF '00000004'X DURING SMP/E PROCESSING. THE LIBRARY RAN OUT OF
                  SPACE. THE LIBRARY IS NOT ELIGIBLE FOR RETRY PROCESSING BECAUSE IT IS SEQUENTIAL.
     GIM69200E ** RETRANSFORMATION FAILED FOR HFS ZWEPAX05 IN THE SYSUT1 LIBRARY FOR SYSMOD UO01948. ABEND B37 OCCURRED WHILE
                  PROCESSING SYSUT1. THE SYSUT1 LIBRARY RAN OUT OF SPACE.
```
This is due to the combination of 2 factors

1. Small primary SPACE allocation in the DDDEF for SYSUT1
```
       REP DDDEF(SYSUT1)   CYL SPACE(20,200) UNIT(SYSALLDA)
       VOLUME(ZOWE02) .
```

1. Disk space shortage on the nominated volume

![image](https://user-images.githubusercontent.com/36740892/85846019-19dec600-b79d-11ea-96a1-9538636b1c52.png)

**To Reproduce**
1. Run Jenkins SMP/E install test

**Expected behavior**
SMP/E APPLY job RC=00

**Additional context**
We need to ensure that adequate disk space is requested and available on the target test system.  
The test should fail early - as soon as it's known that there won't be enough space.
Regular housekeeping is required to ensure there is enough space.
It would be better if DASD could be allocated by UNIT rather than depending on a nominated VOLUME.
We need a more accurate figure for space allocation.

**Comment by John-A-Davies** [comment]
@stevenhorsman FYI.

**Comment by John-A-Davies** [comment]
This is related to #1379

**Comment by John-A-Davies** [comment]
The JCL in Z0PTFUCL still has an inadequate SPACE allocation for later PTFs.  This will cause the build to break, even if there is enough space available on the chosen VOLUME.  PTF 1948 is 338MB so needs 6139 tracks, and PTF 1949 is 177MB so needs 3211 tracks.  To avoid B37 in future, the Z0PTFUCL should really be updated for every PTF.  Adequate space allocations are given in the HTM file shipped with the PTFs, and this allocation is kept up to date.  Customers who use the supplied HTM will not be impacted.

**Comment by John-A-Davies** [comment]
@jackjia-ibm I know how to calculate the SPACE requirement.  Do you think I could add an extra variable in the `sed` list, so that `Z0PTFUCL.jcl` gets updated with the right SPACE value?  I think this might save the build from B37.  The alternative is to update `Z0PTFUCL.jcl` with every new PTF.

**Comment by jackjia-ibm** [comment]
Thanks @John-A-Davies and that sounds better approach than we hardcoded the size of SYSUT1 in Z0PTFUCL. FYI, Yan tried SPACE(20,300) and works for them. Proposed changes are here https://github.com/zowe/zowe-install-packaging/pull/1492/files

**Comment by John-A-Davies** [comment]
@jackjia-ibm Thanks.  SPACE is (primary, secondary), so you probably want SPACE(400,10) for PTF UO01948 and SPACE(215,10) for UO01949 ... as a holding pattern until I complete the proposed work.

**Comment by John-A-Davies** [comment]
There are 2 ways this issue can arise
1.  initial definition of space
This is done by job ZWE1SMPE in the FMID.  It still has inadequate space here for later PTFs

2.  update of space 
This is done by job Z0PTFUCL.  This job defines adequate space.

If the SMP/E sysprog does not run Z0PTFUCL, the original space allocation won't be enough and the APPLY step will fail.

The `readme.htm` file does contain JCL, but that is only for the datasets that hold the PTF itself, not for the DDDEF for the SYSUT1 work dataset that is used by APPLY.  

I think we need to tell the sysprog to run Z0PTFUCL, and this should be in the Program Directory and the `readme.htm` file.

**Comment by John-A-Davies** [comment]
In the build, the current SPACE(20,200) allocation for the DDDEF of SYSUT1 in Z0PTFUCL and ZWE1SMPE has always allowed for a maximum of 3220 CYLINDERS which is 48,300 TRACKS, far bigger than the maximum space allowable for a PTF.  The max PTF size is 7,164 tracks (478 CYL).  So the APPLY step will work provided there is adequate free space on the VOLUME.

The readme.htm file also contain JCL, but that is only for the two datasets that hold the PTF itself, not for the DDDEF for the SYSUT1 work dataset that is used by APPLY.

**Comment by John-A-Davies** [comment]
Similar failure here:
    https://wash.zowe.org:8443/job/zowe-install-test/job/staging/774/consoleFull
This time it's E37-04 on a PDSE, dsn=ZOWEAD3.SMPE.SZWEAUTH on volume VPMVSC (which was low on space)
on the Marist ACF/2 system.

@stevenhorsman @jackjia-ibm  FYI.
