### ISSUE TITLE
The validate-port-available.sh script may cause a false positive.

### ISSUE THREAD

**Issue by vit-tomica** [zowe/zowe-install-packaging#1487]
**Describe the bug**
A subject of the issue is the following line:
https://github.com/zowe/zowe-install-packaging/blob/94d7b3f5cef53433800bf6a71619835752530b0b/scripts/utils/validate-port-available.sh#L15

**To Reproduce**
An example of the false positive:

Assume that we select a port 12345 for some component of Zowe.
Then we may get:
```
#onetstat -P 12345
MVS TCP/IP NETSTAT CS V2R4       TCPIP Name: TCPIP           15:16:44   
User Id  Conn     Local Socket           Foreign Socket         State   
-------  ----     ------------           --------------         -----   
SOMEJOB 00187C2F 175.140.152.87..9876   181.240.123.25..12345  Establsh
```
The script detects that the port 12345 belongs to a foreign socket which may reside for example on a different system but the port is available locally. 

**Expected behavior**
The script should not count such ports described in the example above.

**Comment by stevenhorsman** [comment]
@vit-tomica - this code doesn't existing the staging branch anymore. Can you test against the new version and see if there is still a problem as I tried to fix this specific issue by adding `-c SERVER` to the onetstat

**Comment by vit-tomica** [comment]
@stevenhorsman I'm not sure I'll be able to recreate it but I'll give it a try.

**Comment by vit-tomica** [comment]
It seems that the new code in staging resolves the issue. I close the issue.
