### ISSUE TITLE
Allow APIML LOG_LEVEL=debug to be set in instance.env

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#1496]
**Is your feature request related to a problem? Please describe.**
The APIML can be set to increase logging by adding the line
```
LOG_LEVEL=debug
```
to the `start.sh` script in `<ROOT_DIR>/components/api-mediation/bin`
https://docs.zowe.org/stable/troubleshoot/troubleshoot-apiml.html#enable-api-ml-debug-mode
The problem with this is that is involves asking a user to update their Zowe runtime directory

**Describe the solution you'd like**
A way to specify the logging level at startup, such as with an `instance.env` variable, e.g.
```
APIML_LOG_LEVEL=debug
```
and adding this to the default and commented out

**Comment by NakulManchanda** [comment]
after i turn on 
LOG_LEVEL=debug
- i am unable to fetch log file - it becomes huge to transfer over network. 
- if forget to turn off - run out of spool space
Not related to this just general comment.

**Comment by stevenhorsman** [comment]
I think this has been completed in 1.17, just need to update the docs to match.

**Comment by Joe-Winchester** [comment]
@NakulManchanda - APIML_DEBUG_MODE_ENABLED=false is now added to the instance.env file when `zowe-configure-instance.sh` is executed.  If you have an older `instance.env` from a pre 1.17 workspace file try manually adding this parm.
