### ISSUE TITLE
Improve ease-of-use of certificates

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1500]
*Customer content*

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when users come to me with a certificate problem and I can't quickly rectify the problem.

**Describe the solution you'd like**
The documentation should be so clear and concise, and the install and configuration system should be so foolproof, 
that users never get into these error situations.  That's the ideal. 

**Describe alternatives you've considered**

- Improvements to base documentation
- Improvements to install & config scripts
- Problem detection and correction methods
- Certificate verification mechanism, prior to attempted use in execution
- a troubleshooting guide.  (we have an incomplete solution if users have to resort to this)
- provide debugging/tracing options

**Additional context**

We should address the biggest, commonest problems first, and deliver these improvements progressively, possibly over several iterations.

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** zowe installer,  
**I want** to configure certificates  
**so that** I can use an existing certificate on my z/OS machine held in a SAF keyring

**As a** zowe user,
**I want** to trust a Zowe self-signed certificate
**so that** I don't have to drop to incognito or accept browser warnings

**As a** zowe installer,
**I want** to configure certificates
**so that** I can create a Zowe certificate using an existing certificate authority

**As a** zowe user seeing errors,
**I want** to find an explanation of the error, get to the source of the error, and learn how to rectify it
**so that** I can get Zowe up and running

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by John-A-Davies** [comment]
An example of such an error is here:
```
After configuring ZSS for HTTPS based on ZOWE docs (create certificates, define AT-TLS rules, copy CA cert to USS and configure server.json) :
https://docs.zowe.org/stable/user-guide/mvd-configuration.html#configuring-zss-for-httpsWe are not able to logon to ZOWE Desktop and in ZWESVSTC output can see following error every time when we try logon:
2020-06-24 10:02:29.217 <ZWED:33620403> ZWESVUSR WARN (_zsf.proxy,proxy.js:119) ZWED0040W - Callservice: Service call failed.  { Error: self signed certificatete failed for auth handler org.zowe.zlux.auth.zss. Plugin response: {"success":false,"reason":"ConnectionError"} {"success":
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
```

**Comment by John-A-Davies** [comment]
Another
![image](https://user-images.githubusercontent.com/36740892/87026982-67632600-c1d4-11ea-9dea-acd2b241d461.png)

**Comment by John-A-Davies** [comment]
Another
```When I am starting zssServer, I am seeing:
Will not accept JWTs: JWT keystore configuration missing
in the zssServer***.log
```

**Comment by John-A-Davies** [comment]
Another

This type of message in the MVD logon page is common
```
Authentication failed for <n> types. Types: ["apiml"] ["zss"] etc
```
For example:

```
2020-07-06 21:59:25.826 <ZWED:16842825> ZWESVUSR WARN (_zsf.auth,webauth.js:266) ZWED0003W - epi3Ck3QJ5j9Z4HuuBZnus17lUJx1r1N: Session security call refreshStatus failed for auth handler org.zowe.zlux.auth.trivial. Plugin response: {"success":false,"reason":"ZLUXSessionExp"}
in my error log and on the Zowe log-in panel I am getting:
Authentication failed for 1 types. Types: ["apiml"]
I wonder if I somehow might have stale certificates (I regenerated them on the z/OS side)?
```

**Comment by John-A-Davies** [comment]
Another ... why can't the user find the errors they need to see?
```
I can get into Zowe, and I can run the 3270 terminal, but I get 'Unable to Authenticate' for JES Explorer and MVS Explorer. 
I don't see any errors in any logs or the console that I can find, but maybe there is another job I should be checking?
```

**Comment by John-A-Davies** [comment]
Two users, different results:

```
in my safari browser i see:
```
![image](https://user-images.githubusercontent.com/36740892/87028251-43084900-c1d6-11ea-9235-860a3a969846.png)

Windows user:
![image](https://user-images.githubusercontent.com/36740892/87028300-574c4600-c1d6-11ea-8778-93eae3f1e135.png)

**Comment by John-A-Davies** [comment]
Perhaps we need a "Help! I'm lost" guide.  It might have 3 steps for each fault:

1.  I have an error message, which component or file do I have to check, and how can Zowe help me with that?
2.  Which part of the doc explains my error situation?
3.  Give me step-by-step instructions and pictures to get me working

**Comment by John-A-Davies** [comment]
And perhaps a tutorial ... "this is a trust store, and this is a key store, and this is how they work ... "

**Comment by MarkAckert** [comment]
Closing this issue. We've made multiple enhancements to the certificate setup process, whether self-signed or imported, since this was opened. There's certainly some usability issues that still remain, however, we should focus on those issues individually as they are submitted.
