### ISSUE TITLE
v1.12 install-app.sh not found

### ISSUE THREAD

**Issue by F-LEMANER** [zowe/zowe-install-packaging#1503]
Hello,
I have done the upgrade from 1.9 to 1.12

In DD STDERR of STC ZWESVTC I have :
/SYSTEM/var/ZWE/inst_01/bin/install-app.sh: /var/ZWE/bin/utils/zowe-install-iframe-plugin.sh 97: FSUM7351 not found

In 1.9 install-app.sh was in /var/ZWE/instance_dir/bin/

In 1.12, I look in all dir and subdir and don't find it

![image](https://user-images.githubusercontent.com/63342548/87131073-29c5d200-c294-11ea-8433-b9f6117e9e06.png)

Thanks a lot

**Comment by stevenhorsman** [comment]
Hi @F-LEMANER - install-app.sh in still in <instance-dir>/bin in 1.12.
Did you run `zowe-configure-instance.sh -c /var/ZWE/inst_01` to upgrade your instance after you updated the runtime?

**Comment by F-LEMANER** [comment]
Hello,
Yes i ran zow-configure-instance.sh to create my inst_01
I now have manually copied install-app.sh from /var/ZWE/components/app-server/share//zlux-app-server/bin/ to
var/ZWE/inst_01/bin/
