### ISSUE TITLE
Using different Domain Names/IP Addresses by configuring APIML certificate

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/zowe-install-packaging#1511]
*Customer content*

**Is your feature request related to a problem? Please describe.** _Yes_

_The customer requires to configure ZOWE/IZSME on two different network interfaces/IP addresses, so that it can be connected/accessible from all sites.  External users using a different address then the internal staff. How they can configure ZOWE so that both side can work with a valid certificate?_

**Describe the solution you'd like**

_It seems there is no way to configure it correctly from zowe-setup-certificates.env , so the user will have to modify line 105 from zowe-setup-certificates.sh _(https://github.com/zowe/zowe-install-packaging/blob/master/bin/zowe-setup-certificates.sh#L105)_ to include domain names or IP addresses:_

_SAN="SAN=dns:${ZOWE_EXPLORER_HOST},ip:${ZOWE_IP_ADDRESS},dns:localhost.localdomain,dns:localhost,ip:127.0.0.1"_

_But if Zowe runtime environment ​is located in a READ-ONLY file system, modifying  (zowe-setup-certificates.sh) to include this solution would not be possible. So we require a solution/parameters which should be applied through zowe-setup-certificates.env._

**Describe alternatives you've considered**

**Additional context**

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by jackjia-ibm** [comment]
@NayerNajafi this is the USERMOD can be tested https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/1.14.0-USERS-JACK-MULTIPLE-DOMAINS-FOR-CERT/zowe-smpe-1.14.0-users-jack-multiple-domains-for-cert-2-20200717220036.zip. With this USERMOD, the user can add multiple domains to `HOSTNAME=` entry of `zowe-setup-certificates.env` separated by comma.

**Comment by jackjia-ibm** [comment]
@NayerNajafi After some tests on the USERMOD, I think it works in some cases, but may have problems depends on the customer environment.

First, the USERMOD itself is ok, functionalities verified ok. But besides `HOSTNAME=` definition on `zowe-setup-certificates.env`, the customer also needs to modify `instance.env`, the value of `ZOWE_EXPLORER_FRAME_ANCESTORS=`. The original value is `ZOWE_EXPLORER_FRAME_ANCESTORS="${ZOWE_EXPLORER_HOST}:*,${ZOWE_IP_ADDRESS}:*"`. It needs to be changed to include all domains they are using in the format of `<domain>:*,`. For example, `ZOWE_EXPLORER_FRAME_ANCESTORS="${ZOWE_EXPLORER_HOST}:*,another-domain.com:*,${ZOWE_IP_ADDRESS}:*"`.

The case this fix won't work is the primary domain they defined in `ZOWE_EXPLORER_HOST` cannot be resolved for his users. For example:

- `user group A` uses domain `domain-a.com`,
- `user group B` uses domain `domain-b.com`.

If they define `ZOWE_EXPLORER_HOST=domain-a.com`, then user group B will have issue they cannot resolve `domain-a.com`.

To properly solve this issue requires much more changes, and also documentation updates:
- remove host/port hardcoded in explorer UI index.html
- update documentation explaining that accessing Desktop with port 8544 won't work. The proper way to visit Desktop is using `https://<host>:<gateway-port>/ui/v1/zlux`.

**Comment by jackjia-ibm** [comment]
Just copy over the config instructions from PR:

If the user plans to use multiple domains for the Zowe instance, there are several configurations required. Below description uses `domain-a.com` and `domain-b.com` as example.

1. In `bin/zowe-setup-certificates.env` from runtime folder, the value of `HOSTNAME=` should be `domain-a.com,domain-b.com`. This should be done before running `bin/zowe-setup-certificates.sh`.
2. After Zowe instance directory is created, modify `instance.env`.
  * Add line `ZWE_EXTERNAL_HOSTS=domain-a.com,domain-b.com`
  * Add line `ZWE_REFERRER_HOSTS=domain-a.com,domain-b.com`
  * Find line starts with `ZOWE_EXPLORER_FRAME_ANCESTORS` and modify to `ZOWE_EXPLORER_FRAME_ANCESTORS="${ZOWE_EXPLORER_HOST}:*,domain-a.com:*,domain-b.com:*,${ZOWE_IP_ADDRESS}:*"`. The value should be in one line.

With this change, the user has to use gateway port to access Desktop like this: https://domain-a.com:7554/ui/v1/zlux or https://domain-b.com:7554/ui/v1/zlux. Using Desktop port like https://domain-a.com:8544/  is not supported.

**Comment by stevenhorsman** [comment]
@jackjia-ibm - this item is in new state, but I think the code has been merged. Is there anything outstanding? What about doc updates?

**Comment by jackjia-ibm** [comment]
@stevenhorsman that's good question. I can update doc website related pages but with a little hesitation. One consequence of this change is it introduced incompatibility from previous versions which we may not want to advertise widely because we are in LTS. The incompatibility is this change does not supports the claim in this page: https://docs.zowe.org/stable/user-guide/zowe-getting-started-tutorial.html#prerequisites-and-assumptions `httpsPort is the value that was assigned to node.https.port in zluxserver.json`. This requires the httpsPort has to be gateway port and url is slightly different.

But I think we can add this to troubleshooting section and we suggest the user to always use desktop with gateway port in next LTS. Do you think this is a good idea?

**Comment by stevenhorsman** [comment]
Hi Jack, sorry for the delay. I think that if there if you are worried about backwards compatibility then troubleshooting is a great idea and we need to make sure that these changes (and probably the related internal/external host) are fully designed into v2

**Comment by jackjia-ibm** [comment]
I added it to troubleshooting section. Please see if it's appropriate https://github.com/zowe/docs-site/pull/1349. Thanks @stevenhorsman.
