### ISSUE TITLE
GROUP name needs to be corrected in CONNECT command of ZWESECUR JCL

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/zowe-install-packaging#1514]
**Describe the bug**
_The CONNECT command in ZWESECUR has the wrong group variable/name:
/* CONNECT (userid,userid,...) GROUP(ADMINGRP.) AUTH(USE)           */_

**To Reproduce**
_If we uncomment the command and run it, we will get:
IKJ56702I INVALID GROUP NAME, ADMINGRP.
IKJ56701I MISSING GROUP NAME(S)+       
IKJ56701I MISSING EXISTING GROUP NAME_  

**Expected behavior**
_It should be:
/* CONNECT (userid,userid,...) GROUP(&ADMINGRP.) AUTH(USE)           */_

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by John-A-Davies** [comment]
Superseded by #1515
