### ISSUE TITLE
Install does not check that java is 64-bit

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1516]
**Describe the bug**
```
Just updated to V1.11, now getting this message three times (and servers aren't starting): CEE3501S The module libjli.so was not found.
          From entry point main at compile unit offset +000000AA at entry offset +000000AA at address 2F70C1CA.
```

**To Reproduce**
1. Install Zowe v1.11 on a system with 32-bit JVM
2. Start servers
3. See error

**Expected behavior**
Install fails with error message if JVM is not 64-bit

**Additional context**
Script `java-utils.sh` checks version is high enough, but not that the JVM/JRE is 64-bit.

**Comment by stevenhorsman** [comment]
@John-A-Davies - I think this problem has been diagnosed incorrectly. I was just writing the 64 bit check, when I checked our doc, which doesn't mention 64-bit Java is required, so I tried running Zowe using 31-bit Java and everything started up fine

**Comment by John-A-Davies** [comment]
OK.  That problem came in from Steve Bohn, bohns@us.ibm.com.  Perhaps he can shed some more light on the case.

**Comment by NayerNajafi** [comment]
@John-A-Davies - According to Zowe documentation, the required Java level is **IBM® 64-bit SDK for z/OS®, Java Technology Edition V8 or later** I think the Java level that Steve Bohn is using is 31-bit SDK. 
--

**Comment by stevenhorsman** [comment]
@NayerNajafi - where are you seeing this? The Zowe system requirements page looks like this:
![image](https://user-images.githubusercontent.com/35110159/88064038-a729f600-cb62-11ea-9db8-a3861b467813.png)

**Comment by NayerNajafi** [comment]
@stevenhorsman Oh, my bad. The one that I mentioned is for z/OSMF not Zowe. Sorry!

**Comment by NayerNajafi** [comment]
But seems the documentation needs to be updated for SMP/E part:
![image](https://user-images.githubusercontent.com/44011615/88065099-2a832180-cb3a-11ea-96ed-641670a636fb.png)

**Comment by bohns** [comment]
Sorry to be so late getting back to this but was on vacation. 

We had been using the 31-bit JDK, but when we tried to start 1.11 we got the error (three times):

CEE3501S The module libjli.so was not found.
          From entry point main at compile unit offset +000000AA at entry offset +000000AA at address 2F70C1CA.

I saw the specification that @NayerNajafi posted so we changed the path to the 64-bit SDK and the errors disappeared.
