### ISSUE TITLE
Add SMPHOLD HOLDDATA for changes in issue #1395

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1518]
**Describe the bug**
Changes introduced by #1395 require HOLDDATA

**To Reproduce**
Steps to reproduce the behavior:  n/a
**Expected behavior**

HOLDDATA is supplied

**Additional context**
Doc changes will also be required, to describe extra steps required, for convenience and SMP/E builds.

**Comment by John-A-Davies** [comment]
@nannanli Doc change required?

**Comment by nannanli** [comment]
@John-A-Davies Hi John, yes, it seems users are required to take action when they upgrade to v1.14 so there must be at least an action required section in the release notes to help users successfully upgrade. Some descriptions similar to the following one: 

**Actions required for the upgrade**

The security definitions (ZWESECUR JCL and workflow) are updated to allow the AUX server to use the XMEM cross memory server. The ZWENOSEC JCL is updated to remove this permit. Therefore, when you upgrade to v1.14, you must update your existing customized ZWESECUR JCL to duplicate this change, and execute the command applicable to your security environment to grant this permit.

Can we clarify: 

1. What the permit is? 
2. What commands are needed to be executed?
