### ISSUE TITLE
Automate AT-TLS Configuration

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1530]
*Customer content*

**Is your feature request related to a problem? Please describe.**

For security consideration, the default HTTP connection should be disabled. Ports listened on plain HTTP should be protected with AL-TLS. If no way to convert HTTP to HTTPS connection, we should automate the AT-TLS configuration for ease for user.

**Describe the solution you'd like**

Create configure script to setup AT-TLS for ZLUX Agent (default port 8542).

**Describe alternatives you've considered**

Convert ZLUX Agent to implement HTTPS.

#### Acceptance Criteria

**Scenario 1:* After Zowe is installed, all ports listened by Zowe components should be HTTPS by default.
**Scenario 1:* The AT-TLS configuration step should be added to Ansible playbook to automatically configure Zowe components in desired way.

**Comment by 1000TurquoisePogs** [comment]
Accomplished in v2.17.0 via `zowe.network.server.tls.attls=true`
