### ISSUE TITLE
Integrate zowe-launcher (Stage 1)

### ISSUE THREAD

**Issue by ifakhrutdinov** [zowe/zowe-install-packaging#1544]
*Customer content*

**Is your feature request related to a problem? Please describe.**

We'd like to be able to:
* Terminate Zowe using the `P` operator command
* Restart specific components
* Handle modify commands

**Describe the solution you'd like**

The [zowe-launcher](https://github.com/ifakhrutdinov/zowe-launcher) projects needs to be integrated with this repository.

**Fixes**
* https://github.com/zowe/zowe-install-packaging/issues/1137
* #790

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by ifakhrutdinov** [comment]
@jackjia-ibm, @stevenhorsman [the code](https://github.com/zowe/zowe-install-packaging/tree/users/irek/zlaunch/zowe-launcher) has been placed into the zowe-install-packaging, but so the whole packaging structure seems to be a lot more complicated that I thought.

Here's what needs to be done:
* The launcher needs to be built using make. Where do I invoke it during the build process?
* As the result of the build, there will be a new load library created, where (and how) should it go?
* There is a new JCL for starting the launcher. What pieces do I need to change so that this JCL ends up in the right place in the result pax?
* There is a new config file. Same question as previous. What do I change for it to be placed to the right place.

Perhaps you can forward this to the folks who are responsible for the corresponding items inside zowe-install-packaging.

Thanks,
Irek

**Comment by jackjia-ibm** [comment]
Thanks a lot Irek. I will work with you to maybe build another pipeline to compile/build/publish/release this tool. Then zowe-install-packaging may just add it into binaryDependicies. I think this should allow zowe-install-packaging to concentrate on install and packaging purpose and the release of zowe launcher will be handled outside this repo.

For the load lib, JCL changes and config changes, I will work with you to understand more how it works before we start to modify the packaging process.

**Comment by MarkAckert** [comment]
- Create new repository for Zowe launcher
- Investigate remaining tasks, see if tasks can be rebalanced
- This may be converted into an epic, many stories are required to complete the Zowe launcher

**Comment by ifakhrutdinov** [comment]
@jackjia-ibm, 

> Create new repository for Zowe launcher

Will you do that? I don't think I can make repos in the Zowe project. Once done I'll move the content from [ifakhrutdinov/zowe-launcher](https://github.com/ifakhrutdinov/zowe-launcher)

**Comment by jackjia-ibm** [comment]
@ifakhrutdinov i created https://github.com/zowe/launcher and granted you permission. I may setup a GitHub team so we can add more people easily.

@MarkAckert for your awareness. Also just found the default branch is called `main` now. I probably rename it back to our convention.

**Comment by jackjia-ibm** [comment]
Thanks @ifakhrutdinov @1000TurquoisePogs @stevenhorsman joined the discussion. Based on meeting, here is the suggestion for stage 1 implementation: [zlaunch-suggestions.pptx](https://github.com/zowe/zowe-install-packaging/files/5331236/zlaunch-suggestions.pptx).

I couldn't convert this into an epic, but there are several github issues are linked to this item:

- [HA: Modify ZWESVSTC procedure program to be Zowe Launcher](https://github.com/zowe/zowe-install-packaging/issues/1716)
- [HA: Split run-zowe.sh into utility scripts and create "start-component.sh"](https://github.com/zowe/zowe-install-packaging/issues/1717)
- [[Stage 1] Allow Zowe Launcher to monitor process IDs for failure](https://github.com/zowe/launcher/issues/1)
- [[Stage 1] Standardize Zowe Launcher logs](https://github.com/zowe/launcher/issues/4)

There are also several other issues created in https://github.com/zowe/launcher/issues.

**Comment by jackjia-ibm** [comment]
Majority of features we need to HA are already in place except for item 3 and 4 defined in https://github.com/zowe/launcher/issues/6, which is optional for now. Would like to close this and move to next stage.
