### ISSUE TITLE
zowe-install-xmem.sh is looking for the wrong PROC names

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1550]
**Describe the bug**
zowe-install-xmem.sh instructs zowe-copy-to-JES.sh to look for PROC names ZWESASTC and ZWESISTC, which are not used in the the ZWESASTC and ZWESISTC sample members, causing warning messages that can be easily avoided.

**To Reproduce**
invoke zowe-install-xmem.sh

**Expected behavior**
Update zowe-install-xmem.sh to check for the actual PROC names (ZWESAUX and ZWESIS01), or update the build pipeline and alter the PROC names to be ZWESASTC and ZWESISTC.

**Comment by John-A-Davies** [comment]
This was simply a basic, nice-to-have check to ensure that the PROCs being copied were in the right code page, that they were JCL statements, and that some of the right JCL statements were present.  As it stands the sources for these PROCs don't use their member name as the PROC name internally, which is unusual (they use the PGM name instead).  So the real fix is to change the source to have member name as the PROC name.  

If not, it's simpler to just remove that check.  If you must have the check, you need an extra parameter for the PROC name.  The PROC name doesn't really matter - if a check is wanted then it would be better to check the PGM= value, but again, that means passing an extra parameter.



Changing the internal PROC names in the pipeline adds more confusion.

**Comment by OnnoVdT** [comment]
I agree that altering it in the build pipeline is not ideal, but changes to XMEM samplib source are taking forever. We still have an open issue that dates from when I started on writing the SMP/E packager. The build pipeline currently fixes the errors in the provided source.

If the test is just for codepage check,, I advise to change it to test for // as the first characters of the first line. That will work for any proc. And I also think that if we wnat to do this test we should move it to the build pipeline, it's too late when this problem pops up at the customer system.

**Comment by John-A-Davies** [comment]
Right.  So I suggest we comment out the test at line 140 of `zowe-copy-to-JES.sh`
```
echo Check name of ${input_member} PROC | tee -a ${LOG_FILE}
cat "//'$samplib(${input_member})'" | grep -i "^//${input_member} *PROC" 1>> $LOG_FILE 2>> $LOG_FILE
if [[ $? -ne 0 ]]
then
  echo Did not find PROC name \"${input_member}\" in "$samplib(${input_member})" | tee -a ${LOG_FILE}
  echo PROC statement is : | tee -a ${LOG_FILE}
  cat "//'$samplib(${input_member})'" | grep "^//[^ *][^ ]*  *PROC" | tee -a ${LOG_FILE}
fi
```
with a note to re-instate it when the PROC member name is updated to its correct value.

**Comment by OnnoVdT** [comment]
update done in PR https://github.com/zowe/zowe-install-packaging/pull/1551
