### ISSUE TITLE
Smoke test failures detected in zowe pipeline run

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zowe-install-packaging#1556]
**Describe the bug**
install-and-test-zowe pipeline detected smoke test failures with the latest zowe build(PAX and SMPE: 1.14.0-staging-898-20200729091533)
    cli check zosmf status.should be able to return zosmf status
    cli list jobs of ZWE*.should have an active job ZWE1SV
    cli list data sets of SYS1.LINKLIB*.should have an data set of SYS1.LINKLIB
    cli list data sets of SYS1.LINKLIB*.should be able to download file SYS1.LINKLIB(ACCOUNT)

Error Message:
expected '(node:980) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to \'0\' makes TLS connections and HTTPS requests insecure by disabling certificate verification.\n' to be empty

**To Reproduce**
1. zowe installation is ok
2. run smoke test suites
3. See error:
    cli check zosmf status.should be able to return zosmf status
    cli list jobs of ZWE*.should have an active job ZWE1SV
    cli list data sets of SYS1.LINKLIB*.should have an data set of SYS1.LINKLIB
    cli list data sets of SYS1.LINKLIB*.should be able to download file SYS1.LINKLIB(ACCOUNT)

**Expected behavior**
smoke test cases should pass

**Additional context**
Worked with Jack that zowe pipeline using updated Node.js vs OSS is still using old version of Node.js
Tried to add NODE_TLS_REJECT_UNAUTHORIZED=0 in instance.env, restarted zowe and reran smoke tests, failures are still there.

**Comment by raymondyanli** [comment]
Currently we are using node.js: node-v8.17.0-os390-s390x (VM for PAX build) and node-v12.18.0-os390-s390x(VM for PTF build). Above issue happened on both VMs.

**Comment by stevenhorsman** [comment]
It looks like the tests that are failing are in the cli, so not related to instance.env, or the node version on z/OS. 
Where are you seeing the failure - in z/OSMF logs, or on the client side?
Assuming it is the client-side what is the node version of the client machine/docker image or wherever you have the CLI installed on?

**Comment by raymondyanli** [comment]
One thing we have changed recently is we upgraded node.js version from 8 to 12.18.3 on the test side.

**Comment by raymondyanli** [comment]
The test failures have been fixed with:
https://github.com/zowe/zowe-install-packaging/pull/1572
