### ISSUE TITLE
Typo in HOLDDATA for UO01951

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1574]
**Describe the bug**
```
* Part: $ZOWE_ROOT_DIR/workflows/*                             *
...
More details are avialable in the online documentation:   
```

**Expected behavior**
```
* Part: $ZOWE_ROOT_DIR/workflows/*                             *
...
More details are available in the online documentation:   
```

**Additional context**
You can see this in the output from the APPLY job.

**Comment by OnnoVdT** [comment]
Can't believe I used `/*` right after I told you HOLD cannot have it :(.
Running a build now, https://wash.zowe.org:8443/job/zowe-install-packaging/job/onno-1574-hold/

**Comment by John-A-Davies** [comment]
The actual typo I meant is in this line:

```
More details are avialable in the online documentation:
```

**Comment by OnnoVdT** [comment]
Ah, now I see it. Fixed that too.
