### ISSUE TITLE
Adding additional test cases

### ISSUE THREAD

**Issue by JadinLuong** [zowe/zowe-install-packaging#1602]
*Customer content*

**Is your feature request related to a problem? Please describe.**
Additional test cases should be added to ensure necessary and specific parts/features of Zowe is working as intended.

**Describe the solution you'd like**
The necessary test cases are broken up into three parts. E2E test cases, CLI test cases and API test cases.

Below are some of the test cases that can be added to the test suites:

**E2E Test Cases**
At the moment, the current E2E tests will suffice.

**CLI Test Cases**
Zowe's _zos-console_ command could be tested.

**API Test Cases**
The following API endpoints listed below could be tested:
_GET: /api/v1/datasets/username_

_GET: /api/v1/jobs/{zoweJobName}/{jobId}
GET: /api/v1/jobs/{zoweJobName}/{jobId}/files
GET: /api/v1/jobs/{zoweJobName}/{jobId}/files/2/content
GET: /api/v1/jobs/{zoweJobName}/{jobId}/steps
GET: /api/v1/jobs/username_

_GET: /api/v1/unixfiles?path=/{zoweInstallDir}
GET: /api/v1/unixfiles/{zoweInstallDir}/instance.env_

**Comment by stevenhorsman** [comment]
@JadinLuong - I think that most if not all of the jobs tests are already done in the https://github.com/zowe/jobs repo.
Is there a reason that you specifically want to test those particular directory/file in unix api tests, otherwise they should also be covered in https://github.com/zowe/data-sets?

**Comment by jackjia-ibm** [comment]
Thanks @stevenhorsman for the input. @JadinLuong let's simplify the API coverage to these 3 endpoints.

GET: /api/v1/datasets/username
GET: /api/v1/jobs/username
GET: /api/v1/unixfiles?path=/{zoweInstallDir}

We currently already covered `GET /api/v1/jobs?owner&prefix` test, I agree this should be enough from smoke test point of view. We don't have any on `/api/v1/unixfiles` right now, let's add one test to quick verification.
