### ISSUE TITLE
ZWESECUR, ZWENOSEC, ZWEKRING have RC 0 even when failed

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#1615]
These jobs all have an rc 0 even when commands fail. We should fix these so that it doesn't report working when it's not.

**Comment by Martin-Zeithaml** [comment]
There is a warning in each job to verify all commands, for example `ZWEKRING`:
```
//* 4. This job WILL complete with return code 0.
//*    The results of each command must be verified after completion.
```
