### ISSUE TITLE
Zowe SMP/E z/OSMF Workflow installation - HLQ parm is not set up properly in RECEIVE step 

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/zowe-install-packaging#1631]
**Describe the bug**
I installed Zowe FMID function with z/OSMF workflow definition ZWEWRF01 (available with Zowe 1.14). Receive step failed because the hlq parameter is not set up properly. The receive JCL shows HLQ as **HLQ='${!hlq}'** so that the HLQ defined value (from step1) cannot be placed in this parameter. 

**To Reproduce**

**Expected behavior**
HLQ parm should be HLQ='${hlq}' in workflow definition.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jp669844** [comment]
Closing: #1605
