### ISSUE TITLE
zowe-promote-nightly-staging has false positives

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#1661]
**Describe the bug**
On 17th September both convenience and smpe ptf test jobs failed with timeout. The nightly promote didn't realise this and thought they'd passed, so promoted them and reported to slack that they were good builds.

**To Reproduce**
1. Create a branch and lower the timeout to something very short
2. Run the build
3. See that even with some stages timing out, it think it was successful

![image](https://user-images.githubusercontent.com/35110159/93461025-0cd4fd00-f8dc-11ea-97b6-cfef06baf5a9.png)

![image](https://user-images.githubusercontent.com/35110159/93461063-178f9200-f8dc-11ea-8f01-7a2cce0e3cf1.png)

**Comment by Roavill2** [comment]
PR 1668 merged - UNSTABLE condition now met when install-tests fail

**Comment by stevenhorsman** [comment]
The pipeline marks test failures correctly, but exits before it does the promote and messaging.
In future please don't close issues until they have have through and been tested overnight.

**Comment by Roavill2** [comment]
New fix put in place for this - will wait for confirmation this is working as expected in nightly builds until I close again.

**Comment by Roavill2** [comment]
Has been used over the weekend and appears to have worked as expected. Closing out issue - hopefully for the final time.

**Comment by Roavill2** [comment]
We have just had a scenario where the install-tests that are triggered by the nightly pipeline are timed out so are aborted, but return under the pipeline they class that as successful. 

Need to add logic so that if this happens, the unstable state is set to true.
