### ISSUE TITLE
Make the 'localca' label to be a variable in a keyring scenario 

### ISSUE THREAD

**Issue by vit-tomica** [zowe/zowe-install-packaging#1669]
*Customer content*

**Is your feature request related to a problem? Please describe.**
Since ZWEKRING jcl allows to choose a label of a Zowe local CA then this has to be reflected in other configuration scripts.
https://github.com/zowe/zowe-install-packaging/blob/b630308db85568d208a01560184341475b05f030/files/jcl/ZWEKRING.jcl#L113

The scripts are:
https://github.com/zowe/zowe-install-packaging/blob/staging/bin/zowe-setup-certificates.env (add a new variable here, e.g. ZOWE_LOCALCA_LABEL)
https://github.com/zowe/zowe-install-packaging/blob/staging/bin/zowe-setup-certificates.sh (process the new variable above so that it will appear in the generated zowe-certificates.env file)
https://github.com/zowe/zlux-app-server/blob/c5662916bea0a471236303f237238dc153513e2a/bin/convert-env.sh#L78 (Replace a hardcoded 'localca' value with the variable in the generated zowe-certificates.env file)
 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

---
*Engineering team info *

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by stevenhorsman** [comment]
@vit-tomica - I think this issue has been resolved now, so can it be closed?

**Comment by vit-tomica** [comment]
@stevenhorsman Yes, thanks for reminding me. Closing it.
