### ISSUE TITLE
Add ability to test performance of multiple endpoints in parallel

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1685]
Create new base test case class which allows to test multiple endpoints in parallel. There are 2 ways to test multiple endpoints:

- randomly selected from a set of endpoint list based on the weight.
- define a test scenario and run multiple endpoints in sequence for the same thread. With support of multiple threads, we can say different endpoints are tested in parallel.

**Comment by jackjia-ibm** [comment]
Solved by https://github.com/zowe/zowe-dependency-scan-pipeline/pull/32

**Comment by jackjia-ibm** [comment]
Examples can be found here https://github.com/zowe/zowe-dependency-scan-pipeline/tree/master/performance/client/src/__tests__/examples

**Comment by jackjia-ibm** [comment]
@jordanCain I believe this is something you asked for if I'm not mistaken. Please see if this fulfills your requirement and I can fix it if you think we need improvements. Thanks!

**Comment by jordanCain** [comment]
@jackjia-ibm Yes this looks to cover what I had in mind, I think the most value will come from the sequenced tests as we should be able to see a degradation or improvement overtime
