### ISSUE TITLE
HA: Gateway with D-DVIPA under Sysplex

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1687]
**Is your feature request related to a problem? Please describe.**

The feature supports the overall [Zowe HA plan](https://github.com/zowe/zowe-install-packaging/issues/1477). This feature is relevant for Sysplex deployment.

**Describe the solution you'd like**

Multiple gateway instances are able to work as expected using D-DVIPA enabled in Sysplex.

**Additional context**

We may also need port sharing if we want to start multiple Gateways in one of the LPAR which is also a part of Sysplex.

**Comment by MarkAckert** [comment]
@jalel01 @balhar-jakub FYI

**Comment by balhar-jakub** [comment]
@jandadav It seems we used to have this setup internally, maybe we can share our knowledge somehow with Nayer?

**Comment by jandadav** [comment]
@jackjia-ibm , do you expect to document the needed DVIPA for HA sysplex setup as part of this issue?

**Comment by jandadav** [comment]
Yes, we have DVIPA setup on our system. I am not aware how it's setup or if we can alter it, but definitely it would be good to define a official DVIPA guidance for customers. That would also tell us if our system is setup correctly.

**Comment by jackjia-ibm** [comment]
@balhar-jakub @jandadav yes that will be really helpful if can share the info with Nayer. I original think this will also be the item to prepare the documentation. But if we think it's better to have a new issue to handle the documentation, I'm completely ok.

**Comment by NayerNajafi** [comment]
Hi @balhar-jakub
We have now DVIPA configured on our Sysplex. The configuration works for z/OSMF HA Active-Active mode. Just wondering if there is the info or something you could share in order to try Gateway with DVIPA.
CC: @jackjia-ibm

**Comment by NayerNajafi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing Gateway with distributed DVIPA](https://trello.com/c/8L8zYhJu/22-testing-gateway-with-distributed-dvipa)

**Comment by jackjia-ibm** [comment]
With similar Sysplex Distributor definition on gateway, this works as expected and we can see requests are routed to both gateways.
