### ISSUE TITLE
HA: define manifest file for Zowe packages to simplify Zowe Launcher configurations

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1692]
*Customer content*

**Is your feature request related to a problem? Please describe.**

To simplify the configuration for Zowe Launcher, the definition of the zowe packages should be self-explained. Zowe Launcher should be able to determine the proper way to handle lifecycle of the component by reading the manifest file.

**Describe the solution you'd like**

- Create manifest.json for each Zowe components.
- The manifest.json should include these basic definitions: name, id (long identifier matches Artifactory publish path), description, build information, version.
- The manifest.json should support to define lifecycle commands in 2 ways:
  * USS shell scripts
  * JES start command
- The supported lifecycle commands can be handled by Zowe Launcher are: `start`, `stop`. For `stop`, we may have default behavior for shell script by sending SIGTERM signal, and `P <jobid>` for JES.

**Additional context**

This issue can be related to https://github.com/zowe/zowe-install-packaging/issues/1440, https://github.com/zowe/zowe-install-packaging/issues/1544 and https://github.com/zowe/zowe-install-packaging/issues/1199.

**Comment by MarkAckert** [comment]
Combine with other investigations on common packaging model, Zowe plugin installation Ansible scripts

**Comment by jackjia-ibm** [comment]
Proposal of manifest file [package-manifest-suggestions.pptx](https://github.com/zowe/zowe-install-packaging/files/5388392/package-manifest-suggestions.pptx).

**Comment by jackjia-ibm** [comment]
Currently the manifest sections confirmed with team is:

- name: required. short, computer readable text for extension name. Example: explorer-jes. This will be the folder name under <zowe-runtime>/components or extension runtime folder. So the characters allowed in this name is same as directory name on z/OS USS.
- id: required. long, computer readable text for extension artifactory path. Example: org.zowe.explore-jes. Official Zowe extensions should be uploaded to Zowe artifactory zowe.jfrog.io.
- version: semantic version, optional but suggest to have. Example: 1.2.3. Do not add "v" before the version number.
- title: optional. A human readable name of the extension. It may be used as API Catalog tile, or Desktop Plugin menu item title.
- description: optional. A human readable description of the extension.
- commands: these commands defined below may affect installation, configuration, testing etc.
  * validate: This is original `validate` step of lifecycle script for this component.
  * configure: This is original `configure` step of lifecycle script.
  * start: This is original `start` step of lifecycle script for this component.
    - In a distributed deployment, the stages could be not in expected sequence. For example, one Zowe instance has been fully started, then we start another Zowe instance in the Sysplex.

Other specs:
- manifest can be represented as manifest.json, manifest.yaml or manifest.yml. But we prefer YAML format.

Pending questions:
- If we can support JES command in `commands.start`. Calling opercmd may require SDSF permission, which current runtime user ZWESVUSR doesn't have.
    - Original suggestion: besides defining a USS shell script, we can also define JES command in this format: `jes://S ZWESISTC`, or in a format with template variables `jes://S {{config.JOBNAME}}`

**Comment by jackjia-ibm** [comment]
Updated [package-manifest-suggestions.pptx](https://github.com/zowe/zowe-install-packaging/files/5604913/package-manifest-suggestions.pptx) version on Nov 26. Added new slide 5 for discussion: `os` and `autoTag`.

**Comment by jackjia-ibm** [comment]
There 2 few reasons that last updates on the package-manifest-suggestions.pptx are not made into final:

- `os` is complicated when we think of os versions.
- `autoTag` is not used since this information should be gathered before the installer can read the manifest. So a `--auto-encoding` option is added to `bin/zowe-install-component.sh`.

What went into final will be documented in https://github.com/zowe/docs-site/pull/1526

**Comment by jackjia-ibm** [comment]
Improvements on manifest may still be needed, but the basic support on manifest will be released with v1.19.0.
