### ISSUE TITLE
Spec. for control of creation of ZOWESVR PROCLIB member

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#170]
1.  PROCLIB member name.

- The user should be able to specify the name of the JCL member to be placed in PROCLIB.  
- The default will be ZOWESVR.
- The chosen member name will be logged by the install script and separately available for the user to discover after the install is complete.

2.  PROCLIB dataset name.

- The user should be able to specify the dataset name of the PROCLIB where the member will be placed.
- The standard dataset will be SYS1.PROCLIB.  The install script will report an error if the resultant member and dataset combination does not yield the actual JCL that will be used when the STC is started, according to the ordering rules for PROCLIB dataset concatenation.
- Another choice will be to allow the install script to choose the first PROCLIB dataset in the JES2 PROCLIB concatenation that the user can write to.
- The chosen dataset name will be logged by the install script and separately available for the user to discover after the install is complete.

**Comment by kathysychan** [comment]
The proposal looks good. I thought the current behaviour is ZOWESVR get placed in the first PROCLIB dataset in the JES2 PROCLIB concatenation that the user can write to (not to SYS1.PROCLIB). If that's the case, we should keep that default behaviour unless user specify which PROCLIB to place it in. 

Your proposal to report error if the resultant member and dataset combination does not yield the actual JCL that will be used when the STC is started, according to the ordering rules for PROCLIB dataset concatenation.

**Comment by John-A-Davies** [comment]
Suggested addition to `zowe-install.yaml`:

```
# started task JCL member for Zowe job
zowe-server-proclib:
  dsname=SYS1.PROCLIB
# dsname=auto
  membername=ZOWESVR 
```
If you specify `dsname=auto`, the installer will choose the first available PROCLIB dataset, as it did before.
