### ISSUE TITLE
HA: improve lifecycle start.sh to properly trap termination signals and kill child processes

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1702]
*Customer content*

**Is your feature request related to a problem? Please describe.**

Currently all start.sh don't handle termination signals, this may leave a child processes running after the shell script terminates. The orphan child process will be become a problem for Zowe Launcher to spin up a new process of the component.

**Describe the solution you'd like**

Modify start.sh, provide suggested signal handling template to properly trap termination signals like SIGTERM, SIGKILL, etc and make sure it won't leave any orphan child processes.

**Additional context**

Currently Zowe Launcher implemented "patches" to help on identifying the child processes. This shouldn't be necessary and seems beyond to its responsibility. Especially if the user installed extra extensions, how those components handles child processes are unknown to Zowe Launcher, it becomes impossible for Zowe Launcher to handle all scenarios.

**Comment by MarkAckert** [comment]
If anyone is interested in picking this up, please reach out

**Comment by NakulManchanda** [comment]
@jackjia-ibm it would be great if you can point which core component needs to handle this scenario gracefully? 
I am just wondering - about explorers processes in particular. If they hang, on receiving kill right now. 
Thanks!

**Comment by jackjia-ibm** [comment]
I will investigate more on this item with Irek. Original requirement is about release the duty of defining https://github.com/ifakhrutdinov/zowe-launcher/tree/master/patches from Zowe Launcher. The current way is not expandable, especially when we have extension installed.

**Comment by jackjia-ibm** [comment]
We have added signal trap to the components. The current test we have is verifying if this change breaks Zowe build and sanity test. We didn't really monitoring the processes by sending signals. Once we fix the issues with Zowe Launcher build, we will run an integration test and see if this really solves the issue.
