### ISSUE TITLE
node version check can give incorrect results

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#1704]
On some systems `node --version` gives:
```
WARNING: Could not register product for tailored fit pricing, rc = 4
v8.17.0
```
This results in the node check getting confused and issuing the message `Zowe will be ending support for Node v6 in September 2020.`

I need to try and collect a bit more debug around this so understand it, but we should potentially make the code learn to ignore any warning message.

**Comment by jordanCain** [comment]
I've verified the script does in fact work as intended even with the warning message.
