### ISSUE TITLE
Research Gaps in Testing, Define Action Plan

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#1710]
There's gaps in our integration testing (zowe-install-packaging level). Research where gaps exist, what's required to fill them in, and who should take on the work. Discuss with squads and prioritize with them, and investigate if we have capacity to write any tests ourselves (i.e. critical tests?)

Outcomes:
* Complete list of whats missing in tests, and prioritizing the work to improve them (with squads).

This may grow quickly with certificate support. There's tests in APIML?, but not in zowe-install-packaging.  Bring to TSC as well

**Comment by stevenhorsman** [comment]
The primary gaps in testing that I'm currently aware of:
- **Component testing**
  - open source component testing of the zlux components. This needs to be primarily owned by the app framework team as they have current tests, but aren't open sourced. CI/CD might need to help if there are any dependencies missing that their pytest framework needs in our images.
  - open source APIML component testing. I don't know the status of this. Are there are some 'closed' integration tests in addition to the currently open sourced unit tests that run on a broadcom pipeline that we can migrate to ours? Do we also need to consider the fact that they don't have some of the same concepts as the bulk of zowe, including no staging branch/build?
- **Smoke test/System testing**
  - We only test the basis certificate scenario (creating from scratch) and not any import of external certificates in USS and keyring, or connecting a loaded certificate in keyring. I don't think this is an area that the CI/CD squad has any expertise, so we might need to get help obtaining a 'legit' certificate.
  - We don't have any testing of ZWESECUR for TSS and ACF2 systems #1614. This might require some TSS and ACF2 expertise to make sure that the undo steps are done correctly.
  - We have no testing at all of installing and configuring by z/OSMF Workflows. I don't think any core Zowe commiters has even seen this work, so we need to decide if it is supported, or not. I'm not sure if the work is complete given that there are outstanding PRs for this.

We also need to be careful about where we draw the line of smoke testing. Currently all the smoke tests we have take ~6 hours to complete, if we add in more configurations then we are multiplying out this time to get complete coverage. Once we have transparent open source component tests we need to review the smoke tests and see if there are things that we can modify/remove to ensure we are focussed on the integration of components together and not repeating basic functionality/error case tests.
We also need to get into the habit of reviewing defect that get into the field, or only get found by manual testing before a release to see whether these scenarios can/should be included in the test pipeline somewhere.
