### ISSUE TITLE
Put versions in zowe-install.yaml file

### ISSUE THREAD

**Issue by kathysychan** [zowe/zowe-install-packaging#173]
We have a Jenkins script that handles installation of Zowe.  Since we need to customize ports that Zowe uses, we take a copy of zowe-install.yaml file and update the ports. Because we are taking a copy of the yaml file, we run a risk of having yaml file being outdated (when Zowe driver updates the yaml file). If the zowe-install.yaml file version can be put in the header of the yaml file, our script can just easily compare the versions to know the customized yaml file is outdated or not.

**Comment by kathysychan** [comment]
@Joe-Winchester As the Zowe team is making sweeping changes to the whole install and configuration experience, please consider this request for versioning the zowe-install.yaml and other configuration files so that it's easier to have automation tools work with Zowe installation and configuration.

**Comment by stevenhorsman** [comment]
@kathysychan We are removing the yaml file as part of the cupids work, so I need to understand if there are any requirements based on the design you've seen of the new configuration procedure, or if this can just close?

**Comment by kathysychan** [comment]
Yes. Our script needs to customize Zowe ports. We need to have an easy way to check versions of the file that contain Zowe configuration instance data (such as ports). This will enable our script to do "compatibility checking". We know that our script has been tested with a certain version of Zowe configuration instance format. Possible incompatibility will be flagged when we run our script if we see that the version number of the configuration data is higher than what we had tested earlier.

**Comment by jackjia-ibm** [comment]
I believe we can close this issue, since after CUPIDS applied, we don't use zowe-install.yaml any more. @kathysychan are you ok with it?

**Comment by kathysychan** [comment]
Yes. You can close this now.
