### ISSUE TITLE
Provide easy to process output for post install verify script

### ISSUE THREAD

**Issue by kathysychan** [zowe/zowe-install-packaging#174]
It's great that we now have zowe-verify-post-install.sh in Zowe 0.9.4 driver. Since we would like to run zowe-verify-post-install.sh as part of an install CI/CD pipeline, we would like to request to have the output of the script in a easy to process output format (e.g. JASON) so that the CI/CD pipeline script can easily interpret the result of the post install verify script.  We need access to information such as where Zowe is installed, which PROCLIB is Zowesvr put in, port numbers used etc.

**Comment by Joe-Winchester** [comment]
This is a great request. We could do this two ways, one of which is to dynamically output the results into the response, e.g. pass in an argument like --response-format-json  | --rfj (similar to the Zowe CLI) or else what we could do is each time the script is run we create a persistent file, e.g. zowe-config.js that contains details about what ports are used, which proclib, ...   Which would you prefer ?

**Comment by kathysychan** [comment]
Thanks for considering this request. Our preference is to dynamically output the results into the response. Please let us know if you have something for us to try out.

 @kiril-ibm  FYI.

**Comment by stevenhorsman** [comment]
Hi Kathy, as of 1.8 documentation state that zowe-verify is not update and from 1.9 it will be removed, so closing this issue
