### ISSUE TITLE
ZWE1 Subtasks stay up when Zowe main Started task is shutdown

### ISSUE THREAD

**Issue by shgordon2222** [zowe/zowe-install-packaging#1759]
ZOWE 1.15 Install   v. 1.15.0+20200828

  When we start the ZOWE started Task ZOWESVR (ZWESVSTC), it starts a bunch of other tasks all starting
with ZWE1.  AC, AD, AG, DS1(3), EF, EJ, SZ1, UD, UJ, UU.  When I shut down the task using Cancel Command,
/C ZOWESVR, not all of these tasks shutdown and appear to be left in the system.  If you keep starting and stopping
the ZWESVSTC, it gets a little messy.  Most of the time the ZWE1AG and ZWE1EJ stay up.  Sometimes I have seen the ZWE1AC.
Is this a known issue or am I special.

**Comment by stevenhorsman** [comment]
I haven't seen this behaviour myself, but at the moment we aren't doing full tracking on processes spawned by the zowe started task. This is in plan of the next few months, so should be properly resolved soon.

**Comment by shgordon2222** [comment]
Thanks for the update. For every bounce of the ZOWE main started task, I have had to stop anywhere from one to four of these subtasks.  If I leave them up and change some parameters, there is sometimes  un expected results.  I think the new Zowe started task is using the old subtask with the old information.  Just a guess.  You can see the tasks by doing a /d a,zwe1* command.

**Comment by neils-ibm** [comment]
I have the same problem.  I issue P ZWESVSTC and none of the ZWE* tasks shutdown.  I then have to issue C ZWESVSTC,A=xx approx. 5 times.  Thanks.

**Comment by shgordon2222** [comment]
Here are my issues when trying to shutdown ZOWE.

D A,ZOWEVSTC shows the following:

ZWESVSTC ZWESVSTC ZOWESTEP OWT  SO  A=00AD   PER=NO   SMC=000     

ZWESVSTC STEP1    ZWESVUSR OWT  AO  A=00D1   PER=NO   SMC=000     
 
ZWESVSTC STEP1    ZWESVUSR OWT  AO  A=00CE   PER=NO   SMC=000     

ZWESVSTC STEP1    ZWESVUSR OWT  AO  A=00A9   PER=NO   SMC=000     

ZWESVSTC STEP1    ZWESVUSR OWT  AO  A=00B6   PER=NO   SMC=000     

ZWESVSTC STEP1    ZWESVUSR OWT  AO  A=00AC   PER=NO   SMC=000     

ZWESVSTC STEP1    ZWESVUSR OWT  AO  A=00CB   PER=NO   SMC=000    
 
ZWESVSTC STEP1    ZWESVUSR OWT  AO  A=00E2   PER=NO   SMC=000    

A straight cancel on ZWESVSTC will not work.

C ZWESVSTC                                                      
IEE842I ZWESVSTC DUPLICATE NAME FOUND- REENTER COMMAND WITH 'A='
KEYWORD                                                         

You need to cancel the first one. The one that shows it running in ZOWESTEP.

C ZWESVSTC,A=00AD

This will cause all the ZWESVSTC tasks to stop.

The secondary issue is the ZWE1* tasks that do not get shutdown.

After the ZWESVSTC task has been cancelled a  D A,ZWE1*  will show those abandoned tasks. 
The name and number of leftover tasks vary with each Zowe bounce.

ZWE1AG   STEP1    ZWESVUSR IN   AO  A=00C8   PER=NO   SMC=000    

ZWE1EF   STEP1    ZWESVUSR IN   AO  A=00C0   PER=NO   SMC=000    


I believe if these tasks are not shutdown before the next Zowe start, you
may have issues with multiple sub tasks that may be at different level if 
an upgrade or change has been performed. 

You will need to do a 

C ZWE1AG,A=00C8
C ZWE1EF,A=00C0

to shutdown the tasks.

**Comment by stevenhorsman** [comment]
From @rjmaomao in #1836:
>I run zowe server with started task configured. I usually start zowe by MVS command S ZOWESVR, and stop it by C ZOWESVR. After issuing S ZOWESVR I can see there are around 20 processes created( can be viewed from SDSF S.DA or S.PS), when stop the server after issuing command C ZOWESVR, there were some processes can’t stop successfully, such as ZOWESV28, ZOWESV29. I remember I have seen all processes stoped once C ZOWESVR was issued. Not sure why those processes can’t be stopped now. I had to use MVS command such as C ZOWESVR8,A=xxx to cancel these processes manually one by one. The process that can't stop are from java code as below. I saw this same issue on different versions, including 1.11, 1.15, 1.17

```
ZOWESV29  OTHER KERNEL WAIT  java -Xms16m -Xmx512m -Dibm.serversocket    
ZOWESV28  OTHER KERNEL WAIT  java -Xms16m -Xmx512m -Xquickstart -Dibm    
ZOWESV28  OTHER KERNEL WAIT  java -Xms16m -Xmx512m -Dibm.serversocket    
ZOWESV29  OTHER KERNEL WAIT  java -Xms32m -Xmx256m -Xquickstart -Dibm   
```
>Is there any suggestion on why is this happening and how to prevent it? Thanks!

**Comment by stevenhorsman** [comment]
I'll note that we have made a change in the next version (1.18) that we hope will fix this problem, but haven't had a firm re-create here, so aren't 100%

**Comment by jackjia-ibm** [comment]
Based on yesterday's architecture call, seems Zowe Launcher may not solve the problem if the job is canceled other than purged. Cancelling the job will send KILL to the processes and Zowe Launcher may not have chance to intervene and send proper TERM signal to child processes it's managing.

This issue may be related to many ClosWait FinWait2 showing in netstat. But the difference is netstat issue seems only shows up on APIML ports, but the zombie processes may also happen on Explorer APIs. The explorer APIs are static registered and will not send heartbeat to the Discovery service. Since they are all Java programs, this could be an implementation issue of java HttpClient with keep-alive option. The client should close the connection if there is no intention to reuse the socket. But this is a guess without any test done.

**Comment by Joe-Winchester** [comment]
Issue moved to [zowe/api-layer #1009](https://github.com/zowe/api-layer/issues/1009) via [**ZenHub**](https://www.zenhub.com/)
