### ISSUE TITLE
Multiple ZOWESVR started causing errors

### ISSUE THREAD

**Issue by kathysychan** [zowe/zowe-install-packaging#176]
I found the situation that I have 3 ZOWESVR in the started task and all of them are indicated as running. When I looked closer, 2 of them were running from the Zowe 0.9.4 installed directory and one of them were running from the Zowe 0.9.5 directory. All of the ZOWESVR JCL were loaded from CAN.USER.PROCLIB. 

I think what happened is I started ZOWESVR from Zowe 0.9.4 and started another one without stopping the first one. I don't think it should result in some error message on startup (similar to zOSMF IZUSVR1) as the second one did not start completely but is still showing up as started (not abend).

Then with ZOWESVR still running, I ran the zowe-install script to install the Zowe 0.9.5 nightly driver. It replaces ZOWESVR.JCL that's in CAN.USER.PROCLIB and points to the Zowe 0.9.5 install directory. When I started ZOWESVR, the copy that's in Zowe 0.9.5 install directory got started but did not completed properly again (probably because of ports that's used by previously running ZOWESVR). 

I think the zowe install process should do more error checking to avoid these kinds of problems allowing multiple ZOWESVR to be started.

**Comment by jordanCain** [comment]
@kathysychan @Joe-Winchester @John-A-Davies I've done a little research into this issue as I kept running into it myself during development and testing.

We could issue an operator command to check if there any existing active jobs running with the same prefix, for example 
`opercmd "D A,ZOWEJC"` 
will list active jobs with the prefix ZOEJC, we can then parse that output and if any rows are found alert the user, we would run this command prior to issuing `opercmd "S ZOWEJC,SRVRPATH='"$ZOWE_ROOT_DIR"'"` in the zowe-start.sh script

**Comment by John-A-Davies** [comment]
If you know the JOBNAME, you can do that from USS, without recourse to the OPERCMD script.

`tsocmd status <jobname> | grep EXECUTING`

**Comment by stevenhorsman** [comment]
With the cupids updates multiple zowe instances can be started from the same binary by creating multiple instance directories
