### ISSUE TITLE
Blanks in certificate name caused customer issues

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#1764]
**Describe the bug**
Certificate name with a blank (e.g. `Zowe Cert` unlike the usual `ZoweCert`)
Customer reported that this failed.

**Next steps**
Re-create the problem, document if this is not supported, and if it's possible to fix then try to fix it.

**Comment by stevenhorsman** [comment]
I made a change in 1.18 which wrapped the cert names in double quotes, so this should be fixed now

**Comment by Joe-Winchester** [comment]
> I made a change in 1.18 which wrapped the cert names in double quotes, so this should be fixed now

Awesome !  Thank you @stevenhorsman
