### ISSUE TITLE
Move docker publish to zowe-promote-publish pipeline

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1766]
**Is your feature request related to a problem? Please describe.**

Currently docker push defined in Jenkinsfile will be executed with zowe-install-packaging. This gives the pipeline chance to update official latest/amd64/s390x tags without promote/release process.

**Describe the solution you'd like**

1) move the docker push commands to the release pipeline
2) every release, push `amd64` and `s390x` tags
3) then make a "manifest" of latest as well as `$CURRENT_VERISON`
4) push those manifests too

**Additional context**

Commands to update multi-arch latest tag:

```
# docker manifest create ompzowe/zowe-v1-lts:latest --amend ompzowe/zowe-v1-lts:amd64 --amend ompzowe/zowe-v1-lts:s390x
# docker manifest push ompzowe/zowe-v1-lts:latest
```

**Comment by 1000TurquoisePogs** [comment]
To elaborate on step #1, I think it is actually 2 steps
1) 
https://github.com/zowe/zowe-install-packaging/blob/4a10cf5/Jenkinsfile#L293-L304
and
https://github.com/zowe/zowe-install-packaging/blob/4a10cf5/Jenkinsfile#L228-L233
need to be moved
2) commands need to be preceded with a `docker load` command that loads the image from the artifactory `.tar` for each system (dind and zlinux)
