### ISSUE TITLE
Verify SSO setup on Marist for Top Secret

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/zowe-install-packaging#1776]
As a Zowe user, I want to know that the SSO setup works in the context for the Top Secret ESM.

At the moment the setup was done for RACF and tested within the context of https://github.com/zowe/zowe-install-packaging/pull/1713

**Comment by jackjia-ibm** [comment]
I believe TSS server works well now with discussion and fixes from https://github.com/zowe/zowe-install-packaging/issues/1778
