### ISSUE TITLE
SMP/E readme.htm is different from HOLDDATA

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1787]
**Describe the bug**
File `ZOWE.AZWE001.UO01958.readme.htm` contains some minor difference from the `++HOLD` data in the SMP/E RECEIVE job.

**differences**
```
Run <ROOT_DIR>/bin/zowe-configure-instance.sh -c            
<PATH_TO_INSTANCE_DIR> again with an updated instance.env   
to pick up the new definitions.                             
```
which is not the same as in the readme.htm
```
  Run /bin/zowe-configure-instance.sh -c 
   again with an updated instance.env
  to pick up the new definitions.
```
**To Reproduce**
1. Run RECEIVE job
2. Review ++HOLD data
3. Review File `ZOWE.AZWE001.UO01958.readme.htm`

**Expected behavior**
These files should have the same content

**Additional context**

**Comment by John-A-Davies** [comment]
There may be other differences, but this is the difference I saw.

**Comment by Joe-Winchester** [comment]
@John-A-Davies - can you please create a PR for the fix for this ?

**Comment by OnnoVdT** [comment]
looks like we have to convert characters HTML recognizes as tags to &;-notation, e.g. write `<` as `&lt;` in the html version of the info.

**Comment by OnnoVdT** [comment]
@Joe-Winchester where do you see John already created a fix? In case there isn't one yet, I had a quick look and see we have to augment `function _readme` in `smpe-service.sh` to do these substitutions in the `# append hold data` section. Let me know if I need to do this.

**Comment by John-A-Davies** [comment]
FYI the htm file actually contains the "right" contents:
```
  Run <ROOT_DIR>/bin/zowe-configure-instance.sh -c 
  <PATH_TO_INSTANCE_DIR> again with an updated instance.env
  to pick up the new definitions.
```
so it's the browser rendering that removes `<PATH_TO_INSTANCE_DIR>` because it processes it like a tag instead
of text.

**Comment by John-A-Davies** [comment]
Fixed by PR https://github.com/zowe/zowe-install-packaging/pull/1788
