### ISSUE TITLE
Zowe install fails to startup

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zowe-install-packaging#1800]
**Describe the bug**
Internal zowe pipeline runs into a problem with the latest build for Keyring enabled.
Ansible installation is fine, but can't login zowe desktop with port:8544. 

**To Reproduce**
1. Run ansible install.yum on select system, say, tvt6019
    installation has no errors
2. Open tvt6019.svl.ibm.com:8544
    won't be able to login 

The problem seems related to the latest change in staging of zowe-install-packaging: "add JWTSECRET to known personal certs", "update dafault token name/label" and so, which introduced ZWETOKEN

There are JWT variables generated in instance.env, like
ZWED_agent_jwt_token_name=ZWETOKEN
ZWED_agent_jwt_token_label=jwtsecert
..

Then, tvt6019.svl.ibm.com:8544 will fail to login.

The same build ran ok for Keyring enabled on Nov 18th.

**Expected behavior**
Should be able to login zowe desktop with Keyring certificate

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raymondyanli** [comment]
This issue happened with both Keyring and keystore with the latest zowe build.
Due to ZWED_agent_jwt_token_name=ZWETOKEN, zowe installed, but failed to login.

Error message in zssServer.log

ZWES1013I ZSS Server has started. Version '1.17.0+20201106'
ZWES1033I Using server config file '/opt/zowe/zowe-instance-dir/workspace/app-server/serverConfig/server.json'
ZWES1035I ZSS Server settings: Address='127.0.0.1', port='8542'
ZWES1030W Server startup problem: Could not load the JWT key 'ZWETOKEN' from token 'jwtsecret': rc '12', p11rc '0', p11Rsn '0'

**Comment by stevenhorsman** [comment]
@raymondyanli - I've made a change to staging that I hope will fix this problem, so let us know if tonight's nightly does, or doesn't contain it please

**Comment by raymondyanli** [comment]
@stevenhorsman Thanks, it works. so you can close this issue if you'd like.
