### ISSUE TITLE
It seems the changes in Zowe unix file service caused zWin test cases fail (no longer compress the zWIN JSON contents?)

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zowe-install-packaging#1833]
**Describe the bug**
We have noticed there are quite a lot zWin tests started to fail in daily zowe-ext pipeline runs. and zWin team found out that Zowe unix file service API doesn't compress the zWIN JSON contents as it used to.

zWin team commented out:
"It seems like Zowe unix file service API doesn't compress the zWIN JSON contents as before.
While zWIN assumes the response from Zowe unix file service is always compressed in gzip (A flaw, because we never thought about Zowe configured without compression), and forwards it to browser directly, to avoid decompressing and compressing it again in Zowe application server. Now what Zowe unix file service returns is not compressed, while the response received by browser says its compressed, which results in this Decoding failed.

It was configured with -Dserver.compression.enabled=true in /opt/zowe/runtime/components/files-api/bin/start.sh before."

The failures started to appear around Dec 3.   

**To Reproduce**
Checked latest zowe installed on tvt6019, and found no Content-Encoding in response header.

**Expected behavior**
Keep the behavior of zowe package same as before.

**Screenshots**

The new unix file service response:
<img width="353" alt="new" src="https://user-images.githubusercontent.com/18621966/101654507-9ba27300-3a0e-11eb-92b5-037a8d3465a7.png">

It used to be:
<img width="379" alt="old" src="https://user-images.githubusercontent.com/18621966/101654596-b4ab2400-3a0e-11eb-80ff-9f4a1d6bf436.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NakulManchanda** [comment]
Hi, 

This depends on `gateway-service` as well, and its configuration, what is ultimately received by client.
We added following config in gateway service to support this feature

ribbon config
`builder.setContentCompressionEnabled(false);`  


file containing config when added originally
`gateway-service/src/main/java/com/ca/mfaas/gateway/ribbon/GatewayRibbonLoadBalancingHttpClient.java` 

Refer to original PR:
https://github.com/zowe/api-layer/pull/463/files

**Comment by NakulManchanda** [comment]
@raymondyanli what was the last version which pass all your tests? Would be helpful to know. 
We can work with APIML to resolve this issue.

FYI @nkocsis @jordanCain @CarsonCook @Joe-Winchester 
Thanks for sharing this @jackjia-ibm

**Comment by NakulManchanda** [comment]
@raymondyanli 
 it still to responding with gzip content for me in next version in staging branch 1.18.0, release RC soon
when request made with headers
`Accept-Encoding: gzip, deflate, br`, i see that's the case in screenshot posted above in issue as well

![image](https://user-images.githubusercontent.com/4791635/101676463-34de8300-3a29-11eb-8ff1-e8dfe771079a.png)

**Comment by NakulManchanda** [comment]
Please try out with this latest zowe pax, thanks
https://zowe.jfrog.io/artifactory/libs-snapshot-local/org/zowe/1.18.0-RC/zowe-1.18.0-rc-118-20201209171349.pax

**Comment by raymondyanli** [comment]
@NakulManchanda The zWin test cases started to fail with the zowe build around Dec 3. I will find an "old" zowe build or 1.18.0-rc-x build to try out then.

**Comment by jackjia-ibm** [comment]
@raymondyanli I tried Dec 5th nightly build and seems the response is zipped properly. Could you provide your zowe manifest build information and what's the URL you are testing? Thanks!

**Comment by raymondyanli** [comment]
Hi @jackjia-ibm 
Our pipeline doesn't hold the testing records back to Dec 5th..... can't find manifest info for it.
But, I tried today's build: 1.18.0-staging-1160-20201210051908, with the manifest.json here(let me know if you need full part of manifest.json):

  "homepage": "https://zowe.org",
  "build": {
    "branch": "staging",
    "number": "1160",
    "commitHash": "72c2844f12bb541cae28afc52911560fbbc3252d",
    "timestamp": "1607576144126"
  },

And I can see the problem is still there:
![image](https://user-images.githubusercontent.com/18621966/101824944-f4e7d080-3afa-11eb-9917-deb212a37454.png)

I will see if I can install the build of Dec 5th to see if the problem will be reproducible.. 

@NakulManchanda I had problems for installing libs-snapshot-local/org/zowe/1.18.0-RC/zowe-1.18.0-rc-118-20201209171349.pax ..... I will try to get it installed and test on it.

**Comment by NakulManchanda** [comment]
there are two other end points which can help check calls to Files API.
It eliminates gateway - so help debug API config directly.

![image](https://user-images.githubusercontent.com/4791635/101863671-a873b380-3b41-11eb-95b9-d91291ff98d0.png)

Will try API service directly
- https://mainframe:8547/api/v1/unixfiles?path=%2Fu%2Fibmuser
- https://mainframe:8547/swagger-ui.html

**Comment by raymondyanli** [comment]
@NakulManchanda Thank you for helping me to debug this issue in such late of last night.
When I retrieved the JSON file, I don't see that it is compressed: "Content-Encoding: gzip" is not there.

![image](https://user-images.githubusercontent.com/18621966/101915388-8efb5780-3b93-11eb-8644-e8ffb8db5e40.png)
(zowe-1.18.0-rc-118-20201209171349.pax installed on that system)

**Comment by raymondyanli** [comment]
Hi @jackjia-ibm @NakulManchanda
 
I installed zowe-1.18.0-staging-1148-20201205051752 on vm30051, and tried to retrieve unix files from zWin plugin ( https://vm30051.svl.ibm.com:7554/api/v1/unixfiles/opt/zowe/zowe-instance-dir/workspace/com.ibm.zos.zwin/zwin-test-default/PDBHI.ZABASE.H0021HT2.SMFDUMP.S98MEAS.T2326.JSON), and it failed with decoding issue. 

I worked with zWin team over the weekend, here is what zWin team confirmed:

1.  zWin plugin is expecting the compressed data by default when retrieving unix files.  the configuration defined in here: /opt/zowe/zowe-instance-dir/workspace/com.ibm.zos.zwin/zwin-app/lib/index.js:
     if (forward) {
          res.setHeader('content-encoding', 'gzip');
          res.status(200).send(content).end();
     }
It fails because it got the response with uncompressed data.

2. removed  "res.setHeader('content-encoding', 'gzip');" from above index.js, like:
     if (forward) {
          res.status(200).send(content).end();
     }
It works. 

It seems the problem is "no Content-Encoding in response header". Are there any related changes from Zowe unix file service API part?(builds from Dec 5th)

I installed zowe-1.18.0-staging-1138-20201130051911.pax on tvt6019, it has no problems to retrieve the unix files from zWin plugin (https://tvt6019.svl.ibm.com:7554/api/v1/unixfiles/opt/zowe/zowe-instance-dir/workspace/com.ibm.zos.zwin/zwin-test-default/PDBHI.ZABASE.H0021HT2.SMFDUMP.S98MEAS.T2326.JSON).

**Comment by NakulManchanda** [comment]
Hi @raymondyanli 

Can you try these API endpoint/Url

Unix file Endpoint - https://mainframe:8547/api/v1/unixfiles?path=%2Fu%2Fibmuser
Files API - Swagger Docs - https://mainframe:8547/swagger-ui.html

Both above endpoint don’t go via gateway. So it help us isolate the issue. Whether we debug service or intermediate service i.e. gateway

**Comment by raymondyanli** [comment]
Hi @NakulManchanda 

I can see "Content-Encoding: gzip" in above API endpoint/URL retrievals:  
![image](https://user-images.githubusercontent.com/18621966/102095643-c23b2200-3df1-11eb-9df8-eb99052bbc03.png)

![image](https://user-images.githubusercontent.com/18621966/102095927-1a722400-3df2-11eb-84d4-c1f84a77eaea.png)

**Comment by balhar-jakub** [comment]
I was trying to replicate the problem and at least on the level of whether the proper headers are set on the response I found no issue with respect to the API Gateway. 

Whenever the downstream (southbound) service send the data as gzip encoded the gzip encoding was properly set to the upstream (northbound) services. 

I tested on the internal Discoverable Client, which we use by default for testing with the application/json and image/png types and they worked properly. 

Apart from that I also tested with the USS Jobs API /api/v1/unixfiles/a/apimtst/existingFile and the content had the Content-encoding: gzip properly set. So it looks like the content was actually gzipped in the default configuration of the API Gateway.

**Comment by std4lqi** [comment]
Thanks for all looking into it! Two questions from extender's perspective.

1) In any way, Zowe is configured to send the compressed response by default, unless user explicitly turns it off on API gateway or the individual service. 

2) It seems the uncompressed response was found on zowe-1.18.0-staging-1148-20201205051752 only? The Zowe 1.17 Release is good? And Zowe 1.18 RC1?

**Comment by balhar-jakub** [comment]
I have been on the API Mediation Layer testing on the 1.16, 1.18.1 and 1.19.0-SNAPSHOT

**Comment by NakulManchanda** [comment]
Hi,

We need to revert the spring boot upgrade from 2.1.18 back to 2.1.7
https://github.com/zowe/data-sets/commit/5497ee59dffa9e579032e2b26bc627010ca7ab1d

Did not try job api - it might have same issue if upgraded spring boot version. 

to resolve an issue
https://github.com/zowe/zowe-install-packaging/issues/1833

or find a way to make compression work correctly in upgraded spring boot version.

Able to reproduce the issue with following jar
data-sets-api-server-1.0.4-STAGING-SNAPSHOT-boot.jar

Nov 27 build works correctly.
Dec01 build did not work.
Staging builds of dataset service - https://zowe.jfrog.io/ui/builds/Explorer-Data%20Sets%20::%20staging

It exposed gap in test coverage too
We can add smoke test for future release of zowe-install-packaging 

FYI @jordanCain @jackjia-ibm @stevenhorsman @raymondyanli

**Comment by jordanCain** [comment]
We've reverted the springboot version update and a new RC is being built today, The new data-sets/Unif files service is being pulled into the RC here https://github.com/zowe/zowe-install-packaging/pull/1850

**Comment by raymondyanli** [comment]
Hi, 
I have verified that the compression issue has been fixed in the below build. 
https://zowe.jfrog.io/artifactory/libs-snapshot-local/org/zowe/1.18.0-RC/zowe-1.18.0-rc-129-20201217110340.pax.

I will close this issue once I test it with PTF build later then.
FYI. @NakulManchanda @jackjia-ibm @jordanCain @std4lqi @nkocsis @stevenhorsman Thanks

**Comment by stevenhorsman** [comment]
@raymondyanli - can you confirm if this fix worked please?

**Comment by raymondyanli** [comment]
@stevenhorsman Yes. the issue was fixed. closed this issue.
