### ISSUE TITLE
host value returned by component swagger JSON should not be expected

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1847]
**Describe the bug**

Currently jobs/files api, or maybe other components will return `"host": "<ZOWE_EXPLORER_HOST>:<GATEWAY_PORT>"` as part of the Swagger JSON. This may not work well if the user intend to use multiple domains to visit gateway.

**To Reproduce**

1. Configure `ZOWE_EXPLORER_HOST` as `my-zos-host.com` and start Zowe
2. Visit Zowe api catalog with another host name, for example, IP of `my-zos-host.com` `9.1.2.3`: https://9.1.2.3:7554/
3. Goto APi Catalog, log in and find jobs/files api tile,
4. In Swagger section, it will show `Host: my-zos-host.com:7554` and non of the `Try-Out` section will work.

**Expected behavior**

Ideally this is not proper way to switching how to visit Gateway. But if we tolerate this behavior, we should try to remove `Host: my-zos-host.com:7554` from swagger response and see if host is picked up automatically of how to access api catalog. If we visit API catalog with `https://9.1.2.3:7554/`, the host should be `9.1.2.3:7554`.

Proper way to switching domain, I believe should be update `HOSTNAME=<new-domain>` and re-run `zowe-setup-certificate.sh` and update `instance.env` `ZOWE_EXPLORER_HOST=<new-domain>` and restart Zowe.

**Additional context**

Another solution is changing API Catalog api docs endpoint to remove any `host` definition, or change the value of it. But I think this may not be a good that let API Catalog, which works as proxy here, to manipulate response of another component.

In HA scenario, when API Catalog retrieves the swagger content, it may use internal domains like `https://lpar2:<jobs-api-port>/v2/api-docs`. In this case, the `host` returned by jobs api will be `lpar2:<gateway-port>`. This will definitely break the client side to try out any APIs with API catalog because lpar2 is not accessible from browser.

**Comment by NakulManchanda** [comment]
ZOWE_EXPLORER_HOST (instance.env value configured during zowe install, this value is used for internal communication, where gateway forward request internally)
   -> ZOWE_EXTERNAL_HOST (external host name to reach out to server, 
                                                 **it could be same as ZOWE_EXPLORER_HOST but can be different, that's the trap**)
        ZOWE_EXTERNAL_IP (external host ip to reach out to server)


**Few URLS to try:**
https://ZOWE_EXTERNAL_HOST :7554/apicatalog/api/v1/apidoc/jobs/v1
https://ZOWE_EXTERNAL_IP :7554/apicatalog/api/v1/apidoc/jobs/v1
- both request return swagger.json from jobs api, with host property set to ZOWE_EXPLORER_HOST

https://ZOWE_EXTERNAL_HOST :8547/v2/api-docs               
    -  return swagger.json from jobs api, with host property set to ZOWE_EXPLORER_HOST                 
https://ZOWE_EXTERNAL_IP :8547/v2/api-docs              
    - return swagger.json from jobs api, with host property set to ZOWE_EXTERNAL_IP

**Comment by balhar-jakub** [comment]
As for the mechanism within the API Catalogue which is used with respect to the Swagger documentation behavior there. When API Catalogue retrieves Swagger document from the Southbound service, it looks for the instances of host in it and replace the host with the value of the _environment.gatewayHostname_ which is set in the start script as follows. 

    -Denvironment.gatewayHostname=${ZOWE_EXPLORER_HOST} \

This is the location within repo: https://github.com/zowe/api-layer/blob/master/api-catalog-package/src/main/resources/bin/start.sh 

Maybe this will be the place to replace it with some other value if needed.

**Comment by NakulManchanda** [comment]
right now we configure jobs API like this:

![image](https://user-images.githubusercontent.com/4791635/102506162-d892e900-4050-11eb-8de8-85e8c3aad78a.png)


https://${ZOWE_EXPLORER_HOST}:${JOBS_API_PORT}/v2/api-docs
so, ZOWE_EXPLORER_HOST is how we always fetch swagger doc from jobs

![image](https://user-images.githubusercontent.com/4791635/102506630-50f9aa00-4051-11eb-8259-bf3118d741b8.png)

**Comment by NakulManchanda** [comment]
> -Denvironment.gatewayHostname=${ZOWE_EXPLORER_HOST} \

seems like are deciding this too soon, we should look at `req.host` and use that to replace instead of `gatewayHostname`

**Comment by jackjia-ibm** [comment]
Thanks all for looking into this. Any solution is good to me. The only thing I want to make sure is `services[].instanceBaseUrls` and `services[].apiInfo[] .swaggerUrl` shouldn't be dynamically updated. Those will be the internal host name where the instance is located. Otherwise the changes may be conflicted with HA interest.

**Comment by balhar-jakub** [comment]
@jackjia-ibm I actually believe this is the case. The swaggerUrl with which the JOBS API is onboarded into the API Mediation Layer is used only by the API Mediation Layer. It isn't exposed to the general public. The version that is exposed via API Catalog parses the received swagger document and makes sure that the routes in the document are updated in such way that they will point to the API Mediation Layer gateway.
