### ISSUE TITLE
The explorer UI apps should appear as default tiles within the Desktop

### ISSUE THREAD

**Issue by jordanCain** [zowe/zowe-install-packaging#185]
See: https://github.com/zowe/zowe-install-packaging/pull/100 for reference

**Comment by jackjia-ibm** [comment]
@jordanCain what's our position on this topic? May we close the issue, or will take action on it?

**Comment by jordanCain** [comment]
@jackjia-ibm This had slipped my mind, from my perspective we should add the jes-explorer as a default tile on the launchbar but we can likely leave the uss and mvs explorers in the app menu.

**Comment by stevenhorsman** [comment]
It looks like the JES explorer is default now, so closing this item.
