### ISSUE TITLE
Rename zowe-pre-install to zowe-prereq-verify.sh.  Rename zowe-post-install.sh to zowe-troubleshoot.sh

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#186]
Customers had raised questions about pre-install that looked like it was needed to be run before an install (which it isn't - it's optional and is more of a pre-req checker) and also for the runtime/scripts file a name of zowe-troubleshoot seems better for what it achieves, which is to troubleshoot an install folder

**Comment by John-A-Davies** [comment]
Closed by #187
