### ISSUE TITLE
HA: Verify and document z/OSMF HA

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1863]
We have done research on z/OSMF HA and had been confirmed what's the preferred way to enable z/OSMF HA. Next step, we would like to:

- verify z/OSMF authentication services including:
  * LTPA token should be able to re-use seamlessly across z/OSMF instances, even one of the z/OSMF instance is down.
  * JWT token should be able to re-use seamlessly across z/OSMF instances, even one of the z/OSMF instance is down.
  * PassTicket should be able to re-use seamlessly across z/OSMF instances, even one of the z/OSMF instance is down.
- Document preferred z/OSMF HA configuration in Zowe docs website

**Comment by jackjia-ibm** [comment]
We had verified LTPA/JWT token works well. PassTicket test is pending because of Gateway authentication endpoints returns 403 CORS failure.

**Comment by NayerNajafi** [comment]
- How to configure z OSMF HA for Zowe in Sysplex:
https://github.com/zowe/zowe-install-packaging/wiki/Configure-z-OSMF-HA-for-Zowe-in-Sysplex
- How to enable JWT function on z OSMF HA servers:
https://github.com/zowe/zowe-install-packaging/wiki/Enable-JWT-function-on-z-OSMF-HA-servers

**Comment by NayerNajafi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [z/OSMF HA documentation for Zowe](https://trello.com/c/8FrZErhj/10-z-osmf-ha-documentation-for-zowe)

**Comment by NayerNajafi** [comment]
- How to enable single sign on on zOSMF HA servers:
https://github.com/zowe/zowe-install-packaging/wiki/Enable-single-sign-on-on-zOSMF-HA-servers

**Comment by NayerNajafi** [comment]
- How to enable Zowe to generate and evaluate PassTickets for APIML Services Zowe HA:
https://github.com/zowe/zowe-install-packaging/wiki/Enable-Zowe-to-generate-and-evaluate-PassTickets-for-APIML-Services-Zowe-HA
