### ISSUE TITLE
HA: document how to configure Sysplex to work with Zowe HA

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1864]
Besides z/OSMF HA documentation https://github.com/zowe/zowe-install-packaging/issues/1863, we need to document how Zowe itself should be configured to run in Sysplex.

To prepare Sysplex, these are required and should be documented:

- MAS setup following https://github.com/zowe/zowe-install-packaging/issues/1689.
- RACF data sharing mode
- ARM setup
- USS file sharing
- VSAM RLS
- DVIPA configuration (this may apply to Zowe configuration)

**Comment by NayerNajafi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [z/OSMF HA documentation for Zowe](https://trello.com/c/8FrZErhj/10-z-osmf-ha-documentation-for-zowe)

**Comment by NayerNajafi** [comment]
Close in favor of duplicated issue zowe/docs-site#1086
