### ISSUE TITLE
Investigate various CI/CD tools vs current Jenkins 

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1868]
*Customer content*

**Is your feature request related to a problem? Please describe.**

We use our own Jenkins servers which provides us flexibilities but also has limitations like:

- limited resources which could be slow when we have multiple builds running
- sophisticated jenkins library which limit us to upgrade Jenkins master
- Groovy based Jenkinsfile still has steep learning curve for some users to make changes

**Describe the solution you'd like**

Investigate alternatives to current Jenkins:

- LinuxFoundation hosted Jenkins
- Github Actions
- CircleCI
- TravisCI

After the investigation, we should be able to understand:

- advantage of each platform
- how to support shared tools (like jenkins library)
- limitations, including
  * concurrent builds
  * how it supports organization and how many repositories we can setup
  * performance on spinning up new build agent
  * branching and pull request build support
  * configuration and management
  * retention time for build history and logs
- how much efforts it will take to migrate away from current Jenkins

**Comment by MarkAckert** [comment]
Outcome:
* Recommendation on whether or not pursue Github Actions for the Zowe org

**Comment by jackjia-ibm** [comment]
Investigated and we confirmed will migrate to Github Actions.
