### ISSUE TITLE
Check and Set the extended attributes for explorer in zowe-runtime-authorize.sh

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#19]
If the user doing the install can't unpax and set the extended attribute flags then the Atlas explorer-server fails to connect to the Angel and causes runtime errors.
The zowe-runtime-authorize.sh script should be updated so that it tries to set, and checks, the /explorer-server/wlp/lib/native/zos/s390x files as follows:  -rwxr-xr-x  -ps-  1 TSTRADM  IZUADMIN  380928 May 23  2017 batchManagerZos
-rwxr-xr-x  ap--  1 TSTRADM  IZUADMIN    4096 May 23  2017 bbgzachk
-rwxr-xr-x  ap--  1 TSTRADM  IZUADMIN  315392 May 23  2017 bbgzadrm
-rwxr-xr-x  ap--  1 TSTRADM  IZUADMIN  225280 May 23  2017 bbgzafsm
-rwxr-xr-x  aps-  1 TSTRADM  IZUADMIN  208896 May 23  2017 bbgzangl
-rwxr-xr-x  aps-  1 TSTRADM  IZUADMIN  147456 May 23  2017 bbgzcsl
-rwxr-xr-x  ap--  1 TSTRADM  IZUADMIN  991232 May 23  2017 bbgzsafm
-rwxr-xr-x  ap--  1 TSTRADM  IZUADMIN  540672 May 23  2017 bbgzscfm
-rwxr-xr-x  -ps-  1 TSTRADM  IZUADMIN   94208 May 23  2017 bbgzsrv
-rwxr-xr-x  -p--  1 TSTRADM  IZUADMIN  434176 May 23  2017 bbgzsufm
-rwxr-xr-x  ap--  1 TSTRADM  IZUADMIN  106496 May 23  2017 bboacall
-rwxr-xr-x  -ps-  1 TSTRADM  IZUADMIN  696320 May 23  2017 libzNativeServices.so

child of #11

**Comment by stevenhorsman** [comment]
We no longer have the apf extended attributes in the explorer server
