### ISSUE TITLE
deploy.sh not found when running zowe-install.sh

### ISSUE THREAD

**Issue by jshewbert** [zowe/zowe-install-packaging#190]
I am getting an error message when running the zowe-install.sh script:

.: ./zowe-install.sh 106: deploy.sh: not found

I added a few lines to make sure I was in the correct directory and that the deploy.sh script actually existed:
/NONIPO/local/zowe/0.9.3/zlux-build
total 258
-rw-r--r--   1 SYS1JJS  XCHGMAN    14199 Oct 28 22:16 LICENSE
-rw-r--r--   1 SYS1JJS  XCHGMAN     2197 Oct 28 22:16 README.md
-rw-r--r--   1 SYS1JJS  XCHGMAN     2401 Oct 28 22:16 audit.xml
-rw-r--r--   1 SYS1JJS  XCHGMAN      667 Oct 28 22:16 build.bat
-rwxr-xr-x   1 SYS1JJS  XCHGMAN      638 Oct 28 22:16 build.sh
-rw-r--r--   1 SYS1JJS  XCHGMAN     2306 Oct 28 22:16 build.xml
-rw-r--r--   1 SYS1JJS  XCHGMAN     8318 Oct 28 22:16 build_ng2.xml
-rw-r--r--   1 SYS1JJS  XCHGMAN       39 Oct 28 22:16 common.properties
-rw-r--r--   1 SYS1JJS  XCHGMAN     4067 Oct 28 22:16 common.xml
-rw-r--r--   1 SYS1JJS  XCHGMAN      413 Oct 28 22:16 core-plugins.properties
-rwxr-xr-x   1 SYS1JJS  XCHGMAN     3579 Oct 28 22:16 deploy.sh
-rw-r--r--   1 SYS1JJS  XCHGMAN     5884 Oct 28 22:16 deploy.xml
drwxr-xr-x   3 SYS1JJS  XCHGMAN     8192 Oct 28 22:16 externals
-rw-r--r--   1 SYS1JJS  XCHGMAN     2133 Oct 28 22:16 production.xml
-rw-r--r--   1 SYS1JJS  XCHGMAN       68 Oct 28 22:16 version.properties
.: ./zowe-install.sh 106: deploy.sh: not found

**Comment by Joe-Winchester** [comment]
@jshewbert - what kind of shell are you running in ?  Are you using an ssh terminal or something else ?

**Comment by jshewbert** [comment]
@Joe-Winchester - I have tried an SSH terminal and using the OMVS shell. I get this with both.

I am able to run the deploy.sh manually. So I continued with the installation by entering the remaining commands from zowe-install.sh manually. However, I am still having some issues with the explorer server. Not sure if the troubles I ran into during installation are related yet or not.

**Comment by Joe-Winchester** [comment]
@jshewbert - if it's possible I'd love to get on a webex and see if we can debug this with some screen sharing.  You're the second user who has run into this problem and I'd love to get to the bottom of it.  Are you able to join slack and ping me to find a good time to get together, or else e-mail me at winchest@uk.ibm.com and we can hopefully find a time that works.

**Comment by jshewbert** [comment]
sent an email.

**Comment by jshewbert** [comment]
I was able to get around this issue by changing:
. deploy.sh > /dev/null

to:
./deploy.sh > /dev/null

**Comment by Joe-Winchester** [comment]
This has been fixed in the latest 0.9.5 and later builds - I'll close it so let me know if it still occurs and many thanks for raising and also giving us the fix !  I owe you a beer/coffee/chocolate if we're ever in the same town/bar.
