### ISSUE TITLE
Implement Docker build stages for Dockerfiles

### ISSUE THREAD

**Issue by markjhollands** [zowe/zowe-install-packaging#1923]
**Is your feature request related to a problem? Please describe.**
To adhere to container image best practice, a container image should a) be as small as possible, and b) only container the tools required at runtime for the application to run. Currently, our Docker image includes some tools that are not required, and is currently 1.52GB... largely because of the techniques used in building the image, and poor consideration of Docker image layering.

**Describe the solution you'd like**
There is a technique in Docker builds (multi-stage builds) that allow you to run build like activities in one container, and then copy the build output to a fresh container.

This can drastically reduce the image size and number of layers. In a test I managed to reduce the size of the server-bundle image from 1.52GB to 783MB.

**Describe alternatives you've considered**
Implementing a multi-container architecture. While a mutli-container architecture is definitely the best design pattern in the medium to long term, this technique can reduce the image size with minimal effort.

**Additional context**
As mentioned in the description above, in a test I managed to reduce the size of the server-bundle image from 1.52GB to 783MB. I have raised a PR on the zowe-dockerfiles repo (https://github.com/zowe/zowe-dockerfiles/pull/31) but this change would be better after the merge of the Dockerfiles from that repo to this one.

**Comment by jackjia-ibm** [comment]
This was fixed by https://github.com/zowe/zowe-install-packaging/pull/1974
