### ISSUE TITLE
Change user from root to new zowe user

### ISSUE THREAD

**Issue by markjhollands** [zowe/zowe-install-packaging#1924]
*Customer content*

**Is your feature request related to a problem? Please describe.**
According to best practice for creating container images, it is highly recommended (as it is on any platform), not to run as the root user. When it comes to hosting in some Kubernetes environments (including all OpenShift) action has to be taken for this to work, and it is not recommended.

**Describe the solution you'd like**
Create a new user either in the base image... or in the `server-bundle` image called `zowe`. The Zowe installation will have to be done using this user, into a directory that the user can access (i.e. `not /root/zowe`).

**Describe alternatives you've considered**
No - I would consider this a blocker for any support / GA of this image.

**Additional context**
No

**Comment by stevenhorsman** [comment]
@markjhollands - was this issue supposed to go into the zowe-dockerfiles repo?

**Comment by jackjia-ibm** [comment]
This was fixed by https://github.com/zowe/zowe-install-packaging/pull/1974
