### ISSUE TITLE
Create a CICD pipeline for the desktop explorer-ip app

### ISSUE THREAD

**Issue by vit-tomica** [zowe/zowe-install-packaging#1928]
We'd like to create a CICD pipeline for a new application to Zowe Desktop. The app's repository can be found here, https://github.com/skurnevich/explorer-ip. The repository is ready to be scanned and transferred under [github.com/zowe](https://github.com/zowe) project.

Steps how to build the application are described in the [README](https://github.com/skurnevich/explorer-ip/blob/master/README.md) file.

The application is currently not supposed to be a part of the regular Zowe build/release (pax file). Instead, the application is planned to be built and published as a separate artifact so that it can be optionally installed into Zowe Desktop.

Some remaining work on the application is listed in and tracked by the issue here, https://github.com/zowe/zlux/issues/618.

**Comment by FlappiTomic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a CICD pipeline for the desktop explorer-ip app](https://trello.com/c/82PyvgNe/18-create-a-cicd-pipeline-for-the-desktop-explorer-ip-app)

**Comment by vit-tomica** [comment]
Hello @jackjia-ibm, @FlappiTomic, I created some tests for the explorer-ip app (https://github.com/zowe/explorer-ip/tree/master/dataService/test). They could be added as a part of the pipeline and can be run against alone zss server (with the installed explorer-ip data service )

**Comment by jackjia-ibm** [comment]
Think we can close this item. Pipeline has been implemented and test case I believe currently moved to zowe-install-packaging test.

Please re-open if there are remaining works.
