### ISSUE TITLE
Report pull request test result as github comment

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1937]
**Is your feature request related to a problem? Please describe.**

Currently jenkins test result will show as `jenkins/zowe-install-test/pr-merge` item in Checks section of the PR. When we run multiple tests, only the last test will show and it will not show test result.

**Describe the solution you'd like**

After each test is done, comment directly on the PR with these information:

- test result - succeeded or failed
- test link
- main parameters including test scope, test server, zowe build, etc
- failed test cases (briefly)

**Additional context**

- create utility method `Github.comment()` for class https://github.com/zowe/jenkins-library/blob/master/src/org/zowe/jenkins_shared_library/scm/GitHub.groovy.
- detect if the build is on a Pull Request, only add comment for pull request.
- [_sendEmailNotification](https://github.com/zowe/jenkins-library/blob/master/src/org/zowe/jenkins_shared_library/pipelines/base/Pipeline.groovy#L927) method provides some examples to extract information from Jenkins.
- several ways to embed the comment action:
  * add directly when install test is done here https://github.com/zowe/zowe-install-packaging/blob/master/tests/installation/Jenkinsfile#L343
  * define as [TestStageArguments.githubComment](https://github.com/zowe/jenkins-library/blob/master/src/org/zowe/jenkins_shared_library/pipelines/generic/arguments/TestStageArguments.groovy) to enable github commenting, then submit comment at [GenericPipeline.testGeneric](https://github.com/zowe/jenkins-library/blob/master/src/org/zowe/jenkins_shared_library/pipelines/generic/GenericPipeline.groovy#L983) method. This way, all pipelines test stage can be benefit the same behavior by defining `pipeline.test(githubComment: "test result: {{TEST_RESULT}}")`. If we want to make this generic for all kinds of test, will need to consider comment template. For zowe install test, the template will be very special with zowe build file, test scope, etc. Those information isn't applicable for unit/integration test for other repositories.

@FlappiTomic

**Comment by FlappiTomic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Report pull request test result as github comment](https://trello.com/c/XuIsmwXe/19-report-pull-request-test-result-as-github-comment)
