### ISSUE TITLE
Zowe runs with prefer IP address true as default

### ISSUE THREAD

**Issue by achmelo** [zowe/zowe-install-packaging#1948]
**Describe the bug**
In documentation https://docs.zowe.org/stable/user-guide/api-mediation/api-gateway-configuration.html#prefer-ip-address-for-api-layer-services , there is a reference how to enable prefer IP address. However, in https://github.com/zowe/zowe-install-packaging/blob/master/scripts/instance.template.env file, this parameter is set to true (APIML_PREFER_IP_ADDRESS=true) . Users installing zowe are not aware of it. This will result in strange behavior in API ML  https://github.com/zowe/api-layer/issues/1147

**Expected behavior**
If configuration in zowe install packaging should be as close as possible to users installation, this parameter should be set false as default and modified only in tests.

**Comment by jandadav** [comment]
https://github.com/zowe/zowe-install-packaging/blob/master/scripts/instance.template.env also contains this as true, which means Zowe install default is true

**Comment by jackjia-ibm** [comment]
If we decide `environment.preferIpAddress` is not good option, I would like to suggest we deprecate `APIML_PREFER_IP_ADDRESS` and set `environment.preferIpAddress` to always be `false`. We can always use the value the user input as `ZOWE_EXPLORER_HOST`, whether it's an IP or a hostname/domain.

**Comment by jackjia-ibm** [comment]
@achmelo with fix #2063, is this issue ok to be closed? Maybe APIML will remove the support of `environment.preferIpAddress` but think it's different story.
