### ISSUE TITLE
Excessive configure and runtime logs in v1.19.0 release

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1950]
**Describe the bug**

In v1.19.0, we see excessive logs in 2 places:

- when running `zowe-configure-instance.sh`, the stdout has a lot of details generated by `install-app.sh`.
- in ZOWE job log, STDERR contains many chmod failures.

Additional behavior noticed, which it's hardly to confirm as a bug:

- If we delete zowe instance workspace folder, explorer UI apps will disappear and requires a re-run of `zowe-configure-instance.sh`

**To Reproduce**
1. Install v1.19.0 release
2. Configure instance
3. Start Zowe and check job log

**Expected behavior**

- zowe-configure-instance.sh Log should be concise. The detail log generated by install-app.sh should be redirected into file log for debugging purpose.
- Zowe runtime shouldn't write anything to STDERR.
- Ideally when zowe instance workspace is deleted, at least no plugins should be missing.

**Comment by neils-ibm** [comment]
I experienced the same flood of ICH408I msgs.

Will the fix require us to perform a configure-instance?

Thanks.

**Comment by jackjia-ibm** [comment]
@neils-ibm could you please post an example of `ICH408I` messages?

The fix is mostly suppressing error messages in Zowe job log and configure process, so I suspect it doesn't help on the `ICH408I` messages you saw.

For this change specifically, it doesn't require configure-instance, but configure-instance is recommended for every zowe release upgrade.

**Comment by neils-ibm** [comment]
`ICH408I USER(ZWESVUSR) GROUP(TASKS   ) NAME(ZOWE SERVER         )
  /global/zowe/instance/workspace                                
  CL(FSSEC   ) FID(E2E8C8D6F0F9509E0000000000A20001)             
  INSUFFICIENT AUTHORITY TO CHMOD                                
  EFFECTIVE UID(0000000581)  EFFECTIVE GID(0000000000)           
ICH408I USER(ZWESVUSR) GROUP(TASKS   ) NAME(ZOWE SERVER         )
  /global/zowe/instance/workspace/app-server                     
  CL(FSSEC   ) FID(E2E8C8D6F0F9509E0000000000B00001)             
  INSUFFICIENT AUTHORITY TO CHMOD                                
  EFFECTIVE UID(0000000581)  EFFECTIVE GID(0000000000)           
ICH408I USER(ZWESVUSR) GROUP(TASKS   ) NAME(ZOWE SERVER         )
  /global/zowe/instance/workspace/app-server/plugins             
  CL(FSSEC   ) FID(E2E8C8D6F0F9509E0000000000B10001)             
  INSUFFICIENT AUTHORITY TO CHMOD                                
  EFFECTIVE UID(0000000581)  EFFECTIVE GID(0000000000)           `
...

I had opened a case and level2/dev pointed to this git issue.

**Comment by jackjia-ibm** [comment]
@neils-ibm there is suggestion to put `ZWESVUSR` and install/configure user to be same group, by default, the group name is `ZWEADMIN`. If so, will this eliminate the `ICH408I` warnings?

**Comment by neils-ibm** [comment]
I didn't have this problem with the previous level.

Here's what I posted in the case:
If I compare the previous instance directory, I see that the workspace directory had owner=ZWESVUSR with perms=771 vs. (new one) owner=BPXROOT with perms=770.
And then under that directory, in the app-server directory previous had owner=ZWESVUSR with perms=771 vs. (new one) owner=BPXROOT with perms=771.
So it seems like a chown didn't happen somewhere and permission bits changed?
I can run a chown -Rh ZWESVUSR /global/zowe/instance/workspace, but I don't recall having to do that before?

**Comment by jackjia-ibm** [comment]
Thanks @neils-ibm for the details. Yes we made a change on how to configure explorer UI apps. It was actually configured at runtime, now it's configured at configure-instance.sh step. That makes difference on directory permission because some information we write into `workspace/app-server/` now owned by install user. In your case, is BPXROOT.

Here is a little bit information about user group it requires: https://docs.zowe.org/stable/user-guide/configure-instance-directory.html#creating-an-instance-directory.

Do you want to try once you put BPXROOT and ZWESVUSR both into ZWEADMIN group, and then run the configure-instance.sh again, will it eliminate the warnings?

**Comment by neils-ibm** [comment]
fyi - my id (NEILS); which is UID=0 is in the ZWEADMIN group.  When RACF resolves UID=0, I think it uses the SUPERUSER setting in BPXPRMxx to map the UID to a userid, so in our case BPXPRMxx SUPERUSER=BPXROOT, so that's why the owner of those files=BPXROOT.  I can try just for testing purposes, but probably not a good solution.

Is there a reason, we don't just do a `chown -Rh ZWEADMIN <zowe-instance-dir>/workspace` or `<zowe-instance-dir>` at the end of configuration -- to guarantee correct ownership?  Thanks.

**Comment by jackjia-ibm** [comment]
We do have `chgrp -R ${ZOWE_GROUP} ${INSTANCE_DIR}` in `zowe-configure-instance.sh` but I think it failed on your case even your user is already in ZWEADMIN group. I assume ZWESVUSR should have default group ZWEADMIN. Could you please help check few things:

- default group of your user and ZWESVUSR
- list user/group (`ls -l`) of your `<instance-dir>`, `<instance-dir>/workspace` and `<instance-dir>/app-server/plugins` directories.

We might chgrp too early in zowe-configure-instance.sh.

**Comment by neils-ibm** [comment]
(1) ZWEVSUSR default group is TASKS
(2) Here's the output of the ls commands:

(AQHO)NEILS:/u/neils(!):>ls -al /global/zowe/
total 128
drwxr-x---   8 BPXROOT  DEPTD60     8192 Feb 22 16:00 .
drwxr-xr-x   7 BPXROOT  DEPTD60     8192 Feb 22 16:02 ..
drwxrwxr-x   5 BPXROOT  ZWEADMIN    8192 Feb 16 10:29 instance
drwxrwxr-x   5 BPXROOT  ZWEADMIN    8192 Jan 22 12:16 instance.Feb162021
drwxrwxr-x   5 BPXROOT  ZWEADMIN    8192 Dec  1 13:59 instance.old
drwxr-x---   4 ZWESVUSR DEPTD60     8192 Feb 16 11:02 keystore
drwxr-x---   4 ZWESVUSR DEPTD60     8192 Dec  1 11:06 keystore.old
drwxr-x---   2 BPXROOT  DEPTD60     8192 Feb 16 11:01 logs
(AQHO)NEILS:/u/neils(!):>ls -al /global/zowe/instance
total 96
drwxrwxr-x   5 BPXROOT  ZWEADMIN    8192 Feb 16 10:29 .
drwxr-x---   8 BPXROOT  DEPTD60     8192 Feb 22 16:00 ..
drwxr-xr-x   4 BPXROOT  ZWEADMIN    8192 Feb 16 10:29 bin
-rwxr-xr-x   1 BPXROOT  ZWEADMIN    2826 Feb 16 10:34 instance.env
drwxrwxrwx   2 BPXROOT  ZWEADMIN    8192 Feb 22 16:17 logs
drwxrwx---  13 BPXROOT  ZWEADMIN    8192 Feb 22 16:17 workspace
(AQHO)NEILS:/u/neils(!):>ls -al /global/zowe/instance/workspace
total 256
drwxrwx---  13 BPXROOT  ZWEADMIN    8192 Feb 22 16:17 .
drwxrwxr-x   5 BPXROOT  ZWEADMIN    8192 Feb 16 10:29 ..
-rwxr-xr-x   1 ZWESVUSR ZWEADMIN    3818 Feb 22 16:17 active_configuration.cfg
drwxrwxr-x   3 ZWESVUSR ZWEADMIN    8192 Feb 22 16:17 api-catalog
drwxrwx--x   3 ZWESVUSR ZWEADMIN    8192 Feb 22 16:17 api-mediation
drwxrwx---   8 BPXROOT  ZWEADMIN    8192 Feb 16 10:35 app-server
drwxrwx--x   2 ZWESVUSR ZWEADMIN    8192 Feb 22 16:17 backups
drwxrwx--x   2 ZWESVUSR ZWEADMIN    8192 Feb 16 10:35 discovery
drwxrwx--x   2 ZWESVUSR ZWEADMIN    8192 Feb 16 10:35 explorer-jes
drwxrwx--x   2 ZWESVUSR ZWEADMIN    8192 Feb 16 10:35 explorer-mvs
drwxrwx--x   2 ZWESVUSR ZWEADMIN    8192 Feb 16 10:35 explorer-uss
drwxrwx--x   2 ZWESVUSR ZWEADMIN    8192 Feb 16 10:35 files-api
drwxrwx--x   2 ZWESVUSR ZWEADMIN    8192 Feb 16 10:35 gateway
drwxrwx--x   2 ZWESVUSR ZWEADMIN    8192 Feb 16 10:35 jobs-api
-rwxrwx--x   1 ZWESVUSR ZWEADMIN   11804 Feb 22 16:17 manifest.json
(AQHO)NEILS:/u/neils(!):>ls -al /global/zowe/instance/workspace/app-server/
total 114
drwxrwx---   8 BPXROOT  ZWEADMIN    8192 Feb 16 10:35 .
drwxrwx---  13 BPXROOT  ZWEADMIN    8192 Feb 22 16:17 ..
drwxrwx---   3 BPXROOT  ZWEADMIN    8192 Feb 16 10:29 ZLUX
-rwxrwx--x   1 ZWESVUSR ZWEADMIN      20 Feb 22 16:17 component.json
drwxrwx---   2 BPXROOT  ZWEADMIN       0 Feb 16 10:29 groups
drwxrwx---   2 BPXROOT  ZWEADMIN    8192 Feb 16 10:35 plugins
drwxr-x---   2 BPXROOT  ZWEADMIN    8192 Feb 16 10:29 serverConfig
drwxrwx---   3 BPXROOT  ZWEADMIN    8192 Feb 16 10:29 site
drwxrwx---   3 BPXROOT  ZWEADMIN    8192 Feb 16 11:04 users
(AQHO)NEILS:/u/neils(!):>ls -al /global/zowe/instance/workspace/app-server/plugins/
total 352
drwxrwx---   2 BPXROOT  ZWEADMIN    8192 Feb 16 10:35 .
drwxrwx---   8 BPXROOT  ZWEADMIN    8192 Feb 16 10:35 ..
-rwxrwx--x   1 ZWESVUSR ZWEADMIN     105 Feb 22 16:17 org.zowe.api.catalog.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     156 Feb 16 10:35 org.zowe.configjs.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     129 Feb 16 10:35 org.zowe.editor.json
-rw-rw----   1 BPXROOT  ZWEADMIN     107 Feb 16 10:29 org.zowe.explorer-jes.json
-rw-rw----   1 BPXROOT  ZWEADMIN     107 Feb 16 10:29 org.zowe.explorer-mvs.json
-rw-rw----   1 BPXROOT  ZWEADMIN     107 Feb 16 10:29 org.zowe.explorer-uss.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     170 Feb 16 10:35 org.zowe.terminal.proxy.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     137 Feb 16 10:35 org.zowe.terminal.tn3270.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     129 Feb 16 10:35 org.zowe.terminal.vt.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     184 Feb 16 10:35 org.zowe.zlux.appmanager.app.propview.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     166 Feb 16 10:35 org.zowe.zlux.auth.safsso.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     163 Feb 16 10:35 org.zowe.zlux.auth.trivial.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     152 Feb 16 10:35 org.zowe.zlux.bootstrap.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     146 Feb 16 10:35 org.zowe.zlux.logger.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     159 Feb 16 10:35 org.zowe.zlux.ng2desktop.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     192 Feb 16 10:35 org.zowe.zlux.ng2desktop.settings.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     149 Feb 16 10:35 org.zowe.zlux.sample.angular.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     147 Feb 16 10:35 org.zowe.zlux.sample.iframe.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     145 Feb 16 10:35 org.zowe.zlux.sample.react.json
-rwxrwx---   1 BPXROOT  ZWEADMIN     140 Feb 16 10:35 org.zowe.zosmf.workflows.json

**Comment by jackjia-ibm** [comment]
Thanks @neils-ibm . I think chgrp in configure-instance is actually successful, because usually ZWEADMIN will not be your default group. So now I wonder is ZWESVUSR in ZWEADMIN group? If this user was created by ZWESECUR jcl, it should have default group ZWEADMIN.

**Comment by neils-ibm** [comment]
ZWESVUSR is in group ZWEADMIN. 
ZWESVUSR default group is TASKS (part of our userid/security policy).

**Comment by jackjia-ibm** [comment]
Thanks Neil. I think I fully understand the issue now with your information and some investigations. The fix of this issue won't solve your audit log in 1.20.0. We need a more thorough solution and I need to talk to other squad to completely resolve it. I created a new issue to track this https://github.com/zowe/zowe-install-packaging/issues/1980
