### ISSUE TITLE
Define global ZWE_TLS_CIPHERS and apply to node/java applications automatically

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1951]
*Customer content*

**Is your feature request related to a problem? Please describe.**

Currently components implement their own way to define TLS ciphers. For example, explorer-ui-server has a hard-coded list of cipher list. We need to make this configurable for end-user.

**Describe the solution you'd like**

- Define ZWE_TLS_CIPHERS in instance.env and assign default value of `ZWE_DEFAULT_TLS_CIPHERS=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384`
- Convert this cipher list to the format node.js uses (`ECDHE-RSA-AES256-GCM-SHA384,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-SHA256,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-ECDSA-AES128-SHA256,ECDHE-ECDSA-AES256-SHA384`).
- Apply the value to `NODE_OPTIONS`, `IBM_JAVA_OPTIONS` and `JAVA_TOOL_OPTIONS`.

**Additional context**

We need to create a cipher suite name converting tool and ship with Zowe. Few useful links:

- https://testssl.sh/openssl-iana.mapping.html
- https://gist.github.com/Chion82/dafc1b209eb94b90f4bf090c6ae694e5
- https://www.openssl.org/docs/man1.0.2/man1/ciphers.html

**Comment by 1000TurquoisePogs** [comment]
I think you mean `ZWE_TLS_CIPHERS` instead of `ZWE_LTS_CIPHERS` but just checking since LTS and TLS both mean things to zowe...

**Comment by 1000TurquoisePogs** [comment]
Accomplished in v2, zowe.network.server.tls.ciphers
