### ISSUE TITLE
Zowe Install: Allow installation without zOSMF

### ISSUE THREAD

**Issue by jandadav** [zowe/zowe-install-packaging#1976]
*Customer content*
There are some customers that do not want to depend on zOSMF as a prerequisite for Zowe.
In support of that theme, APIML has implemented alternative auth providers so authentication can be performed even without zOSMF present. The current installation process requires zOSMF instance to be present and zOSMF data being entered.

**Describe the solution you'd like**
A Installation process that lets you choose wether Zowe will depend on zOSMF or wether it will be self-sufficient

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As Sherman,  
**I want to be able to install Zowe without installing zOSMF
**so that I don't have to install zOSMF....

#### Acceptance Criteria

Zowe install lets you choose the type of installation
Installation of Zowe without zOSMF can be selected
Installation sets up Zowe SSO correctly

**Comment by jackjia-ibm** [comment]
From v1.8.0 release, the docs site had mark z/OSMF as optional prerequisite. But seems code never works that way. So consider this as a bug. @Joe-Winchester @NayerNajafi

**Comment by jackjia-ibm** [comment]
When z/OSMF is not present, instance.env should use `saf` as `APIML_SECURITY_AUTH_PROVIDER`: https://docs.zowe.org/stable/user-guide/api-mediation/api-gateway-configuration.html#saf-as-an-authentication-provider.

**Comment by jackjia-ibm** [comment]
@jandadav do you mind try out if PR-2158 build fixes the issue? I tried it locally and APIML can start as my expected. But I'm not sure if I covered all the scenario. Thanks.

You can find the build from https://wash.zowe.org:8443/view/Zowe/job/zowe-install-packaging/job/PR-2158/

**Comment by jackjia-ibm** [comment]
Close for release. Please reopen if there are issues.
