### ISSUE TITLE
Excessive audit warnings shown with v1.19.0 release

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1980]
**Describe the bug**

Similar to https://github.com/zowe/zowe-install-packaging/issues/1950, there are also audit logs like:

```
ICH408I USER(ZWESVUSR) GROUP(TASKS ) NAME(ZOWE SERVER ) /global/zowe/instance/workspace CL(FSSEC ) FID(E2E8C8D6F0F9509E0000000000A20001) INSUFFICIENT AUTHORITY TO CHMOD EFFECTIVE UID(0000000581) EFFECTIVE GID(0000000000)
ICH408I USER(ZWESVUSR) GROUP(TASKS ) NAME(ZOWE SERVER ) /global/zowe/instance/workspace/app-server CL(FSSEC ) FID(E2E8C8D6F0F9509E0000000000B00001) INSUFFICIENT AUTHORITY TO CHMOD EFFECTIVE UID(0000000581) EFFECTIVE GID(0000000000)
ICH408I USER(ZWESVUSR) GROUP(TASKS ) NAME(ZOWE SERVER ) /global/zowe/instance/workspace/app-server/plugins CL(FSSEC ) FID(E2E8C8D6F0F9509E0000000000B10001) INSUFFICIENT AUTHORITY TO CHMOD EFFECTIVE UID(0000000581) EFFECTIVE GID(0000000000)
```

which cannot be resolved by fix https://github.com/zowe/zowe-install-packaging/pull/1958.

**To Reproduce**
1. Install v1.19.0 release
2. Configure instance
3. Enable audit log
4. Start Zowe and check job log

**Expected behavior**

There shouldn't be security warnings show in audit log.

**Additional context**

In our documentation, we asked the put Zowe runtime user and install user be in same group, by default is ZWEADMIN. This will not solve the chmod warnings completely because some files are owned by the other.

There are several places we have chmod:

- `zowe-configure-instance.sh`, there are `chmod 775 ${INSTANCE_DIR}`
- `run-zowe.sh`, `prepare-workspace.sh`, `chmod -R 771 ${WORKSPACE_DIR}` and `chmod 750 ${WORKSPACE_DIR}/app-server/serverConfig` `chmod -R 740 ${WORKSPACE_DIR}/app-server/serverConfig/*`
- `app-server` `initInstance.js`, `chmod -R 770 instancePluginStorage`

`${WORKSPACE_DIR}/app-server/serverConfig/` permission is suggested by security team, we need to leave it that way.

Possible solutions:

- define clear permission we need for instance directory and sub-directories.
- clean up unnecessary chmod.
- remove configuration information outside of workspace folder and store in config file and let Zowe runtime user to fully own and handle the workspace folder.

**Comment by 1000TurquoisePogs** [comment]
Why starting with 1.19.0? That code has been there since 1.8.0. Did something surrounding the code change to cause it?

**Comment by 1000TurquoisePogs** [comment]
Talked about it ant it seems to be due to the code execution being moved from runtime to install time, and the permissions associated with the users that execute the code during those times.
More research is needed about the solution to the problem generally, as this probably will be encountered by more groups over time if its just invocations of chmod that are a concern

**Comment by jackjia-ibm** [comment]
With PR1983, the issue described in the issue should be resolved. But this only temporarily solve for core components, if the user has desktop plugins from vendor, this issue is still there.

To proper solve the issue, we should properly separate configurations from workspace, because those belongs to different users. This requires redesign and potentially a breaking change. We should cover it with more suitable GitHub issue.
