### ISSUE TITLE
Reduce the amount of checking of Java and node levels 

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#1997]
**Is your feature request related to a problem? Please describe.**
Customer looking at the log saw five `Java version 1.8.0_261 is supported` messages and three `Node v12.18.0` valid messages.

**Describe the solution you'd like**
Check Java and node once and log once, based on the component groups
Gateway needs Java and node
ZLUX needs node

![image](https://user-images.githubusercontent.com/28100302/110145429-530e1200-7dd1-11eb-8203-e622232d683c.png)

**Comment by jackjia-ibm** [comment]
Changes have been done and all explorer UIs/APIs are modified and merged. api-layer changes is also in PR review and should be merged soon.
