### ISSUE TITLE
Errors trying to do chown: deploy/instance and deploy/site during install - 0.9.5-RC1

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#200]
Problem:
0.9.5 RC1.

Beginning install of Zowe 0.9.5 into directory  /u/winchj/zowe/0.9.5
  Installing API Mediation into /u/winchj/zowe/0.9.5/api-mediation ...
  Installing zLUX server into /u/winchj/zowe/0.9.5/zlux-example-server ...
chown: FSUM6180 file "deploy/instance": EDC5139I Operation not permitted.
....

Why this occurs:
The script zlux-install-script.sh is doing a chown on lines 29 and 30.
Not all users can do this so the script fails for everyone except a super user.
The chown is for #180 to allow pinning of desktop items.

**Comment by jackjia-ibm** [comment]
This should have been fixed by https://github.com/zowe/zowe-install-packaging/pull/204 and merged into 0.9.5-RC2.
