### ISSUE TITLE
Zowe fails to start because insufficient rx permissions on the /zowe folder it creates

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#201]
Problem:
Zowe fails to start and reports that it can't stat the run-zowe.sh.  
16.14.15 STC24377  ICH408I USER(IZUSVR  ) GROUP(IZUADMIN) NAME(MVS TASK         
   775               /u/winchj/zowe/0.9.5/explorer-server/../scripts/internal/ru
   775               zowe.sh                                                    
   775               CL(DIRSRCH ) FID(F3C2C8F0F0F2E643000000005EE200CD)         
   775               INSUFFICIENT AUTHORITY TO STAT                             
   775               ACCESS INTENT(--X)  ACCESS ALLOWED(OTHER      ---)         
   775               EFFECTIVE UID(0000000210)  EFFECTIVE GID(0000000202)       

Solution:
The install by default creates the folder /zowe/0.9.5 (or other build number) from the install.yaml file
The /zowe folder has very limited permissions, so a chmod ag+x zowe  needs to be run (realizing that /zowe is configurable to be a different path or set of folders)

**Comment by stevenhorsman** [comment]
This has been cleared up as much as possible and doc'd so can be closed now
