### ISSUE TITLE
Failure to import z/OSMF certificates during install - 0.9.5 RC1

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#202]
Problem:

Running an install if the user is not able to import the certificates from z/OSMF the failure is not a graceful one.

Setting up Zowe API Mediation Layer certificates FSUM6785 File or directory "keystore/local_ca/extca.*.cer" is not found

keytool: trust_zosmf 4: scripts/apiml_cm.sh 436: FSUM9209 cannot execute: reason code = 0b1b03d1: EDC5139I Operation not permitted.

apiml_cm.sh --action trust-zosmf has failed. See /u/winchj/zowe-0.9.5/install/..//log/2018-12-17-12-44-04.log for more details

ERROR: z/OSMF is not trusted by the API Mediation Layer. Follow instructions in Zowe documentation about manual steps to trust z/OSMF
 
Certificate setup done.

 Installing explorer-server into  /u/winchj/zowe/0.9.5/explorer-server 
Zowe 0.9.5 runtime install completed into directory /u/winchj/zowe/0.9.5

The install script zowe-install.sh does not need to be re-run as it completed successfully
Attempting to set Unix file permissions 

Solution:
The import should be moved to a script that is run as part of the zowe-runtime-authorize.sh or similar so that the first part of the install doesn't attempt to do anything that requires elevated priviledges, and it later does these in a script that can be given to someone else to run which is the design oint behind the "Attempting to set Unix file permissions ...".

**Comment by plavjanik** [comment]
Hello @Joe-Winchester, it actually works similarly as you have described. The error is displayed but it does not stop the script. Then the user can issue the command after the installation with higher privileges.

I am improving the messages to make it clearer. What about having this output:

```
Setting up Zowe API Mediation Layer certificates 

apiml_cm.sh --action trust-zosmf has failed. See /u/winchj/zowe-0.9.5/install/..//log/2018-12-17-12-44-04.log for more details

WARNING: z/OSMF is not trusted by the API Mediation Layer. Follow instructions in Zowe documentation about manual steps to trust z/OSMF
  Issue following commands as a superuser:
    cd $ZOWE_RUNTIME/api-mediation
    scripts/apiml_cm.sh --action trust-zosmf --zosmf-keyring IZUKeyring.IZUDFLT --zosmf-userid IZUSVR

Certificate setup done.
```

**Comment by Joe-Winchester** [comment]
@plavjanik - this looks awesome with the way the script now reports.  What I wanted mostly was that if the script ran and created everything on disk but failed because the user couldn't import the certificiates, they could re-run the certificate step or get another user to run that.  This looks like it's done now, and apologies that my first attempt to do this was bad because I moved the script order and broke something.  I haven't been able to test the importing because on our systems I don't have good enough permissions but I know folks on machines that do have permissions that have got it to work.

**Comment by plavjanik** [comment]
@Joe-Winchester Thank you for reporting it. The old messages were confusing. Importing certificates from the keyring is the safest method. Another possibility is to read the public certificate via the network from the z/OSMF server. But that is not safe since the APIML does not trust z/OSMF yet. We can allow it if the user can confirm that fingerprint of that certificate matches the fingerprint of the z/OSMF certificate in a browser that trusts the z/OSMF server.
