### ISSUE TITLE
Caching service is not able to use VSAM

### ISSUE THREAD

**Issue by achmelo** [zowe/zowe-install-packaging#2036]
**Describe the bug**
Caching service is now configured to use VSAM as storage. It seems to work on marist-1 and marist-2.There is a problem on marist-3. We were able to fix such issues with creating new VSAM. I can't see a step where the VSAM is being removed. If there is none, could we add DELETE '#dsname' to files/jcl/ZWECSVSM.jcl ?

**Expected behavior**
Provide such VSAM that can be used by Caching service.

**Comment by jackjia-ibm** [comment]
@achmelo I will investigate more why it fails on marist-3. We use playbook to create and delete the VSAM. The databset is created here https://github.com/zowe/zowe-install-packaging/blob/staging/playbooks/roles/configure/tasks/create_vsam_dataset.yml#L38 with `zowe_dataset_prefix`. When we clean up, the uninstall will delete everything under `zowe_dataset_prefix` https://github.com/zowe/zowe-install-packaging/blob/staging/playbooks/roles/zowe/tasks/uninstall.yml#L142.

I checked log, the VSAM dataset are deleted. So could be something else I will look into it.

**Comment by jackjia-ibm** [comment]
After reading job log, I found it failed to read the VSAM database with this error:

```
2021-03-26 01:49:13.755 [35m<ZWEACS1:main:67178410>[0;39m ZWESVUSR [31mERROR[0;39m [36m(o.z.a.c.s.v.VsamStorage)[0;39m ZWECS151E Problem initializing storage of type 'VSAM': 'opening of VsamConfig(generalConfig=GeneralConfig(evictionStrategy=reject, maxDataSize=10000), fileName=//'ZOWEAD3.ZWE.CACHE1', keyLength=32, recordLength=512, encoding=IBM-1047) in mode WRITE failed'. Exception: 'org.zowe.apiml.caching.service.vsam.VsamRecordException: Failed opening of file'
2021-03-26 01:49:13.770 [35m<ZWEACS1:main:67178410>[0;39m ZWESVUSR [32mINFO [0;39m [36m(o.a.c.c.StandardService)[0;39m Stopping service [Tomcat]
```

Job ZWECSVSM seems successful and VOLUME(ZOWE02) is 54% used.

```
  DEFINE CLUSTER -                                       
   (NAME(ZOWEAD3.ZWE.CACHE1) -                           
    VOLUME(ZOWE02) -                                     
    SHAREOPTIONS(2 3) -                                  
    REC(80 20) -                                         
    INDEXED) -                                           
   DATA(NAME(ZOWEAD3.ZWE.CACHE1.DATA) -                  
    RECSZ(80 4096) -                                     
    UNIQUE -                                             
    KEYS(128 0)) -                                       
   INDEX(NAME(ZOWEAD3.ZWE.CACHE1.INDEX) -                
    UNIQUE)                                              
IDC0508I DATA ALLOCATION STATUS FOR VOLUME ZOWE02 IS 0   
IDC0509I INDEX ALLOCATION STATUS FOR VOLUME ZOWE02 IS 0  
IDC0001I FUNCTION COMPLETED, HIGHEST CONDITION CODE WAS 0
```

Sys log shows:

```
 21084 21:49:13.67 STC03321 00000090  TSS7220E 101 J=ZWESVSTC A=ZWESVUSR VOL=VPALNB ACC=UPDATE DSN=ZOWEAD3.ZWE 
                                      .CACHE1                                                                  
 21084 21:49:13.67 STC03321 00000090  TSS7221E Dataset Not Accessible - ZOWEAD3.ZWE.CACHE1                     
 21084 21:49:13.70 STC03321 00000090  IEC161I 040(056,006,IGG0CLFT)-002,ZWE1CS,STEP1,SYS00011,,, 749           
                        749 00000090  IEC161I ZOWEAD3.ZWE.CACHE1                                               
```

Seems it's a permission issue with [TSS7221E](https://techdocs.broadcom.com/us/en/ca-mainframe-software/security/ca-top-secret-for-z-vm/12-1/messages-and-return-codes/z-vm-messages/tss7200-to-tss7299/tss7221e.html). Zowe runtime user ZWESVUSR doesn't have permission on this data set created by ZOWEAD3. @MarkAckert not sure if you can help on this. Thanks!

**Comment by achmelo** [comment]
There is also some problem on RACF, caching service can store, delete and get records but it is not able to update https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/staging/1287/testReport/junit/(root)/test%20caching%20service%20via%20gateway%20should%20be%20able%20to%20use%20caching%20service%20/

**Comment by MarkAckert** [comment]
I updated permissions on TSS system, ZWESVUSR has ALL access to ZOWEAD3.ZWE.CACHE1. Let me know if that works, then we can dial in the authorization level.

**Comment by jackjia-ibm** [comment]
@achmelo I will add some debug code to troubleshooting what happened on marist-1 https://github.com/zowe/zowe-install-packaging/pull/2048.

Seems v1.20.0 release are ok (https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/master/60/), so could be something related to recent changes.

**Comment by jackjia-ibm** [comment]
Didn't see caching service test failure in few days. @achmelo please re-open if you think this issue still exists.
