### ISSUE TITLE
ZWE1SV may use up all spool

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2042]
**Describe the bug**

If we enable APIML DEBUG mode and leave it unattended, the job will write many logs to the spool and may eventually use up all free spool space.

This happened on marist test system and we have to do a restore.

**Additional context**

Maybe we can write job log to /ZOWE/tmp to minimize impact to job spool.

**Comment by MarkAckert** [comment]
Closing as we'll cover this in #1486
