### ISSUE TITLE
Failure to Login to Zowe Application Framework for V 1.20  Authentication failed for 3 types. Types: ["saf","apiml","zss"]

### ISSUE THREAD

**Issue by shgordon2222** [zowe/zowe-install-packaging#2069]
Jumping from V1.12 to V1.20.  Login to Application Framework under V1.12 is working fine.
Under V1.20 I am getting Authentication failed for 3 types. Types: ["saf","apiml","zss"]

Release info from login screen   v. 1.20.0+20210303

Messages from ZWESVSTC STDOUT (ip address redacted):

021-04-07 18:25:16.158 <ZWED:67401> ZWESVUSR WARN (_zsf.routing,webapp.js:1295) 
ZWED0171W - Rejected undefined referrer for url=/login, ip=xx.xxx.xxx.x  
    
2021-04-07 18:25:16.460 <ZWED:67401> ZWESVUSR WARN (_zsf.auth,webauth.js:328) 
ZWED0003W - M8Gn8w60z2irLVx22PM44ntPktrAA-MS: Session security call authenticate 
failed for auth handler org.zowe.zlux.auth.safsso. Plugin response: 
{"success":false,"error":{"message":"ZSS 403 Forbidden"},"reason":"Unknown","apiml":true,
"zss":true,"sso":false,"canChangePassword":true}

2021-04-07 18:25:16.461 <ZWED:67401> ZWESVUSR INFO (_zsf.auth,webauth.js:325) 
ZWED0070I - M8Gn8w60z2irLVx22PM44ntPktrAA-MS: 
Session security call authenticate succesful for auth handler org.zowe.zlux.auth.trivial. 
Plugin response: {"success":true}

I cannot find doc on these error messages.  I had similar issues when I tried the V1.16 release last year.  I was hoping that one of the newer releases would resolve the issue.  I cannot seem to install any release after 1.12. Maybe I missed some security issue that changed from 1.12 to 1.20

Any help would be appreciated.

**Comment by jackjia-ibm** [comment]
This may related to the configurations of `ZOWE_EXPLORE_HOST` and `ZWE_REFERRER_HOSTS`. Could you please provide your `instance.env` and also Zowe job log where shows the app server configuration after line `ZWED5015I - Processed environment variables:`. Thanks.

@1000TurquoisePogs for you awareness.

**Comment by shgordon2222** [comment]
I redacted the hostname and ip-address from this data.  If you need the exact name, let me know.
hostname and ZOWE_EXPLORER_HOST are the same
Not sure it matters but ZOSMF_HOST and ZOWE_EXPLORER_HOST are different.

ZWED5015I - Processed environment variables:                                    
{                                                                               
  "node": {                                                                     
    "mediationLayer": {                                                         
      "enabled": true,                                                          
      "server": {                                                               
        "hostname": "xxxxxxxxxxx.xxx.xxxx.statefarm.org",                       
        "gatewayPort": 60687,                                                   
        "port": 60686                                                           
      }                                                                         
    },                                                                          
    "https": {                                                                  
      "keys": Ý                                                                 
        "/global/zowe/keystore/localhost/localhost.keystore.key"                
      ¨,                                                                        
      "port": 60693,                                                            
      "certificates": Ý                                                         
        "/global/zowe/keystore/localhost/localhost.keystore.cer-ebcdic"         
      ¨,                                                                        
      "certificateAuthorities": Ý                                               
        "/global/zowe/keystore/local_ca/localca.cer-ebcdic"                     
      ¨                                                                         
    }                                                                           
  },                                                                            
  "privilegedServerName": "ZWESIS_STD",                                         
  "agent": {                                                                    
    "jwt": {                                                                    
      "token": {                                                                
        "label": 0,                                                             
        "name": 0                                                               
      },                                                                        
      "fallback": true                                                          
    },                                                                          
    "http": {                                                                   
      "port": 60694                                                             
    }                                                                           
  },                                                                            
  "productDir": "/usr_lpp/zowe/components/app-server/share/zlux-app-server/defaults"
} 


instance.env:

# global config                                             
ROOT_DIR=/usr_lpp/zowe                                      
ZOWE_PREFIX=ZWE                                             
ZOWE_INSTANCE=1                                             
                                                            
# Comma separated list of components should start from ÝGATE
LAUNCH_COMPONENT_GROUPS=GATEWAY,DESKTOP                     
                                                            
JAVA_HOME=/sfopt/java80_b64                                 
NODE_HOME=/usr/lpp/IBM/cnj/v12r0/IBM/node-latest-os390-s390x
                                                            
# Set to 1 to skip using nodejs. This can only be done if th
SKIP_NODE=0                                                 
                                                            
# z/OS MF config                                            
ZOSMF_PORT=443                                              
ZOSMF_HOST=xx-xxxxxxxxx.xxx.xxxx.statefarm.org              
                                                            
ZOWE_EXPLORER_HOST=xxxxxxxxxxx.xxx.xxxx.statefarm.org       
ZOWE_IP_ADDRESS=xx.xxx.xxx.x                                
                                                            
# keystore config                                           
KEYSTORE_DIRECTORY=/global/zowe/keystore                    
                                         
# APIML variables                    
CATALOG_PORT=60685 # the port the API
DISCOVERY_PORT=60686 # the port the d
GATEWAY_PORT=60687 # the port the API
APIML_ALLOW_ENCODED_SLASHES=true     
APIML_CORS_ENABLED=false             
APIML_PREFER_IP_ADDRESS=true         
APIML_GATEWAY_TIMEOUT_MILLIS=600000  
APIML_SECURITY_X509_ENABLED=false    
APIML_SECURITY_ZOSMF_APPLID=IZUDFLT  
APIML_SECURITY_AUTH_PROVIDER=zosmf   
# List of discovery service URLs sepa
ZWE_DISCOVERY_SERVICES_LIST=https://$
# Enable debug logging for Api Mediat
APIML_DEBUG_MODE_ENABLED=false       
APIML_MAX_CONNECTIONS_PER_ROUTE=100  
APIML_MAX_TOTAL_CONNECTIONS=1000     
####################                 
# caching service                    
# TCP port of caching service        
ZWE_CACHING_SERVICE_PORT=7555        
# specify amount of records before ev
ZWE_CACHING_STORAGE_SIZE=10000       
# specify eviction strategy to be use
ZWE_CACHING_EVICTION_STRATEGY=reject 
# specify persistent method of cachin
# currently VSAM is the only option  
ZWE_CACHING_SERVICE_PERSISTENT=VSAM  
# specify the data set name of the ca
ZWE_CACHING_SERVICE_VSAM_DATASET=    
                                     
# explorer variables                    
JOBS_API_PORT=60688 # the port the jobs 
FILES_API_PORT=60689 # the port the file
JES_EXPLORER_UI_PORT=60690 # the port th
MVS_EXPLORER_UI_PORT=60691 # the port th
USS_EXPLORER_UI_PORT=60692 # the port th
ZOWE_EXPLORER_FRAME_ANCESTORS="${ZOWE_EX
                                        
# Zowe Desktop/app framework variables  
ZOWE_ZLUX_SERVER_HTTPS_PORT=60693       
ZOWE_ZSS_SERVER_PORT=60694              
ZOWE_ZSS_XMEM_SERVER_NAME=ZWESIS_STD    
ZOWE_ZLUX_SSH_PORT=22                   
ZOWE_ZLUX_TELNET_PORT=1029              
ZOWE_ZLUX_SECURITY_TYPE=tls             
  # The security type of the tn3270 conn
                                        
# Extender variables                    
ZWEAD_EXTERNAL_STATIC_DEF_DIRECTORIES= #
EXTERNAL_COMPONENTS= # For third-party e

**Comment by jackjia-ibm** [comment]
I don't see obvious issues from the configuration. @1000TurquoisePogs do you have any suggestions on how to debug the issue? Please feel free to move the issue to https://github.com/zowe/zlux if it makes sense. Thanks.

**Comment by jackjia-ibm** [comment]
@shgordon2222 you can also reach #zowe-dev slack channel to find troubleshooting guidance. For now, the issue is not clear enough to be a bug.
