### ISSUE TITLE
Unnecessary NODE_HOME dependency for APIML

### ISSUE THREAD

**Issue by js665999** [zowe/zowe-install-packaging#2073]
**Describe the bug**
APIML fails to start because NODE_HOME is empty even if node is not needed / SKIP_NODE=1 does not work

**To Reproduce**
1. set LAUNCH_COMPONENT_GROUPS=GATEWAY (APIML does not use node)
2. set SKIP_NODE=1 (should allow startup without node)
3. keep NODE_HOME empty during start-up 
> Error 0: NODE_HOME is empty
2021-04-13 09:28:20 <ZWELS:33950340> SOBJA02 ERROR (prepare-workspace.sh:27) Error 0: NODE_HOME is empty

**Expected behavior**
Start of APIML without NODE_HOME set

**Comment by jackjia-ibm** [comment]
Thanks @js665999 for reporting issue. NODE_HOME is mandatory right now for several tools we built to handle YAML files used by launch scripts. This is a temporary solution and the tool set will be migrated to other language when we are ready. `SKIP_NODE` is an unofficial variable we are not guaranteed it will work as it suggests.

**Comment by MarkAckert** [comment]
Closing this. For v1, we will keep the NODE_HOME dependency as that release line is in maintenance mode. For v2, we have Config Manager which offers a path away from the NODE pre-requisite. We also want to convert existing Node tools to another language - https://github.com/zowe/zowe-install-packaging/issues/2261 .
