### ISSUE TITLE
Improvements on ZWEKRING

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2089]
**Improvements would like to apply to ZWEKRNG jcl**

- ~~option 3 should be default~~ (fixed by https://github.com/zowe/zowe-install-packaging/pull/2101)
- ~~change jcl to tolerate empty value of ITRMZWCA, ROOTZWCA and ROOTZFCA~~ (fixed by https://github.com/zowe/zowe-install-packaging/pull/2101)
- ~~jwtsecret should be defined as config variable from beginning~~ (fixed by https://github.com/zowe/zowe-install-packaging/pull/2101)
- ~~re-organize jcl~~
- zowe-certificates.env is missing `EXTERNAL_CERTIFICATE_AUTHORITIES` value for keyring mode. This value should take correct CA list with safkeyring prefix and spaces in label.
- Investigate reasons why spaces are removed from `EXTERNAL_ROOT_CA` and consequences.
- `EXTERNAL_CERTIFICATE_AUTHORITIES` shouldn't use space as delimiter because cert label may have spaces in it.
- ZWEKRING hardcoded to only take one `CERTAUTH` label/cert to connect, if z/OSMF certificate doesn't have CA and defined as `PERSONAL` usage, it will not be able to handle.

If the user uses keyring mode, we have a step to export jwtsecret to pem and later will import it back to keyring again. This seems redundant and it requires unnecessary permission on `RDATALIB` for export permission.

**Comment by NayerNajafi** [comment]
@jackjia-ibm 
The current ZWEKRNG jcl has the following lines in the common part that should be clarified:
```
/* Uncomment this command if SITE acid owns the Zowe certificate     */
/*  PERMIT IRR.DIGTCERT.GENCERT CLASS(FACILITY) ID(&ZOWEUSER.) +       
/*         ACCESS(CONTROL)                                             
```
CONTROL authority to IRR.DIGTCERT.GENCERT is required for the RACDCERT GENCERT function. Users without SPECIAL authority must have authority to the IRR.DIGTCERT.GENCERT. According to [RACF document](https://www.ibm.com/docs/en/zos/2.1.0?topic=syntax-racdcert-gencert-generate-certificate), CONTROL access to IRR.DIGTCERT.GENCERT depends on specifying SIGNWITH operand in RACDCERT GENCERT command

![image](https://user-images.githubusercontent.com/44011615/115599818-0364a680-a2aa-11eb-9bca-b8c003db16b1.png)

So, I would interpret above lines in ZWEKRNG jcl as I want to use RACDCERT GENCERT command to create a new SITE certificate. The user ID who issue the command (SITE acid) will be ID(&ZOWEUSER.) that owns Zowe certificate.

My question is RACDCERT GENCERT SITE command is not included in ZWEKRNG jcl, so why that authority is needed? 
I already removed those lines in PR #2100, but want to make sure that my understanding is correct. Thanks!

**Comment by vit-tomica** [comment]
@NayerNajafi 
That requirement for 
```
/*  PERMIT IRR.DIGTCERT.GENCERT CLASS(FACILITY) ID(&ZOWEUSER.) +       
/*         ACCESS(CONTROL)       
```
is described here:
https://www.ibm.com/docs/en/zos/2.4.0?topic=library-usage-notes
and here:
https://www.ibm.com/docs/en/zos/2.4.0?topic=is-scenario-7-sharing-one-certificate-among-multiple-servers
The permission basically allows to read a private key from a cert owned by SITE acid

**Comment by NayerNajafi** [comment]
@vit-tomica 
Thanks for the clarification. I will add the PERMIT command back to ZWEKRING.

**Comment by jackjia-ibm** [comment]
Confirmed with Nayer we have done all improvements related to ZWEKRING for now. Closing.
