### ISSUE TITLE
Keytool importkeystore keystore password was incorrect

### ISSUE THREAD

**Issue by GilPen** [zowe/zowe-install-packaging#2108]
Hello

I'm trying to install the 1.20.1 version and to import zosmf.p12 certificate in a USS keystore.

I'm using the script zowe-setup-certificates.sh with a file zowe-setup-certificates.env 

Here the file zowe-setup-certificates.env

£ The hostname of the system running API Mediation.
£ script attempts to calculate the value on its own.                    
HOSTNAME=sdev.dns21.socgen                                              
£ The IP address of the system running API Mediation. If the IP address 
£ script attempts to calculate the value on its own.                    
IPADDRESS=192.64.144.1                                                  
£ Should APIML verify certificates of services - true/false             
VERIFY_CERTIFICATES=true                                                
£ Name of the z/OSMF keyring                                            
ZOWE_ZOSMF_HOST=sdev.dns21.socgen                                       
ZOSMF_KEYRING=SDEVzosmf                                                 
£ z/OSMF server user ID                                                 
ZOSMF_USER=IZUSRVR                                                      
£ optional - Path to a PKCS12 keystore with a server certificate for API
EXTERNAL_CERTIFICATE=/SYSTEM/etc/zowe/certificats/CSZOSMF2.p12          
£ optional - Alias of the certificate in the keystore                   
EXTERNAL_CERTIFICATE_ALIAS=1                                            
£ optional - Public certificates of trusted CAs                         
£XTERNAL_CERTIFICATE_AUTHORITIES="/SYSTEM/etc/zowe/certificats/CAUPAUTS 
EXTERNAL_CERTIFICATE_AUTHORITIES="/SYSTEM/etc/zowe/certificats/CAUN2ROT 
                                                                        
£ Select a password that is used to secure EXTERNAL_CERTIFICATE keystore
£ that will be also used to secure newly generated keystores for API Med
KEYSTORE_PASSWORD= XXXXXXX                                             
£ Location for generated certificates                                   
KEYSTORE_DIRECTORY=/usr/lpp/zowe/keystore                               
£ Select an alias for the certificate in the generated keystore         
KEYSTORE_ALIAS=localhost                                                
£ Specify zowe user id to set up ownership of the generated certificates
ZOWE_USER_ID=ZWESVUS                                                    
£ Specify zowe user id to set up ownership of the generated certificates
ZOWE_GROUP_ID=ZOWEADM                                                   

When I run the script, I get the error :
Import the signed certificate and its private key to the keystore:              
Calling keytool -importkeystore -v -deststorepass password -destkeypass password -destkeystore /usr/lpp/zowe/keystore/localhost/localhost.keystore.p12 -deststoretype 	PKCS12 -destalias localhost -srckeystore /SYSTEM/etc/zowe/certificats/CSZOSMF2.p12 	-srcstoretype PKCS12 -srcstorepass password -keypass password -srcalias 	1
keytool error (likely untranslated): java.io.IOException: keystore password was 
keytool returned: 1    

The CSZOMSF2.p12 password is not password. How can I declare a new passord in the setup script ?

Regards
Gilles Peniguel

 - Z/OS 2.4
 - Zowe Version 1.20.1

**Comment by jackjia-ibm** [comment]
Hi Gilles, if I'm correct, we currently simply use `KEYSTORE_PASSWORD` value as `EXTERNAL_CERTIFICATE` password. We can try to distinguish source keystore password from destination keystore password, but will be only available in future versions. For now, if you set `KEYSTORE_PASSWORD` to be the password of `CSZOSMF2.p12`, will it work?

**Comment by GilPen** [comment]
Hello 

Thank you for your reply.

I just need to get the password now.

Regards
Gilles Peniguel

**Comment by GilPen** [comment]
Thanks that'ok
