### ISSUE TITLE
Epic - Zowe on Kubernetes Research

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#2133]
Research and issues related to running Zowe on Kubernetes
---
#### Acceptance Criteria

Complete other issues for Zowe+Kube work and research. 
Creation of another epic for delivering Zowe on Kubernetes if necessary.

**Comment by jackjia-ibm** [comment]
This is done with containerization work.

Epic: https://github.com/zowe/zowe-install-packaging/issues/793
