### ISSUE TITLE
creating new instance with current existing instance running on the same LPAR

### ISSUE THREAD

**Issue by rmsmith2** [zowe/zowe-install-packaging#2163]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
when running zowe-configure-instance.sh the script goes into a wait state and does not complete execution if a already existing zowe instance is currently running on the LPAR on which you are working. This seems like an unrealistic restriction and should be fixed or al least documented.

**Comment by jackjia-ibm** [comment]
@Joe-Winchester

**Comment by Joe-Winchester** [comment]
Hi @rmsmith2 ,  I tried to re-create this running `zowe-configure-instance.sh` both on the existing instance directory of an active Zowe, and also for a new `-c` instance directory.  Both of these worked OK and looking at the scripts and knowing how they work I can't see a situation where a hang should occur.
Do you have any details about how we could re-create this or whether it's still failing if you re-do the same scenario ?
Cheers.

**Comment by rmsmith2** [comment]
Sorry, but I have no idea what you are talking about
Thank you, Bob
 
 
----- Original message -----From: "Joe Winchester" ***@***.***>To: "zowe/zowe-install-packaging" ***@***.***>Cc: "rmsmith2" ***@***.***>, "Mention" ***@***.***>Subject: [EXTERNAL] Re: [zowe/zowe-install-packaging] creating new instance with current existing instance running on the same LPAR (#2163)Date: Tue, Dec 14, 2021 9:37 AM      Hi @rmsmith2 , I tried to re-create this running zowe-configure-instance.sh both on the existing instance directory of an active Zowe, and also for a new -c instance directory. Both of these worked OK and looking at the scripts and knowing    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
Hi @rmsmith2 , I tried to re-create this running zowe-configure-instance.sh both on the existing instance directory of an active Zowe, and also for a new -c instance directory. Both of these worked OK and looking at the scripts and knowing how they work I can't see a situation where a hang should occur.Do you have any details about how we could re-create this or whether it's still failing if you re-do the same scenario ?Cheers.

**Comment by JoeNemo** [comment]
This will be out of support in Sept 2024.
