### ISSUE TITLE
Integrate new springboot based data-sets app into install 

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#217]
Similar to #206, but for data-sets
Depends on https://github.com/zowe/data-sets/issues/1
Depends on https://github.com/zowe/data-sets/issues/2

Pull down the assets from artifactory
Add a new port for the app into the yaml
share the api ml certificate with the app
Create a script to start the jar and call this from zowe-start?
What else?

**Comment by jackjia-ibm** [comment]
Done by https://github.com/zowe/zowe-install-packaging/pull/242
