### ISSUE TITLE
Containerization Spike: component image conformance

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2171]
Discuss and propose conformance related to Zowe containerization.

General rules for all Zowe components
- Base images (compliance, license)
- Folder structure (image and runtime)
- Start command
- Volume sharing
- Configuration & Secrets
- Preinstalled Linux tools
- Versioning recommendations

Special rules for component with plugin capability – AppServer
- Persistent Volume
- How Plugins should be imported

How to define zowe-install-packaging image:
- Folder structure
- Volume sharing

**Comment by NakulManchanda** [comment]
[Zowe Docker & Kubernetes -OS.pptx](https://github.com/zowe/zowe-install-packaging/files/6678926/Zowe.Docker.Kubernetes.-OS.pptx)
