### ISSUE TITLE
Change zowe-install-proc.sh to be able to copy ZWESLSTC (Zowe HA launcher)

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/zowe-install-packaging#2189]
As part of Zowe high availability installation, we require to copy Zowe Launcher to PROCLIB data set through zowe-install-proc.sh script. Right now it only support ZWESVSTC procedure. 
https://docs.zowe.org/stable/user-guide/scripted-configure-server.html#zowe-z-os-components

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by NayerNajafi** [comment]
Thanks @AdarshdeepCheema 
I just tried the script and it worked fine. Now both ZWESVSTC and ZWESLSTC will be copied to PROCLIB data set.

**Comment by AdarshdeepCheema** [comment]
We are now copying Zowe Launcher(ZWESLSTC ) to PROCLIB data set through zowe-install-proc.sh script.
