### ISSUE TITLE
zowe-install.sh unable to run deploy.sh on line 116

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#222]
A number of users have reported problems with zowe-install.sh when it is unable to run deploy.sh on line 116.
This is because the line is
. deploy.sh
and changing it to be 
./deploy.sh
picks up the file correctly.

**Comment by jackjia-ibm** [comment]
Fixed with PR https://github.com/zowe/zowe-install-packaging/pull/223
