### ISSUE TITLE
Create APIML component images

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2240]
**Description**

Build per-component images for APIML components:
- gateway
- discovery
- api catalog
- caching service

**Exit Criteria**

1. The images should be one image per component.
2. The images can be started without Zowe context and be used in APIML repository Github Actions CI tests.
3. The images should follow conformance defined at https://github.com/zowe/zowe-install-packaging/pull/2220
4. The images should use base images created by https://github.com/zowe/zowe-install-packaging/issues/2238
5. The images should provide flavor mixes of `ubuntu`, `ubi`, `amd64` and `s390x`.
6. Provide basic automation to build and release images.

**Comment by anton-brezina** [comment]
Hi, @jackjia-ibm , we'd like to know whether here is some support required by the API ML squad.

**Comment by jackjia-ibm** [comment]
I believe we can close this since all 4 conformant images are created.
