### ISSUE TITLE
Convert Kubernetes deployment to docker-compose

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2249]
**Description**

`docker-compose` still provides value for users don't have Kubernetes environment. For example, quick development environment without concern of multiple component instances, or deploying to zCX.

**Exit Criteria**

1. One instance per component is good enough.
2. Should be able to start all components working on Kubernetes deployment.
3. Should use same images used in Kubernetes deployment.
4. Should verify it works well with zCX.
5. Add this new sample configurations as part of containerization artifact.

**Comment by 1000TurquoisePogs** [comment]
Not MVP?

**Comment by MarkAckert** [comment]
I am going to close this issue. The primary target for `docker-compose` is zCX, and zCX itself is moving away from docker compose and into Kubernetes. For development environments, we can prefer `minikube` over `docker-compose`, and Docker Desktop ships w/ Minikube. If anyone disagrees, please re-open and share your reasoning. Thanks!
