### ISSUE TITLE
Convert zowe-install-packaging-tools to C

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2261]
**Description**

Currently zowe-install-packaging-tools hard pre-reqs node.js. Would like to convert it to Golang based so we can remove node.js dependency in some scenario.

Restrictions: Golang binary can only run on z/OS v2.4+ with certain LE PTFs.

**Exit Criteria**

1. Convert tools `njq`, `fconv`, and `config-converter` to Golang based, compile on both Ubuntu and z/OS system.
2. Create new tool called `gotest` to verify if golang binary can run properly on target system.
3. Package both golang and node.js version into final package.
4. Install the new utilities with zowe-install-packaging and based on `gotest` result, choose which set of tools will be used.
5. Change component base image to remove node.js.

**Comment by jackjia-ibm** [comment]
Based on Golang SDK requirement: https://www.ibm.com/common/ssi/cgi-bin/ssialias?infotype=AN&subtype=CA&htmlfid=897/ENUS221-044&appname=USN

```
Key requirements

IBM Z servers that support z/OS V2R4 (5650-ZOS), or later.
```

That means the go version tool only works on z/OS v2.4+. So we would like to change this scope to use C.

**Comment by jackjia-ibm** [comment]
There is C YAML format library listed in https://yaml.org/.

**Comment by jackjia-ibm** [comment]
General requirement: the compile program should work on z/OS major version Zowe claimed to support, as well as running on Linux (amd64 and s390x CPU), so we can use same tool in Kubernetes deployment.

Tools we need:

- `file-converter`: convert JSON file to YAML file, or convert YAML file to JSON file. The output can be a target file specified with `-o` parameter, or to `stdout`.
- `jq`: extract value from JSON file (ideally also works directly on YAML file without extra call of `file-converter`). Information of `jq`: https://stedolan.github.io/jq/manual/. We don't need to support full jq features but just the most basic cases of extracting value from a path. The path should support reading array. Examples to read https://github.com/zowe/zowe-install-packaging/blob/master/manifest.json.template:
  * `jq -r ".version"`
  * `jq -r ".build.hash"`
  * `jq -r ".imageDependencies[1].registry"`
- `update`: to update values of json/yaml file. Ideally when we updating YAML file, the comments inside the YAML file will be kept and won't disappear. Usage example:
  * `update /path/to/my/yaml ".version" "2.0.1"`
  * `update /path/to/my/json ".build.hash" "8324893095094"

The program/utility tool name is not important. So above name is just an idea.

The tools should stay in https://github.com/zowe/zowe-install-packaging-tools repo

**Comment by jackjia-ibm** [comment]
Detail introduction of zowe.yaml: https://docs.zowe.org/stable/user-guide/configure-instance-directory#updating-the-zoweyaml-configuration-file

There are few very special about zowe.yaml:

- [Extract sharable configuration out of zowe.yaml](https://docs.zowe.org/stable/user-guide/configure-instance-directory#extract-sharable-configuration-out-of-zoweyaml)
- [Configuration override](https://docs.zowe.org/stable/user-guide/configure-instance-directory#configuration-override)
- [YAML configurations - certificate](https://docs.zowe.org/stable/user-guide/configure-instance-directory#yaml-configurations---certificate)

**Comment by 1000TurquoisePogs** [comment]
This has largely been done by removal of shell code.
