### ISSUE TITLE
Remove explorer-server from Zowe

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#235]
Remove explorer-server from Zowe
1)  Update the install scripts:
**zowe-install.sh.**     Dont' call /zowe-install-liberty-server.sh
**zowe-verify.sh**      Needs separate git issue to be updated
**zowe-explorer-ui-configure.sh.   Swop ZOWE_EXPLORER_HOST to ZOWE_IPADDRESS for EXPLORER_JES_FULLURL
**zowe-api-mediation-configure.sh**   Remove lines for static definition for MVS datasets
     datasets.yml
**zowe-prepare-runtime.sh**  line 41 makes a /explorer
**zowe-runtime-authorize.sh**  at end of file remove the symlink for bootstrap.properties, jvm.security.override.properties and ltpa.keys and the folders it creates beneath /Atlas
**zowe-parse-yaml.sh** remove the reading and setting of ZOWE_EXPLORER_HTTP_PORT and ZOWE_EXPLORER_HTTPS_PORT
**run-zowe.sh** remove the line that starts Atlas
**zowe-install-yaml.template** Remove explorer-server's httpPort and httpsPort= lines, update comment "ports for `explorer-api-servers`

Remove the install scripts
      **zowe-install-liberty-server.sh**

2) Update the build
         update **artifactory-download-spec-json.template** to drop atlas-wlp packaging and also update the file that has the count it compared against (can't remember what this is)

**Comment by 1000TurquoisePogs** [comment]
I'll approve a PR that removes explorer-server from "zlux" repo, just let me know.
