### ISSUE TITLE
Configure DB2 on Marist and migrate DB2 testing

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2432]
Zowe DB2-CLI requires DB2 package SYSSH200 present in DB2. @db2cli.lst must be run to bind NULLID.SYSSH200

**Comment by NayerNajafi** [comment]
Bind package SYSSH200 on zzow04.zowe.marist.cloud was done successfully. I am able to interact with IBM DB2 for z/OS through zowe db2 CLI command on Marist.
