### ISSUE TITLE
Zowe Cross Memory server  is unable to connect to zOSMF 

### ISSUE THREAD

**Issue by rashmijtp44** [zowe/zowe-install-packaging#2441]
I am installing ZOWE for the first time in Mainframe. I am using ACF2 Certificate and keyring. While bringing up Zowe cross memory server, I am getting below error. Looking for assistance. 

(prepare-instance.sh:326) starting Zowe instance sy78 from /etc/zowe ...       
(config-utils.sh,convert_all_component_manifests_to_json:1) prepare component m
(prepare-instance.sh,global_validate:1) process global validations ...         
(prepare-instance.sh,global_validate:24) Node v12.21.0 is supported.           
(prepare-instance.sh,global_validate:28) Java version 1.8.0_271 is supported   
(prepare-instance.sh,global_validate:34) Error 0: Could not contact z/OS MF on 'https://sy78.newyorklife.com:30443/zosmf/info' - 403 
(prepare-instance.sh,global_validate:44) global validations are successful     
(prepare-instance.sh,prepare_workspace_dir:1) prepare workspace directory ...  
(prepare-instance.sh,validate_components:1) process component validations ...  
(prepare-instance.sh,configure_components:1) process component configurations .
(prepare-instance.sh:366) Zowe runtime environment prepared                    
-component.sh:95) starting component caching-service ...                       

Thanks,
Rashmi

**Comment by jackjia-ibm** [comment]
@rashmijtp44 do you see other following failures in job log?

Depends on the Zowe version, the zosmf 403 failure could be missing proper header when we testing, but the server is actually there and live. My current thought is we can ignore it.

**Comment by Martin-Zeithaml** [comment]
Closing (Zowe V1 is not supported).
