### ISSUE TITLE
v1~v2 extension migration guidance

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2454]
Prepare documentation for extenders to migrate their extensions from v1 to v2. This migration documentation will be more from zowe-install-packaging pov.

**Comment by MarkAckert** [comment]
Work as part of https://github.com/zowe/docs-site/issues/1826

**Comment by MarkAckert** [comment]
Where does this doc go on docs.zowe.org?

**Comment by jackjia-ibm** [comment]
Implemented in https://github.com/zowe/docs-site/pull/2035/files#diff-2c736848cc63bfd524a40479405d71fd99cbe5ba862636778b9ceb480151b27aR1
