### ISSUE TITLE
Investigate automatically generating reference documentation

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2460]
The reference documentation includes:

- all `zwe` CLI commands
- all `bin/libs` shell functions

**zwe CLI Commands**
- [x] Scan `.xxx` files
- [x] Generate md files from `.xxx` files
- [x] Include inherited documentation from parent commands
- [x] Link to parent and child commands
- [x] Add synopsis section
- [x] Fix parameter documentation
- [x] Clean up code to be maintainable and extensible
- [x] Fix file title and add links in synopsis

**bin/libs shell functions**
moved this work to new issue #2685 

**docs site**
- [x] Merge PR to docs side to add documentation for the first time
- [x] Create side bar reference
- [x] Generate nav menu
- [x] Fix code formatting in examples

**automation**
- [x] Run GHA job on push to submit PR to update docs site content

**Comment by jackjia-ibm** [comment]
Yes it works like that. The intention is providing a quick reference for all available `zwe` commands and library function for the end-user on website and easier to read through.

**Comment by MarkAckert** [comment]
> Yes it works like that. The intention is providing a quick reference for all available `zwe` commands and library function for the end-user on website and easier to read through.

See Zowe CLI web-help for an example

**Comment by jalel01** [comment]
hey @jackjia-ibm do you have a destination for this already decided? You say 'website' earlier and i'm curious where it will live.
