### ISSUE TITLE
Migrate playbooks and installation/sanity test for v2

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2462]
To successfully test v2, we need to migrate:

- playbooks to apply v2 installation/configuration experience,
- remove unused or adjust sanity test for v2
- adjust installation test for v2 if neccessary

**Comment by achmelo** [comment]
api-layer squad will take a look at sanity tests

**Comment by jackjia-ibm** [comment]
Sounds good and thank you.`tests/sanity/test/utils-scripts` mostly will not be valid for v2 since we changed a lot on the library functions. It's ok to remove these tests and test the functions with task https://github.com/zowe/zowe-install-packaging/issues/2457.
