### ISSUE TITLE
z/OSMF Zowe Create Runtime Workflow Loop Condition

### ISSUE THREAD

**Issue by EnsonoStevenPerva** [zowe/zowe-install-packaging#2473]
**Describe the bug**
When executing the Zowe Create Runtime workflow, Step 6 "Run install script" has a loop condition when Node.js is not present on the system. The script seems to loop indefinitely until a condition is met on the system to terminate the process.

**To Reproduce**
1. From an LPAR **without** Node.js installed, continue through the workflow until step 6.
2. Launch step 6 from the Perform tab.
3. Wait for the job to fail, this will depend on your system configuration.
4. Output will show the follow messages:
```
Beginning install of Zowe 1.25.0 into directory  /usr/lpp/zowe
Error 0: NODE_HOME: /usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin does not point to a valid install of Node
Press Y or y to accept current node home '/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x', or Enter to choose another location
Please enter a path to where node is installed.  This is the a directory that contains /bin/node
Error 1: NODE_HOME is empty
Press Y or y to accept current node home '', or Enter to choose another location
Please enter a path to where node is installed.  This is the a directory that contains /bin/node
[...]
Error 145992: NODE_HOME is empty
Press Y or y to accept current node home '', or Enter to choose another location
Please enter a path to where node is installed.  This is the a directory that contains /bin/node
```

**Expected behavior**
The workflow should detect that `NODE_HOME` is invalid and fail through this non-interactive invocation of the script.

**Screenshots**
![chrome_mvtTCSJuAl](https://user-images.githubusercontent.com/87535226/143049664-22077c81-cfa8-4b1b-9f19-30e50c342605.png)

**Additional context**
I understand this issue would not occur had Node.js been installed and setup correctly, I would just expect the workflow to fail and not loop.

**Comment by muzikovam** [comment]
This is only valid for v1 workflow and the workflow for v2 doesn't have this issue. It was caused by the zowe-install.sh which required manual input and is not easy to handle by the workflow.
