### ISSUE TITLE
ZWEAM511E error accessing ZSS service from catalog

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zowe-install-packaging#2479]
Running into issue accessing ZSS service (Zowe 1.24.0).  Always got a ZWEAM511E error.

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/44960894/143861480-17f8dca3-d3b8-4ea5-b7a1-114e287aa05e.png">

After some debugging Jack found following errors in our log.

```
"CSFPTRC retCode = 0x8, rsnCode = 0x3e80" error.
 
3E80 (16000)
RACF failed your request to use this service or PKCS #11 token. This may be caused by the CSFSERV or CRYPTOZ class..
User action: Contact your ICSF or RACF administrator if you need this service.
 ```

Double checked all the resource needed, one of the resource CSFRNGL under CSFSERV was needed. 

<img width="938" alt="image" src="https://user-images.githubusercontent.com/44960894/143860270-38fdae07-b5e2-4281-8fd9-5a69547cccc2.png">

We used to have access to this profile. But there's a new feature in CSF called profile prefixing, so related profile  in our system is  called &CSFSYS.CSFRNGL  , and Zowe user has READ access to it. But I still have issues using this profile.  Not sure if ZSS can deal with this change? 

Open this for tracking. Thanks.

**Comment by jackjia-ibm** [comment]
Thanks @rjmaomao for raising the issue.

After talked to the team, seems we may need some permissions we didn't document.

This document covers how to control what user can access which `CSF*` services: https://www.ibm.com/docs/en/zos/2.4.0?topic=in-setting-up-authorization-icsf-callable-services

From within the code and Zowe's docs, I see 4 total calls that Zowe may do:

- `CSFPTRL` =  The initial loading, which failed
- `CSFPOWH` = verifying SSO token according to algorithm type
- `CSFPHMG` = verifying SSO token according to a different algorithm type
- `CSFRNGL` = cookie generation upon successful authentication

So, can you check if "`ZWESVUSR` (or your Zowe runtime user) has permissions to use these services? Sorry if this was not covered already.

Seems on our testing server, we granted `UACC(READ)` that's why our testing is ok:

```
 CLASS      NAME                                         
 -----      ----                                         
 CSFSERV    * (G)                                        
                                                         
 LEVEL  OWNER      UNIVERSAL ACCESS  YOUR ACCESS  WARNING
 -----  --------   ----------------  -----------  -------
  00    SYS1            READ               READ    NO    
```

FYI @1000TurquoisePogs

**Comment by rjmaomao** [comment]
Hi Jack, 

So you mean the new profile pattern is not a problem, Zowe can deal with it correctly. The issue here is we are lacking authorization of some CSF profiles, and these requirement are not documented in Zowe doc, right?

We don't have generic profile * under class CSFSERV, the control is more strictly in out env. I just confirmed that we don't have CSFPTRL, CSFPOWH, CSFPHMG in our CSF configuration. If we are going to create related profiles, we can create &CSFSYS.CSFPTRL, &CSFSYS.CSFPOWH, &CSFSYS.CSFPHMG, right?

Thanks.

**Comment by jackjia-ibm** [comment]
@rjmaomao I didn't get confirmation where ZSS can handle profile prefixing correctly or not. But seems `CSFPTRL` permission is required. So yes would like to suggest to create those permissions and see if that helps. Thanks a lot Jing.

**Comment by rjmaomao** [comment]
@jackjia-ibm  All the profiles are in place and user id has access to it , but I still get the same error message when accessing ZSS service. Could you please help to take a look? Thanks!

&CSFSYS.CSFPTRL
&CSFSYS.CSFPOWH
&CSFSYS.CSFPHMG
&CSFSYS.CSFRNGL

**Comment by rjmaomao** [comment]
@jackjia-ibm We added another resource &CSFSYS.CSF1TRC(see lacking of this authorization from syslog), but still seeing same error.  Is there any document on what CSF requirement needed for Zowe? I checked in Zowe doc, only see user id ZWESVUSR under system requirement section mentioned some CSF authorization, but seems not enough. 
https://docs.zowe.org/stable/user-guide/systemrequirements-zos/#zwesvusr

Now I see more ICH408I against following profile.  Can you clarify if they are needed and if there will be more?
&CSFSYS.CSFIQA       
&CSFSYS.CSF1SKD

**Comment by jackjia-ibm** [comment]
@rjmaomao you are right, those permissions are not documented.

I don't have enough knowledge on this.  @1000TurquoisePogs or @lchudinov do you know what could go wrong? Will the profile prefixing affect ZSS to read the token?

**Comment by rjmaomao** [comment]
@jackjia-ibm 
After adding authorization to following profile, I didn't see  ZWEAM511E any more. But using ZSS service still fail. Please see my screenshot attached  below.
&CSFSYS.CSFIQA
&CSFSYS.CSF1SKD
&CSFSYS.CSF1SKE

401 was returned with Not Authorized, do you know what authorization is it asking? I didn't see more ICH408I in CSF, so this may not related to ICSF?
<img width="1577" alt="image" src="https://user-images.githubusercontent.com/44960894/145364728-7210eb3d-9407-46e8-9773-e3f8901d6f4d.png">

**Comment by jackjia-ibm** [comment]
FYI I believe after this PR https://github.com/zowe/zss/pull/363 was merged at Dec 8, this may not be an issue any more in v1.27.0 release.

**Comment by MarkAckert** [comment]
I will be closing this issue, as it has not seen recent activity and a potential fix was merged. If you think this issue persists in the v1.27+ release line, please re-open the issue with additional details. Thank you!
