### ISSUE TITLE
Split ZWEKRING jcl for v2

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2482]
In v2, we would like to separate the use case of certificate import vs generate.

For ZWEKRING, we can split the usage for 2 purposes and the user can choose which use case fits them:
- The user is importing external certificates they requested from other services.
- The user is using Zowe generated certificates.

**Comment by Martin-Zeithaml** [comment]
Solved by https://github.com/zowe/zowe-install-packaging/pull/3890.
