### ISSUE TITLE
Allow to define port offset instead arbitrary port number

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2486]
For now, all port number definition is a fixed number.

Would like to have ability to define an offset from gateway. For example, `port: "+1"` which means it will use a port number of `gateway-port + 1` as final port number. If the user gateway port is 7554, that means this component will be started as `7555`.

Add documentation which instructs the user to reserve port range for Zowe.

Further consideration: this should be compatible with containerization works.

**Comment by achmelo** [comment]
api-layer squad is willing to help with this issue

**Comment by jackjia-ibm** [comment]
Sounds good and thank you.

To complete this work, will need to work on [zowe/zowe-install-packaging-tools ](https://github.com/zowe/zowe-install-packaging-tools/tree/v2.x/master/config-converter) where parses zowe.yaml.
