### ISSUE TITLE
Install creates a bad proclib if the length of the rootDir flows over the end of the proclibJCL

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#254]
The installer should either
1) Not allow the rootDir to be such that col 72 is hit in the ZOWESVR proclib
OR better would be
2) the JCL generated inserted some kind of continuation character and wrapped correctly

**Comment by stevenhorsman** [comment]
Rootdir not injected in PROCLIB JCL anymore
