### ISSUE TITLE
zowe.yaml dense reading

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#2541]
In zowe v2, zowe.yaml is an important file to read and understand.
But when I first read it, it was less than ideal for me to read the comments next to the properties. I think we need to improve the formatting.

Some ideas:
- Put more blank lines between comments that are related to a line of code, and an unrelated line of code
- Put some better `#----------Headers----------` for sections, perhaps with descriptions of what the section is about?

**Comment by achmelo** [comment]
@jackjia-ibm does this issue still need work?

**Comment by jackjia-ibm** [comment]
@1000TurquoisePogs does this https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/bin/example-zowe.yaml#L31 look as expected? Detail comments we can always create PR to fix anytime. I hope PR#2563 fulfilled the purpose of this issue.
