### ISSUE TITLE
installer failure logging cp: ../zlux-example-server/config/server.cert: EDC5129I No such file or directory.

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#255]
The 1.0.0 install log failures
cp: ../zlux-example-server/config/server.cert: EDC5129I No such file or directory.
cp: ../zlux-example-server/config/server.key: EDC5129I No such file or directory.

**Comment by dmitrynikolaev** [comment]
Have no idea why it works this way, but the zlux pipeline pulls it from https://gizaartifactory.jfrog.io/gizaartifactory/list/rocket-closed-source-builds/latest/

**Comment by 1000TurquoisePogs** [comment]
I'm trying to fix this via https://github.com/zowe/zlux-build/pull/14/files

**Comment by dmitrynikolaev** [comment]
The fix has been merged, and zlux has been re-built.

**Comment by 1000TurquoisePogs** [comment]
Closing this with the assumption that it's fixed, but reopen if it isnt.
