### ISSUE TITLE
install failure.   ..//scripts/zowe-api-mediation-configure.sh 102:  Execute permission failure

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#256]
/u/winchj/zowe-1.0.0/install/..//scripts/opercmd: /u/winchj/zowe-1.0.0/install/..//scripts/zowe-api-mediation-configure.sh 102: .: zowe-install.sh 136: FSUM9209 cannot execute: reason code = ef076015: EDC5111I Permission denied.
Attempting to setup Zowe Explorer API certificates ... 
ls: FSUM6785 File or directory "jobs-api-server-*.jar" is not found
ls: FSUM6785 File or directory "data-sets-api-server-*.jar" is not found

**Comment by jackjia-ibm** [comment]
The last 2 lines are related to issue #259 and should have been fixed with #264 .

**Comment by jackjia-ibm** [comment]
The first line of error is related to issue #266.

**Comment by jackjia-ibm** [comment]
Verified with build 403.
