### ISSUE TITLE
tomcat api start scripts for jobs and datasets explorers

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#259]
Error: Invalid or corrupt jarfile /u/stonecc/zowe/1.0.0/scripts/internal/../../explorer-jobs-api/scripts/../     
Error: Invalid or corrupt jarfile /u/stonecc/zowe/1.0.0/scripts/internal/../../explorer-data-sets-api/scripts/../
******************************** BOTTOM OF DATA *****************************************************************

The data-sets-api-server-start.sh and 
jobs-api-server-start.sh don't have the .jar file correct

**Comment by jackjia-ibm** [comment]
PR https://github.com/zowe/zowe-install-packaging/pull/264

**Comment by jackjia-ibm** [comment]
Verified with build 403.
