### ISSUE TITLE
v2 PSWI support

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#2598]
PSWI automation should run against v2 install and generate a valid Zowe v2 PSWI instance.

**Comment by MarkAckert** [comment]
Blocked by #2590

**Comment by jackjia-ibm** [comment]
After PR https://github.com/zowe/zowe-install-packaging/pull/2610 is merged, we can successfully build SMPE. This should unblock PSWI work. Test build is https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/2.0.0-PR-2610/zowe-smpe-2.0.0-pr-2610-3-20220128151106.zip.
