### ISSUE TITLE
Research - RACDCERT Create and Zowe

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#2602]
RACDCERT Created certificates do not appear to work correctly with Zowe - certificate is in error (domain mismatch, other).

**Comment by 1000TurquoisePogs** [comment]
This canont be. We do this in zowe testing: https://github.com/zowe/zowe-install-packaging/blob/feature/v3/jcl/files/SZWESAMP/ZWEIKRR1#L108-L143

I'm closing this but reopen if you believe it's still valid and have more info on how it's different than above?
