### ISSUE TITLE
Init certificates can fail in automation

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#2608]
Posted for an extender trying out v2.

Try running `zwe init certificates` in an environment that has few env vars such as automation, and you may find this result:
```
zwe init certificate --allow-overwritten --update-config -c /myzowe/zowe.yaml
-------------------------------------------------------------------------------
>> Creating certificate authority "local_ca"

>>>> Generate PKCS12 format local CA with alias local_ca:
  * Exit code: 127
  * Output:
    keytool: pkeytool 4: pkcs12_create_certificate_authority 18: /myzowe/bin/commands/certificate/pkcs12/create/ca/index.sh 40: .: zwecli_process_command 4: /myzowe/bin/zwe 96: .: zwecli_inline_execute_command 9: /myzowe/zowe_runtime/bin/commands/init/certificate/index.sh 198: .: zwecli_process_command 4: /myzowe/zowe_runtime/bin/zwe 96: FSUM7351 not found
Error ZWEL0168E: Failed to create certificate authority "local_ca".
```

When I look at the code I see: https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/bin/libs/certificate.sh#L35
keytool comes from $JAVA_HOME/bin, but we call it directly here. Likely the cause of failure is that PATH didnt contain it.
I imagine the fix is just to reference $JAVA_HOME when possible.

**Comment by jackjia-ibm** [comment]
Please validate if this is still an issue in v2.0.0-TP2. I made some changes to check whether java is available on certain commands.

**Comment by jackjia-ibm** [comment]
Please reopen if this is still an issue.
