### ISSUE TITLE
Install logs message ZOWE_EXPLORER_SERVER_MVS_PORT not specified: Defaulting..

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#261]
The install logs the failure  message
ZOWE_EXPLORER_SERVER_MVS_PORT not specified:  Defaulting to 7443

**Comment by jackjia-ibm** [comment]
PR https://github.com/zowe/zowe-install-packaging/pull/262

**Comment by jackjia-ibm** [comment]
Verified with build 403.
