### ISSUE TITLE
Investigate  possibilities to automated `zwe install` command

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2628]
Some people may not fully understand why we need `zwe install` command. Options we have could be:

- identify if it's convenience build or SMPE install
- if it's convenience build, we can do `zwe install` automatically when the user run `zwe init`.

**Comment by 1000TurquoisePogs** [comment]
It is limited to pax in doc, but also separate from init for keeping runtime separate from instance.
