### ISSUE TITLE
Define default search path of zowe.yaml

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2629]
Make `-c|--config` optional by looking few default locations of zowe.yaml:

- `$(pwd)/zowe.yaml`
- `~/zowe.yaml`
- `~/.zowe/zowe.yaml`
- ~~`/etc/zowe/zowe.yaml`~~

Other enhancement: allow relative path with `-c|--config` option.

When we display error ZWEL0105E, also saying what are the default locations you can put.

Also consider pre-define `ZWE_CLI_PARAMETER_CONFIG` variable.

**Comment by DivergentEuropeans** [comment]
Will do easier things first & then come back to this

**Comment by jackjia-ibm** [comment]
Added quick tip into README: https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/ZOWE.md#zoweyaml of how to define `ZWE_CLI_PARAMETER_CONFIG`.
