### ISSUE TITLE
ZOWE_ZOSMF_PORT is failed to get a value during installation

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#263]
**Test Build:**

`libs-snapshot-local/com/project/zowe/1.0.0-SNAPSHOT/zowe-1.0.0-20190115.114341-392.pax`.

**Test System**

zD&T

**Description:**

During Zowe installation, in certain cases ZOWE_ZOSMF_PORT is failed to get a value. This may cause several consequences:

- `api-mediation/api-defs/zosmf.yml` has a `instanceBaseUrls` with value `https://S0W1:/zosmf/`, which will fail to load this service in apiml.
- `explorer-jobs-api/scripts/jobs-api-server-start.sh` has line of `-Dzosmf.httpsPort= \`, which will fail the jobs api calls,
- `explorer-data-sets-api/scripts/data-sets-api-server-start.sh` has line of `-Dzosmf.httpsPort= \`, which will fail the data sets api calls.

**Comment by kathysychan** [comment]
I ran into the same problem of zowe-install.sh not able to get zOSMF port on a zOS LPAR. This typically happens when running zowe-install.sh from our Jenkins pipeline. This only starts to happen after we pick up the 01/11 Zowe nightly driver.
