### ISSUE TITLE
Investigate Zowe v2 CANCEL (/C) Handling

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#2632]
Zowe v2 requires /P to shut down. There is some concern that /C shutdowns may still happen for various reasons, and Zowe should handle the /C command gracefully.

**Comment by jackjia-ibm** [comment]
Experiment on launcher to know it's `/C` before launcher receives SIGKILL.

**Comment by jackjia-ibm** [comment]
Several discussions concludes `P` is the right command to terminate Zowe job. Close for now.
