### ISSUE TITLE
zwe components install does not set enabled/disabled state

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#2634]
It seems there's some ongoing work to allow components to set default config values as stated from their manifest.
However, even the simplest component needs an enabled/disabled boolean, right?
I noticed when installing an external component, zowe.yaml does not get updated to add a section for it with an `enabled`, and there's no `--update-config` option to force that. Also, it seems the component is disabled by default. I would expect enabled by default for simplicity.

**Comment by jackjia-ibm** [comment]
There are 2 commands missing `zwe components enable` and `zwe components disable`.

We can enable the newly installed component by default.

**Comment by 1000TurquoisePogs** [comment]
I like the `--skip-enable` or other similar ways to explain that the default behavior of `zwe components install` should be enable by default. I feel most people would expect components to be enabled right after they install them, but some components may need extra config and therefore document the need for `--skip-enable`
