### ISSUE TITLE
zowe.yaml "hlq" really means "dataset prefix"

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#2635]
https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/bin/example-zowe.yaml#L42
the "hlq" parameter in zowe.yaml is not used as an HLQ nor is the default an HLQ. An HLQ is the first up to 8 characters of a dataset name before the '.'
Its actual usage is as a dataset prefix. I think it's fine to just say "prefix" as it will read as "zowe.setup.mvs.prefix" which should be easily understood.

**Comment by jackjia-ibm** [comment]
Not in TP1.

**Comment by adityadr-joy** [comment]
PR is merged so closing this issue
