### ISSUE TITLE
Upgrade ZOWE version 1.26.0, no zlux connection

### ISSUE THREAD

**Issue by GilPen** [zowe/zowe-install-packaging#2655]
Hello

I'm trying to upgrade to 1.26.0 ZLUX version.

First I was trying to interface with TOP SECRET SAF but it didn't work so I decide to install the certificats in USS directories as previous versions.

With the new version, I can't logging to ZLUX because the IP port isn't listening. However the API ML page is answering correctly.

I noticed a new parameter is necessary in instance.env : APIML_SECURITY_JWTINITIALIZERTIMEOUT=120

In logs, the message "ZWED0151W - unhandledRejection  TypeError: locations.forEach is not a function" appears. The log file is joined.

Thanks for your help

Gilles Peniguel

Versions :
ZOS 2.4
ZOWE 1.26.0
Nodejs v12.18.0
Java version 1.8.0_311

[appServer-2022-02-10-15-18.log](https://github.com/zowe/zowe-install-packaging/files/8048270/appServer-2022-02-10-15-18.log)

**Comment by jackjia-ibm** [comment]
@GilPen based on the error trace, seems `node.https.certificateAuthorities` should be an array but it's a string. I can think of 2 variables to check:

1. If you defined `ZWED_node_https_certificateAuthorities` in your instance.env. If so, you can try to add a comma `,` at the end of the value. This way, the configuration should be converted to an array instead of string.
2. If you don't have that variable in instance.env, you may check `EXTERNAL_CERTIFICATE_AUTHORITIES` defined in `<keystore>/zowe-certificates.env`. Add comma at the end of the value if it doesn't have.

@1000TurquoisePogs for you awareness.

**Comment by GilPen** [comment]
Thank you very much for your fast answer

Now the IP port is listening and I have the ZOWE authentification page. Unfortunatly, the message "Authentication failed for 1 types. Types: ["zss"]".  I'm investigating

**Comment by GilPen** [comment]
Hello, 

Now the ZOWE authentification web page is displayed correctly. But I can't log in. The message  "Authentication failed for 1 types. Types: ["zss"]" appears.

I suppress the line "ZWED_node_https_certificateAuthorities=" from instance.env file and I put them in the zowe-certificates.env file as "EXTERNAL_CERTIFICATE_AUTHORITIES=".

[appServer-2022-02-14-10-35.log](https://github.com/zowe/zowe-install-packaging/files/8061651/appServer-2022-02-14-10-35.log)

Regards
Gilles Peniguel

**Comment by GilPen** [comment]
Hello

In the log we can see this message as well : "2022-02-14 10:35:26.101 <ZWED:178> ZWESVUS WARN (_zsf.bootstrap,util.js:261) ZWED0052W - Error when reading file=/usr/lpp/zowe/keystore/local_ca/extca.1.cer-ebcdic. Error=Too few bytes to read ASN.1 value.". 

However I generated the certificate with the script "zowe-setup-certificates.sh -p /usr/lpp/zowe/keystore/". Is it just a warning or is it an error ?

Regards
Gilles Peniguel

**Comment by GilPen** [comment]
Hello

I can see some errors for authentification in the log file. I replace my password in the log file; maybe it's not a good idea to display the password for security reason.

[Log_zss_authentification.txt](https://github.com/zowe/zowe-install-packaging/files/8078869/Log_zss_authentification.txt)

**Comment by GilPen** [comment]
Hello

Finally, The problem is solved.

We added SAF ressources : CSF1SKD + CSF1SKE + CSF1TRC and now it's ok.

Regards
Gilles Peniguel
