### ISSUE TITLE
v2 server+extension configuration 

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#2662]
This is a ticket to track all threads regarding making v2 configuration:
- Verifiable as valid through automated tools
- Trackable when additions/removals/changes occur between versions
- Familiar for unix and mvs experts alike
- Concise
- Extendable for products to build onto
- Dependency-less. We have a nodejs dependency today that we want to drop so that server setup needs no extra installed software
- Editable through intelligent editors. Not just syntax highlighting, but to have hoverhelp, dropdown options, warnings, all the features you'd expect from an IDE
- Easy to clone. It is difficult to clone a v1 instance to another system due to hardcoded paths for example, so keeping non-portable attributes separate from portable ones, and making as many attributes portable is idea

...maybe more? Please comment on additional desires we have.

This has so far resulted in the following design that is under implementation:
- Zowe should take a list of configuration "files" as an argument to the STC startup
- The files are not exclusively yaml. To make MVS experts happy too, we want to support at minimum both yaml and parmlib.
- The list is comma separated
- There is a documented way in which the different file types can contain the same type of information, such as port numbers
- The list gets merged into a single output configuration. Files on the right hand side have their properties overridden by the files to the left
- The output will include attributes that are references in a Schema
- json-schema will be the technology, as it is standard and is already in use elsewhere in zowe (CLI)
- Schema can have sections that are open-ended, or to be filled in by extenders, so although the attributes are  backed by a schema, the schema itself can be as restrictive or as open as desired.
- The schema will serve as one type of documentation. Our docs site can derive valid attributes and their descriptions from it. Our docs site can generate change notes by sensing the differences between versions.
- We should stick to json schema features that are widely supported by popular editor plugins/schema inspectors, as this will allow us to use or create powerful wizards and IDE tools for quickly and simply customizing zowe servers
- Templating within config files would be very nice, such as a component referencing a java lib via {{java.java_home}}/lib/some-jar.... but we should stick to a template style that is compatible with json schema tools, or else make statements such as that schema validation happens after template resolution, or that templates are considered strings if they look like strings, so that editors can continue to function.

**Comment by balhar-jakub** [comment]
Thanks for capturing the requirements. Just one comment on one of the requirements. 

Dependency-less. We have a nodejs dependency today that we want to drop so that server setup needs no extra installed software - While this is nice, the main problem is that nodejs isn't open source and freely available for zOS so if the dependency is open source and freely available on zOS it could be used. E.g. Golang at some point.

**Comment by 1000TurquoisePogs** [comment]
I think we should go further than just care about whether the dependency is open & free, because dependencies of any sort make an installation harder to complete. Golang is a good example of a solution to the dependency problem, because it isn't a dependency, its compiled code. Another solution is scripting, but its inefficient and messy. Interpreted languages that use a free & open embedded interpreter would also be great - something we could ship within zowe without violating licenses.

**Comment by 1000TurquoisePogs** [comment]
This is the primary PR https://github.com/zowe/zowe-install-packaging/pull/2885

It depends upon the following PRs. Most of them are quite small, just little manifest changes and the addition of a schema file.
https://github.com/zowe/zlux-app-server/pull/230
https://github.com/zowe/common-java/pull/13
https://github.com/zowe/api-layer/pull/2379
https://github.com/zowe/zowe-common-c/pull/285
https://github.com/zowe/zowe-install-packaging/pull/2881
https://github.com/zowe/explorer-jes/pull/343
https://github.com/zowe/explorer-mvs/pull/228
https://github.com/zowe/explorer-uss/pull/168
https://github.com/zowe/launcher/pull/36
https://github.com/zowe/jobs/pull/194
https://github.com/zowe/data-sets/pull/256

**Comment by 1000TurquoisePogs** [comment]
PRs that are still needed:
- Update this repo to pull in configmgr builds (https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/configmgr/)
- The big PR in which I have a whole bunch of TS files https://github.com/1000TurquoisePogs/zowe-install-packaging/tree/feature/v2/configmgr-ts
That's the final PR that depends on everything else. I need to do some cleanup first.
