### ISSUE TITLE
zwe init stc fails to read file but still prints "succeeded"

### ISSUE THREAD

**Issue by struga0258** [zowe/zowe-install-packaging#2676]
When I tried `zwe init stc ` with custom member names it failed to copy which is correct, but the script continued to say "Succeeded". This is a bug and should be fixed.

![image](https://user-images.githubusercontent.com/23221196/154772045-0840b2e9-30d3-4be9-83e2-33be814bdbcf.png)

**Comment by jackjia-ibm** [comment]
Should be fixed. Please reopen if the issue still exists.
