### ISSUE TITLE
Can't set custom STCs names if the default names are occupied

### ISSUE THREAD

**Issue by skurnevich** [zowe/zowe-install-packaging#2684]
**Describe the bug**

Can't set custom STCs names if STCs with default names are already exist.

**Case** 

You have Zowe v1 installed on your system and there are ZWESISTC and ZWESASTC members already exist in your PROCLIB. 
You want to install Zowe v2 in addition, so you need to specify another unique names of STCs in your zowe.yaml for Zowe v2. 
Probably also valid if you want to have multiple v2 instances.

**To Reproduce**

0. Have ZWESLSTC, ZWESISTC or ZWESASTC stc in your PROCLIB
1. Define non-default STCs names in zowe.yaml (zowe.setup.security.stcs.zowe, zowe.setup.security.stcs.aux, zowe.setup.security.stcs.xmem) 
2. Run `zwe init stc --config <...>` without --allow-overwritten flag
3. See error:
```
- read_yaml .zowe.setup.security.stcs.aux from yaml content
  * Exit code: 0
  * Output:
    ZW2SASTC
Error ZWEL0158E: MYUSER.PROCLIB(ZWESASTC) already exists.
```

Despite it read proper STC name from zowe.yaml (ZW2SASTC) - it fails on checking because it uses [default hardcoded stc name](https://github.com/zowe/zowe-install-packaging/blob/0e69018ffd3201639994102b33a6457f4ef07f33/bin/commands/init/stc/index.sh#L65) (ZWESASTC) for comparison.

**Comment by jackjia-ibm** [comment]
Should be fixed. Please reopen if the issue still exists.
