### ISSUE TITLE
Generate documentation for `bin/libs` shell functions

### ISSUE THREAD

**Issue by CarsonCook** [zowe/zowe-install-packaging#2685]
- generate “Zowe server shell library reference” based on files under https://github.com/zowe/zowe-install-packaging/tree/v2.x/staging/bin/libs. The reference will look like javadoc
- example of comments https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/bin/libs/zos-fs.sh#L27-L53
- we may need to discuss more what annotations we want to support. here are a short list: @param , @output, @return, @note, @internal, @example, @ref

Goal is to have a reference on docs.zowe.org so extenders can learn about the functions they can use in install/configure/start/validate scripts.

**Comment by 1000TurquoisePogs** [comment]
I recommend not doing this for now.
Many things within we'd rather not document for use by others.
But more importantly the shell scripts have proven slow, and I'd rather document how to use the typescript equivalents instead.
