### ISSUE TITLE
`zwe [sub-commands] -h` displays invalid characters

### ISSUE THREAD

**Issue by adityadr-joy** [zowe/zowe-install-packaging#2697]
**Describe the bug**
`zwe [sub-commands] -h` displays invalid characters

**To Reproduce**
`zwe -h`

**Expected behavior**
`zwe [sub-commands] -h` should not display invalid characters

**Screenshots**
![image](https://user-images.githubusercontent.com/88372575/155995577-3deb9e4c-d4e7-48dd-b619-86910d43849b.png)

**Comment by jackjia-ibm** [comment]
@adityadr-joy, I assume you are using bash, could you please post your shell environment? Another question, do you see same error for all the -h output or just the command you are showing? Thanks.

**Comment by adityadr-joy** [comment]
Yes I am using bash and all zwe sub-commads -h output displaying same invalid chars.

**Comment by 1000TurquoisePogs** [comment]
Hi, I have this issue too. Once the command is made, bash becomes completely broken and requires a shell restart to fix.

![image](https://user-images.githubusercontent.com/30730276/157517346-6450254f-0099-4b68-840a-85e39433a7c5.png)

**Comment by 1000TurquoisePogs** [comment]
Also note: this issue did not happen in TP1. And Zowe did not have this issue in any v1 operations.

**Comment by jackjia-ibm** [comment]
This is the diff of `zwecli_process_help` between TP1 and recent build: https://github.com/zowe/zowe-install-packaging/compare/967328cfcf7433c2fe98a99e8c377c94cbd3a63b..d39fe5fff09f9dd91badfcdf48640f79d484db10#diff-c798e1f61b1444ad05a646d1bb5a752a4859dcca17a483ea8683efe8606161f6R233-L291.

I don't really see suspicious code. Is bash handling empty echo `>&2 echo` differently?

**Comment by adityadr-joy** [comment]
This is not caused only by `>&2 echo`, even without empty echo same invalid chars are getting displayed. 
This is combination of 

1. `>&2` here https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/bin/libs/zwecli.sh#L276-L277
2. `sed` here https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/bin/libs/string.sh#L106

When i removed any one of the above issue is not reproduced.

**Comment by jackjia-ibm** [comment]
I see. It's either padding .help or .examples files, do you notice it happen on all commands, or just few commands. Maybe some invalid characters get into .help or .examples files?

**Comment by adityadr-joy** [comment]
It happens for all sub commands
