### ISSUE TITLE
API ML Extension installation issue with directory structure in Gateway shared libs

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-install-packaging#2709]
**Describe the bug**

We've been trying out the convenience build of Zowe v2 in the context of testing extensions for the API Mediation Layer.

- Extensions are being copied from `zowe.extensionDirectory` setting to `instance/workspace/gateway/sharedLibs/<extension_id>` where `<extension_id>` is taken from the `manifest.yaml` file belonging to the extension itself.

Currently the procedure consists on replicating the structure of the `gatewaySharedLibs` in the workspace, taken exactly like in the sample: https://github.com/zowe/api-layer/blob/master/apiml-sample-extension-package/src/main/resources/manifest.yaml#L21, this results in a too deep directory structure and the gateway loader cannot find the binaries.

**To Reproduce**
1. Install Zowe v2 convenience build with the provided sample extension enabled (sample extension: https://github.com/zowe/api-layer/tree/master/apiml-sample-extension-package)
2. Start Zowe
3. Verify the extension was successfully installed, the directory structure inside the workspace should resemble:

```
.../sharedLibs/org.zowe.apiml.sdk.apiml-sample-extension-package
    bin/
         archive.jar
```
4. When zowe starts up verify the following curl is 404, indicating the extension was not loaded:
`curl https://host:gatewayport/api/v1/greeting`

**Expected behavior**
Files referenced in the `manifest.yaml` of the extension under `gatewaySharedLibs` should be placed in the root directory of the extension so they can be found by the gateway loader.

e.g.:
```
.../sharedLibs/org.zowe.apiml.sdk.apiml-sample-extension-package
     archive.jar
```

**Comment by pablocarle** [comment]
We are extenders of the API ML developing custom extensions. This defect prevents our extensions from being installed in Zowe v2 and as such we consider this high priority.

**Comment by jalel01** [comment]
@jackjia-ibm please could you let us know if this will be addressed ahead of v2 GA. If not we'll need to explore workarounds and document limitations. Thank you.

**Comment by jackjia-ibm** [comment]
Please see if https://github.com/zowe/zowe-install-packaging/pull/2717 can fix the issue. Thanks.

**Comment by pablocarle** [comment]
> Please see if #2717 can fix the issue. Thanks.

Sure I'll check it. Is it available as part of a convenience build to try? Or I could try it as a patch probably.

**Comment by jackjia-ibm** [comment]
Yes all PRs will be automatically built like this https://github.com/zowe/zowe-install-packaging/pull/2717#issuecomment-1062207917. You can download from https://zowe.jfrog.io/ui/repos/tree/General/libs-snapshot-local/org/zowe/2.0.0-PR-2717/
