### ISSUE TITLE
In v2 API ML Extensions installation could copy the manifest.yaml file to the workspace directory

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-install-packaging#2710]
*Customer content*

**Is your feature request related to a problem? Please describe.**
Related to https://github.com/zowe/api-layer/issues/1986

As part of the API ML issue we need to be able to read extension information from the API ML runtime. This can be accomplished by a mix of getting installation parameters such as the list of components that are installed (`ZWE_INSTALLED_COMPONENTS `) and enabled (`ZWE_ENABLED_COMPONENTS `) and reading the extension manifest. However the manifest is not copied over to the workspace and there's not guarantee that the installation media of the extensions will be available during runtime.

**Describe the solution you'd like**
The installation scripts should copy not only the binaries specified in `gatewaySharedLibs` of the `manifest.yaml` in an extension but also the manifest.yaml (or json) itself to the same destination. Also see #2709 

**Describe alternatives you've considered**
- Finding the manifest in the original `extensionDirectory` is an option but it's not reliable since the installation media could not be available during API ML runtime.
- An alternative could be if the installation procedure exposes these extension manifest parameters for the runtime to find.

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by jackjia-ibm** [comment]
Please see if https://github.com/zowe/zowe-install-packaging/pull/2717 can solve the issue. Thanks.

Few notes:

- I didn't copy manifest.yaml directly to `workspace/gateway/sharedLibs`, which seems a little off from the directory name, also we may need to rename it to plugin-id to avoid conflicts.
- Instead I copied to `workspace/<component>/`. I'm not sure if this fits the requirements.
- Another thought is how the component `enabled` status (true or false) will affect this feature. If the user disabled the extension/component which was enabled before, the sharedlib will still be left in `workspace/gateway/sharedLibs`. Not urgent and not blocking, so I think we can think of this in the future.

**Comment by jackjia-ibm** [comment]
The file is copied to `${ZWE_PRIVATE_WORKSPACE_ENV_DIR}/${component_name}/` https://github.com/zowe/zowe-install-packaging/pull/2717#issuecomment-1062207849 . `${ZWE_ENABLED_COMPONENTS}` is an enabled component list separated by comma for you to loop through.
