### ISSUE TITLE
zwe components uninstall

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2727]
- During uninstall, it may trigger an event to all other components to know this component will be uninstalled, any cleanup needs to be done.
- Do we need a management STC so it can have proper permission to cleanup workspace directory? Or use ACL?
- Uninstall permission?
- component manifest may define `commands.uninstall`.

**Comment by MarkAckert** [comment]
Waiting for results of the app store innovation to further define this issue.
