### ISSUE TITLE
Support for installing extensions with discovery extensions

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-install-packaging#2742]
*Customer content*

**Is your feature request related to a problem? Please describe.**
Related to issue:
https://github.com/zowe/api-layer/issues/1968

API ML supports extensions in gateway and discovery components. Currently the standard installation mechanism for extensions supports defining a list of files to be copied over to the gateway shared libs. Ref: https://docs.zowe.org/stable/extend/packaging-zos-extensions/#:~:text=with%20this%20path.-,gatewaySharedLibs,-%3A%20Array%20of%20objects

The idea of this issue is to have it similarly for discovery shared libs directory.

**Describe the solution you'd like**

Define a new property for the `manifest.yaml` (suggested `discoverySharedLibs`) that works in similar fashion as `gatewaySharedLibs`.

**Describe alternatives you've considered**
Lack of this support means extensions that extend the discovery service will be required to perform custom installations. Meaning it's possible but not recommended.

**Additional context**
https://docs.zowe.org/stable/extend/packaging-zos-extensions/#zowe-component-manifest

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by jackjia-ibm** [comment]
Fix added to PR #2742

**Comment by MarkAckert** [comment]
Closing as complete
