### ISSUE TITLE
Unable to detect z/OS MF HTTPS port during zowe-install

### ISSUE THREAD

**Issue by kathysychan** [zowe/zowe-install-packaging#276]
Starting with the 01/11 Zowe nightly driver, we were not able to get the zosmf port when running the zowe-install through our Jenkins pipeline. Here's the console output when installing the 01/15 build 406 of Zowe nightly:

Finding z/OSMF HTTPS port...
   Unable to detect z/OS MF HTTPS port
   Please enter the HTTPS port of z/OS MF server on this system
** Adding line: export ZOWE_ZOSMF_PORT= to ~/.zowe_profile  **

However, when I run the following command manually, I can get the zosmf port (at 443):

netstat -b -E IZUSVR1
MVS TCP/IP NETSTAT CS V2R2       TCPIP Name: TCPIP           14:25:21
01/16/2019          MVS TCP/IP Real Time Network Monitor
User Id  BytesOut             BytesIn              LPort State
-------  --------             -------              ----- -----
IZUSVR1  00000000000000000000 00000000000000000000 00443 Listen
 Foreign Socket: ::..0
Connections displayed: 1

The symptom of this problem seems to be similar to the problem @jackjia-ibm found in #263. However, even in build 406 that is supposed to have the fix for issue #263, this problem still exist.

**Comment by kathysychan** [comment]
It turns out that this is a problem when running zowe-install.sh through our Jenkins pipeline. If I run zowe-install.sh in a shell script, it could successfully get zosmf port. 

@Joe-Winchester and @jackjia-ibm , this is what Kiril found:

netstat on zOS is not a real file on zOS

IBMUSER:/u/ibmuser>ls -la /bin/netstat
erwxrwxrwx   1 ROOT     1              8 Apr 11  2017 /bin/netstat -> ONETSTAT

I created script test.sh with content

#!/bin/sh

echo `netstat -b -E IZUSVR1 2>/dev/null|grep .*Listen | awk '{ print $4 }'`


If I execute it from my ssh session I do get output but when I do the same from Java it is empty.

In addition when I do from Java directly

/bin/netstat -b -E IZUSVR1

I get

java.io.IOException: /bin/netstat: not found
		 at java.lang.UNIXProcess.fullPath(UNIXProcess.java:362)
		 at java.lang.UNIXProcess.<init>(UNIXProcess.java:188)
		 at java.lang.ProcessImpl.start(ProcessImpl.java:167)
		 at java.lang.ProcessBuilder.start(ProcessBuilder.java:1040)
Caused: java.io.IOException: Cannot run program "/bin/netstat": /bin/netstat: not found
		 at java.lang.ProcessBuilder.start(ProcessBuilder.java:1059)

**Comment by kiril-ibm** [comment]
I used ./tsocmd.sh NETSTAT to get zosmf port and it works from java

**Comment by kathysychan** [comment]
This is an issue customers might find if they use a pipeline to install zowe from Java.  We just could not get "netstat" to work calling from Java.

**Comment by kiril-ibm** [comment]
@stevenhorsman you have to call ./tsocmd.sh NETSTAT instead of netstat to fix it for everyone

**Comment by stevenhorsman** [comment]
Sorry for being slow - what is ./tsocmd.sh and where should it be called from?

**Comment by kiril-ibm** [comment]
sorry we use a wrapper  around real command. The real command is  **tsocmd NETSTAT**

**Comment by jackjia-ibm** [comment]
@kiril-ibm @kathysychan is this still an issue? Are we safe to close this?

**Comment by kiril-ibm** [comment]
@jackjia-ibm pls close
