### ISSUE TITLE
Don't try to import certificates if verifyCertificatesOfServices=false

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#279]
Problem:
zowe-install.yaml has the configuration option of
    verifyCertificatesOfServices=false
This means that the API Gateway does not verify SSL certificates for APIs on its southbound edge, this means, however the install script still does attempt to do the import.  This can in the log having misleading messages written that imply keyrings need setting up which misleads users as it's not necessary.

![image](https://user-images.githubusercontent.com/28100302/51529253-45cf7c80-1e30-11e9-88d4-064d19fa4805.png)

Solution:
Modify zowe-api-mediationlayer-configure.sh to bypass setting up the call to etup-apiml-certificates.sh if the environment variable ZOWE_APIM_VERIFY_CERTIFICATES is false.

**Comment by plavjanik** [comment]
Hello, this is a good idea and it will be resolved by https://github.com/zowe/api-layer/pull/217 and https://github.com/zowe/zowe-install-packaging/pull/306. Can you please help me with the code review?
