### ISSUE TITLE
Define new component init hooks so any component can intervene into "zwe init" process

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2819]
Currently `zwe init` is predefined as 6 steps and component has no way to provide hooks and intervene.

This is specifically we inherit v1 initialize VSAM data set for caching service. Ideally this init process should be defined in caching service itself.

Goals:

- Allow component to define `commands.init` hook
- Allow component to customize `zowe.setup` section of zowe.yaml
- Move VSAM related init tasks to caching service.

**Comment by 1000TurquoisePogs** [comment]
This would complicate and confuse when extensions are installed.
But components do have a `.install` hook that runs when they get installed.

Rather a `.upgrade` may help to exist.
But for core components, their pax actions or zowe-install-packaging github workflow actions are enough.
