### ISSUE TITLE
Support different job names for the ZOWESVR started tasks

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#283]
Currently, the jobnames of the ZOWESVR started tasks are all formed from ZOWESVR (or its chosen name) plus a decimal number starting from 1.  This makes it difficult to know which process is which.  It would be better if they had different names, to help with data collection for resource monitoring etc.

**Comment by stevenhorsman** [comment]
Completed (pending defect fixes) using _BPX_JOBNAME_
