### ISSUE TITLE
Plugin identifier is not created

### ISSUE THREAD

**Issue by ghost** [zowe/zowe-install-packaging#2833]
**Describe the bug**
After running installation for component plugin identifier is not presented in `workspace/app-server/plugins` directory.

**To Reproduce**
1. Run the command `zwe components install -o "/<path-to-extension>" -c "<path-to-zowe-yaml>"`
2. Check  `<path-to-zowe-workspace>/app-server/plugins` directory if identifier with plugin id as title is presented 

**Expected behavior**
Plugin identifier should be created for installed plugin

**Environment**
 - OS: z/OS 2.4
 - Zowe version: 2.0.0

**Comment by 1000TurquoisePogs** [comment]
Content within the "plugins" folder is now managed by "enabled" status of components.
Each time the servers start, content from the plugins folder will be added or removed according to component status.
This means, you will **not** see a change in that folder simply from doing `zwe components install`. you must enable the component and start the server first.

**Comment by ghost** [comment]
Okay, thanks for response. Here is a follow up question.
Right now `zwe components enable` doesn't work correctly according this issue: https://github.com/zowe/zowe-install-packaging/issues/2827
And in comments for it there is mention about fix in v2.1. Is there approximate date for 2.1 release?

**Comment by 1000TurquoisePogs** [comment]
Yes, you can find the 2.1 release, and other releases, scheduled here https://github.com/zowe/community/blob/master/Project%20Management/Schedule/Zowe%20PI%20%26%20Sprint%20Cadence.md
It's a good page to bookmark as its updated regularly.

**Comment by jackjia-ibm** [comment]
My understanding is this is expected behavior in v2. Please reopen if this is still considered as issue. Thanks.
