### ISSUE TITLE
Add Github Action Runnners

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#2834]
During the v2 release process we ran into our action runners limit, which caused jobs to queue for potentially long periods of time. We are looking into how to increase our Github Actions limit w/ enough runners to avoid a case where jobs are queued for hours.

**Comment by jackjia-ibm** [comment]
Implemented with John's help:

Folks from GH got back to me and said they bumped you up to Enterprise at no extra cost.  You should now have 180 concurrent jobs.

Let me know if there is anything else we can do.

Thank you,

John Mertic
Director of Program Management - Linux Foundation
