### ISSUE TITLE
Zowe install does not allow for different user and group for z/OSMF

### ISSUE THREAD

**Issue by hogstrom** [zowe/zowe-install-packaging#284]
Some customers do not use the default z/OSMF user IZUSVR or IZUADMIN for their z/OSMF instance.  Zowe needs to allow for accommodating this configuration item in the install.

Perhaps we put zosmf-user, zosmf-unauthenticated-user and zosmf-group to the install and default to the z/OSMF defaults but allow for overrides.

Raised by Leon in slack at:
https://openmainframeproject.slack.com/archives/CC60ALD61/p1547600912055200

**Comment by stevenhorsman** [comment]
I added zosmf user and group to the yaml as part of #573
