### ISSUE TITLE
--config in zwe start command not working properly

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zowe-install-packaging#2854]
Starting Zowe V2.0.0 main server with zwe start command, command completed  successfully. 
```
178:/zowe/instance/instance2.v2 $ zwe start -vv -l start.log -c /zowe/instance/instance2.v2/zowe.yaml
Log file created: /zowe/instance/instance2.v2/start.log/zwe-start-20220509T023437.log
===============================================================================
>> STARTING ZOWE

- read_yaml load content from /zowe/instance/instance2.v2/zowe.yaml
  * Exit code: 0
- read_yaml .zowe.job.name from yaml content
  * Exit code: 0
  * Output:
    ZOWESV2
- read_yaml load content from /zowe/instance/instance2.v2/zowe.yaml
  * Exit code: 0
- read_yaml .zowe.setup.security.stcs.zowe from yaml content
  * Exit code: 0
  * Output:
    null
- read_yaml load content from /zowe/instance/instance2.v2/zowe.yaml
  * Exit code: 0
- read_yaml .haInstances.z2.sysname from yaml content
  * Exit code: 0
  * Output:
    null
- opercmd S ZWESLSTC,HAINST=z2,JOBNAME=ZOWESV2
  * Succeeded
  * Exit code: 0
  * Output:
    Z2        2022129  02:34:44.38             ISF041I CONSOLE NAME RENJING MODIFIED TO RENJING$
    Z2        2022129  02:34:44.38             ISF031I CONSOLE RENJING$ ACTIVATED
    Z2        2022129  02:34:44.38            -S ZWESLSTC,HAINST=z2,JOBNAME=ZOWESV2
-------------------------------------------------------------------------------
>> Job ZOWESV2 is started successfully.
```
But MVS job failed RC008, following error were in joblog. Indicates config file not found 
```
2022-05-09 06:30:06 <ZWELNCH:50464620> DEFTASK INFO ZWEL0021I Zowe Launcher starting                                                               
2022-05-09 06:30:06 <ZWELNCH:50464620> DEFTASK DEBUG failed to get properties for file CONFIG='#zowe_yaml' - EDC5129I No such file or directory.   
2022-05-09 06:30:06 <ZWELNCH:50464620> DEFTASK ERROR ZWEL0061E failed to find CONFIG='#zowe_yaml', check if the file exists                        
2022-05-09 06:30:06 <ZWELNCH:50464620> DEFTASK ERROR ZWEL0036E failed to initialize launcher context        
```

So looks like the --config option is not accepted?  Then  I updated  zowe.yaml in ZWESLSTC JCL 
```
 //STDENV   DD  *                                
 CONFIG=/zowe/instance/instance2.v2/zowe.yaml 
```   

then ran without --config , it's saying config is required. But in this [doc](https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/zwe-start), required for this parameter is no 

```
179:/zowe/instance/instance2.v2 $ zwe start -vv -l start.log
Log file created: /zowe/instance/instance2.v2/start.log/zwe-start-20220509T023557.log
===============================================================================
>> STARTING ZOWE

Error ZWEL0108E: Zowe YAML config file is required.
```

Now I have to specify correct zowe.yaml location in JCL, and use --config in zwe start command at the same time. I thought --config should be a way to overwrite the value in JCL, right?  If  I omit this parameter in zwe command it should be able to use value in JCL. 

Could you  please help to see what should be the correct usage here? Thanks.

**Comment by jackjia-ibm** [comment]
@rjmaomao Sorry this could be confusing on the responsibilities of each part.

- `zwe start` take responsibility to run `S <STC>` and nothing more. So it needs `--config` parameter to know what is the custom STC name from `zowe.setup.security.stcs.zowe`. It also reads `zowe.job.name` to know what job name should start with and more can be found with `zwe start -h`. After it issues `S <STC>` command, then it's done and whether the job is success or fail is out of it's control.
- `S <STC>` can be issued without `zwe start` command. So from here, the `CONFIG=<path>` defined in STC is critical. It requires to be correct path.
- `zwe start` won't modify `CONFIG=<path>` defined in STC. It's `zwe init stc` command's responsibility.

If we allow `zwe start` to modify/replace config path defined in STC, then this command will not be same as issuing `S <STC>`. It potentially to be even more confusing.

Hope this clears your question.

**Comment by jackjia-ibm** [comment]
My understanding is the behaviors described are expected. Please re-open if you consider some of them are issues. Thanks.
