### ISSUE TITLE
GSK tracing in v2

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-install-packaging#2926]
**Describe the bug**
How do I specify gsk tracing in zowe.yaml?
For the debugging purposes in v1 ```instance.env``` was updated for example by this:
```
GSK_TRACE=0xFF  # Include all settings
GSK_TRACE_FILE=/path/to/trace.trc
```
How is it done in ```zowe.yaml```?
Where is it documented?

**Describe the solution you'd like**
Clear instruction how to use gsk tracing.

**Comment by jackjia-ibm** [comment]
You can define it in `zowe.environments` section described here https://docs.zowe.org/v2.0.x/appendix/zowe-yaml-configuration#extra-environment-variables.

Please re-open if there are issues.
