### ISSUE TITLE
USERID of ZOWESVR is not IZUSVR

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#293]
The userid of the ZOWESVR STC is not IZUSVR, because the command to add ZOWESVR to the STARTED task list has not been run.  This is done in `zowe-config-stc.sh` but that is not run by the install script.  

This will happen on any system that has not previously had Zowe installed.  

The doc tells the user to execute the necessary commands, but they might not do so, therefore it might be better if the install script ran the `zowe-config-stc.sh` script, or the doc told the user to run it.

**Comment by stevenhorsman** [comment]
Joe has doc'd zowe-config-stc.sh
