### ISSUE TITLE
Add support on relative path

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2964]
*Customer content*

In v2 `zwe` command, some path arguments, including `--config` and `zwe components install --component`, require absolute path. This is not convenient in some use cases.

**Describe the solution you'd like**

Allow the user to specify relative path with those arguments.

**Describe alternatives you've considered**

A better validation check and reasonable error message if the path is absolute path.

**Additional context**

In v1, we have some auto-conversion on relative path, but heard complains. When we convert, sometimes the &SYSNAME prefix will be added to the absolute path and the end-user doesn't want them. This could be a problem when updating `CONFIG=` path in `ZWESLSTC`. This shouldn't have &SYSNAME especially in Sysplex environment.

**Comment by 1000TurquoisePogs** [comment]
Are we going to take a relative path in but then print an absolute path into the runtimeDirectory var?

**Comment by MarkAckert** [comment]
Note: We need to modify both the shell script and the typescript implementation of the zwe command.
