### ISSUE TITLE
Should --security-dry-run create VSAM file?

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/zowe-install-packaging#3020]
*Customer content*
It's a report from the internal person trying to install Zowe, and the person was surprised by the behavior of the zwe init. 

zwe init vsam --security-dry-run
-------------------------------------------------------------------------------
>> Create VSAM storage for Zowe Caching Service

Modify ZWECSVSM
- ZDNT.ZOWE.V220.JCLLIB(ZWECSVSM) is prepared

Submit ZDNT.ZOWE.V220.JCLLIB(ZWECSVSM)
- Job ZWECSVSM(JOB02349) ends with code 0 (COMPLETED).

>> Zowe Caching Service VSAM storage is created successfully.

**Is your feature request related to a problem? Please describe.**
It seems that the VSAM is actually created instead of the JCL being prepared, but the documentation clearly states on
https://docs.zowe.org/stable/user-guide/initialize-vsam-dataset/ :

If you want to preview the member before submitting it use the value --security-dry-run, otherwise the command will submit the JCL and wait for its completion.

**Describe the solution you'd like**
Either change the documentation to reflect what is actually happening or change the behavior so it behaves as stated in documentation.

**Comment by Martin-Zeithaml** [comment]
Will be solved in [3718](https://github.com/zowe/zowe-install-packaging/pull/3718):
`--security-dry-run` will be used for security setup, `dry-run` will be generally used for printing JCL without submitting.

**Comment by Martin-Zeithaml** [comment]
If needed, reopen this.
