### ISSUE TITLE
Migrate to Swarm agent to better distribute load to other servers

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#305]

**Comment by jackjia-ibm** [comment]
These repository pipelines had been migrated to use Swarm (label: ibm-jenkins-slave-jnlp):

- zowe-install-packaging
- zowe-promote-publish
- explorer-jes
- explorer-uss
- explorer-mvs
- orion-editor-component
- explorer-ui-server
- jobs
- data-sets
- explorer-api-common
- docs-site Archive pipeline (label: ibm-jenkins-slave-nvm)

These repository pipelines requires privileged container which stays on old agent based on Docker Cloud (label: ibm-jenkins-slave-dind):

- docs-site Documentation build pipeline
- zowe-install-test

**Comment by jackjia-ibm** [comment]
Pending issue to solve: run dind container in Swarm mode.

**Comment by MarkAckert** [comment]
@jackjia-ibm  is this work complete, or is more outstanding? thanks

**Comment by jackjia-ibm** [comment]
@MarkAckert
this work is not done, pending items could be:

- migrating other agent Docker images,
- investigate and support dind image.

But since we are moving to OMP Jenkins soon, we can decide after we have solid knowledge of their infrastructure.

**Comment by jackjia-ibm** [comment]
Close this for moving to LF.
