### ISSUE TITLE
Error message during ZOWE startup

### ISSUE THREAD

**Issue by zbotzer** [zowe/zowe-install-packaging#309]
During ZOWESVR startup I'm getting an error message:
  "install INFO¨ - Setting up proxy (com.zowe.explorer.server.proxy:data) to destin
  install WARNING¨ - Error: Proxy: need a host and port"

I didn't manage to find where exactly to enter the host and port.
I refered Proxy exception logging fix #33 but with no help.
 
 
**Steps to Reproduce**

1.  S ZOWESVR

**Comment by stevenhorsman** [comment]
@zbotzer - I think this issue got fixed in the 1.0 GA release. Are you able to check and confirm? Thanks

**Comment by zbotzer** [comment]
Sure, I'll do it on Thursday.

בתאריך יום ג׳, 12 בפבר׳ 2019, 18:06, מאת Steven Horsman <
notifications@github.com>:

**Comment by MarkAckert** [comment]
@zbotzer  Hi, Were you able to check if the issue was fixed? Thanks!

**Comment by zbotzer** [comment]
Hi Mark, sorry for the delay.
I installed the last version of 1.0.1 RC2 but during the installation I got this error message:

IBMUSER:/zowe/1.0.1/api-mediation: >scripts/apiml_cm.sh --action trust-zosmf --zosmf-keyring IZUKeyring.IZUDFLT  --zosmf-userid IZUSVR                          
Listing entries in the z/OSMF keyring (IZUKeyring.IZUDFLT):                     
keytool error (likely untranslated): java.io.IOException: R_datalib (IRRSDL00) e
rror: not RACF authorized to use the requested service (8, 8, 8)                
It is not possible to read z/OSMF keyring IZUSVR/IZUKeyring.IZUDFLT. The effecti
ve user ID was: OMVSKERN. You need to run this command as user that has access to the z/OSMF keyring:                                                           
  cd /zowe/1.0.1/api-mediation                                                  
  scripts/apiml_cm.sh --action trust-zosmf --zosmf-keyring IZUKeyring.IZUDFLT --
zosmf-userid IZUSVR                                                             
IBMUSER:/zowe/1.0.1/api-mediation: >                                            

What exactly I need to do? I've covered any mention of this issue and did what was described
but without help.

**Comment by hogstrom** [comment]
All security keyring functions have been re-worked.  Closing
