### ISSUE TITLE
In latest Zowe version (nightly 2.4) the manifest copy is not working anymore

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-install-packaging#3091]
**Describe the bug**
The original feature requested in #2710 was working until 2.3

**To Reproduce**
`/zowe/zowe-vnightly-v2/runtime/instance/workspace/.env/ccs-idt/manifest.json`
or
`/zowe/zowe-vnightly-v2/runtime/instance/workspace/.env/ccs-idt/manifest.yaml`

manifest.yaml files for extensions and main components used to be copied to the private workspace.

**Expected behavior**
manifest.yaml files should be available in private workspace, especially for apiml extensions that read from them.

**Comment by MarkAckert** [comment]
@pablocarle We think this is fixed on the latest version of Zowe (2.4). Could you please review the behavior and let us know if you agree? Thank you

**Comment by pablocarle** [comment]
Hi, I missed this comment, I'll verify and confirm, but I believe it works as before now since our CI is working with the latest nightly builds.
