### ISSUE TITLE
 zwe init certificate  -- Error ZWEL0157E: Zowe dataset prefix (zowe.setup.dataset.prefix) is not defined in Zowe YAML configuration file.

### ISSUE THREAD

**Issue by ActionThisDay** [zowe/zowe-install-packaging#3103]
**Describe the bug**
Im running the zwe init certificate step standalone .. and its reporting this failure .

# zwe init certificate --update-config
  * Output:
    Error: error reading input file: All collection items must start at the same column
Error ZWEL0157E: Zowe dataset prefix (zowe.setup.dataset.prefix) is not defined in Zowe YAML configuration file.
#

I have rebuilt my zowe.yaml from example-zowe.yaml. And still the same error . 

![image](https://user-images.githubusercontent.com/115551126/195573007-cb2047e1-30b2-4fd3-a486-9d1c95a5ea76.png)

    /usr/lpp/zowe/zowe.yaml
 ===>
----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8--
zowe:

  #-------------------------------------------------------------------------------
  # These configurations are used by "zwe install" or "zwe init" commands.
  #-------------------------------------------------------------------------------
  setup:
    # MVS data set related configurations
    dataset:
      # **COMMONLY_CUSTOMIZED**
      # where Zowe MVS data sets will be installed
      prefix: SYSG.ZWEV2
      # **COMMONLY_CUSTOMIZED**
      # PROCLIB where Zowe STCs will be copied over
      proclib: SYSG.PROCLIB
      # **COMMONLY_CUSTOMIZED**
      # Zowe PARMLIB
      parmlib: SYSG.ZWEV2.CUST.PARMLIB
      # Holds Zowe PARMLIB members for plugins
      parmlibMembers:
        # For ZIS plugins

**Comment by js665999** [comment]
This is most likely an issue with your YAML file. Try to use any tool for YAML validation to see if its valid. For example it could be  incorrect indentation or some value with space character without quotes around it. 

_zowe.setup.dataset.prefix_ in not necessarily the affected area, its just first value in the invalid file.

**Comment by ActionThisDay** [comment]
I was able to find the YAML issue, it was a misplaced comment #
Was able to use ZOWE dataset explorer and a VSCODE YAML checker to find the error.
As you say it was not where the error msg indicated it was. 
thanks for your tip.

**Comment by 1000TurquoisePogs** [comment]
Thank you both. There's an ongoing effort to make these errors easier to spot and more intuitive what to fix when one does occur, but we will be improving little by little. In 2.4+ due to https://docs.zowe.org/stable/user-guide/configmgr-using being introduced you'll likely get a different error message than "zowe.setup.dataset.prefix" so that it will be less misleading, though maybe not totally human readable yet.
