### ISSUE TITLE
Certifcate fails to import on Windows -  local_ca.cer - File Type is not recognisable - 

### ISSUE THREAD

**Issue by ActionThisDay** [zowe/zowe-install-packaging#3105]
Certifcate fails to import on Windows -  local_ca.cer - File Type is not recognisable - 
Anyone come across this before . 

My cert looks good 

![image](https://user-images.githubusercontent.com/115551126/195637866-1f6bbd57-ac92-4525-80af-1d2f4f8975bd.png)

The download ran fine 

C:\WINDOWS\system32>zowe zos-files download uss-file --binary /var/zowe/keystore/local_ca/local_ca.cer
USS file downloaded successfully.
Destination: local_ca.cer

But Windows Certificate Manager cannot IMPORT it does not recognise it 

![image](https://user-images.githubusercontent.com/115551126/195638690-dd41b1e8-f513-405f-82f6-b39bd95cecbd.png)

![image](https://user-images.githubusercontent.com/115551126/195638427-3842c599-a706-480e-ab72-d2309679d438.png)

**Comment by 1000TurquoisePogs** [comment]
That's a PEM file. I'm not sure if Windows supports that, you'd have to look at Windows documentation instead of Zowe.
But, in that same folder is a P12 file. Since windows mentions that, perhaps the P12 file will work better.

**Comment by ActionThisDay** [comment]
Thank you . That worked I was able to import the P12 version. 
Ive opened a doc issue to get this clarification added.
