### ISSUE TITLE
useConfigmgr property in zowe.yaml does not work when we use space while adding the entry.

### ISSUE THREAD

**Issue by AdarshdeepCheema** [zowe/zowe-install-packaging#3121]
**Describe the bug**

**To Reproduce**
USING 2.3.1 zowe with node version v14.17.6
1. add "useConfigmgr : true" in zowe.yaml. Note we added space ' ' after useConfigmgr keyword.
2. start the zowe using "./zwe start --config /path/to/czowe.yaml"
3. you will see in the JOB logs ZWE_zowe_useConfigmgr=true, but it seems like this configuration is not getting used as the zowe startup time does not change and remains the same when using "useConfigmgr: false"
4. If you remove the space after "useConfigmgr" in step 1 and use "useConfigmgr: true" in zowe.yaml, then the startup time will decrease significantly as expected and in this case also, job logs show ZWE_zowe_useConfigmgr=true.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AdarshdeepCheema** [comment]
@1000TurquoisePogs  FYI

**Comment by DivergentEuropeans** [comment]
According to the YAML spec, https://yaml.org/spec/1.2.2/ (see 2.1. Collections)
": " is the only supported way to separate key-value pair so this isn't a configMgr issue, this is a YAML issue. It probably looks at 
configMgr : true as something like "configMgr " is true

Closing, lmk if you find something that disagrees @AdarshdeepCheema

**Comment by AdarshdeepCheema** [comment]
I opened this issue because if we specify it incorrectly(`useConfigmgr : true `)in in the YAML file then in the JOBLOGS it says`ZWE_zowe_useConfigmgr=true,` @DivergentEuropeans 
It should not pick the value from YAML if the YAML entry is incorrect
