### ISSUE TITLE
Node v18 Support

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#3130]
Node v18 is slated to go LTS End of 2022. We should add a Node v18 installation to the Marist systems and add it to our test suite. Any issues uncovered will be handled in separate backlog items.

We should update Zowe documentation to indicate support for v18 once our testing is complete. We need to decide if v18 support will be from time of testing forward, for one or both Zowe release lines, and any other valid compatibility matrix.

**Comment by armstro** [comment]
[EM-ENUSZP22-0443-CA.PDF](https://github.com/zowe/zowe-install-packaging/files/10354831/EM-ENUSZP22-0443-CA.PDF)

Node 18 for z/OS announcement letter attached.

**Comment by armstro** [comment]
- Node V12 out of support 

- [Node V14](https://www.ibm.com/common/ssi/ShowDoc.wss?docURL=/common/ssi/rep_sm/d/872/ENUS5655-NOD/index.html&lang=en&request_locale=en) is end of marketing (meaning no new orders can be placed) but fee based support is until 9/30/2023 

- Node V16 [https://www.ibm.com/common/ssi/ShowDoc.wss?docURL=/common/ssi/rep_sm/e/872/ENUS5655-NOE/index.html&lang=en&request_locale=en](url) No statement has been made on end of market or end of support.

**Comment by MarkAckert** [comment]
Completed and running on zzow04.
