### ISSUE TITLE
Update Node v16 in base container images

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#3138]
We should update the `NODE_VERSION` used in our v2.x base images to the latest version of v16 to pick up bug fixes and enhancements.

**Comment by AdarshdeepCheema** [comment]
@MarkAckert @nkocsis 
FYI From https://nodejs.org/en/blog/vulnerability/openssl-november-2022/ and https://nodejs.org/en/download/releases/
It seems like it is not safe to upgrade to any existing Node versions, I will wait for the Node release which will have the non vulnerable openSSL
