### ISSUE TITLE
Install scripts use literal default values instead of referring to YAML keys

### ISSUE THREAD

**Issue by GrahamHannington** [zowe/zowe-install-packaging#314]
Some Zowe install scripts use literal default identifier values instead of referring to YAML keys.

Values include (there might be others) the following z/OSMF defaults:

* `IZUSVR` (already has the YAML key `zosmfUser`, but the scripts do not always use that key)
* `IZUADMIN`
* `IZUUSER`

For example, in `zowe-check-prereqs.sh` (which extracts other YAML key values):

    tsocmd lg izuadmin 2>/dev/null |grep IZUSVR >/dev/null

and in `zowe-runtime-authorize.sh`:

    chgrp -R IZUUSER ./zlux-app-server/deploy

If z/OSMF is already installed, and whoever installed it didn't use the default values for these identifiers, then you have to debug the Zowe installation scripts (identify which scripts use these values and edit them).

**Comment by stevenhorsman** [comment]
Since 1.8 the yaml file and IZU user and groups are not used with the zowe server, so from 1.9 dev build onwards these changes have been removed
