### ISSUE TITLE
Java 11 version string does not pass version check

### ISSUE THREAD

**Issue by skurnevich** [zowe/zowe-install-packaging#3142]
**Describe the bug**
Tried to run Zowe with Java 11 in ConfigMgr mode, but get failure on check
<img width="1021" alt="Screenshot 2022-11-09 at 16 54 33" src="https://user-images.githubusercontent.com/61471197/200877819-8c79a4e2-c143-4d1b-88b5-21f2436d61da.png">

Version String Naming changed for that particular version to be `java version "11.0.16" 2022-07-19` and does not start with 1. anymore.

Noticed that [java.ts](https://github.com/zowe/zowe-install-packaging/blob/677a607686e6ee7ecb349dc5925a6f58dd9e61da/bin/libs/java.ts#L125) has incorrect logic and basically checks only that major version is equal to '1'.

Older[ java.sh](https://github.com/zowe/zowe-install-packaging/blob/677a607686e6ee7ecb349dc5925a6f58dd9e61da/bin/libs/java.sh#L124) (without ConfigMgr) seems to be processing this version better

**Comment by JoeNemo** [comment]
fixed in code
