### ISSUE TITLE
Need to automate java compatibility flag for PKCS12 keystore generation 

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#3157]
https://github.com/zowe/docs-site/issues/2459 describes a problem when generating keystores of PKCS12 type specifically, when using newer versions of java.
The problem manifests when using ZSS. If the keystore is not backward compatible, ZSS prints:
`ZWES1060W Failed to init TLS environment, rc=1(Handle is not valid)`

[java.sh](https://github.com/zowe/zowe-install-packaging/blob/v2.x/master/bin/libs/java.sh) (*non-configmgr mode*)
and [java.ts](https://github.com/zowe/zowe-install-packaging/blob/v2.x/master/bin/libs/java.ts) (*configmgr mode*)
are where java version checks occur.

[certificate.sh](https://github.com/zowe/zowe-install-packaging/blob/v2.x/master/bin/libs/certificate.sh) is where keytool stuff occurs. There is no configmgr version of this file yet, it's planned for the future.

Between the java files and the certificate.sh file, it seems like we should be assigning the compatibility flags depending on the version of java that is used. I'm also told that java sr7fp25 will use add the flag `-Dkeystore.pkcs12.legacy` to do similar things, so we may need to set flags depending on whether the java version is `<sr7fp15`, `>=sr7fp15 && < sr7fp25`, and `>=sr7fp25`

The acceptance criteria is...
Be able to generate a PKCS12 keystore on every type of java version listed above, without encountering `ZWES1060W Failed to init TLS environment, rc=1(Handle is not valid)`

**Comment by 1000TurquoisePogs** [comment]
Note: this very likely also effects v1! I guess that means we have to check [this file](https://github.com/zowe/zowe-install-packaging/blob/v1.x/master/bin/apiml_cm.sh) too

**Comment by achmelo** [comment]
Is there any chance that ZSS could support the new algorithm? I am wondering if using a legacy algorithm would not create a security vulnerability.
Here is the reason for introducing a new algorithm in JDK:
PKCS12 is the default keystore format since JDK 9, but we have been using weak algorithms which was the standard of 1990s. The algorithms are becoming a security issue now especially for the key protection algorithms which is used to protect private keys.

**Comment by 1000TurquoisePogs** [comment]
> Is there any chance that ZSS could support the new algorithm?

ZSS uses the System SSL (GSK) library for TLS.  So you're asking if either that library will support the new algorithm or if ZSS will move to a new library. I think this is up to IBM to enhance System SSL but I am not sure if that is tied to a revision of z/OS and when it will happen, so I don't expect this to change quickly.

**Comment by Joe-Winchester** [comment]
I am seeing this occuring at a customer site where the `zwe init certificate` PKCS12 isn't valid for ZSS.   
For the `-D` args, do these need to be edited into the `apiml_cm.sh` script by hand to get the cert generated correctly ?

**Comment by jalel01** [comment]
Hi Joe, the apiml script you refer to is not part of V2. Sean above refers to the following script where changes can be made:

[certificate.sh](https://github.com/zowe/zowe-install-packaging/blob/v2.x/master/bin/libs/certificate.sh) is where keytool stuff occurs
