### ISSUE TITLE
Zwe support --target-dir -> package always in /tmp/

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-install-packaging#3164]
**Describe the bug**
It seems ```--target-dir``` is ignored.

**To Reproduce**
1. ```zwe support -c /x/zowe/zowe.yaml --target-dir /x/zowe/tmp```
2. Last line of zwe support command: ```>> Zowe support package is generated as /tmp/zwe-support.2022-11-22-09-13-22.pax.Z```

**Expected behavior**
Package created in target dir, in this example ```/x/zowe/tmp```

**Additional context**
I have tried following with the same result:
- ```zwe support -c /z/zowe.yaml --target-dir /z/userID/zowe/tmp```
- ```zwe support --target-dir /z/userID/zowe/tmp -c /z/zowe.yaml```
 -```zwe support --target-dir "/z/userID/zowe/tmp" -c /z/zowe.yaml```

It seems, that in [index.sh](https://github.com/zowe/zowe-install-packaging/blob/0d8d5bf395041167f07bb047f34708e3ba261405/bin/commands/support/index.sh#L19)
```target_dir="${ZWE_CLI_PARAMETER_CONFIG_TARGET_DIR}"```
should be 
```target_dir="${ZWE_CLI_PARAMETER_TARGET_DIR}"```

I can fix that.

**Comment by 1000TurquoisePogs** [comment]
Thanks for handling this.

**Comment by MarkAckert** [comment]
Looks like this is completed; closing. You can reopen this issue if you disagree.
