### ISSUE TITLE
Patterns for dataset, member and jobname in server-common.json

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-install-packaging#3172]
**Describe the bug**
The pattern for [dataset](https://github.com/zowe/zowe-install-packaging/blob/677a607686e6ee7ecb349dc5925a6f58dd9e61da/schemas/server-common.json#L19), datasetMember and jobname is not corect.

**To Reproduce**
1. _Dataset_: pattern does not include hyphen (possible on position 2-8 for each segment)
2. _Dataset, datasetMember and jobname_: Number is accepted as the first char (number(s) only are accepted too)

Current patterns:
```
Dataset:
"0.0.0" =~ ^([A-Z0-9\$\#\@]){1,8}(\.([A-Z0-9\$\#\@]){1,8}){0,11}$
Member:
"0" =~ ^([A-Z0-9\$\#\@]){1,8}$"
```

**Expected behavior**
Follow the rules.

- Dataset: ```^([A-Z\$\#\@]){1}([A-Z0-9\$\#\@\-]){0,7}(\.([A-Z\$\#\@]){1}([A-Z0-9\$\#\@\-]){0,7}){0,11}$```
  - Dataset segment: ```([A-Z\$\#\@]){1}([A-Z0-9\$\#\@\-]){0,7}```
    - Mandatory char: ```[A-Z\$\#\@]){1}```
    - Optional chars: ```[A-Z0-9\$\#\@\-]){0,7}```
  - Continue with ```.``` and another segment
  - Hyphen can be last in the segment, this is legal name for dataset: ```DS.A-.B-```

- Jobname and dataset member: ```^([A-Z\$\#\@]){1}([A-Z0-9\$\#\@]){0,7}$```
  - Mandatory char ```([A-Z\$\#\@]){1}```
  - Optional chars: ```([A-Z0-9\$\#\@]){0,7}```

**Comment by MarkAckert** [comment]
Closing as complete, thank you for submitting the fix!
