### ISSUE TITLE
Update licenses for 1.0.0

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#319]
The current licenses in 1.0.0 early builds need updating

![image](https://user-images.githubusercontent.com/28100302/51919982-670a0d00-23dc-11e9-9b56-082d81274412.png)

These licenses are
/Explorer_Server_Licenses.zip
/Rocket_Notices.txt
/Zowe_APIML_TOSRs.zip
/Zowe_CLI_TPSRs.zip
/Zowe_Open_Beta_License_Agreement.pdf

**Comment by MarkAckert** [comment]
I will take the action on this - all 3rd party dependencies, including transitive dependencies, will have their licenses provided in a single large zip in the PAX file. The first go around for licenses will be done ad-hoc; the completed automation to provide licenses will be post 1.0.0.

**Comment by jmertic** [comment]
Sent a note to the ZLC on the full process, but for here +1 mark having licenses in the pax and somewhere online to reference for each binary produced.

**Comment by MarkAckert** [comment]
Completed and in PAX - all old licenses removed, and a new zowe_licenses_full.zip which contains the TPSRs markdown, Bill of Materials markdown, and an automatically generated NOTICES file.
