### ISSUE TITLE
ZIS plug-in install does not propagate return code

### ISSUE THREAD

**Issue by nosrednayduj** [zowe/zowe-install-packaging#3212]
**Describe the bug**
If you install a component that has a zis plug-in, and requires inserting variables into ZWESIP00, this may fail if ZIS (or maybe even Zowe) is running. However, the return code from the component install is 0. The plug-in install should propagate the return code from failures.

Additionally, it would be very clever if you were to use the "safe copy" mechanism rather than cp, which requires exclusive access for no apparent reason. Looks like you don't have this in version 2 anymore; it was in scripts/utils/zowe-copy-to-JES.sh in version 1. Anyway, if you use this clist mechanism, then you can put files in open PDS's, and then you won't get this failure in the ZIS install.

**To Reproduce**
Create a component with a manifest which contains zisplugins:
...
```
zisPlugins:
  - id: zss-data-provider
    path: zss-data-provider/zisServer
```
...

Plug-in contains a file with variables for configuration that will end up in ZWESIP00, example
file zss-data-provider/zisServer/samplib/izpzssp0:
```
* PROVIDER PLUGIN
ZWES.PLUGIN.ZSSP=IZPDPROV

* CUSTOM AUX STC NAME
IZP.ZSSP.AUXNAME=$ZWE_zowe_setup_security_stcs_aux
```

Run zwe component install while Zowe and ZIS are still up.

**Expected behavior**
Plug-in should either say it failed and propagate its return code up so that the entire component install knows that it failed, or it should succeed by using a different mechanism for copying the file.

**Screenshots**
```
ERROR:     cp: FSUM6259 target file "//'RSQA.IZP.IZPS097.SZWESAMP(ZWESIP00)'": EDC5061I An error occurred when attempting to define a file to the system. (errno2=0xC00B0403)
    /tmp/ZWESIP00-3754 -> RSQA.IZP.IZPS097.SZWESAMP(ZWESIP00): text
Successfully installed ZIS plugin: zss-data-provider
```

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
This problem has been around since version 1, I just didn't officially complain about it then.

**Comment by MarkAckert** [comment]
cc @1000TurquoisePogs - should we move this issue to a zss/zis repo?

**Comment by nosrednayduj** [comment]
Apparently in the week between Christmas and New Year's I poke around at technical debt because nobody's paying attention to what I'm doing. I have a fix to this that I'd like to propose.

I tested this by modifying zowe runtimeDirectory/bin/libs/component.js. I'm just guessing that the sh change would also work. Maybe I could check by turning off config manager, but maybe I can't actually do that because UMS install requires config manager.

Could someone with a Zowe development environment take this on?

```
diff --git a/bin/libs/component.sh b/bin/libs/component.sh
index 6494b5393..9fc6c7f1e 100644
--- a/bin/libs/component.sh
+++ b/bin/libs/component.sh
@@ -551,6 +551,10 @@ zis_plugin_install() {
 
   if [ $changed -eq 1 ]; then
     copy_to_data_set "$parmlib_member_as_unix_file" "$zwes_zis_parmlib($zwes_zis_parmlib_member)" "" "true"
+    if [ $? != 0 ]; then
+      print_error "Error ZWEL0200E: Failed to copy USS file ${parmlib_member_as_unix_file} to MVS data set ${zwes_zis_parmlib}." 
+      return 200
+    fi
   fi
 }
 
diff --git a/bin/libs/component.ts b/bin/libs/component.ts
index 7318c3b4f..1680ca3f6 100644
--- a/bin/libs/component.ts
+++ b/bin/libs/component.ts
@@ -672,7 +672,11 @@ export function zisPluginInstall(pluginPath: string, zisPluginlib: string, zisPa
   if (changed) {
     common.printDebug(`Parmlib modified, writing as \n${parmlibContents}`);
     xplatform.storeFileUTF8(parmlibMemberAsUnixFile, xplatform.AUTO_DETECT, parmlibContents);
-    zosdataset.copyToDataset(parmlibMemberAsUnixFile, `${zisParmlib}(${zisParmlibMember})`, "", true);
+    const rc = zosdataset.copyToDataset(parmlibMemberAsUnixFile, `${zisParmlib}(${zisParmlibMember})`, "", true);
+    if (rc != 0) {
+      common.printError(`Error ZWEL0200E: Failed to copy USS file ${parmlibMemberAsUnixFile} to MVS data set ${zisParmlib}.`);
+      return 200;
+    }
   }
   return 0;
 }
```

**Comment by DivergentEuropeans** [comment]
https://github.com/zowe/zowe-install-packaging/pull/3697 implemented
