### ISSUE TITLE
Provide a clear, documented way of overriding all temporary files destination

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-install-packaging#3236]
*Customer content*

There currently is no clear/unified/documented way of selecting the directory for temporary files. By default in USS `/tmp` is used, but the IBM documentation states that this can be configured by overriding the `TMPDIR` variable.

In testing, setting this variable in https://github.com/zowe/launcher/blob/004d1a3e94e9d4f07288f949eab5ca71cb0a0492/samplib/ZWESLSTC#L46 did not have the expected result.

Also, the scripts make use of a variable called `TEMP_DIR`

There's also the `environments` section in `zowe.yaml` which can add to the confusion.

**Describe the solution you'd like**
I'd like to have a documented way to apply a change to the temporary directory used that applied to the entire Zowe run, from installation to components running.

**Describe alternatives you've considered**
Described above, tried to set the environment variable in different locations of the zowe installation, with varying results (some but no all the temporary files were being created in the custom directory, some were still sent to the system `/tmp`)

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by pablocarle** [comment]
Hi,
For context, this issue originates in a customer report where the extensive use of the main `/tmp` directory ended in a corrupted filesystem, thus affecting other products that rely on this temporary directory.
This issue could affect the adoption of Zowe.
In another comment, I will add the results of our analysis where we found some areas of improvement.

**Comment by pablocarle** [comment]
One more variable to consider is `CATALINA_TMPDIR` which controls the temporary folder used by Tomcat servers.

**Comment by pablocarle** [comment]
In testing we found the following:

We added logs in zwe command to understand where the values from https://github.com/zowe/launcher/blob/004d1a3e94e9d4f07288f949eab5ca71cb0a0492/samplib/ZWESLSTC#L46 reached:

```
Tue Jan 24 12:51:38  2023: in zwe. Params: (internal config get --configmgr --config /z/zwesvusr/api-layer-perf/zowe-v2.3.1/zowe.yaml --ha-instance lpar --path .zowe.workspaceDirectory) env: TMPDIR: "/z/zwesvusr/tmp/1"                                                       , TEMP_DIR: "/z/zwesvusr/tmp/2"                                                     , CATALINA_TMPDIR: "/z/zwesvusr/tmp/6"                                              , _BPX_SHAREAS: 
Tue Jan 24 12:51:42  2023: in zwe. Params: (internal start prepare --config /z/zwesvusr/api-layer-perf/zowe-v2.3.1/zowe.yaml --ha-instance lpar) env: TMPDIR: "/z/zwesvusr/tmp/1"                                                       , TEMP_DIR: "/z/zwesvusr/tmp/2"                                                     , CATALINA_TMPDIR: "/z/zwesvusr/tmp/6"                                              , _BPX_SHAREAS: 
Tue Jan 24 12:53:33  2023: in zwe. Params: (internal get-launch-components --config /z/zwesvusr/api-layer-perf/zowe-v2.3.1/zowe.yaml --ha-instance lpar) env: TMPDIR: "/z/zwesvusr/tmp/1"                                                       , TEMP_DIR: "/z/zwesvusr/tmp/2"                                                     , CATALINA_TMPDIR: "/z/zwesvusr/tmp/6"                                              , _BPX_SHAREAS: 
Tue Jan 24 12:53:45  2023: in zwe. Params: (internal start component --config /z/zwesvusr/api-layer-perf/zowe-v2.3.1/zowe.yaml --ha-instance lpar --component caching-service) env: TMPDIR: , TEMP_DIR: , CATALINA_TMPDIR: , _BPX_SHAREAS: YES
Tue Jan 24 12:53:45  2023: in zwe. Params: (internal start component --config /z/zwesvusr/api-layer-perf/zowe-v2.3.1/zowe.yaml --ha-instance lpar --component zss) env: TMPDIR: , TEMP_DIR: , CATALINA_TMPDIR: , _BPX_SHAREAS: YES
Tue Jan 24 12:53:45  2023: in zwe. Params: (internal start component --config /z/zwesvusr/api-layer-perf/zowe-v2.3.1/zowe.yaml --ha-instance lpar --component gateway) env: TMPDIR: , TEMP_DIR: , CATALINA_TMPDIR: , _BPX_SHAREAS: YES
Tue Jan 24 12:53:45  2023: in zwe. Params: (internal start component --config /z/zwesvusr/api-layer-perf/zowe-v2.3.1/zowe.yaml --ha-instance lpar --component discovery) env: TMPDIR: , TEMP_DIR: , CATALINA_TMPDIR: , _BPX_SHAREAS: YES
```

From here we can see that the environment variables defined were not reaching the `start component` phase, for this we are working on a fix in the launcher at: https://github.com/pablocarle/launcher/tree/share-env-sh. This proposed solution prioritizes the variables defined in zowe.yaml.

The launcher fix will not fix everything, something else that's odd if the extra whitespaces we see in the messages from `internal get-launch-components`, `internal config get` and `internal start prepare` for which we don't have a solution currently. 

And lastly, in API ML, the components had the `/tmp` hardcoded: https://github.com/zowe/api-layer/pull/2769

These are some specific issues we found, though still would be better to have a centralised way of updating these variables.

**Comment by janan07** [comment]
Issue addressed in https://github.com/zowe/docs-site/pull/2656
