### ISSUE TITLE
RACF error on STC startup ZWE1SV

### ISSUE THREAD

**Issue by ccc13481** [zowe/zowe-install-packaging#3267]
On starting the ZWE1SV from the ZWESLSTC I get an ICH408I error as a userid is not assigned to the ZWE1SV STC:

S ZWESLSTC,JOBNAME=ZWE1SV                                                
$HASP100 ZWE1SV   ON STCINRDR                                            
ICH408I USER(CNOSTC  ) GROUP(FNOSTC  ) NAME(IKKE DEFINEREDE STC.) 537    
  IEFIB600 CL(PROGRAM )                                                  
  INSUFFICIENT ACCESS AUTHORITY                                          
  FROM ** (G)                                                            
  ACCESS INTENT(READ   )  ACCESS ALLOWED(NONE   )                        
CSV025I PROGRAM CONTROLLED MODULE IEFIB600 NOT ACCESSED, USER UNAUTHORIZ 
ED                                                                       
CSV028I ABEND306-30  JOBNAME=ZWESLSTC  STEPNAME=STARTING                 
IEF170I 1 ZWE1SV   CSV025I PROGRAM CONTROLLED MODULE IEFIB600 NOT ACCE   
IEF170I 1 ZWE1SV   CSV028I ABEND306-30  JOBNAME=ZWESLSTC  STEPNAME=STA   
IEA848I DUMP SUPPRESSED - USER NOT AUTHORIZED BY SAF - JOB ZWESLSTC      
IEF170I 1 ZWE1SV   IEA848I DUMP SUPPRESSED - USER NOT AUTHORIZED BY SA   
IEA989I SLIP TRAP ID=X33E MATCHED.  JOBNAME=*UNAVAIL, ASID=0178.         
$HASP310 ZWE1SV   TERMINATED AT END OF MEMORY                            
$HASP250 ZWE1SV PURGED -- (JOB KEY WAS DCCC832D)                         

The ZWE1SV is defined in the STARTED RACF Class:

![image](https://user-images.githubusercontent.com/51124172/216353377-5c558065-b749-4395-8a31-6ab3d23823f2.png)

This is zowe 2.5, z/OS 2.4 - fresh install.

The BPX.JOBNAME is assigned to the same userid as the STC

What more information can I provide?

BR
Frank Allan Rasmussen
Danske Bank

**Comment by MarkAckert** [comment]
Hi Frank,

Could you confirm that you've followed the security initialization docs? Available here: https://docs.zowe.org/v2.5.x/user-guide/initialize-security-configuration . The "Next steps" section lists out the exact security steps that need to be completed before Zowe starts up, one of them is the User ID setup.

If you already went through this doc, could you list what actions you performed (i.e. `zwe init`, submit ZWESECUR, then started zowe)? 

Thank you!

**Comment by JoeNemo** [comment]
A good similar/same issue around a 306-30 abend is noted here:  https://knowledge.broadcom.com/external/article/52616/running-casysview-without-racf-attribut.html

Maybe this use is not in a SAF group for class=PROGRAM

**Comment by ccc13481** [comment]
Reinstalled zowe 2.5.
Had our security group go over the security setup
Error gone.
