### ISSUE TITLE
What is proper .profile  (or  .bshrc) setting for zowe installation?

### ISSUE THREAD

**Issue by likepunk** [zowe/zowe-install-packaging#327]
I  have  encountered  several cases  where files  are  not encoded  correctly on USS  and/or  not  readable  within USS/SSH. 

Some suggested  tagging,  some suggested  take  out BPXK_AUTOCVT=ON ,  but  without  BPXK_AUTOCVT,  the  ssh doesn't really  work. 

What is  the  proper settings  for  .profile (where  it  copies  to .zowe_profile)  environment  variables?

If  I assume I  only use Zowe  -  please  provide  a working  environment variable  example.

Also,  is bash  a  recommended  or NOT recommended  to install ZOWE? 

Thanks in  advance!

Alex

**Comment by MarkAckert** [comment]
Hi @John-A-Davies, have you seen this and does it overlap with your Epic #365 ?

**Comment by John-A-Davies** [comment]
All our shell scripts start with `#!/bin/sh` so Bourne shell will be used.
