### ISSUE TITLE
Invalid probably unused piece of code

### ISSUE THREAD

**Issue by pavel-jares-bcm** [zowe/zowe-install-packaging#3330]
**Describe the bug**

During the review code, I found this piece of code.

https://github.com/zowe/zowe-install-packaging/blob/ac188dfb0859f7d76fec49202dc7ce4459038606/bin/libs/zos-dataset.ts#L279-L293

https://github.com/zowe/zowe-install-packaging/blob/ac188dfb0859f7d76fec49202dc7ce4459038606/bin/libs/zos-dataset.ts#L20-L23

The code means that it searches for a member with a random name until the member is found. If not it is an infinity loop. Definitely, it does not create any temporary members, just try to find any matching.

Could you please verify why this code is there and fix or remove it?

**Comment by MarkAckert** [comment]
cc @1000TurquoisePogs

**Comment by 1000TurquoisePogs** [comment]
Yes, the shell source used max retry=100
https://github.com/zowe/zowe-install-packaging/blob/ac188dfb0859f7d76fec49202dc7ce4459038606/bin/libs/zos-dataset.sh#L355
Shall we do the same here? Again like you say, I'm not sure this is ever used.

**Comment by pavel-jares-bcm** [comment]
The shell script is used (https://github.com/zowe/zowe-install-packaging/search?q=create_data_set_tmp_member) in security and certificates. I guess both are not rewritten to TS. Actually, there are two differences with SH. The most important is condition `if (memberExist) {`. It should return the name of an element if it does not exist. 

Anyway, I guess the easiest way is to fix it. Therefore I have created PR #3370.
