### ISSUE TITLE
If node home is set but the backing code doesn't exist, install fails

### ISSUE THREAD

**Issue by mikefultoniphone** [zowe/zowe-install-packaging#34]
As part of my clean up, I deleted node from my system but didn't unset node home.
This made the install unhappy.
Joe Winchester pointed out that https://github.com/zowe/zowe-install-packaging/blob/master/scripts/zowe-init.sh is only checking for node home existing - and not for node being installed and operational (which is probably what should be done)

**Comment by jackjia-ibm** [comment]
Duplicate of #18.

**Comment by stevenhorsman-ibm** [comment]
Jack did this work as part of #18
