### ISSUE TITLE
Config manager should be enabled by default

### ISSUE THREAD

**Issue by boris-bc** [zowe/zowe-install-packaging#3422]
The config manager component of the Zowe startup process controlled via the `zowe.useConfigmgr` property is currently disabled by default, that is, when the property is not specified in the `zowe.yaml` file, it is not enabled. This behavior should be the opposite and the config manager should be enabled unless explicitly indicated otherwise in the `zowe.yaml` configuration.

**Additional context**
The config manager is a major improvement of the Zowe startup process. Many new adopters are not familiar with its existence and struggle with poor performance during startup.

**Comment by 1000TurquoisePogs** [comment]
Yes, if its not present, it's `false`, despite the latest example file having it `true`.
This effectively means new installs will default to `true`, but old installs remain `false` unless they opt-in.

That was on purpose. Originally, the TSC desired configmgr to be purely opt-in, to not disrupt existing installs by making zowe more strict than it was in 2.0.

Then around 2.4, the TSC desired new installs to have it set to `true`.

This is a symptom of that zowe upgrades do not get config updates, which is being solved by switching from an example-based config to a default-based config, which I'm working on this PI.

Until then, let's get TSC approval to default to `true` when absent. This could break existing installs. If someone has a harmless but invalid config versus the schema, it will result in the servers not starting until corrected. So, I don't want to do this without permission, it could be seen as a breaking change.

**Comment by boris-bc** [comment]
I am a fan of default-based config in general and I am fine if this change makes it into V3 instead (which is not that far in the future anyway).

**Comment by 1000TurquoisePogs** [comment]
Completed during that timeframe.
