### ISSUE TITLE
Unable to bring up zlux where the installing user isn't in the same group as the ZOWESVR user

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#345]
Fixed with https://github.com/zowe/zowe-install-packaging/pull/207

**Comment by 1000TurquoisePogs** [comment]
#207 isn't making any changes to users or groups. Was there a different ticket that resolves this?

**Comment by Joe-Winchester** [comment]
Fixed with pull request https://github.com/zowe/zowe-install-packaging/pull/344

**Comment by John-A-Davies** [comment]
I got this today
```
Error: EACCES: permission denied, open '../deploy/instance/ZLUX/serverConfig/zluxserver.json'      
```
and I can see 
```
TSTRADM:/zaas1/zowe/1.0.0: >ls -l ./zlux-app-server/deploy/instance/ZLUX/serverConfig/zluxserver.json
-rwxrwx-w-   1 OMVSKERN SYS1        2522 Feb  5 05:58 ./zlux-app-server/deploy/instance/ZLUX/serverConfig/zluxserver.json
```
This is from PAX 503 of 4 Feb.

**Comment by Joe-Winchester** [comment]
Closing this as in 1.0.0 we are now doing a chgrp IZUADMIN on the /deploy folders, and because IZUSVR is part of IZUADMIN and we have set up group permissions this will avoid any EACCES problems we used to get with the log and also keep user any from reading or writing into folders they shouldn,t unless they're also in IZUADMIN.
