### ISSUE TITLE
Remove server-bundle from v2.x branches

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#3473]
Currently we have a folder under `containers` directory named `server-bundle`. This was used to publish a Dockerized version of Zowe in the v1.x line, however, we migrated to Kubernetes for the v2.x line. 

There is no intersection between these images and the Kubernetes distribution, so we should remove them from the 2.x branch.

**Comment by MarkAckert** [comment]
@1000TurquoisePogs See above - do you have any opposition to removing `server-bundle` in 2.x? Thanks

**Comment by 1000TurquoisePogs** [comment]
Sounds fine to remove
