### ISSUE TITLE
Errors during workflow creation from xml/properties files

### ISSUE THREAD

**Issue by Shobhajayanna** [zowe/zowe-install-packaging#3486]
**Describe the bug**

When I tried to create workflows from the workflow xml/ properties files present under runtime directory, I got an error saying "IZUWF0120E Content is not allowed in prolog". I have attached the error screenshot below for reference.

**To Reproduce**
1. Login to zosmf 
2. Click on create workflow
3. Fill the paths to workflows files(xml/properties) from your runtime directory
    I have tried for below 4 workflows which are required to set up Zowe certificates  
     ZWECONF.propert 
     ZWECONF.xml     
     ZWECRECR.proper 
     ZWECRECR.xml    
     ZWEKRING.proper 
     ZWEKRING.xml  
     ZWESIGNC.proper
     ZWESIGNC.xml     
4. See the error

<img width="465" alt="workflow error" src="https://github.com/zowe/zowe-install-packaging/assets/36433611/563026ae-d4aa-4c99-bfec-f41efb36b830">

**Expected behavior**
workflows should be created

**Screenshots**
atached

**Zowe**
 - Version : 2.7

**Additional context**

**Comment by JoeNemo** [comment]
Is this ZOSMF or Zowe issue?

**Comment by Shobhajayanna** [comment]
hi, it looks like a syntactical issue on zosmf workflow xmls.

**Comment by muzikovam** [comment]
The workflows were uploaded in the incorrect encoding during the build proccess.

**Comment by muzikovam** [comment]
Was fixed by #3593
