### ISSUE TITLE
Github actions tests keep failing due to recent update on the runner images Ubuntu 22.04

### ISSUE THREAD

**Issue by ojcelis** [zowe/zowe-install-packaging#3493]
**Describe the bug**
The recent update on runner images Ubuntu 22.04 that includes updating Ansible to 2.15 breaks our GitHub actions tests

**To Reproduce**
1. Go to zowe-install-packaging
2. Force to use Ansible 2.15 in GHA prepare workflow
3. Click on Actions then click Zowe CICD Integration Tests
4. In the right click Run workflow and populate needed details then press Run

**Expected behavior**
Test Passed

**Actual behaviour**
Error message below:
The task includes an option with an undefined variable. The error was: 'zos_uss_user_profile' is undefined. 'zos_uss_user_profile' is undefined

The error appears to be in '/home/runner/work/zowe-install-packaging/zowe-install-packaging/playbooks/roles/common/tasks/upload_essentials.yml': line 32, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

**Comment by ojcelis** [comment]
Fixed it with https://github.com/zowe-actions/shared-actions/pull/26 to force the action to use Ansible 2.14.6

**Comment by MarkAckert** [comment]
Closing as complete
