### ISSUE TITLE
For ACF2 the STCGRP needs to be set on line 174 of the `zwe init certificate` generated JCL

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#3498]
**Describe the bug**
The command `zwe init certificate` is incomplete for ACF2 in the JCL it generates

**To Reproduce**
Set the `zowe.security.product` to be `ACF2.
Run `zwe init certificate -c zowe.yaml --security-dry-run` and look at the generated JCL, especially line 174

```
//*
//* ACF2 ONLY -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
//*                     12345678
//         SET  STCGRP=
//*                     12345678
//*
//* end ACF2 ONLY -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
```
**Expected behavior**
the value of of the `STCGRP=` should have been picked up from `zowe.security.product.groups.stc`.  

**Screenshots**
 
<img width="662" alt="image" src="https://github.com/zowe/zowe-install-packaging/assets/28100302/de8bc81b-0d30-4f76-84ea-f267836720e7">

**Comment by JoeNemo** [comment]
Is this coming from a "real" customer of Zowe (not Zowe development)?

**Comment by JoeNemo** [comment]
@codezfire  Please watch this.

**Comment by Joe-Winchester** [comment]
> Is this coming from a "real" customer of Zowe (not Zowe development)?

Hi @JoeNemo .    This came out of a review of the blogpost https://medium.com/zowe/master-zowe-certificates-use-an-existing-jceracfks-certificate-for-zowes-z-os-components-975ffa0d9f2f that @MarkAckert did, where the blogpost is full of RACF steps (mostly because that's the system Sam and I had access to) and Mark pointed out that for ACF2 an additional step was needed that the `ZWEKRYING` didn't perform.  Based on that we slacked back and forth about why the JCL didn't include the step, which led to this this PR.   
I don't have access to an ACF2 system so I'm not actually sure what the step does, so the best testing I can do is to eyeball the JCL and see that the `STCGRP` is set.

**Comment by codezfire** [comment]
Hi Joe 
We could work on a mini-system DE15 for ACF2 testing.
