### ISSUE TITLE
zowe-install.sh reports that ZOWE_ZOSMF_USERID is not specified and defaults, even when it's in the .yaml

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#354]
```
Reading install variables from zowe-install.sh
  ZOWE_ZOSMF_USERID not specified:  Defaulting to IZUSVR
Beginning install of Zowe 1.0.0 into directory  /u/winchj/zowe/1.0.0_RC1
```

**Comment by Joe-Winchester** [comment]
This logging line is used when a value is first looked for in the .zowe_profile and if not there then a default value it used.  The ZOWE_ZOSMF_USERID is not persisted in the .zowe_profile as it's a variable that is read from the zowe-install.yaml file itself and is per-install rather than per environment (which is the purpose of .zowe_profile).  As an enhancement we should consider whether we can work out the z/OSMF user ID and we should persist it in .profile and remove it from the .yaml, and likewise for the keyring name.

**Comment by MarkAckert** [comment]
This issue will sit in the backlog pending install procedure review....will circle back

**Comment by stevenhorsman** [comment]
yaml file no longer exists
