### ISSUE TITLE
Node v14.21.3.1 and v16.20.1 fails on ACF2 and TSS systems

### ISSUE THREAD

**Issue by ojcelis** [zowe/zowe-install-packaging#3552]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JoeNemo** [comment]
This bug needs some detail, please.

**Comment by ojcelis** [comment]
@JoeNemo Looks like the issue is occurring on the current version of node 14 and 16 in the marist sytems. Plaese refer to my message on the release slack here https://openmainframeproject.slack.com/archives/G01M2C8QB3K/p1692800514264279. thank you.

**Comment by ojcelis** [comment]
Checked and found out the issue is occurring with the current version of node on marist sytems. This issue is not related to the new node specify in this ticket so closing the ticket.
