### ISSUE TITLE
Cleaup Artifactory To Reclaim Space

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#3565]
It was brought to our attention that we're currently over utilizing space provided by Artifactory's free OSS plan. The majority of the space usage appears to be in docker-snapshot.

Fix timeline TBD with team.

**Comment by MarkAckert** [comment]
cc @achmelo , @ojcelis , @balhar-jakub for awareness. I haven't investigated yet but I believe APIML generates a lot of docker snapshots. Space utilization may not be terrible if there's efficient re-use of layers...but if there's not efficient layer caching, is there any way we can automate cleanup or reuse container tags efficiently?

**Comment by balhar-jakub** [comment]
If it's coming from API ML, let us know and we will plan as soon as possible to do something about the topic.

**Comment by MarkAckert** [comment]
We need to remove ~ 1.6 TB of artifacts in the short term, and can take our time after that. I'm going to start by removing duplicate snapshots for old versions of Zowe and see where that gets me. e.g., we have a lot of `componenta-snapshot-<#n>`, and I'll cleanup everything < n. 

We do have many more APIML containers than other component groups. 

If we can simply remove containers from docker-snapshots that would be ideal. I'll check with all the component groups to make sure we're not relying on them anywhere.

**Comment by MarkAckert** [comment]
Update - continuing to work through what is safe to delete - duplicate copies of a SNAPSHOT version, or artifacts built from PRs/temporary branches. We're down by about 1 TB and should make the 5TB cutoff. I also changed our Artifactory policy to prune old/unused SNAPSHOTS more aggressively. We'll probably still need to cleanup occasionally, but much less so compared to this time. 

As it turns out, docker-snapshots was only half the story, libs-snapshot-local used a similar amount of storage with less efficient compaction. Artifactory is smart enough with docker images to re-use existing layers across many different images/tags, so we're going to wind up saving more space from our libs-snapshot-local cleanup rather than docker-snapshots. 

For libs-snapshot-local, some stats by artifact count (not space):
```
Processed 265779 artifacts.
Will keep 54364 of the latest unique artifacts, deleting 180307 artifacts for a reduction of 67.84095056419055%
```

For docker-snapshots, some stats by artifact count (not space):
```
Processed 22307 artifacts.
Will keep 5879 of the latest unique artifacts, deleting 16428 artifacts for a reduction of 73.6450441565428%
```

**Comment by MarkAckert** [comment]
Closing as complete. Our final binaries consumption size is down to 2.46TB. Scripts to automate this have been shared via private repo for systems squad members.
