### ISSUE TITLE
The createZosmfTrust parameter still persists in example-zowe.yam certificate setup scenario 3

### ISSUE THREAD

**Issue by skurnevich** [zowe/zowe-install-packaging#3577]
The createZosmfTrust parameter was introduced in [PR 3270](https://github.com/zowe/zowe-install-packaging/pull/3270) and then reverted [here](https://github.com/zowe/zowe-install-packaging/commit/96f7aa7c3535c95f5264305ef6268b9c2de7f8d9). 

But it still persists in [example-zowe.yaml](https://github.com/zowe/zowe-install-packaging/blob/c3ea9c99a23e8e5b7a8ae2226d3944a606b4ed08/example-zowe.yaml#L180) for certificate setup scenario 3.

As a result, Zowe fails on schema validation if the user uncomments scenario 3.

**Comment by Joe-Winchester** [comment]
@skurnevich ,  just got a customer who ran into this too so wanting to make a fix.
Is there logic to process the `createZosmfTrust` value so we should allow it to pass validation and the schema needs fixing up, or should we just remove it from the original template file ?

**Comment by skurnevich** [comment]
Hi @Joe-Winchester, as far as i recall, the logic and schema should be fine already and the issue is rather small, we just need to remove the `createZosmfTrust` from the `example-zowe.yaml`

**Comment by Joe-Winchester** [comment]
Thanks @skurnevich ,  I've created PR that removes the `example-zowe.yaml` and create a PR for you to review.
Cheers !
