### ISSUE TITLE
XML Parser Error

### ISSUE THREAD

**Issue by nkocsis** [zowe/zowe-install-packaging#3591]
Problem Description:

we failed to load the zOSMF workflow
/usr/lpp/zowe/files/workflows/ZWECONF.xml
with the following error message

The validation of workflow definition file "/tst/prd23c1/usr/lpp/zowe/files/workflows/ZWECONF.xml" failed. See line "1" for errors. More information from the XML parser: "Content is not allowed in prolog."

Using help for message IZUWF0120E The validation of workflow definition file file-name failed. See line line-number for errors. More information from the XML parser: error-data

brings the following information: 

User response
If error-data is the message Content is not allowed in prolog it is likely that a mismatch exists between the encoding specified on the first line of the workload definition file and the actual encoding of the file. This error can occur, for example, if the file was developed in a workstation-based editor that requires the UTF-8 encoding standard, but you transferred the file in ASCII mode to z/OS, which resulted in an automatic conversion to EBCDIC. If this has happened, you can re-transmit the file in binary mode, or edit the file on z/OS and change the encoding to IBM-1047. Then, try adding the workflow again.

In our case this workflow definition file was transferred by SMP/E during SMP/E installation, so there was no transfer done by us.

Analysis of problem:
Per the doc site in [zowe.org](http://zowe.org/), client can use zosmf to configure zowe (i.e. zowe.yaml) using .../runtime/files/workflows/ZWECONF.xml, however, when the file is used in zosmf, client see error as in below screen.  The issue is codepage of ZWECONF.xml is ebcdic but zosmf takes ASCII files.  Client needs to use iconv to convert the file from IBM-1047 to ISO8859-1. This has been raised as issue in multiple client complains. Is there a chance to make zosmf files in ISO8859-1?

![Screenshot 2023-10-05 at 10 55 28 AM](https://github.com/zowe/zowe-install-packaging/assets/36776369/a56acfe7-eda6-44f8-97e9-3bb2fa418b9e)

**Comment by nkocsis** [comment]
Another issue but for doc squad and packaging ...

As below - https://docs.zowe.org/stable/user-guide/configure-zowe-zosmf-workflow/
In second paragraph, it indicated that Install Zowe with SMP/E build, PSWI, or convenience build as requirement for using zosmf workflow to configure zowe.yaml...The client use SMP/E build from Shopz and SMP/E install is done, then point 3 in Configure the zowe instance directory is not require for them and could cause confusions...
Because SMP/E install is actual done (in my opinion) and we need to run zwe init but not the zowe install

**Comment by ojcelis** [comment]
Hi @nkocsis we have the same issue here https://github.com/zowe/zowe-install-packaging/issues/3486

**Comment by bobbydixon** [comment]
I see a couple of issues (#3591 this case, [#3593](https://github.com/zowe/zowe-install-packaging/pull/3593), [#3486](https://github.com/zowe/zowe-install-packaging/issues/3486)) referring to this issue, but it's not clear to me whether these have, or will be resolving the issue, and I have a client who is not happy that they had to transfer the EBCDIC ZWECONF.xml file to UTF-8 format in order to successfully load the file into z/OSMF in order for their team to utilize the z/OSMF workflows?

**Comment by MarkAckert** [comment]
Our intent is to have the workflow files in an encoding z/OSMF can load without the need to transfer/convert from EBCDIC. PR #3593 will resolve the encoding issue when it's complete and merged in. This fix might not make it into Zowe 2.12, and if not it should make Zowe 2.13.
