### ISSUE TITLE
Many missing variables in Zowe configuration workflow

### ISSUE THREAD

**Issue by js665999** [zowe/zowe-install-packaging#3594]
**Describe the bug**
Workflow is hardcoded to outdated Zowe version. Following variables are missing from zowe.yaml generated by workflows. Compared against v2.11

**zowe.setup.dataset.parmlibMembers.zis: ZWESIP00
zowe.setup.dataset.loadlib: IBMUSER.ZWEV2.SZWELOAD
zowe.useConfigmgr: true
zowe.configmgr.validation: "COMPONENT-COMPAT"
zowe.rbacProfileIdentifier: "1"
zowe.cookieIdentifier: "1"
zowe.onComponentConfigureFail: "warn"
components.cloud-gateway.enabled: false
components.cloud-gateway.port: 7563
components.cloud-gateway.debug: false
components.jobs-api.enabled: false
components.files-api.enabled: false
components.caching-service.infinispan.jgroups.port: 7600
components.app-server.debug: false
components.zss.agent.jwt.fallback: true**

**Additional issues**

- For versions lower than v2.9 config manager will be disabled by default because of the missing variable and user will not even know it exists.

- Many comments are also outdated.

- Disabled components will not be generated at all and if later decide to enable component I have to regenerate the workflow instead of just making small changes to the zowe.yaml file.

- Workflow asks users what components they want enabled without showing defaults of explanations, so many just enable everything without knowing what they do.  For example **components.gateway.server.internal.enabled** should be set to false in majority cases, but there have been multiple issues related to users setting this to true and breaking their instance.

**Comment by balhar-jakub** [comment]
I believe that around 2.9 the config manager is the default mode of operation, when there is no value in zowe.useConfigMgr as such it probably doesn't need to be part of the workflow.

**Comment by js665999** [comment]
> I believe that around 2.9 the config manager is the default mode of operation, when there is no value in zowe.useConfigMgr as such it probably doesn't need to be part of the workflow.

Will that be ok with backward compatibility requirements? Without the variable, same config file will behave differently on different versions.

**Comment by balhar-jakub** [comment]
There was an agreement about it and the decision on TSC call was that we are able to live with the potential risk.

**Comment by JoeNemo** [comment]
I am not sure how these workflows are staying in sync with the example and the json schema(s) of zowe base and components.

**Comment by balhar-jakub** [comment]
They probably don't and therefore the correct answer would be to generate them based on the JSON schema, which I believe @jp669844 plans to open as a new issue to actually discuss.

**Comment by jp669844** [comment]
They are clearly out of sync. The plan is to employ a JSON schema, potentially enhancing it, and make it the sole source of truth for both the YAML file and the z/OSMF workflow.

**Comment by jp669844** [comment]
https://github.com/zowe/zowe-install-packaging/issues/3608
