### ISSUE TITLE
property "internal" in the zowe-example yaml file

### ISSUE THREAD

**Issue by Shobhajayanna** [zowe/zowe-install-packaging#3595]
Hi,

In the yaml file 
https://github.com/zowe/zowe-install-packaging/blob/0628690b204fc2efdbaf3cdd6aa2b3085368767f/example-zowe.yaml, 

components.gateway.server.**internal**.ssl.enabled is the property "internal"  being referenced anywhere or can it be removed?

Thanks,
Shobha

**Comment by MarkAckert** [comment]
There's at least one reference to `gateway.server.internal` in zowe-install-packaging-tools here: https://github.com/zowe/zowe-install-packaging-tools/blob/v2.x/master/config-converter/src/libs/yaml.js#L250 . There's a matching test case as well. 

Besides that, does `gateway.server.internal` have a use case we know about? I'm not familiar with the history of this config and if it's used anywhere once it's converted to ENV form.

**Comment by balhar-jakub** [comment]
It's relevant in the HA scenario. The API Gateway can run with two ports one for external communication and one for internal communication.

**Comment by MarkAckert** [comment]
Closing this issue then, as we should not remove the property.
