### ISSUE TITLE
After installing UO90031 and UO90032 the ZOWE launcher issues FSUM6807 and ZWED0159E messages

### ISSUE THREAD

**Issue by bobbydixon** [zowe/zowe-install-packaging#3604]
After applying UO90031 and UO90032 the ZOWE launcher issues the following error messages that previously did not appear.

Specifically

Ý: /usr/lpp/zowe/components/app-server/bin/[configure.sh](https://configure.sh/) 26: .: FSUM6807 expression syntax error

And

<ZWED:65804> ZWESVUSR CRITICAL (_zsf.utils,util.js:110) ZWED0159E - Could not read zowe manifest, version unknown

We found no reference for message ZWED0159E in the zowe doc, but we do see ZWED0159I is documented.  If the documented ZWED0159I message is the correct message, this needs to be corrected in the documentation please.

**Comment by Joe-Winchester** [comment]
Hi Bobby,  I've noticed the same errors.  Are you able to get the STC to come up correctly or is the issue about it being logged and causing unnecessary noise.

**Comment by codezfire** [comment]
No errors in sysprint when I removed the "y" symbol from the code configure.sh as below:


 000026 if   "$ZWE_components_gateway_enabled" == "true" ; then
 000027   if  "$ZWE_components_zss_enabled" == "true" ; then
 000028     if  "${ZWE_RUN_ON_ZOS}" != "true" ; then
 000029       zss_def_template="zss.apiml_static_reg.yaml.template"
 000030       export ZSS_PORT="${ZWE_components_zss_port}"
 000031       if  "${ZWE_components_zss_tls}" != "false" ; then
 000032         export ZSS_PROTOCOL=https
 000033       else
 000034         export ZSS_PROTOCOL=http
 000035       fi

**Comment by Martin-Zeithaml** [comment]
FSUM6807 was [fixed](https://github.com/zowe/zlux/issues/979).

**Comment by bobbydixon** [comment]
Thanks for the information, much appreciated.

From: codezfire ***@***.***>
Sent: Thursday, October 12, 2023 6:58 AM
To: zowe/zowe-install-packaging ***@***.***>
Cc: Bobby Dixon ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [zowe/zowe-install-packaging] After installing UO90031 and UO90032 the ZOWE launcher issues FSUM6807 and ZWED0159E messages (Issue #3604)

No errors in sysprint when I removed the "y" symbol from the code configure. sh as below: 000026 if "$ZWE_components_gateway_enabled" == "true" ; then 000027 if "$ZWE_components_zss_enabled" == "true" ; then 000028 if "${ZWE_RUN_ON_ZOS}" !=
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2A-oiVaV6VDRUs8Yc6qN5h_QSsOR2Z0hgcMxDxF-tlY2I5ypZWBjofulq2XLBxxJruN51n8nCcrTiF-_T9sIN4QnjJOb8qGjGBHBfAQNXVG_aTe5zOs$>   ‌
ZjQcmQRYFpfptBannerEnd

No errors in sysprint when I removed the "y" symbol from the code configure.sh as below:

000026 if "$ZWE_components_gateway_enabled" == "true" ; then
000027 if "$ZWE_components_zss_enabled" == "true" ; then
000028 if "${ZWE_RUN_ON_ZOS}" != "true" ; then
000029 zss_def_template="zss.apiml_static_reg.yaml.template"
000030 export ZSS_PORT="${ZWE_components_zss_port}"
000031 if "${ZWE_components_zss_tls}" != "false" ; then
000032 export ZSS_PROTOCOL=https
000033 else
000034 export ZSS_PROTOCOL=http
000035 fi

**Comment by bobbydixon** [comment]
Thanks for the information, much appreciated

From: Martin Zeithaml ***@***.***>
Sent: Thursday, October 12, 2023 7:45 AM
To: zowe/zowe-install-packaging ***@***.***>
Cc: Bobby Dixon ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [zowe/zowe-install-packaging] After installing UO90031 and UO90032 the ZOWE launcher issues FSUM6807 and ZWED0159E messages (Issue #3604)

FSUM6807 was fixed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <zowe/zowe-install-packaging/issues/3604/1759449624@ github. com> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2A-oiVaV6VDRUs8Yc6qN5h_QSsOR2Z0hgcMxDxF-tlY2I5ypZWBjofulq2XLBxyoG1KTDK5wRSF9t-91VhwL3Rr1TLSsAUr8BbyAQpZMwC3rcIsAthA$>   ‌
ZjQcmQRYFpfptBannerEnd

FSUM6807 was fixed<https://github.com/zowe/zlux/issues/979>.

**Comment by MarkAckert** [comment]
Closing this as resolved in 2.11. The PR above has fix details.
