### ISSUE TITLE
What is the correct/intended behavior of /bin/libs/fs.ts: resolvePath?

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-install-packaging#3613]
Is this working as intended?

```
console.log(fs.resolvePath('/bin/', '/libs/'));
console.log(fs.resolvePath('/bin/ ', '/libs/'));      // extra trailing space for the first argument
=== output ===
/bin/libs
/bin/ /libs
```
* The first output line is fine
* The second is returning 2 paths separated by space, which is significant for example for `rm`

**Comment by JoeNemo** [comment]
@1000TurquoisePogs ,  Sean, is this actually causing a problem, or will it someday?
