### ISSUE TITLE
zwe diagnose: shell only and no doc

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-install-packaging#3627]
1) Shell version is working only 
2) There is no doc update for this feature

Add a text to shell version of `diagnose` command:
`zowe/runtime/2120/bin/commands/diagnose: echo "echo 'hello, world'" >> index.sh`

Call `diagnose` with `--configmrg`
`zowe/runtime/2120/bin: ./zwe diagnose -e "ZWEL0111E" --configmgr`

Shell version is executed:
```
This code corresponds to the errors related to the Zowe Launcher and ZWE
To find the description of this error code, refer to the Zowe documentation for the Launcher at https://docs.zowe.org/stable/troubleshoot/launcher/launcher-error-codes and https://github.com/zowe/launcher/blob/v2.x/master/src/msg.h, and for ZWE at https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/
You may also explore reports from other users experiencing the same error by searching here https://github.com/search?q=org%3Azowe+ZWEL0111E&type=discussions
hello, world
```

**Comment by 1000TurquoisePogs** [comment]
no doc update because doc automation is broken. i need to fix it. there was some code conflict which broke the bot.

**Comment by 1000TurquoisePogs** [comment]
what is the reason to make the shell version? its fine but currently we have both TS & shell because we were moving away from shell. personally I wasn't going to write more shell, but maybe someone else would & maybe there is a good reason to?

**Comment by Martin-Zeithaml** [comment]
Probably the wrong description of a problem, `diagnose` is already in `shell` **and** `TS`.
But no matter what, only shell is executed.

There is missing in the `index.sh: IF USE_CONFIG -> run _CEE_RUNOPTS... configmgr -script ...`
