### ISSUE TITLE
Write a tool to clean up artifactory history

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#363]
Need to clean up branch/PR builds regularly to free up storage.

**Comment by MarkAckert** [comment]
Is this an ongoing challenge? Do we expect frequent cleanups with the transition to LF Infra?

**Comment by jackjia-ibm** [comment]
@MarkAckert since we may move to LF infra soon, we may not need this. So I didn't really start on this.

**Comment by MarkAckert** [comment]
OK, I'll put this at the bottom of the backlog, we can circle back after transition

**Comment by jackjia-ibm** [comment]
This is done.
