### ISSUE TITLE
bin/shell.ts: exec family is not able to run zwe

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-install-packaging#3636]
Exec family is:
* `execSync`
* `execOutSync`
* `exec`
* `execErrSync`
* `execOutErrSync`

Let's have a test file `test.js`:
```
import * as shell from './libs/shell'
shell.execOutSync('sh', '-c', './zwe -h');   
```
Then the output is:
```
$ configmgr -script ./test.js
trim: ./zwe 50: FSUM7351 not found
zwecli_load_parameters_definition: ./zwe 52: FSUM7351 not found
zwecli_load_parameters_default_value: ./zwe 55: FSUM7351 not found
zwecli_locate_parameter_definition: ./zwe 59: FSUM7351 not found
print_error_and_exit: ./zwe 61: FSUM7351 not found
lower_case: ./zwe 64: FSUM7351 not found
print_error_and_exit: ./zwe 73: FSUM7351 not found
zwecli_validate_parameters: ./zwe 98: FSUM7351 not found
zwecli_process_command: ./zwe 100: FSUM7351 not found
```
**Reason**
* [common.ts](https://github.com/zowe/zowe-install-packaging/blob/b31828d2ff9813c77efdd11b9ac394d4cef21d44/bin/libs/common.ts#L379) will set `ZWE_PRIVATE_CLI_LIBRARY_LOADED=true`
* `zwe` (when executed) then [skips](https://github.com/zowe/zowe-install-packaging/blob/b31828d2ff9813c77efdd11b9ac394d4cef21d44/bin/zwe#L30C32-L30C32) the loading of utilities/functions in `libs/index.sh`.
* That's why `trim` and others were not found

**Workaround**
Always import all shared libraries in `bin/zwe`:
~if [ -z "${ZWE_PRIVATE_CLI_LIBRARY_LOADED}" ]; then~
  . ${ZWE_zowe_runtimeDirectory}/bin/libs/index.sh
~fi~

**Comment by 1000TurquoisePogs** [comment]
makes sense. yup, zwe-ts confuses regular zwe

**Comment by Martin-Zeithaml** [comment]
This is a type of problem customers probably will not face.
Anyway the problem and solution is recorded here for future generations.
