### ISSUE TITLE
zowe-verify does not detect some processes running zowe code

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#364]
When examining processes that are running code in ZOWE_ROOT_DIR, the `zowe-verify.sh` script does not correctly un-wrap all the relevant output lines from the command.  This gives an incorrect list of zowe runtime processes.  

A minor improvement around line 90 fixes this.

**Comment by MarkAckert** [comment]
@John-A-Davies Was the fix submitted? Thanks

**Comment by John-A-Davies** [comment]
fixed at line 92 of zowe-verify.sh in master.
