### ISSUE TITLE
Files in wrong code page

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#365]
We have had various cases during install and runtime when files have been accessed in the wrong code page; files are presented in ASCII when EBCDIC is required or vice-versa.  This epic describes the issues, the factors that influence code page decisions, and how we should deliver our files to the customer system for their configuration.

Factors include:

- file tags; code page and auto-convert
- the actual encoding of the file
- the encoding expected by the programs that access the file; different programs may demand different encodings of the same file.
- whether the file is to be converted with iconv during install
- whether the file is to be converted automatically when it's accessed
- the AUTOCVT settings of the customer system;
- USS system settings and shell environment variable settings during install and runtime, such as:
  - AUTOCVT=ON
  - _CEE_RUNOPTS
  - _BPXK_AUTOCVT=ON
  - _BPXK_CCSIDS
  - _TAG_REDIR_OUT=txt

This epic also covers setting up test systems or users to demonstrate the faults encountered thus far, and verify that our solution rectifies the faults.

parent of #327

**Comment by John-A-Davies** [comment]
Addresses the issues in issue #142.

**Comment by John-A-Davies** [comment]
See also #739 for "expected" setting of AUTOCVT.

**Comment by dmitrynikolaev** [comment]
@John-A-Davies 
One more scenario to get the errors is to add alternative versions of shell tools to `PATH`, e.g. ported tools provided by `IZODA` or some others.

For example, if I have `PATH=/rsusr/ported/IBM/izoda/anaconda/bin/:$PATH`, I get the encoding issues.
Possible solution is to use full paths running the commands, e.g. `/bin/sed` instead of `sed`.

**Comment by stevenhorsman** [comment]
With the changes for node 12 in 1.9 we've done a bunch of updates to this. Closing this hanging epic - any problems should be created as issues.
