### ISSUE TITLE
Auto-detect z/OSMF keyring name

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#367]
The API ML script needs to know the name of the z/OSMF keyring if it's other than the default.

The install script can discover this from a couple of places; the bootstrap.properties file, and the IZUPRMxx PARMLIB member.

**Comment by John-A-Davies** [comment]
This file can also contain over-riding values:  `/var/zosmf/configuration/local_override.cfg`.

**Comment by MarkAckert** [comment]
Would automated detection be reliable - is there one and only one discover-able answer in `IZUPRMxx` or `/var/zosmf/configuration/local_override.cfg`? Would we set then set the zosmf keyring YAML fields to "auto_detect" by default? Thanks

**Comment by stevenhorsman** [comment]
keyring name not needed anymore
