### ISSUE TITLE
River doesn't have CIM set-up properly

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#374]
The delete job test is failing with:
{"status":"INTERNAL_SERVER_ERROR","message":"CIM connection failure"}
It looks like the CIM server isn't setup properly on river.

This has probably also resulted in river being completely filled with test jobs, which will impact performance and eventually stop the system working.

**Comment by MarkAckert** [comment]
@jackjia-ibm are you aware of this? Thanks

**Comment by jackjia-ibm** [comment]
@stevenhorsman I manually started CFZCIM job on river. Could you please verify if this works or not. If it works, I will continue investigate why it's not started on startup.

**Comment by jordanCain** [comment]
CIM is now working and jobs are able to be purged via z/OSMF. Previously ignored tests now being turned on https://github.com/zowe/jobs/pull/85
