### ISSUE TITLE
Ensure IZUSVR running zssServer has UPDATE access to BPX.SERVER and BPX.DAEMON.SAF

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#375]
For zssServer to be able to operate correctly the IZUSVR user ID should have UPDATE access to BPX.SERVER and BPX.DAEMON SAF resources.

We could try to do this at install time try to do this with the zowe-runtime-authorize.sh script, with a check beforehand as to whether IZUSVR already has access.  If so does the user running the install have permission to do this typically as it's a SAF check ?

We could also add this into the zowe-verify.sh

**Comment by John-A-Davies** [comment]
You’ll need this command for USS
```
# This should have already been set
extattr +p $ZOWE_ROOT_DIR/zlux-app-server/bin/zssServer
```
And these commands for RACF
```
/* Define security setup to permit IZUSVR to access BPX resources */ 
/* Activate and RACLIST the FACILITY class (probably already done)  */     
/* SETROPTS CLASSACT(FACILITY)                 */   
/* SETROPTS RACLIST(FACILITY)                    */   
/* Define the BPX facilities (maybe already done)
RDEFINE FACILITY BPX.SERVER UACC(NONE)
RDEFINE FACILITY BPX.DAEMON UACC(NONE)                              
  */                            
/* Permit IZUSVR to update the BPX facilties */
PERMIT BPX.SERVER CLASS(FACILITY) ID(IZUSVR) ACCESS(UPDATE)
PERMIT BPX.DAEMON CLASS(FACILITY) ID(IZUSVR) ACCESS(UPDATE)
/* Activate these changes */
SETROPTS RACLIST(FACILITY) REFRESH          
```

**Comment by MarkAckert** [comment]
This will miss the 1.0.1 cutoff. We also need comparable TSS/ACF2 commands, and support manual documentation.

**Comment by Joe-Winchester** [comment]
I've updated the docs to include the RACF steps needed in the section for manual installation of the APF server (https://github.com/zowe/docs-site/pull/400).  @John-A-Davies is looking to update the zowe-apf-server-install.sh script for RACF also.  I think both of these will make 1.0.0, so it'll be the updates for TSS and ACF/2 that will need to wait for 1.0.2 to be updated.
