### ISSUE TITLE
Show localized Zowe release date

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#377]
As requested by Frans Beyl, wants to show localized release date based on browser settings.

https://openmainframeproject.slack.com/archives/CC961JYMQ/p1550221769003400

**Comment by jackjia-ibm** [comment]
This is done.

**Comment by fbeyl** [comment]
Today website dates are no longer localized.

**Comment by fbeyl** [comment]
Today website dates are no longer localized.

**Comment by jackjia-ibm** [comment]
@fbeyl could you please make a screenshot on what it looks like on your side? And what was it look like before. Thanks.

**Comment by fbeyl** [comment]
I tried to have as much info on the screenshot as possible.



As you can see date is in US layout while system (Linux Mint 17.3 Rosa 
Mate) is set to Dutch/Flemish/Belgium. I think it might be related to 
the system settings.

On iphone the date is ok (in European layout).

Best regards,

Frans.

**Comment by jackjia-ibm** [comment]
@fbeyl I cannot see the screenshot, maybe it's been removed by GitHub? I know from GitHub website, when you making comment, you can drag/drop a file into the comment box.

**Comment by fbeyl** [comment]
![image](https://user-images.githubusercontent.com/42418931/54551622-ba491680-49ae-11e9-819a-4211f9855ae5.png)

**Comment by fbeyl** [comment]
![image](https://user-images.githubusercontent.com/42418931/54551666-ca60f600-49ae-11e9-861c-4ff5da3487d4.png)

**Comment by jackjia-ibm** [comment]
Thanks @fbeyl, I made a quick fix. Could you please check if it works for you?

**Comment by fbeyl** [comment]
No.

**Comment by fbeyl** [comment]
Tried Firefox and Chromium but no luck.

**Comment by jackjia-ibm** [comment]
A quick comment is Browser doesn't have really access to the system locale settings and for security concerns, it won't expose directly to the web pages. Browser has it's own locale settings. Could you please show what's your browser language settings?

**Comment by fbeyl** [comment]
That's it!
I changed language to Dutch and now date is ok.
![image](https://user-images.githubusercontent.com/42418931/54554960-0055a880-49b6-11e9-8702-6068ecf836e7.png)
Thanks!

**Comment by fbeyl** [comment]
Even with 'English' in top position the dates were US form? Had to set Dutch on top.
My mistake, sorry.
