### ISSUE TITLE
verify script can't detect STARTED task name of ZOWESVR

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#380]
The `zowe-verify.sh` script gave this error 
```
Check ZOWECEX1 is defined as STC to RACF and is assigned correct userid and group.
Warning: Started task ZOWECEX1 not assigned to the correct RACF user or group
```
Reason:  The installing user does not have authority to list all the entries in the STARTED class.
This would require ATTRIBUTES=AUDITOR.

**Comment by MarkAckert** [comment]
Would the user installing Zowe typically have this attribute, or is it restricted to security administrators?

**Comment by stevenhorsman** [comment]
As of 1.8 documentation state that zowe-verify is not update and from 1.9 it will be removed, so closing this issue
