### ISSUE TITLE
Problems with installation scripts when Rocket port of sed is sued

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-install-packaging#381]
Hello,

I am reporting a problem that @JakubSkrivanek has discovered during testing.

The templates such as `api-mediation/scripts/setup-apiml-certificates-template.sh` has been stored in ASCII even when his environment had no autoconversion settings on.

It was caused by `sed` because his path contained version from Rocket's Python instead of `/bin/sed`. The Rocket's version is storing output in ASCII. 

Jakub has followed the Zowe installation documentation and has installed all the prereqs including Python (https://zowe.github.io/docs-site/latest/user-guide/systemrequirements.html#overview).

The documentation says:

> To install Node.js on z/OS, follow the procedures at https://developer.ibm.com/node/sdk/ztp

Later, it there are notes:

> The following requirements for installing Node.js are NOT needed, so you can skip those configurations.
>   - Python, Make 4.1, or Perl
>   - C/C++ compiler

The notes does not forbid to install Python.

My suggestion is to use absolute path to `/bin/sed` in our installation script or the modify the PATH variable within the installation scripts to put `/bin` to the first place so we can be sure that z/OS versions of UNIX utilities are used all the time no matter what is set in the user profile.

**Comment by John-A-Davies** [comment]
Yes, we should tighten up the use of all commands like `sed` and `awk` by using full pathnames.
