### ISSUE TITLE
defaults should not be assumed as naming conventions may be different from site to site

### ISSUE THREAD

**Issue by fbeyl** [zowe/zowe-install-packaging#383]
by default zssServer assumes the server name is ZWESIS_STD
All naming be it stcname, username, groupname, port ... should be available for change defined in settingsfile or parmlib member

**Comment by John-A-Davies** [comment]
It's possible for z/OSMF to use non-default values for
IZUADMIN
IZUUSER
IZUSECAD
IZUGUEST
IZUSVR
which you can discover (among other settings) from IZUPRMxx, once you discover what xx is.

**Comment by 1000TurquoisePogs** [comment]
ZWESIS_STD is a default but customizable name - both at install time and during later configuration.
But, the general idea behind the customization is:

The configuration of Zowe is becoming more unified in release 1.8 in which most important variables are found within a file, `$INSTANCE_DIR/instance.env` which turn into environment variables that the components read. 

For backwards compatibility, with the app-server component we secondarily rely upon the contents of a server configuration JSON file. You can see one here: https://github.com/zowe/zowe-install-packaging/blob/master/files/zlux/config/zluxserver.json#L36 ... so `privilegedServerName` controls if ZWESIS_STD is used.
The location of this file on zowe pre-1.8 is `$ZOWE_ROOT_DIR/zlux-app-server/deploy/instance/ZLUX/serverConfig/zluxserver.json` but in 1.8+ it will be `$INSTANCE_DIR/workspace/app-server/serverConfig/server.json`

**Comment by fbeyl** [comment]
Nice, issue closed.
