### ISSUE TITLE
zowe-install-apf-server.sh fails to copy PROCLIB member

### ISSUE THREAD

**Issue by kiril-ibm** [zowe/zowe-install-packaging#384]
************************ Install step 'PROCLIB' start **************************
Check if USER.PROCLIB exists
Info:  dataset USER.PROCLIB exists
Copy PROCLIB member ZWESIS01 to USER.PROCLIB
Error:  PROCLIB member ZWESIS01 has not been copied to dataset USER.PROCLIB
cp: FSUM6258 cannot open file "//'USER.PROCLIB(ZWESIS01)'": EDC5061I An error occurred when attempting to define a file to the system.
************************ Install step 'PROCLIB' end ****************************

**Comment by dmitrynikolaev** [comment]
https://github.com/zowe/zss/issues/5

**Comment by dmitrynikolaev** [comment]
https://github.com/zowe/zowe-install-packaging/pull/387
