### ISSUE TITLE
OMP LPAR Research

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#386]
We have 3 potential LPARs becoming available for usage within the Zowe project. We need to research and define the following points in order to acquire/configure the LPARs:

* Machine specs (CPs, zIIPs, DASD, Memory, etc.)
* Dependent Software (e.g. ANT, Metal C Compiler, NodeJS) 
* Dependent Subsystems (e.g. RACF/TSS/ACF2, DB2, CICS)
* Any other consideration not listed above

**Comment by likepunk** [comment]
- Would these LPARs be 'native' z/OS or guest OS on z/VM? 

- Would Parallel Sysplex be part of this? If yes, should consider adding ICF?
 
- Would z/OSMF configured for Sysplex?
 
- Connectivity and I/O - OSA port(s), FICON channel(s), IC Links(assuming a single CEC)

- Performance monitoring tool (Omegamon for JAVA etc.)

**Comment by MarkAckert** [comment]
@hogstrom Hi Matt, do you have any information about the LPARs which may answer Alex's questions above?
