### ISSUE TITLE
ZWESLSTC slow startup after restart

### ISSUE THREAD

**Issue by rudatp** [zowe/zowe-install-packaging#3875]
After few restarts, within short time, the startup time of ZWESLSTC goes from minutes to hours.
Do I miss some option/necessary cleanup?

**Comment by 1000TurquoisePogs** [comment]
I haven't heard this before.
Can you post logs showing where time is taken?
v2.15.0, v2.16.0, and v2.17.0 all have enhancements for startup time.

**Comment by rudatp** [comment]
I must check with the customer if they agree to post their logs. If not, I will have to cut them a bit to hide customer related information.

**Comment by rudatp** [comment]
[ZOWESV.JOBLOG.D240626.zip](https://github.com/user-attachments/files/16016124/ZOWESV.JOBLOG.D240626.zip)

**Comment by 1000TurquoisePogs** [comment]
From the log it appears they have "zowe.useConfigmgr" in the YAML file set to `false`.
This is an extremely slow option and can easily explain the issue.
Try setting it to `true` instead.

**Comment by rudatp** [comment]
Much better, thank you!. Did 5 restarts, startup took only 3 minutes each time.
At some earlier version Configmgr was causing ZOWE startup to fail, so I set it to off and never enabled again.
The only "issue" with configmgr is this message at startup:
FSUM7422 node is not found
Node found in NODE_HOME
It seems harmless, but I don't get it with configmgr set to false.

**Comment by 1000TurquoisePogs** [comment]
Unrelated to original description, but we just merged a fix for 
FSUM7422 node is not found
Node found in NODE_HOME
So that will be in v2.18.1 and v3.1.0
Closing this as I believe complete.
