### ISSUE TITLE
ACF2 Scripts Do Not Work in USS

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#388]
ACF2 Commands in USS do not execute correctly; an ACF2 APAR is in development which will add the capability to run ACF2 commands from USS correctly. We will need to pre-req this APAR for ACF2 users in the Zowe documentation, and we will need to update scripts to reference the new functionality (should be of the form ' tsocmd acfuss \\"acf2_command_text\~with_tilda_delimiters\~for_compound_commands\\" '.

**Comment by Martin-Zeithaml** [comment]
Utility is [here](https://techdocs.broadcom.com/us/en/ca-mainframe-software/security/ca-acf2-for-z-os/16-0/reporting/utilities/acfunix-utility.html)

Some progress or findings are mentioned in [3362](https://github.com/zowe/zowe-install-packaging/issues/3362).
