### ISSUE TITLE
Add TSS Security Commands for ZSS Install Scripts

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#389]
Add and validate TSS security commands for ZSS. Validation may be performed on private infrastructure. Documentation should be updated to reflect the commands.

**Comment by hogstrom** [comment]
@MarkAckert is this something we should move to an active issue?

**Comment by stevenhorsman** [comment]
With the updates to ZWESECUR ACF2 and TSS equivalents are in the JCL
