### ISSUE TITLE
Allow install to specify and control PROCLIB to be used

### ISSUE THREAD

**Issue by nannanli** [zowe/zowe-install-packaging#40]
@BrandonJenkins14 commented on [Thu Aug 16 2018](https://github.com/zowe/docs-site/issues/27)

Allow the ability to override the PROCLIB where ZOESVR is placed. zoe-install.yaml should have a proclib variable, default to CALCULATE, with values such as SYS1.PROCLIB, USER.PROCLIB, and so forth so that an installer can exercise manual control.

@John-A-Davies   @JoeWinchester should both review this Issue and determine if it can be removed from docs-site repo. Doesn't seem to be doc-focused.

**Comment by nannanli** [comment]
@John-A-Davies Hi John, this issue was opened by Joe in the docs-site repo. However, this issue seems more like a development issue so I moved it to this repo. Can you take a look? Thanks!

**Comment by John-A-Davies** [comment]
Yes, this is mainly an install script task, so we should change the install script to accept an additional parameter, namely the target PROCLIB for the ZOWESVR PROC.  

However, we should not force the user to think too hard about this; they may have little idea of their preferred PROCLIB - they just want it to work straight out of the box.  So perhaps if the default is 'CALCULATE' then install will attempt to find a suitable location as before, but if they change 'CALCULATE' to 'USER.PROCLIB' then that's where it will go.
