### ISSUE TITLE
Trap ZOWE  log messages to alert

### ISSUE THREAD

**Issue by GilPen** [zowe/zowe-install-packaging#4000]
Hello

We use Tivoli System Automation and we would like to trap errors messages via TSA.

Is it possible to redirect errors instance ZOWE USS logs to zos syslog ? It could be trapped by TSA to generate an alert.

Other possibility is to send a WTO message when ZOWE encounters a sevgere alert.

Regards
Gilles

**Comment by Martin-Zeithaml** [comment]
Hi Giles,

there is a possibility to duplicate selected messages to z/OS syslog. You can achieve this by this [configuration setting](https://github.com/zowe/zowe-install-packaging/blob/f0e3b345ab153479173118b42cef434a0f842733/example-zowe.yaml#L381-L404). You can add messages there of your own choice.

**Comment by GilPen** [comment]
Hi 

Thank you very much for your answer. It's exactly what I need.

Regards
Gilles

**Comment by GilPen** [comment]
Hello 

And is it possible to use a generic like ZWEAM000* with a '*' ?

Regards
Gilles

**Comment by Martin-Zeithaml** [comment]
Hello, 

Based on the code and quick test, I am afraid the wildcards are not supported. You have to state all messages you would like to trap.
