### ISSUE TITLE
ZSS Copy Loadlib Error if STC Running

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#407]
`/scripts/zss/zowe-xmem-deploy-parmlib.sh` will fail if the ZSS STC is currently running, and the error is not particularly insightful:
```
PARMLIB - Error
Please correct errors and re-run the following scripts:
sh /u/users/ackertm/zowe/zowe-1.0.1/install/../scripts/zss/zowe-xmem-deploy-parmlib.sh /u/users/ackertm/zowe/zowe-1.0.1/install/../files/zss ACKERTM.ZOWE.PARMLIB ZWESIP00       
```
```
Info:  dataset ACKERTM.ZOWE.PARMLIB exists
Copying parmlib member ZWESIP00
cp: FSUM6259 target file "//'ACKERTM.ZOWE.PARMLIB(ZWESIP00)'": EDC5061I An error occurred when attempting to define a file to the system.
Error:  PARMLIB member ZWESIP00 has not been copied to dataset ACKERTM.ZOWE.PARMLIB
```

We should consider checking if the STC is running or the resources are locked as part of the ZSS install script, and provide better error output. This will primarily affect users performing an upgrade (irrelevant on clean install), and may be affected by installation improvement discussions.

**Comment by stevenhorsman** [comment]
These zss scripts are no longer used, the parmlibs and proclibs are written directly to data-sets, so this issue as is is no longer in the product
