### ISSUE TITLE
PSWI - z/OSMF Workflow: Input Variables Components 

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-install-packaging#4077]
When running the z/OSMF Workflow to install Zowe v3 and defining "main" variables you see this panel:
![image](https://github.com/user-attachments/assets/48a15ded-ab79-495b-83dd-1e5783dfcecd)

These components are not consistently referred to.  In some cases, "the" is present and in others it is not on the left and right hand side of the components description and information bubble.  One example:
* Enable API Catalog vs Enable **the** Discovery Service 

Usage of "the" should be consistent as well as capitalization of services. 

Most components say "Check this option to enable [**the**] <component>" except "Enable ZAAS" which says "Should the APIML ZAAS be enabled".   This message should be consistent. 

Lastly, each entry ends with a colon (`:`).  However, nothing follows the colon.  These should be removed.

**Comment by pavelzlatnik** [comment]
> Usage of "the" should be consistent as well as capitalization of services.
> 
> Most components say "Check this option to enable [**the**] " except "Enable ZAAS" which says "Should the APIML ZAAS be enabled". This message should be consistent.
> 
> Lastly, each entry ends with a colon (`:`). However, nothing follows the colon. These should be removed.

Message could be synchronized to be consistent.

A colon (`:`) can't be removed, this is going directly from z/osmf, not manageable within workflow source code.
