### ISSUE TITLE
PSW - z/OSMF Workflow: Gateway vs Cloud Gateway

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-install-packaging#4078]
![image](https://github.com/user-attachments/assets/917439b7-4072-4af8-87ca-59d980cd41a2)

While most of the z/OSMF Workflow steps refer to the "gateway", the previous screen references the "cloud gateway". For consistency in installing Zowe v3, should "Gateway" be used or "Cloud Gateway"?

**Comment by JoeNemo** [comment]
@jp669844  - There are several bugs noted by Dan and I don't know who is best to notify.  I think many of these are easy fixes to documentation and /or prompting.

**Comment by jp669844** [comment]
Hi Joe, we are already working on them. I marked them by PSWI label for easy tracking. And yes, many of them are quick fixes.
