### ISSUE TITLE
RACF JCL created in a Top Secret environment

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-install-packaging#4079]
**Describe the bug**

I attempt a PSWI installation of Zowe in a Top Secret environment. Jobs in the Deployments Checklist are generated that contain RACF commands.

**To Reproduce**

- I strictly follow the steps for a PSWI installation in sequence from the Zowe & IBM documentation.
- In "Defining new deployments" doc, you are instructed to "Submit Deployment Jobs"
- The job named IZUD01RA contains RACF commands. However, I am in a Top Secret environment, so that job will fail.
- I also assume that it is likely that a Top Secret customer will not know how to translate RACF commands to the required Top Secret commands.

**Expected behavior**

Any generated security commands should be Top Secret commands.

**Screenshots**

**Desktop (please complete the following information):**

z/OS 3.1
Windows 11
Chrome Version 130.0.6723.117

**Smartphone (please complete the following information):**

**Additional context**

**Comment by muzikovam** [comment]
Hi,
what HLQ did you put there for the SMP/E? If it was something non-existing then please specify some existing HLQ so the zOSMF doesn't want to create a new prefix definition in the catalog. Unfortunately those JCLs that are being created during the deployment are out of our touch and should be reported directly to IBM if you really wish to create new dataset prefix. Thank you.

**Comment by gejohnston** [comment]
I simply accepted the HLQ (ZWE) that comes from the Zowe PSWI. I would expect that defaults from the PSWI should work. The documentation that the user is directed to read never mentions reasons for renaming the datasets in the "configure deployment" step.

I realize that most of the z/osmf Software Management documentation is from IBM. However, if the Zowe PSWI contains a default HLQ (which a user may not have access to), some Zowe doc should inform users that they must change the HLQ to avoid generating a job that will always contain RACF commands.

**Comment by gejohnston** [comment]
Even if you change your HLQ from ZWE to your user name (in the “Configure Deployment - Data Sets” window), there are also “Source Data Set Name” entries in that same window. You cannot change the “Source Data Set Names” and they also begin with “ZWE.” Thus, your user ID must have READ access to ZWE. If you do not, the IZUD01UZ job fails with CC 0012 and an error like this:

```
1PAGE 0001     5695-DF175  DFSMSDSS 3.1 DATA SET SERVICES         2024.319 11:47
- RESTORE INDD(SYSUT1) -
   DATASET(INCLUDE( -
     ZWE.PSWI.AZWE003.ZFS -
   )) -
   RENAMEUNCONDITIONAL( -
     (ZWE.PSWI.AZWE003.ZFS, -
       PROD004.ZWE.V3PSWI.ZFS.#) -
   ) -
   
0ADR402E (001)-AUTH (28), AUTHORIZATION CHECK FAILED FOR DATA SET ZWE.PSWI.AZWE003.ZFS, ON VOLUME ZOS003, 4, IN CATALOG MASTERV.CATALOG
```

While the medium.com article https://medium.com/zowe/a-step-by-step-guide-to-deploying-zowe-with-a-z-osmf-pswi-f1b5be962a4d states "your user ID requires READ access to data set names with ZWE HLQ", I did not see any such direction in the formal Zowe doc.

The Zowe doc should direct users to change the target ZWE HLQ to their user ID (and why). The Zowe doc should also identify that READ access is still required for the ZWE HLQ (and why).

**Comment by muzikovam** [comment]
Hello Gene,
I checked our documentation and I found the information there.
Here is the one regarding the READ access to ZWE HLQ:
![image](https://github.com/user-attachments/assets/9daa8dd8-ff0f-44a3-a26f-9434d69a1405)
And here is where the main issue lies:
![image](https://github.com/user-attachments/assets/5e81100e-c8eb-4a72-acda-65486facda15)

So follow this documentation https://docs.zowe.org/stable/user-guide/install-zowe-pswi-deployment while deploying Zowe and it should be successful. If you would still like to change the doc you can open a new issue on the doc site https://github.com/zowe/docs-site

**Comment by gejohnston** [comment]
For the record, I diligently read all related documentation. The doc on prerequisites is very early in the documentation path. The ZWE READ access did not register with me at that time. It was many documents and many questions later before I encountered the panel where ZWE was listed in a read-only field on the screen. It would have been helpful to identify the READ access requirement at that time in the doc related to that panel

I also read the doc that states `For Data sets, change the target data set name prefix to the one that you want to use for your deployment.` For the uninitiated, simply stating "for deployment" does not clearly define how the dataset HLQ will be used and what permissions will be required. That information could possibly be placed in the tooltip help for this field on the panel.

Since documentation does exist for these items, I accept that we are closing this issue.
