### ISSUE TITLE
Enhance Security Subsystem Detection

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#408]
The current methodology for discovering security subsystem installation is by checking active jobs on the LPAR, and match against a whitelist of job names (RACF, TSS, ACF). This can run into two possible errors, though their prevalence is more pronounced on development LPARs 
* The jobname of the security subsystem may vary - i.e. TSS160 for Top Secret v16, as opposed to just TSS.
* In a PLEX, there may be a different security subsystem on an LPAR within the PLEX. In this case, the script may detect one of those subsystems rather than the one running on the current LPAR.

Proposed solution: Issue commands in USS via tsocmd and check output for active security subsystem. Security subsystems which are not installed will have RC 255, while the installed one should have rc <=8.

**Comment by Martin-Zeithaml** [comment]
There is a small utility [getesm](https://github.com/zowe/zowe-install-packaging/tree/v2.x/staging/bin#utilities), however it is working on LPAR only, no SYSPLEX scan.

**Comment by 1000TurquoisePogs** [comment]
How about we somehow default zowe.setup.security.product to a value found by `getesm`?
One way, maybe, would be to expose the logic of `getesm` in configmgr zos module, and then have defaults.yaml contain `product: ${{ zos.getesm() }}`

**Comment by Martin-Zeithaml** [comment]
I believe, we can close this issue:
* There is a [utility](https://github.com/zowe/zowe-install-packaging/tree/v2.x/staging/bin#utilities) for all zowe users
* There is a support for this utility in [`javascript`](https://github.com/zowe/zowe-common-c/blob/cf8c51d28bb606f0428c920db101e61518b2502b/c/qjszos.c#L170C16-L170C22)
