### ISSUE TITLE
PSWI - z/OSMF Workflow: Create configuration

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-install-packaging#4080]
When installing Zowe v3 via PSWI and running workflows, you get to a step "Create configuration":"
![image](https://github.com/user-attachments/assets/cc07f85c-4117-4ee6-816e-24caedcb9ea0)

Near the bottom there is an option of "Apply updates to:"
1. What update is being applied?  Does this mean the job header is applied? 
2. There is a checkbox selection but only 1 checkbox may be selected.  Should this be a dropdown instead?  Typically, checkboxes indicate one or more selections are permitted within a UI, but that is not the case here.

**Comment by MarkAckert** [comment]
These are baked in z/OSMF workflow steps when submitting jobs as part of workflows. We can't change anything present here. To your questions:

1. The job header is applied
2. A dropdown may have made more sense, but its out of our control
