### ISSUE TITLE
PSWI - z/OSMF Workflow

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-install-packaging#4081]
For Zowe v3 under Zowe configuration, there are two steps:
* Run the Zowe init
* Run the Zowe init security 

Found here: 
![image](https://github.com/user-attachments/assets/188d7e3b-2516-4452-873a-ec94d8e0618d)

However, this runs "zwe init ..." commands, not "Zowe init" so it seems the description is not accurate.

**Comment by MarkAckert** [comment]
Agree the description could be improved. Do you have an opinion on whether its better to call out the underlying tool, e.g. `Run zwe init`, or the function, e.g. `Run scripts for Zowe initialization`. I lean towards the latter...
