### ISSUE TITLE
PSWI - z/OSMF Workflows: ZWEV2.SZWEEXEC no created 

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-install-packaging#4083]
When running `zwe init mvs` in V3 I get the following messages:

```
>> Initialize Zowe custom data sets

Create data sets if they do not exist
Creating dkelosky.ZWEV2.CUST.PARMLIB
Creating dkelosky.ZWEV2.CUST.JCLLIB
Creating dkelosky.ZWEV2.SZWEAUTH
Creating dkelosky.ZWEV2.CUST.ZWESAPL

Copy dkelosky.ZWEV2.SZWESAMP(ZWESIP00) to dkelosky.ZWEV2.CUST.PARMLIB(ZWESIP00)
  * Exit code: 12
  * Output:
    exec 'dkelosky.ZWEV2.SZWEEXEC(ZWEMCOPY)' 'dkelosky.ZWEV2.SZWESAMP(ZWESIP00) dkelosky.ZWEV2.CUST.PARMLIB(ZWESIP00)'
    DATA SET DKELOSKY.ZWEV2.SZWEEXEC NOT IN CATALOG OR CATALOG CAN NOT BE ACCESSED
Error ZWEL0111E: Command aborts with error.
bash-4.3$ zwe init mvs -c '/u/users/dkelosky/zowe-smpe/zowe.yaml' --allow-overwrite
```

At what point should `DKELOSKY.ZWEV2.SZWEEXEC` be created since all of the other `DKELOSKY.ZWEV2.` data sets are created during `zwe init mvs` ?

**Comment by dkelosky** [comment]
It seems like the MVS prefix:
![image](https://github.com/user-attachments/assets/1502ed85-56a6-4bf8-9c29-44979222d218)

Should default to the the deployment data sets specified in during the "Configure Deployment":
![image](https://github.com/user-attachments/assets/da60f6d4-f8eb-498c-a582-0afffcfb5eba)

It says the prefix is where Zowe MVS data sets will be installed, but it doesn't mention that it references pre-existing data sets to use the REXX code in `...SZWEEXEC` for example.

**Comment by muzikovam** [comment]
You are right, the description is not the best. But we took it from example-zowe.yaml
![image](https://github.com/user-attachments/assets/0d91758b-f3aa-4b41-9cda-8fdd622dc340)
Do you reckon we should change it in the workflow? Because then we wouldn't be in sync with the example-zowe, I guess there should stay the original description because of the convenience build?

**Comment by dkelosky** [comment]
There are a few options I see:
* you could change the wording (but it puts burden on the user)
* you could add extra information into the z/OSMF workflow informational bubble to describe what is required 
* you could default `Zowe Setup MVS prefix` to the data set HLQ generated at deployment for `...SZWEXEC` which would be `DKELOSKY.PSWI.AZWE003.T` in my case.
