### ISSUE TITLE
PSWI - z/OSMF Workflow: ACF2 Command on RACF system

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-install-packaging#4086]
The notes in the z/OSMF workflow mention ACF2 commands specifically:
![image](https://github.com/user-attachments/assets/a3747bd0-e8db-41a3-9c97-38676f06da8c)

Is this actually ESM dependent?

**Comment by MarkAckert** [comment]
In addition, the ACF GENREQ URL is a dead link. It looks like this comment was intended for the previous `<step>` in the workflow xml, where an ACF GENREQ is run.

**Comment by pavelzlatnik** [comment]
> In addition, the ACF GENREQ URL is a dead link. It looks like this comment was intended for the previous `<step>` in the workflow xml, where an ACF GENREQ is run.

yes, comment should be for previous step. But anyway there is no reference to GENREQ anymore in doc, so I will remove the link

**Comment by pavelzlatnik** [comment]
after discussion with TI team, they provided new link with update, https://techdocs.broadcom.com/us/en/ca-mainframe-software/security/ca-acf2-for-z-os/16-0/administrating/digital-certificate-support/process-digital-certificates-with-acf2/genreq-subcommand.html

**Comment by JoeNemo** [comment]
@dkelosky @pavelzlatnik :   I think Pavel says this should be closed.   Do you agree, Dan?

**Comment by dkelosky** [comment]
I reviewed the PR - it probably makes sense to close this once the PR is merged.  Thank you!
