### ISSUE TITLE
ZWES0117E Not APF-authorized (4) message after IPL

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#409]
When you START the ZSS xmem server after IPL, it fails with this message

```
JOBNAME  ASCB    (ASID) TCB       MSGID     MSGTEXT                                                          
ZWESIS01 00FC3700(0053) 008F8588  ZWES0001I ZSS Cross-Memory Server starting, version is 1.0.3               
ZWESIS01 00FC3700(0053) 008F8588  ZWES0002I Input parameters at 0x6FE6:                                      
ZWESIS01 00FC3700(0053) 008F8588  ZWES0101I 00000000  0016D5C1 D4C57EE9 E6C5E2C9 E26DE2E3 |..NAME=ZWESIS_ST| 
ZWESIS01 00FC3700(0053) 008F8588  ZWES0101I 00000010  C46BD4C5 D47EF0F0                   |D,MEM=00|         
ZWESIS01 00FC3700(0053) 008F8588  ZWES0004I Server name is 'ZWESIS_STD      '                                
ZWESIS01 00FC3700(0053) 008F8588  ZWES0117E Not APF-authorized (4)                                           
ZWESIS01 00FC3700(0053) 008F8588  ZWES0011E ZSS Cross-Memory server not started, RC = 80                     
ZWESIS01 00FC3700(0053) 008F8588  ZWES0013E ZSS Cross-Memory Server terminated due to an error, status = 8   
```
This is because `scripts/zss/zowe-xmem-apf.sh` runs SETPROG which adds the LOADLIB to the dynamic APF list but this is temporary and does not survive across IPL.  

For the LOADLIB to be permanently APF-authorised, the PROGxx and IEAAPFxx parmlib members can be used.

**Comment by John-A-Davies** [comment]
You could maybe add the xxx.PARMLIB(LOADxx) to the api yaml file and add lines to it like
```
000070 APF ADD                                                                        
000071     DSNAME(ZOWE.ZIS.SZISLOAD)                            VOLUME(USER10)        
```
but it may be worth keeping that as a manual step for the sysprog, because otherwise the script needs access to xxx.PARMLIB(LOADxx) which they could reasonably refuse to grant.

**Comment by stevenhorsman** [comment]
@John-A-Davies - is this defect still valid after the updates to use ZWESECUR?

**Comment by John-A-Davies** [comment]
It's not a valid defect now.  The APF-auth of ZOWE.ZIS.SZISLOAD or the site's chosen library is a matter for them.
ZWESECUR is related to SAF products, which is independent of APF-auth.  

APF-auth was done before by scripts/zss/zowe-xmem-apf.sh but that's gone.  We no longer deliver scripts to perform APF-auth.
