### ISSUE TITLE
Fixing scenario where explorers appear to pickup incorrect hostname

### ISSUE THREAD

**Issue by armstrongibm** [zowe/zowe-install-packaging#41]
The install I believe uses `hostname -c`  to resolve the hostname to be used across Zowe, and this is then used across the explorers and is hard coded into their code.

In my system, `hostname -c`  was not actually resolving to the correct hostname. 

The result of this was when trying to load the explorers I would get a Not resolved error when the iframe URL's are wrong in the various explorers' index.html.

Changing them to be my correct hostname resolved the issue.

Would it be possible to shift the configuration of these explorers (which is currently one time, at install time) into a yaml configuration file, allowing users to easily reference ports, hostnames, and other important connectivity information in a central place? It also allows users to more easily manipulate the automatic configuration at install time.

**Comment by MarkAckert** [comment]
Hi, are you still experiencing this issue on current zowe installs? Do other hostname commands work on your machine, like `hostname -r`? Do you have multiple TCPIP stacks running your machine?

We could update configuration to allow manual entry of hostname, but I want to understand the environment where this issue may pop up, and if any other remediations are available.

**Comment by ianc-d** [comment]
Hi, we experience this issue. The hostname is set by the hosting provider so we cannot change that, but the DSN entry set by the provider does not use the same hostname configured on the z/OS system. 

So the hostname may be configured on z/OS as 'S003', but the DNS entry for the IP stack on that system may be EXTR6.DSN.DOMAIN.COM. 

Happy to put an IP address in somewhere, but can't work out where it needs to go.

**Comment by 1000TurquoisePogs** [comment]
This does not seem to be valid since use of zowe.externalDomains in v2. Reopen if you think otherwise.
