### ISSUE TITLE
Epic - Branching Rollout

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#412]
Enable teams to participate in the branching model.

(Goal for managing branches)
* Zowe CLI Shared Pipeline
** Tests are complicated
** Breakage is a risk
** 2-3 weeks to modify the library to support our use case
** Multiple NodeJS Pipelines?
** Manual approval of stages within the pipeline - review if this is appropriate for all repositories
*** What should be the right default?
*** How do approvals work with PRs? Should we ignore versioning?
** Interface/CLI driven deployment - support variable deployment targets
*** Definitely deploy to LF stuff - Artifactory or Nexus
*** Should it also support deployment to mvncentral (Nexus, strict) / public npmregistry (just npm)
**** Enhancement? Set up for it architecturally 
**** gradle release plugin / shadow/spring-boot library interaction?
*** We need to add a gradle project to the pipeline.
**** Assumptions about gradle projects? We can be opinionated for the first draft.
*** We should also consider sonar integration, OWASP dependency check - at least we should try to prepare for this in the shared library. 
**** We should either provide optional feature in the shared library,  or doc how to add a custom step. 

* zowe-install-packaging roll-out branches manually to create RCs. 
** zowe-install-test may need to branch as well
** zowe-promote-publish we can leave for now, wait for pipeline management
*** Should we migrate install-test into install-packaging? Install-test does a release along with install-packaging to keep everything in sync. Ditto promote-publish?

* Requirements for rolling out shared library
** Jenkins Pipeline
** You need to point to shared library
** You need test cases
** Deploy may vary - need to address differences. Multiple NodeJS Pipelines?
*** zLUX does not meet these requirements
**** How do we rollout to zLUX? Talk with Sean
*** zLUX only exception (10-12 subprojects)
*** Should we consider modification of the zlux repository structure as part of this effort.

* Timeline for rollout
** Early May release rollout target with the shared pipeline
** Extra time for zLUX team - need to discuss on the side and re-estimate their effort
** Manual branching for install-packaging to be completed by early April release.

===
Parent of https://github.com/zowe/zowe-install-packaging/issues/452
Parent of https://github.com/zowe/zowe-install-packaging/issues/453

**Comment by jackjia-ibm** [comment]
Updates:

All explorer repos and zowe-install-packaging are updated.

https://github.com/zowe/explorer-api-common is pending on a fix of https://github.com/zowe/jenkins-library/issues/9.

zlux test implementation: https://github.com/zowe/sample-angular-app/pull/20

**Comment by jackjia-ibm** [comment]
https://github.com/zowe/explorer-api-common is also migrated.
