### ISSUE TITLE
Epic - Enterprise Installer (SMP/E)

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#414]
### Initial install ###

Single FMID ZWE100 ( not IBM / Broadcomm / Rocket / other ISV owned prefix )
This is created by the Zowe community and made available on the Zowe.org web site.
**ISVs can redistribute this with additional terms for support and maintenance.** 

**The redistribute SMP/E is going to use the Zowe community ZWE100 FMID and customers cannot deliver PTFs, APARs on this in isolation from the Zowe community SMP/E build as this has upstream consequences for code overwrite by disparate channels**

**ISVs should not create their own SMP/E distribution.  If they do they cannot use the same FMID and they cannot use the USS location the community SMP/E installs into, e.g.  /usr/lpp/zowe/**

zowe.org will still distribute the zowe.pax file.  SMP/E is a wrapper of this pax build.
The SMP/E installer will target the install directory /usr/lpp/zowe/v.r.m

A symlink folder /usr/lpp/zowe/v1 will point to 

### Maintenance ###

**Monthly**

A Zowe convenience build is created monthly at the end of each iteration and packaged by the Zowe community as an SMPE/PFT.  The PTF numbering will be ZW0001, ZW0002, ...   
ISVs cannot create their own SMP/E PTFs to be installed on top of the base Zowe SMP/E.  The reason for this is that if independent customers create their own ISVs with their own numbering, e.g. UI0001 from IBM or CA0001 from Broadcomm, without each PTF having knowledge of the other PTFs a customer applying a PTF from one vendor will overwrite a PTF applied from another vendor.

Under EPL 2.0 terms an ISV using Zowe base for commercial extension must make available any change to base code to the community, so it is in the benefit of the community and the ISV for any fix to base Zowe to get into the zowe.org convenience build.  

**Patch**

A defect found in base code (such as a security vulnerability) that needs to be made available to customers mid iteration.

Zowe convenience builds are scheduled every 4 weeks and increment the v.r.m numbering.  For example 1.0.3 is superseded by 1.0.4 , 1.0.5 and so forth.  Because the next build's work in process is held in a staging branch it is possible mid iteration to create a build that contains just the master branch + some code fixes and deliver this as a fix numbering, e.g. 1.0.4.1.   This allows a .pax build and an SMP/E APAR to be created mid iteration.

This is reliant on the Zowe community CICD pipeline having automation and tooling to create SMP/E PTF and APAR releases.

APAR numbers must come from the community so that the PTF is aware of them.

**Emergency Fix**

A customer finds a problem mid iteration that must be fixed and delivered to that user as soon as it is available for testing and cannot wait for an SMP/E build to occur

This should only be done if the **Patch** option above is not sufficient.  A private Zowe.pax can be created from the pipeline with custom install instructions that overwrite code modules in the customer's Zowe.  If there is time for an SMP/E build to be created this is created from a branch in github

**Base build**

Zowe kernel and core.  

Zowe apps

![image](https://user-images.githubusercontent.com/35110159/59196340-4457e400-8b86-11e9-855d-372baec0f71e.png)

**Comment by hogstrom** [comment]
The following sentence should be emphatic:

> **ISVs do not/should/cannot(?) create their own SMP/E distribution.**

Redistribution of the package is allowed **without** modification.  Any changes to the packaging require the content packager to use their own:

- FMID
- Message prefixes
- Modified Zowe recommended install locations and recommendations must be modified to avoid conflicts
- other artifacts that have been assigned to the OMP by IBM must be redone to use the packager''s license

**Comment by hogstrom** [comment]
I started to make changes to the body although there is no change control.  Perhaps we move the statements to git in a file and point to it ?

**Comment by Joe-Winchester** [comment]
Superceded by #437
