### ISSUE TITLE
Epic - Configure at runtime instead of install time

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#415]
**Configure**

The zowe-install.yaml file should not contain runtime data such as ports, location of pre-reqs, or any other information only needed at runtime.  It should only contain information needed for the installer (such as the target path to install to)

Desire to bring up Zowe with a PARMLIB member. 
```
/S ZWESVR, PARM=CS
```
This would then pickup ZWEPRMCS.  The default parmlib will be ZWEPRM00

The PARMLIB member will contain key values, e.g.
```
JAVA_HOME=
NODE_HOME=

API-CATALOG-PORT=26000

API-GATEWAY-VERIFY-CERTIFICATES-OF-SERVICES=false
```
The values in the PARMLIB will be injected into the various places in the relevant files so that the ZWESVR instance that is brought up has been configured accordingly.

**Core**

There should be a core that contains the current zowe-1.0.2 pax - some of the "beta and sample" apps

**Comment by stevenhorsman** [comment]
Dup of #433
