### ISSUE TITLE
Consolidate / identify the number of address spaces used by ZOWESVR STC

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#416]
The number of address spaces used by the ZOWESVR started task is about 12.  
This story is to look at consolidating address spaces where possible,

**Comment by 1000TurquoisePogs** [comment]
Is there a better place to put this ticket? It's more architectural than install and packaging, isnt it?
Such as, identifying what the explorer nodejs servers require in an effort to have them exist within the zowe app server, reducing spaces by 3, if the purpose is similar enough to align.

**Comment by stevenhorsman** [comment]
I agree with Sean - this isn't an issue that we can fix in zowe-install-packaging and given there hasn't been an update in 11 months, I'm closing this. If it is still a burning problem, then it's probably one for the architecture call to discuss
