### ISSUE TITLE
Investigate OWASP ZAP

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#417]
Leverage OWASP ZAP for Security Testing of the Zowe Server code.

Points of interest:
* Running OWASP ZAP (persistent vs container?)
* Stable backend system running Zowe z/OS Code (Wait for bare metal?)
* Report results and format for presentation to community
* Periodicity of scan

**Comment by jackjia-ibm** [comment]
Duplicated of https://github.com/zowe/zowe-install-packaging/issues/721
