### ISSUE TITLE
Warn users when install is run on a host whose name can't be externally accessed

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#421]
Problem
If the value of ```hostname -c``` returns a value that can't be externally resolved, then problems occur at runtime with the desktop or API ML not being accessible, or else internal microservices can't be resolved

Soution
Check whether the ```hostname -c``` returns a value that can't be resolved
Short term put in a check to see if the hostname starts with S0W1. as that is the one used for ZD&T which seems to fail a fair amount as we are finding this mounted in a cloud/VM environment. 
Other solution could be to use a dig command, parse the output, and see if the hostname can be reached.
If the server looks like it's not accessible externally then warn the user and let them either press Y to accept it or else have them enter what they know the hostname is

File to update will be:
https://github.com/zowe/zowe-install-packaging/blob/master/scripts/zowe-init.sh

**Comment by Joe-Winchester** [comment]
Feedback from slack 
![image](https://user-images.githubusercontent.com/28100302/55328293-efac3480-5483-11e9-823d-bec511e7c029.png)

![image](https://user-images.githubusercontent.com/28100302/55328302-f89d0600-5483-11e9-9d17-00d816d08abf.png)

**Comment by John-A-Davies** [comment]
All you can do is use `ping`, `host` and `dig`.  If these all tally, then all is good, but if not, you have to ask the user to enter the external IP, which you can't verify from that host, so just warn the user that you can't verify the IP.
