### ISSUE TITLE
Set the executable bit on zowe-install-apf-server.sh

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#426]
Problem:
The /install/zowe-install-apf-server.sh file does not have the executable bit set
zowe-install-apf-server.yaml: cannot execute
Build 1.1.0

Solution:
Set the bit during the packaging process. 

![image](https://user-images.githubusercontent.com/28100302/55732545-13d3bc80-5a14-11e9-890e-07fdcd667c51.png)

**Comment by stevenhorsman** [comment]
that file has been removed now
