### ISSUE TITLE
zowe-verify.sh gives false negative if user can't read BPX.* SAF resources

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#429]
The expected output of this section is
```
Check SAF security settings are correct
Check IZUSVR has UPDATE access to BPX.SERVER and BPX.DAEMON
OK
```
but if the installing user running the script does not have the authority to list BPX, then it incorrectly reports that IZUSVR does not have access to them.

**Comment by stevenhorsman** [comment]
As of 1.8 documentation state that zowe-verify is not update and from 1.9 it will be removed, so closing this issue
