### ISSUE TITLE
Create SMP/E distributable for Zowe

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#437]
Epic to cover creation and distribution of SMP/E for Zowe

**Comment by stevenhorsman** [comment]
Current plan is to produce the 1.4 smpe alpha after the 1.4 convenience release, so this will be planned early after 1.4 GA

**Comment by stevenhorsman** [comment]
The SMPE alpha is finished. More work on the PTF process under #738
