### ISSUE TITLE
SMP/e install of cross memory server 

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#438]
The Zowe cross memory server is installed from zowe-install-apf-server.sh.  This works alongside zowe-install-apf-server.yaml that conatins installation configuration information.  The installer steps are doc'd at https://github.com/zowe/docs-site/blob/master/docs/user-guide/install-zos.md#installing-the-zowe-cross-memory-server-on-z-os.  

These include:
APF Authorized LOADLIBRARY and copies across the ZWESIS01 load library
PPT Entry
PARMLIB member 
PROCLIB member for ZWESIS01

**Comment by stevenhorsman** [comment]
Onno says this is done as part of the main path
