### ISSUE TITLE
Move config out of run script

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#446]
**As a** zowe user,  
**I want** to have my configurations specified in a properties file, outside of the read-only runtime directory
**so that** I can easily understand and manage my zowe instances.

*Details/notes*
Once we can modify the install scripts we have to move the properties out of run-zowe.sh because that will become read-only and into a /etc/zowe/v1/config.properties file.

After this story the zowe-install.yaml/install config options (we might want to refactor to command parameters) will only have details relating to install:
 - rootDir: Where the binaries are installed to - Defaults to `~/zowe-{ZOWE_VERSION}`
 - datasetPrefix - defaults to `{userid}.ZWE`
 - propertiesLocation - defaults to /etc/zowe/v1/config.properties

Regardless of which we choose we need to have this properties location included as a parameter into the zowe started task JCL, but allow it to be overwritten using something like /S ZWESVR, PRM='/u/stevenh/zowe.properties'
We will create a read-only version of the properties file in zowe install directories, which will be our template - with defaults that are currently in the zowe-install.yaml file + the zowe-profile entries

The install processing we then be:
- During install we check to see if the config file already exists:
    - If it doesn't we will copy the read-only template properties to the new file. If we don't have write access to the location then we can issue a warning, but fall back to pointing the properties file at the read-only template, so a user can still work with it.
       **Question** - how do we do this for SMP/E
    - If it does we need to be very carefully and migrate any new properties in, but not override any extender properties, or reset defaults #843 
- We inject this properties file as the default PRM into the started task JCL

During startup:
 - Follow the PRM in the started task and read in the properties into the shell right at the start, then follow the processing that run-zowe.sh currently takes.

**Question** - whilst we are waiting for all the services to be componentised do we start this and seed the content from the yaml, or does everything block this? Lack of completion on componentisation means this had to be started and complete in #845

Later we might decide to split the properties into global/site properties and instance, but we'll spin off a different work item for that.

- [x] Ensure all users of .zowe-profile are removed

#### Acceptance Criteria

*Given* A system with none of the default ports in use, or files taken
*When* I install zowe fresh and then start it
*Then* It comes up and everything works on the default ports without user modification

*Given* A previous install of Zowe and a copied version of the properties file with different ports
*When* I run zowe linked to the new properties file
*Then* It comes up and everything works as per the modification

**Comment by 1000TurquoisePogs** [comment]
> rootDir: Where the binaries are installed to - Defaults to ~/zowe-{ZOWE_VERSION}

That's the case today, but in the long run aren't we trying to get the binaries elsewhere, and have the writable files in the home dir instead?
I'm unsure what will work best for the largest audience, but ~/.zowe is pretty normal for modern unix, whereas ~/zowe-{ZOWE_VERSION} might make more sense for people who don't like "." folders

**Comment by stevenhorsman** [comment]
Hey Sean, I think there might be some confusion - probably at my end. For the convenience build (which we assume is for the purpose of evaluation/testing) I've not heard any suggestions to move the install to a new location and if they are a normal user then they probably can't install outside of their home directory anyway? This build also defaults the user-dir folder (which we'll possible rename to instance dir or something else) into ~/zowe-user-dir. In future when we have user specific preferences I would expect them to go into .zowe without asking the user which, as you said, seems to be standard.
For proper enterprise install I'd expect the default binary location to be /usr/lpp/zowe or similar, the default 'instance-dir' to be /global/zowe or similar and the user preferences to stay in .zowe. Does this match your thinking, or do we need more discussion/a work item to cover changes?

**Comment by stevenhorsman** [comment]
Design discussed and initially agreed: https://ibm.box.com/s/hhe243vyobgc1jctcfqogw0i4syri6hl

**Comment by kathysychan** [comment]
@stevenhorsman Could you please give me access to the Box folder with the design or place it in a location that others can easily access?

**Comment by stevenhorsman** [comment]
@kathysychan - sorry I seem to have problems with the sharing setting resetting - does this one work https://ibm.box.com/s/x8nhi7e293oyzqnm5vaof4lzwfkuow9l ?
