### ISSUE TITLE
zowe-check-prereq inaccurately complains about space

### ISSUE THREAD

**Issue by patbossman** [zowe/zowe-install-packaging#447]
Hello,
I consistently get this error on the pre-check.  

Check enough free space is available in target z/OS USS HFS install folder
Info: Existing directory to be checked is /rw/dex/ptf2/zowe/1.0.0
Error: NO adequate-sized area(s) found
size of largest free area in /rw/dex/ptf2/zowe/1.0.0 is 19654 KB
minimum required is 650 MB

Here is my df -P within this directory:
$ df -P .
Filesystem          512-blocks        Used  Available  Capacity Mounted on     
DVOP02.UTEC492.DEXRW.V1.ZFS 1848000     1808692      39308       98% /rw/dex

The zFS is allocated as 750,250 cylinders.  It just extends when it needs more space.  I am up to 1500 cylinders.  I believe I can get to 4GB before I will run into issues because this is not SMS managed.  I'm not sure the right way to determine the space available, but I know the current check is prone to false positives.

**Comment by John-A-Davies** [comment]
Yes, the script needs to use something like `zfsadm aggrinfo -long` for zFS systems.

Some work required to do this.

**Comment by stevenhorsman** [comment]
From 1.9 dev build onwards we've streamlined and simplified zowe-check-prereqs.sh, so the code that caused this issue has been removed
