### ISSUE TITLE
zowe-install.sh fails when home directory is root.

### ISSUE THREAD

**Issue by patbossman** [zowe/zowe-install-packaging#449]
One of our new user installs is installing into /var/zowe.  So they are using an id that has UID 0 and a home directory of root (/).

The pre-check runs OK, then the install fails attempting to reference //.zowe_profile.  I have seen similar behavior with the double slash before using root.  (screen capture below).

One solution is to update the script to handle setting root correctly.
Do we want a user with root home directory doing the install?  If yes, ... fix the script...
If no, then I think we'd want the pre-check to determine if the users home directory maps to root and error/warn, and have the install script do the same.

![zowe-root-home-dir-fail](https://user-images.githubusercontent.com/36768713/56756479-d71bfb00-675f-11e9-93bd-141bb2ca78b0.gif)

**Comment by John-A-Davies** [comment]
Is the home directory /root?  Does it exist already with .profile files and so on?

I would discourage the use of root for install.  It's difficult for the scripts to get right, and if something goes wrong you are root and can trash the system.

**Comment by patbossman** [comment]
The userid has uid 0 and home directory of /.  For our environment, we agreed the userid should be changed to use a home directory for the userid, and this was done.  We agreed that install using id with home directory of / is a bad idea.  So we ought to flag and fail gracefully if the userid home directory is / in the pre-check script and the install scripts.  I don't know the commands to do this, but I will look into this.

**Comment by FreekCornelis** [comment]
My personal home directory as set in my OMVS segment is also '/' and I had the same problem.
I was able to bypass it by simply setting HOME to /var:
export HOME=/var
before invoking the install script.
Although I have seen cases for other software where this was not enough, it worked here.

Perhaps check the home directory and if  it is /, prompt the user to enter another directory?

**Comment by stevenhorsman** [comment]
Now (in 1.8+) .zowe_profile, which was stored in the home directory has been removed, either this problem has slightly changed, or (hopefully) been removed

**Comment by MarkAckert** [comment]
Closing as stale.
