### ISSUE TITLE
Create check/hook to prevent merges into `master` from branches other than `rc` and `staging`.

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#452]
`master` branch should be further protected from merge/pull request. No pull request should be created from feature/bug fix branches into `master`.

**Comment by jackjia-ibm** [comment]
Possible solution: https://github.com/bertrand-benoit/pyGitHook

**Comment by 1000TurquoisePogs** [comment]
Branch protection and audits now protect against this.
