### ISSUE TITLE
Build zowe from "cupids staging" branch on river

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#461]
**Outcome**

Cupids-staging will contain an smpe.sh file that creates the SMP/e artifacts.
The output of this story will be that there is a build script that can be run that will create the SMP/e artifacts in a zowe-smpe-v.r.m.pax file, as well as the original zowe-v.r.m.pax file.

The output of completed story this will then drive install testing and also allow a tech preview distribution to be shared with customers

**Comment by stevenhorsman** [comment]
@Joe-Winchester - what is the difference between this and #481?

**Comment by stevenhorsman** [comment]
Dup of #481
