### ISSUE TITLE
Hostname returned shortname causing ZOWE_IPADDRESS error when zowe 1.2.0 installing script is called from Java

### ISSUE THREAD

**Issue by kathysychan** [zowe/zowe-install-packaging#465]
When installing zowe1.2.0-RC1 from script, ZOWE_IPADDRESS cannot be detected (resulting in ZOWE_IPADDRES set to null in .zowe_profile). This caused problem further down in the zowe-install.sh and cause zowe server to not start. This problem does not exist in the nightly build 38 when we installed it using the same script yesterday morning. Now we found this problem with nightly build 43 and in zowe-1.2.0-RC1. 

Note that this problem only occurs when installing zowe using script but not when I call zowe-install.sh directly. 

This is the console output when installing using script:

14:46:28  Locating Environment Variables...
14:46:28    Liberty bootstrap.properties found  at /var/zosmf/configuration/servers/zosmfServer/
14:46:28  ** Adding line: export ZOWE_ZOSMF_PATH=/var/zosmf/configuration/servers/zosmfServer/ to ~/.zowe_profile  **
14:46:28  ZOWE_ZOSMF_PORT value of 443 will be used
14:46:28     java version 18 found at  /usr/lpp/java/J8.0_64
14:46:28  ** Adding line: export ZOWE_JAVA_HOME=/usr/lpp/java/J8.0_64 to ~/.zowe_profile  **
14:46:28    NODE_HOME value of /usr/lpp/IBM/cnj/IBM/node-v6.14.4-os390-s390x will be validated
14:46:28  ZOWE_EXPLORER_HOST value of tvt4188.svl.ibm.com will be used
14:46:49  Usage: grep [-E|-F] [-BNbcilnqsvx] [-A|-P|-C num] [-S string] [-W option[,option]...] [-e pattern] ... [-f patternfile] ... [pattern] [file ...]
14:46:49  error : dig could not find IP of hostname tvt4188.svl.ibm.com
14:46:49      Please enter the ZOWE_IPADDRESS of this system
14:46:49  warning : ping tvt4188.svl.ibm.com did not match stated IP address 
14:46:49  ** Adding line: export ZOWE_IPADDRESS= to ~/.zowe_profile  **
14:46:49  Reading install variables from zowe-install.sh
14:46:50    ZOWE_ZOSMF_USERID not specified:  Defaulting to IZUSVR

With problem like this, the install should fail or exit with non-zero value but in this case, it just proceed as normal and I only found out later when I the zowe server did not start properly.

**Comment by kathysychan** [comment]
@John-A-Davies For your awareness.

@kiril-ibm Kiril will add more debugging traces and add to this issue to try to narrow down the cause (which was just introduced in the last day or so).

**Comment by kathysychan** [comment]
@jackjia-ibm For your awareness of this problem in RC1.

**Comment by John-A-Davies** [comment]
The script worked for me just now
```
IBMUSER:/u/ibmuser/scripts>zowe-init.sh
Locating Environment Variables...
ZOWE_ZOSMF_PATH value of /var/zosmf/configuration/servers/zosmfServer/ will be used
ZOWE_ZOSMF_PORT value of 443 will be used
  ZOWE_JAVA_HOME value of /usr/lpp/java/J8.0_64 will be validated
   java version 18 found at  /usr/lpp/java/J8.0_64
  NODE_HOME value of /usr/lpp/IBM/cnj/IBM/node-v6.14.4-os390-s390x will be validated
ZOWE_EXPLORER_HOST value of tvt4188.svl.ibm.com will be used
OK resolved tvt4188.svl.ibm.com to 9.30.241.209
ZOWE_IPADDRESS value of 9.30.241.209 will be used
IBMUSER:/u/ibmuser/scripts>
```

**Comment by John-A-Davies** [comment]
The problem arises because `hostname` works differently when the shell is run from java instead of at the command line.  The automated pipeline uses java to run its scripts.

For scripts run under java on this TVT system, all forms of `hostname` return the short hostname, TVT4188, which is acceptable, but the script then proceeds to run `dig hostname` to confirm that the IP address is real.  The `dig` command needs the full hostname, so this test fails.

Workaround:  set the IP ADDRESS in `.zowe_profile`

Solution:  Add 2 extra lines to `zowe-init.sh` to derive the full hostname.  Must check that this works on all types of system.  The `hostname` command is used only in that script.  

Note:  The `host` command may also return the wrong result under java.

**Comment by vvvlc** [comment]
I have one partially related comment 
It looks that `ping` command is not always available however `oping` is always available.

```
/a/vlcvi01/zowe/builds/zowe-1.3.0/install/..//scripts/zowe-init.sh: line 278: ping: command not found
warning : ping USILCA31.lvn.broadcom.net did not match stated IP address 10.175.84.31
ZOWE_IPADDRESS value of 10.175.84.31 will be used
```

Could we use `oping` instead of `ping` ?

> Note: ping is a synonym for the oping command in the z/OS UNIX shell. ping command syntax is the same as that for the oping command.
(https://www.ibm.com/support/libraryserver/BOOKS/F1A1C211/3.6?DT=20021018141156)

**Comment by kathysychan** [comment]
@John-A-Davies I don't believe I should be the owner of this issue. Please reassign. 

I believe you have been sending some fixes for @kiril-ibm  to try and would have the latest update on this.

**Comment by John-A-Davies** [comment]
@jackjia-ibm Is `oping` available in java in the build pipeline?

**Comment by jackjia-ibm** [comment]
@John-A-Davies yes oping exists in both zD&T and the coming marist environment.

**Comment by stevenhorsman** [comment]
No update on the outcome of this for > 6months, so assuming the test worked. Note that zowe-init.sh uses oping now

**Comment by kathysychan** [comment]
Yeah, OK to close.
