### ISSUE TITLE
"which" not found in nodeCluster.sh when starting Zowesvr

### ISSUE THREAD

**Issue by kathysychan** [zowe/zowe-install-packaging#466]
After I started Zowe 1.2.0 RC1, I got this error in the ZOWESVR started task:

which: ./nodeCluster.sh 137: FSUM7351 not found 

Despite that error, ZOWESVR seems to start OK.

**Comment by rjmaomao** [comment]
I have the same issue on my Zowe 1.2.0. This error message is always at the bottom of the joblog.

**Comment by yann-59** [comment]
I have the same issue on my Zowe 1.3.0 in the joblog.

**Comment by vvvlc** [comment]
i think this is solved in 1.4.0

**Comment by 1000TurquoisePogs** [comment]
`type` is now used instead of `which`, in 1.4.0 as vvvlc said.
