### ISSUE TITLE
zowe-verify.sh not looking for node in correct location

### ISSUE THREAD

**Issue by CForrest97** [zowe/zowe-install-packaging#470]
Problem
-
A customer found a bug when running zowe-verify.sh. 
Their .zowe_profile contains 
`NODE_HOME=/rdtplex1/usr/lpp/node/node-v6.14.4-os390-s390x`
However the verify script logs
```
Check Node is installed and working
Warning: node not found in your path ... searching standard location
ls: FSUM6785 File or directory "/usr/lpp/IBM/cnj/IBM/node-*" is not found
Error: node not found 
```

Environment details of system the bug was found on
-
Version: 1.0.1

More details are to be expected on 7th May

**Comment by John-A-Davies** [comment]
`zowe-verify.sh` should check NODE_HOME.

**Comment by John-A-Davies** [comment]
Fixed in `zowe-verify.sh` in staging.
