### ISSUE TITLE
zowe install plugin not found

### ISSUE THREAD

**Issue by yugeshpothuru** [zowe/zowe-install-packaging#471]
Getting error as  "Error: cannot read plugin ID, install aborted." 

from the log dataset.
<zowe-explorer-ui-configure.sh>                         
  Configuring Explorer UI: JES ...                      
    - plugin ID   :                                     
    - plugin name :                                     
    - port        : 8546                                
    - base uri    :                                     
  Error: cannot read plugin ID, install aborted.

**Comment by yugeshpothuru** [comment]
I tried executing the command that retrieves these values directly and it is failing

IBMUSER:/S0W1/var/zowe/zowerun/v1.1.0/jes_explorer: >EXPLORER_PLUGIN_ID=$(/var/z
owe/zowerun/nodejs/bin/node -e "process.stdout.write(require('./package.json').c
onfig.pluginId)")                                                               
[1] + Done(137) EXPLORER_PLUGIN_ID=$(/var/zowe/zowerun/nodejs/bin/node -e "proce
ss.stdout.write(require('./package.json').config.pluginId)")                    
  67174471      Killed  -sh

**Comment by jackjia-ibm** [comment]
@yugeshpothuru We noticed maybe 2 possibilities which node fails to start.

* the node.js version is a trial version which has expired,
* ICSF is not properly configured but is required for node.js (https://zowe.github.io/docs-site/latest/user-guide/install-nodejs-zos.html#hardware-and-software-requirements). We have an improvement on notifying ICSF configuration at https://github.com/zowe/zowe-install-packaging/issues/434.

Will need some debugging/testing to determine what really caused the issue. If you need more help on this, please let us know.

**Comment by yugeshpothuru** [comment]
Hi Jack,

I have used IBM's  "IBM SDK for Node.js – z/OS Trial"  "(File name: ibm-6.17.0.0-trial-node-v6.17.0-os390-s390x.pax.Z, Size: 189 MB, SHA-256)" 

We were able to run the pre check zowe successfully and was able to issue node --version which returned. V6.17

**Comment by jackjia-ibm** [comment]
Hi, I downloaded node.js v6.17.0 and tried on my machine, and seems working. So we may need to debug more.

If you run the below command on your machine, will it show `hello` as output?

```
IBMUSER:/S0W1/var/zowe/zowerun/v1.1.0/jes_explorer: > /var/zowe/zowerun/nodejs/bin/node -e "console.log('hello')"
```

Or this command should give you a result of `org.zowe.explorer-jes`:

```
IBMUSER:/S0W1/var/zowe/zowerun/v1.1.0/jes_explorer: > /var/zowe/zowerun/nodejs/bin/node -e "process.stdout.write(require('./package.json').config.pluginId)"
```

**Comment by yugeshpothuru** [comment]
hi jackjia, I will check on these commands and share the ouputs

**Comment by yugeshpothuru** [comment]
Hi jackjia,

I'm receiving the below error when I try to run the commands:

/var/zowe/zowerun/nodejs/bin/node -e "process.stdout.write(require('./package.json').config.pluginId)"
IEA995I SYMPTOM DUMP OUTPUT 017                                 
  USER COMPLETION CODE=4087 REASON CODE=00000000                
 TIME=22.05.37  SEQ=01021  CPU=0000  ASID=0062                  
 PSW AT TIME OF ERROR  078D1401   9FB657CE  ILC 2  INTC 0D      
   ACTIVE LOAD MODULE           ADDRESS=1F95C000  OFFSET=002097C
   NAME=CELQLIB                                                 
   DATA AT PSW  1FB657C8 - 00181610  0A0DEBEC  4C1C0096         
   AR/GR 0: 00000000/00000000_84000000   1: 00000000/00000000_84000FF7
         2: 00000000/00000048_00000000   3: 00000000/00000048_00106EA0
         4: 00000000/00000048_082E6DD8   5: 00000000/00000000_1FB67328
         6: 00000000/00000048_00108398   7: 00000000/00000048_00103E28
         8: 00000000/00000048_00106E68   9: 00000000/00000048_082E96F8
         A: 00000000/00000048_082E7DD7   B: 00000000/00000048_00108398
         C: 00000000/00000048_082E8DD6   D: 00000000/00000000_2009D6A8
         E: 00000000/00000000_1FB62962   F: 04564F72/00000048_00000000
 END OF SYMPTOM DUMP                                            
IEF450I IBMUSER5 STEP1 - ABEND=S000 U4087 REASON=00000000       

IBMUSER:/S0W1/var/zowe/zowerun/v1.1.0/jes_explorer: >/var/zowe/zowerun/nodejs/bi
n/node -e "console.log('hello')"                                                
[1] + Done(137) /var/zowe/zowerun/nodejs/bin/node -e "console.log('hello')"     
  50397237      Killed  /var/zowe/zowerun/nodejs/bin/node                       
IBMUSER:/S0W1/var/zowe/zowerun/v1.1.0/jes_explorer: >

**Comment by yugeshpothuru** [comment]
+CEE3797I LANGUAGE ENVIRONMENT HAS DYNAMICALLY CREATED A DUMP.          
+CEE0374C CONDITION=CEE3561S TOKEN=00030DE9 59C3C5C5 00000000_00000001  
348                                                                     
          WHILE RUNNING PROGRAM v8::internal:: WHICH STARTS AT 213EF710 
          AT THE TIME OF INTERRUPT                                      
          PSW     00000001 80000000 00000000_1FB782B2                   
          GPR 0-2 BBBBBBBB_BBBBBBBB BBBBBBBB_BBBBBBBB BBBBBBBB_BBBBBBBB 
          GPR 3-5 BBBBBBBB_BBBBBBBB 00000048_082F3E18 00000000_1FB77B98 
          GPR 6-8 00000000_1FB77670 00000000_1FB782B2 00000048_00108398 
          GPR 9-B 00000048_082F4C10 00000048_082F4C10 00000048_082F4C30 
          GPR C-E 00000000_00000007 00000000_2009D6A8 00000000_00000000 
          GPR F   00000000_1FE6D6C4                                     
+CEE0374C CONDITION=CEE5702S TOKEN=00031646 59C3C5C5 00000000_00000000  
349                                                                     
          WHILE RUNNING PROGRAM CEEHSGLT WHICH STARTS AT 1FB78248       
          AT THE TIME OF INTERRUPT                                      
          PSW     00000001 80000000 00000000_1FB782B2                   
          GPR 0-2 BBBBBBBB_BBBBBBBB BBBBBBBB_BBBBBBBB BBBBBBBB_BBBBBBBB 
          GPR 3-5 BBBBBBBB_BBBBBBBB 00000048_082EB238 00000000_1FB77B98 
          GPR 6-8 00000000_1FB77670 00000000_1FB782B2 00000048_00108398 
          GPR 9-B 00000048_082EBF50 00000000_00000000 00000048_08B4B810 
          GPR C-E 00000048_00108398 00000000_2009D6A8 00000048_08B4B810 
          GPR F   00000000_00000000                                     
          GPR F   00000000_00000000                                    
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME=IBMUSER3, ASID=0068.       
BPXP011I THREAD 1FE6200000000002, IN PROCESS 33620105, WAS 351         
TERMINATED DUE TO A PTHREAD QUIESCE OF TYPE 2.                         
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME=IBMUSER3, ASID=0068.       
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME=IBMUSER3, ASID=0068.       
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME=IBMUSER3, ASID=0068.       
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME=IBMUSER3, ASID=0068.       
IEA989I SLIP TRAP ID=X422 MATCHED.  JOBNAME/ASID NOT AVAILABLE.        
BPXP011I THREAD 1FE7780000000005, IN PROCESS 33620105, WAS 357         
TERMINATED DUE TO A PTHREAD QUIESCE OF TYPE 2.                         
BPXP011I THREAD 1FE7080000000003, IN PROCESS 33620105, WAS 359         
TERMINATED DUE TO A PTHREAD QUIESCE OF TYPE 2.                         
BPXP011I THREAD 1FE6180000000001, IN PROCESS 33620105, WAS 358         
TERMINATED DUE TO A PTHREAD QUIESCE OF TYPE 2.                         
BPXP011I THREAD 1FE7700000000004, IN PROCESS 33620105, WAS 360         
TERMINATED DUE TO A PTHREAD QUIESCE OF TYPE 2.                         
BPXP011I THREAD 1FE7880000000006, IN PROCESS 33620105, WAS 361         
TERMINATED DUE TO A PTHREAD QUIESCE OF TYPE 2.                         
IEA995I SYMPTOM DUMP OUTPUT 362                                        
  USER COMPLETION CODE=4087 REASON CODE=00000000                       
 TIME=00.19.29  SEQ=00593  CPU=0000  ASID=0068                         
 PSW AT TIME OF ERROR  078D1401   9FB657CE  ILC 2  INTC 0D             
   ACTIVE LOAD MODULE           ADDRESS=1F95C000  OFFSET=002097CE      
   NAME=CELQLIB                                                        
   DATA AT PSW  1FB657C8 - 00181610  0A0DEBEC  4C1C0096                
   AR/GR 0: 00000000/00000000_84000000   1: 00000000/00000000_84000FF7 
         2: 00000000/00000048_00000000   3: 00000000/00000048_00106EA0 
         4: 00000000/00000048_082E6DD8   5: 00000000/00000000_1FB67328 
         6: 00000000/00000048_00108398   7: 00000000/00000048_00103E28 
         8: 00000000/00000048_00106E68   9: 00000000/00000048_082E96F8 
         A: 00000000/00000048_082E7DD7   B: 00000000/00000048_00108398 
         C: 00000000/00000048_082E8DD6   D: 00000000/00000000_2009D6A8 
         E: 00000000/00000000_1FB62962   F: 04564F72/00000048_00000000 
 END OF SYMPTOM DUMP                                                   
IEF450I IBMUSER3 STEP1 - ABEND=S000 U4087 REASON=00000000              
+CSQX251I %CSQ8 CSQXSTRL Listener started, TRPTYPE=TCP INDISP=QMGR     
+CSQX218E %CSQ8 CSQXLSTT Listener not started - unable to bind, 365

**Comment by yugeshpothuru** [comment]
closing this issue

**Comment by yugeshpothuru** [comment]
closed the issue as it got resolved.
