### ISSUE TITLE
Verify If Zowe Pre-reqs Are Installed Properly on Marist College Build Environment

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#477]
Before we create a snapshot of the LPAR(VM), we need to make sure we have all pre-reqs in place.

TSS/ACF2 installation task is tracked separately.

**Comment by John-A-Davies** [comment]
If `zowe-install-packaging\install\zowe-check-prereqs.sh` does not give you all you need, please let me know.

**Comment by John-A-Davies** [comment]
@jackjia-ibm Please advise if `zowe-check-prereqs.sh` does not give you all you need.

**Comment by jackjia-ibm** [comment]
The original purpose of this issue had been fulfilled. We can track improvements of `zowe-check-prereqs.sh` separately.
