### ISSUE TITLE
Create Snapshot for LPAR from Marist College Build Environment

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#478]
After we have all the pre-reqs installed and verified, also the pre-set users created, we can contact Marist College support to create a snapshot.

This task relies on https://github.com/zowe/zowe-install-packaging/issues/476 and https://github.com/zowe/zowe-install-packaging/issues/477.

**Comment by supmi01** [comment]
@jackjia-ibm Jack what is Marist College Build Environment ?

**Comment by jackjia-ibm** [comment]
@supmi01 It's a new smoke testing environment for Zowe on real hardware.

**Comment by jackjia-ibm** [comment]
This has been done and we have monthly backup in place.
