### ISSUE TITLE
Build Pipeline to create AZWE001.pax.Z on river

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#481]
1. Put the BLD.#.JCL(BUILD) and related /var/bld files from Onno's work into git source control
? Should this be new repo or part of zowe-install-packaging

2. Create a pipeline to use these on river.zowe.org to package the zowe-1.1.0 build and output back in to artifactory

**Input**
Zowe-1.1.0.pax and CLI.zip from libs-release-local/org/zowe/1.1.0/ in artifactory
Also need JCL and shell scripts from SCM.

**Pipeline Steps**
1. SCP the pax and zip file and shell scripts into USS on river
2. Move the JCL and REXX into a data set on river.  ?  Do we use brightside to upload or scp or ocopy ?
2a.  Check codepages are correct as JCL is stored in ASCII in github and needs to be EBCDIC on river
3. Inject the right variables into smpe.input that points to the location of the zowe.pax, cli.pax
4. Execute smpe.sh from unix shell passing in output HLQ,  output zFS folder,  smpe.input location
5. Wait until shell script finished.  ~10 minutes.
(Can we upload directly from river on Z or do we need to upload back into unix before step 6)
6. Upload AZWE001.pax.Z and AZWE001.readme.txt from zFS to artifactory into artifactory libs-snapshot-local/org/zowe/smpe/1.1.0/buildNoTimeStamp

**Jenkins job**
Create a new job to run the pipeline.  
? Under what conditions ?   Not every pull request because of CPU overhead.  ? Should we run overnight after zowe-install-test runs ?  Can it be done manually by whom ?

**Comment by Joe-Winchester** [comment]
This is the BUILD JCL showing how Onno drives the smpe.sh script
```
//$SMPE    JOB CLASS=A,MSGCLASS=A,MSGLEVEL=(1,1),NOTIFY=&SYSUID        
/*JOBPARM SYSAFF=M094                                                    
//*                                                                    
//* test smpe.sh  
//*                                                                      
//EXPORT SYMLIST=(DEBUG,VRM,ROOT,HLQ)                            
//SET DEBUG='-d' '' or -d'  
//SET DEBUG=''  '' or -d'  
//*                                                                      
//SET VRM='001'          
//SET ROOT='/var/bld'       
//SET HLQ='BLD.ZOWE'         
//*                                                                      
//SMPE     EXEC PGM=BPXBATCH,REGION=0M,COND=(4,LT)                      
//STDOUT   DD SYSOUT=*                          
//STDERR   DD SYSOUT=*                           
//STDPARM  DD *,SYMBOLS=JCLONLY         
  SH &ROOT/smpe.sh &DEBUG                       
  -a &ROOT/_alter.sh         
  -h &HLQ                                    
  -i &ROOT/downloads/ZWE110.INPUT          
  -r &ROOT                                 
  -v &VRM                 
2>&1                                                               
//*  
```

**Comment by stevenhorsman** [comment]
Most of this pipeline is fixed, but until we get a confirmed working SMPE build leave this open.

**Comment by stevenhorsman** [comment]
Current plan is to produce the 1.4 smpe alpha after the 1.4 convenience release, so this will be planned early after 1.4 GA
