### ISSUE TITLE
SMP/E package has no REJECT or RESTORE jobs

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#487]
JCL is not provided in the package for jobs to REJECT or RESTORE the SYSMODs.

**Comment by OnnoVdT** [comment]
Sample jobs to LIST, REJECT,RECEIVE,APPLY,ACCEPT, and RESTORE SYSMODs will be added in the next code drop.

**Comment by John-A-Davies** [comment]
The same applies to the PTF; the `readme.htm` contains RECEIVE and APPLY but needs REJECT and RESTORE to be added.
