### ISSUE TITLE
pax FSUMF073 user not authorized to restore extended attribute "a"/"p"

### ISSUE THREAD

**Issue by admattingly** [zowe/zowe-install-packaging#5]
At two points in the Zowe install script, pax attempts to set 'a' and/or 'p' bits on executables.  The user running the install requires READ access to BPX.FILEATTR.APF and BPX.FILEATTR.PROGCTL profiles in the FACILITY class for this to be allowed.  Without these permissions, the install reports errors for these two pax commands:

+ echo Unpax /u/zowe/zowe/zowe-0.9.0/install/..//files/ZLUX.pax
+ 1>> /u/zowe/zowe/zowe-0.9.0/install/..//log/2018-08-20-12-17-16.log
+ **pax -r -px -f /u/zowe/zowe/zowe-0.9.0/install/..//files/ZLUX.pax**
pax: FSUMF073 zlux-example-server/bin/zssServer: user not authorized to restore extended attribute "a"
...
+ echo Unpax of /u/zowe/zowe/zowe-0.9.0/./files/atlas-wlp-package-0.0.3.pax into /u/zowe/zowe/0.9.0/explorer-server
+ 1>> /u/zowe/zowe/zowe-0.9.0/install/..//log/2018-08-20-12-17-16.log
+ **pax -rf /u/zowe/zowe/zowe-0.9.0/./files/atlas-wlp-package-0.0.3.pax -ppx**
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzadrm: user not authorized to restore extended attribute "a"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzadrm: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzafsm: user not authorized to restore extended attribute "a"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzafsm: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzachk: user not authorized to restore extended attribute "a"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzachk: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzangl: user not authorized to restore extended attribute "a"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzangl: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzsafm: user not authorized to restore extended attribute "a"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzsafm: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzscfm: user not authorized to restore extended attribute "a"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzscfm: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzsrv: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzsufm: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/libzNativeServices.so: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/bboacall: user not authorized to restore extended attribute "a"
pax: FSUMF073 wlp/lib/native/zos/s390x/bboacall: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/batchManagerZos: user not authorized to restore extended attribute "p"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzcsl: user not authorized to restore extended attribute "a"
pax: FSUMF073 wlp/lib/native/zos/s390x/bbgzcsl: user not authorized to restore extended attribute "p"

The install script should check that the current user has these privileges before proceeding.  The z/OSMF started task user (usually IZUSVR) does not need these privileges under normal circumstances.  Accordingly, to support the notion of a super-user running the install, it would be desirable, at the end of the install process, to change ownership of all the installed files to the user/group of the user that will run the Zowe started task, so that this user doesn't need these elevated privileges.  To make this practical, the install script should read the started task user and group from the yaml, and issue a 'chown' at the end of the process, if the started task user is not the current user.

**Comment by Joe-Winchester** [comment]
@admattingly - During our install we try to pick up errors when users can't set permissions or set bits correctly, and we write a file "zowe-runtime-authorize.sh" that has the idea that this file can be passed to a super user who can run this later on (being distinct from the install itself). If we did want to do a check I have questions 1) How do we do this check from a USS shell script to check privileges ?  2) If we do change ownership of all of the installed files is this for every file in the Liberty server or just the ones in /s90x that have the extended attribute ?  Also - how in USS is it possible for us to check the user/group of the user that runs the Zowe started task ?  Tks

**Comment by Joe-Winchester** [comment]
@admattingly - a lot of changes have been made for 1.0.0 and we no longer set APF bits on any of the programs we install into USS.  I'm going to close this defect but please comment or re-open it if you run into any more issues installing Zowe.  Also note that in the /install folder we have a zowe-check-prereqs.sh script that will check that the user doing the install has sufficient priviledges to do the install, as well as system pre-reqs so things should be a lot cleaner.
