### ISSUE TITLE
zowe-check-prereq.sh parsing error in checking user auth

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#512]
Check user has the basic auth to list the resources

Error: Unexpected response to RACF LISTUSER command
ICH30002I NOT AUTHORIZED TO LIST IZUSVR            
 
The script does a ‘tsocmd lu izusvr 2>/dev/null | head -1’ and if NOT AUTHORIZED TO LIST is output then it should echo ‘Info:  User IZUSVR is defined but you are not authorized to list it Warning: IZUADMIN, IZUGUEST and IZUUNGRP will not be checked as a result’ 

![image](https://user-images.githubusercontent.com/35110159/59189491-0d77d300-8b72-11e9-9e1f-810d393ccd52.png)

The script outputs the ICH30002I message yet does not select the correct message in the CASE/ESAC.

![image](https://user-images.githubusercontent.com/35110159/59189588-5760b900-8b72-11e9-9a2d-5da8ee4f25b7.png)

If I do this same command via ISHELL I get ‘ICH30002I NOT AUTHORIZED TO LIST IZUSVR’ output as per the batch invoked zowe-check-prereqs.sh so it appears that the script is not parsing correctly.

**Comment by John-A-Davies** [comment]
I tried this with my work-in-progress version, with userid DAVIESJ, who is NOT AUTHORIZED TO LIST IZUSVR, and it worked for me.  I will create a PR that includes this version soon, so it can be re-tested.

**Comment by John-A-Davies** [comment]
PR is #728

**Comment by stevenhorsman** [comment]
From 1.9 dev build onwards we've streamlined and simplified zowe-check-prereqs.sh, so the code that caused this issue has been removed
