### ISSUE TITLE
Creating JCL job to set up security config

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#518]
Replace the script creating security config with JCL. Onno recommends using a z/OS MF workflow for this eventually

Onno's recommendation is that that customers won't be happy with the 'hidden' nature of the security config set up in the script, and there will need to be more parameters supplied. It is also something that a typically zowe installer may not have permission to do, so having a JCL job to run it is something that customers are more familiar with.  This work was done in the staging/cupids branch and is in https://github.com/zowe/zowe-install-packaging/blob/stagings/cupids/files/templates/ZWESECUR.jcl

We need to update the SMPE packaging build to make sure the JCL is included in it.
This setup also only needs to be done on the first install (or if the config changes), not every update.
This issue requires a doc update and the pipeline needs changing to reflect this.

This item should cover the work to diverge from the IZU user and group to create our own Zowe ones, so need to decide these names

**Comment by OnnoVdT** [comment]
The core (RACF) is delivered with pull request https://github.com/zowe/zowe-install-packaging/pull/800. It still needs to be reviewed by somebody with TSS and ACF2 knowledge to fill in the missing parts.

**Comment by OnnoVdT** [comment]
reassigned to @John-A-Davies as he's doing updates to the sample members.

**Comment by John-A-Davies** [comment]
We should probably also have a corresponding un-install JCL job, to remove all the Zowe SAF objects that ZWESECUR creates.

**Comment by John-A-Davies** [comment]
@kathysychan  FYI the updated ZWESECUR.jcl file is available in repo `zwesecur`.

**Comment by kathysychan** [comment]
I see that ZWESECUR.jcl is in the scripts/templates directory of a Zowe install. Would Zowe team be providing a script (may be in the scripts/utils folder) to call that (or any) JCL?

**Comment by John-A-Davies** [comment]
Yes, that's #848.

**Comment by OnnoVdT** [comment]
I created https://github.com/zowe/zowe-install-packaging/issues/974 for the removal of security definitions.

**Comment by 1000TurquoisePogs** [comment]
Completed in v2 and refined into ESM specific scripts more recently (v2.17.0?)
