### ISSUE TITLE
Create SAMPLIB entries for the PROCLIB/PARMLIB in the install

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#519]
1. Add a PDS prefix to the zowe-install.yaml.  During `zowe-install.sh -I `Create/Check if existing one for the ZWESIS01 load library and another one for the samplib.  #740 

2. During smpe receive make sure that these data sets are also created/verified and that the result of an smp/e install is the same as the end of 1.  #748 

3. Create a `/scripts/utils/zowe-install-proc.sh` that does JES concatenation path updates #766 

Doc all of the above and allow a transition phase

Create a /scripts/utils/zowe-install-xmem.sh that shares logic with the ZOWESVR promote script

4. Remove the install step that does the auto-create of the PROCLIB and tidy up code #863 

zssCross MemoryServerName=ZWESIS_STD updates ZWESISTC and this is moved to the doc

The user: section logic will be in the ZWESECUR JCL.

zoweUser
userstssFacilityOwner=
stcUser
stcUserUid
stcGroup

**Comment by Joe-Winchester** [comment]
Writing a spec for this at: https://github.com/zowe/zowe-install-packaging/wiki/Spec-for-MVS-artifacts---git-issue-519

**Comment by John-A-Davies** [comment]
A note on un-install via SMP/E.  

When you run RESTORE, remember to undo the actions that APPLY performed with its pre-install and post-install scripts.

**Comment by Joe-Winchester** [comment]
@John-A-Davies - for our SMP/E where do the pre and post-install scripts live ?  Do we put anything in them ?

**Comment by John-A-Davies** [comment]
@Joe-Winchester Yes, it's file `smpe\pax\USS\ZWESHPAX.sh` in `zowe-install-packaging` and this ends up in RELFILE 4:  `ZOE.ZOWE.AZWE001.F4(ZWESHPAX)`.

**Comment by OnnoVdT** [comment]
Actually, ZWESHPAX is the SMP/E-driven install script that unpaxes the data in the RELFILEs. 
Pre-install scripts would be the SMPE sample members SZWESAMP(ZWE1->8*)
Post-install would be zowe-configure.sh in USS and whatever config scripts we put in MVS, like SZWEAMP(ZWESECUR) for security setup.

**Comment by OnnoVdT** [comment]
For item 4 of this issue (create customized MVS samples), see https://github.com/zowe/zowe-install-packaging/blob/stagings/cupids/scripts/zowe-configure-jcllib.sh zowe-configure-parmlib.sh zowe-configure-proclib.sh
