### ISSUE TITLE
zowe-verify.sh wrongly gives Error: Job ZWESIS01 is not running as a started task

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#538]
The search pattern at line 450 doesn't catch the required line, hence the error.

This was fixed before but the fix has been lost.  It's a 1-line change.

**Comment by stevenhorsman** [comment]
As of 1.8 documentation state that zowe-verify is not update and from 1.9 it will be removed, so closing this issue
