### ISSUE TITLE
Create new content on zowe.org downloads page for getting access to the smpe pax

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#545]
Needs to be clear which docs are relevant for which installer.

**Comment by Joe-Winchester** [comment]
The page https://github.com/zowe/docs-site/blob/zowe-smpe/docs/user-guide/install-zowe-smpe.md#allocate-file-system-to-hold-the-download-package is being authored to mirror the format of a program directory.
