### ISSUE TITLE
Remove CRASTART dependency from smpe-packaging build

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#547]
CRASTART is a proprietary part of RSE, so I don't think we can use it in the Open source pipeline. It also only works with uppercase directory names, which isn't compatibly with the pipeline as river has all its space mounted at zaas1, not ZAAS1

**Comment by John-A-Davies** [comment]
### Problem:

CRASTART is a vehicle to start TSO from within USS in such a way that you can run authorized programs.  CRASTART can start any program with the required DDs, and that's how we use it, we start GIMZIP (not TSO, that is how IDz uses it)

GIMZIP is an authorised program, so you need an authorised environment to run it.  The USS-based build needs to run and verify the result of GIMZIP, which means waiting for it to be done.  For these reasons we opted to start off with CRASTART, as it offers a solution for all these requirements.  
JCL offers a simple solution for APF and DDs, but not the waiting and verification.

### Proposal:

The existing install-SMPE-PAX.sh script runs GIMUNZIP (also authorised) by submitting a JCL job, polling until it’s finished, and checking the return code.  So we can do exactly the same for GIMZIP in the SMP/E packaging step and avoid CRASTART completely.

**Comment by Joe-Winchester** [comment]
@John-A-Davies - can you close this issue so it's no longer open, which means it is no longer on the zenhub board.  This will move it from the Backlog column in https://github.com/zowe/zowe-install-packaging/issues/547#workspaces/zowe-install-packaging-5c7e80581157be532ce67ea9/board?milestones=19-09-16%201.5%232019-09-16&filterLogic=any&repos=144592776,144595426,186826146,143049506&showPipelineDescriptions=false.   Tks

**Comment by John-A-Davies** [comment]
Closed by https://github.com/zowe/zowe-smpe-packaging/pull/27
