### ISSUE TITLE
private keys have wrong wrong access attributes

### ISSUE THREAD

**Issue by vvvlc** [zowe/zowe-install-packaging#571]
private keys are accessible by anyone
 * `runtime_dir/api-mediation/keystore/local_ca/localca.keystore.p12` should have `600`
 * `runtime_dir/api-mediation/keystore/localhost/localhost.keystore.*` should have `600`
![image](https://user-images.githubusercontent.com/15854496/61814524-8c864980-ae48-11e9-9307-655f12804dd3.png)

**Comment by stevenhorsman** [comment]
After further conversation we think the follow is the best plan to address this:
1) adding group param in to `zowe-install.yaml`,
2) create zoweruntime_directory
3) change group of zoweruntime_directory to group specified in `zowe-install.yaml`
4) install zowe
5) remove read permission for others everywhere (edited) 

regarding execute permission I would removeit for others,  and I would keep in for folder and executable files only (owner and group), but I don't have to do it now
we need to remove write permission for others in  zoweruntime_directory/script folder
