### ISSUE TITLE
Implement new naming scheme for ZOWESVR started tasks

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#582]
Revise the STC naming scheme as follows;

In the YAML template file, you will now see

    install:prefix 
    install:instance

which will appear like this

    install:
      rootDir=~/zowe/{ZOWE_VERSION}
      prefix=ZOWE
      instance=1

Together, these tags define a prefix for Zowe address space STC names associated with 
USS processes. Each component has its own STC name according to the following format:

    pfxNss

where:
• pfx - prefix that contains up to four characters, for example, ZOWE.
• N   - Zowe instance number or letter

• ss - a component identifier that consists of 2 characters:

• AG - API ML Gateway
• AD - API ML Discovery Service
• AC - API ML Catalog
• EJ - Explorer API Jobs
• ED - Explorer API Data Sets
• UD - Explorer UI Data Sets
• UJ - Explorer UI Jobs
• UU - Explorer UI USS
• DT - Zowe Desktop Application Server
• SV - Master STC that spawns the others

**Comment by Joe-Winchester** [comment]
I like this a lot as it reduces the current 3 letter prefix to classify address spaces into 2.  @vvvlc - are you happy that the instance number gets moved from the end to the middle, so ZOWEAAG1 and ZOWEADS1 now would become ZOWE1AG and ZOWE1AD ?   The reason is that it is easier in SDSF to do a PRE ZOWE1* (or PRE ZOWE2*).  Eventually we may move from ZOWE to ZWE which would give us another letter at the end for duplicate address spaces

**Comment by John-A-Davies** [comment]
I agree.  

Also note that to keep all the STC names unique for one instance of ZOWE, the jobname in the START command in `zowe-start-template.sh` must be 7 or fewer characters.  This is because MVS appends a digit to the sibling job spawned from the master server job, for example ZOWE1SV, giving ZOWE1SV2.  The other job names are fine, they can have 8 characters.

**Comment by vvvlc** [comment]
I think the instance number in @plavjanik original post (https://github.com/zowe/zowe-install-packaging/issues/385#issuecomment-489555612) was meant for additional instances from HA perspective.  Eg:

one gateway and discovery services in non HA mode would have these jobnames
* ZOWEAGW1
* ZOWEADS1

while in HA mode where we have many instances of same services would result in
* ZOWEAGW1
* ZOWEAGW2
* ZOWEADS1
* ZOWEADS2

Although I love ZOWE prefix I would rather reserve trailing number for HA instances and squeeze ZOWE prefix to ZWEx

ie
pfxNsssM, where
 * pfx - is a use defined zowe prefix eg ZWE
 * N - is overall zowe instance number or character
 * sss - is service name
 * M - is service instance within Zowe

HA Joe's zowe and  non HA Vitek's zowe running on one LPAR 
* Joe's jobs
  * ZWEJAGW1
  * ZWEJAGW2
  * ZWEJADS1
  * ZWEJADS2
* Vitek's jobs
  * ZWEVAGW1
  * ZWEVADS1

**Comment by John-A-Davies** [comment]
My scheme with instance=2 gives
```
ZOWE2AC  STEP1             STC44234
ZOWE2AD  STEP1             STC44229
ZOWE2AG  STEP1             STC44218
ZOWE2DT  STEP1             STC44230
ZOWE2DT  STEP1             STC44241
ZOWE2DT  STEP1             STC44232
ZOWE2DT  STEP1             STC44235
ZOWE2DT  STEP1             STC44371
ZOWE2DT  STEP1             STC44245
ZOWE2DT  STEP1             STC44217
ZOWE2DT  STEP1             STC44242
ZOWE2ED  STEP1             STC44238
ZOWE2EJ  STEP1             STC44233
ZOWE2EJ  STEP1             STC44244
ZOWE2SV  ZOWE2SV  ZOWESTEP STC44372
ZOWE2SV2 STEP1             STC44243
ZOWE2UD  STEP1             STC44237
ZOWE2UU  STEP1             STC44239
```
The jobname on the START command is ZOWE2SV (STC44244), and JES adds a suffix of '2' (not because it's the same as the instance number) to the jobname of STC44243.  The PS display shows 
```
ZOWE2AC  java -Xms16m -Xmx512m -Dibm.serversocket
ZOWE2AD  java -Xms32m -Xmx256m -Xquickstart -Dibm
ZOWE2AG  java -Xms32m -Xmx256m -Xquickstart -Dibm
ZOWE2DT  /bin/sh /u/tstradm/zowe/1.4.0/zlux-app-s
ZOWE2DT  tee /u/tstradm/zowe/1.4.0/zlux-app-serve
ZOWE2DT  /ZOS203/usr/lpp/IBM/cnj/v8r0/IBM/node-v8
ZOWE2DT  tee /u/tstradm/zowe/1.4.0/zlux-app-serve
ZOWE2DT  node --harmony zluxCluster.js --config=.
ZOWE2DT  /ZOS203/usr/lpp/IBM/cnj/v8r0/IBM/node-v8
ZOWE2DT  ./zssServer ../deploy/instance/ZLUX/serv
ZOWE2DT  /bin/sh ./nodeCluster.sh --allowInvalidT
ZOWE2ED  java -Xms16m -Xmx512m -Dibm.serversocket
ZOWE2EJ  java -Xms16m -Xmx512m -Dibm.serversocket
ZOWE2EJ  /usr/lpp/IBM/cnj/v8r0/IBM/node-latest-os
ZOWE2SV  BPXBATSL                                
ZOWE2SV2 /bin/sh /u/tstradm/zowe/1.4.0/scripts/in
ZOWE2UD  /usr/lpp/IBM/cnj/v8r0/IBM/node-latest-os
ZOWE2UU  /usr/lpp/IBM/cnj/v8r0/IBM/node-latest-os
```

I don't know where High Availability comes into this.  I've only ever seen one extra job being started, and that was during penetration testing.  Is this explained by the normal, automatic behaviour of nodeCluster, and does it apply to the other Zowe STCs?

**Comment by vvvlc** [comment]
High Availability will come in future, today all services except for nodeCluster run in single instance mode, therefore they should end with '1'.
Once we move to HA we will be running multiple instances of same service on same host then other numbers will come into play.

Btw you are using a bit different naming convention than proposed  in  https://github.com/zowe/zowe-install-packaging/issues/385#issuecomment-489555612
eg 
 * ZOWE2AG -> ZOWE2GW  (GW - API Gateway)
 * ZOWE2DT -> ZOWE2DS    (Zowe Application Server)

**Comment by John-A-Davies** [comment]
@vvvlc Yes, @Joe-Winchester and I chose this scheme, keeping all suffixes neatly to 2 letters.  

For these jobs, their jobnames 
```
ZOWE2SV  ZOWE2SV  ZOWESTEP STC44372
ZOWE2SV2 STEP1             STC44243
```
come from the JOBNAME on the START command, and I think JES will always try to append '2' to the second one if there's room, so if you had 
```
JOBNAME=ZWE2SV1  
```
then I think the other job would be automatically given the name
```
ZWE2SV12
```
Do those jobs participate in the HA scheme?

**Comment by vvvlc** [comment]
What I realized thanks to  @John-A-Davies  that `ZOWEDS1` is not handled correctly

here is what I get in our environment (I added new lines to separate components)
```sh
VLCVI01@USILCA31:~ # ssh ca32 'ps -A -o jobname,pid,ppid,args' | grep ZOWE
JOBNAME         PID       PPID ARGS
========== ======== ========== ============================
ZOWESI0P   33948017          1 ZWESIS01
ZOWESVRP     393597          1 BPXBATSL
ZOWESVRP   17170815          1 /bin/sh /C/zowe/installed/scripts/internal/run-zowe.sh

ZOWEAAC1   50725250          1 java -Xms16m -Xmx512m -Dibm.serversocket.recover=true -Dfile.encoding=UTF-8 -D
ZOWEADS1   17170820          1 java -Xms32m -Xmx256m -Xquickstart -Dibm.serversocket.recover=true -Dfile.enco
ZOWEAGW1   17170821          1 java -Xms32m -Xmx256m -Xquickstart -Dibm.serversocket.recover=true -Dfile.enco

ZOWEEAJ1   67502470          1 java -Xms16m -Xmx512m -Dibm.serversocket.recover=true -Dfile.encoding=UTF-8 -D
ZOWEEAD1   17170826          1 java -Xms16m -Xmx512m -Dibm.serversocket.recover=true -Dfile.encoding=UTF-8 -D

ZOWEEUJ1   33948043          1 /C/ibmnode/node-v6.14.4-os390-s390x/bin/node /C/zowe/installed/jes_explorer/se
ZOWEEUD1   33948044          1 /C/ibmnode/node-v6.14.4-os390-s390x/bin/node /C/zowe/installed/mvs_explorer/se
ZOWEEUU1   33948046          1 /C/ibmnode/node-v6.14.4-os390-s390x/bin/node /C/zowe/installed/uss_explorer/se

ZOWED1       393601   17170815 /bin/sh ./nodeCluster.sh --allowInvalidTLSProxy=true
ZOWEDS1    33948039     393601 node --harmony zluxCluster.js --config=../deploy/instance/ZLUX/serverConfig/zl
ZOWED1       393609     393601 tee /C/zowe/installed/zlux-app-server/log/nodeServer-2019-08-04-02-05.log
ZOWEDS1    33948045   33948039 /C/ibmnode/node-v6.14.4-os390-s390x/bin/node --harmony /C/zowe/installed/zlux-
ZOWEDS1      393615   33948039 /C/ibmnode/node-v6.14.4-os390-s390x/bin/node --harmony /C/zowe/installed/zlux-
ZOWEDS1      393616   33948045 /bin/sh /C/zowe/installed/zlux-app-server/bin/zssServer.sh
ZOWESZ1    67502483     393616 ./zssServer ../deploy/instance/ZLUX/serverConfig/zluxserver.json
ZOWEDS1      393620     393616 tee /C/zowe/installed/zlux-app-server/log/zssServer-2019-08-04-02-06.log
```

likely I would move 
```
no change<- ZOWED1       393601   17170815 /bin/sh ./nodeCluster.sh --allowInvalidTLSProxy=true
no change<- ZOWEDS1    33948039     393601 node --harmony zluxCluster.js --config=../deploy/instance/ZLUX/serverConfig/zl
no change<- ZOWED1       393609     393601 tee /C/zowe/installed/zlux-app-server/log/nodeServer-2019-08-04-02-05.log
ZOWEDS2  <- ZOWEDS1    33948045   33948039 /C/ibmnode/node-v6.14.4-os390-s390x/bin/node --harmony /C/zowe/installed/zlux-
ZOWEDS3  <- ZOWEDS1      393615   33948039 /C/ibmnode/node-v6.14.4-os390-s390x/bin/node --harmony /C/zowe/installed/zlux-
ZOWED1   <- ZOWEDS1      393616   33948045 /bin/sh /C/zowe/installed/zlux-app-server/bin/zssServer.sh
no change<- ZOWESZ1    67502483     393616 ./zssServer ../deploy/instance/ZLUX/serverConfig/zluxserver.json
ZOWED1   <- ZOWEDS1      393620     393616 tee /C/zowe/installed/zlux-app-server/log/zssServer-2019-08-04-02-06.log
```
to keep all helper shells and tee under `ZOWED1`, and ensure that node participating in cluster are properly numbered under `ZOWEDSx`.

Going back to your question:

> Do those jobs participate in the HA scheme?

Because HA is a future feature, I don't know at this moment if HA will be achieved by running `ZOWE2SV` PROC multiple times or whether `ZOWE2SV` will spawn multiple instances of `ZOWE2xx` services.
Definitely `ZOWE2DT` should be broken down to separate `tee`, `sh`,  `zssServer` and `node`.

**Comment by John-A-Davies** [comment]
Completed by #608.
