### ISSUE TITLE
zowe-check-prereqs.sh error msg: "/usr/lpp/IBM/cnj/IBM/node-*" is not found

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#583]
On MV3B, `zowe-check-prereqs.sh` gave this output:
```
Check Node version
node: ./zowe-check-prereqs.sh 446: FSUM7351 not found
ls: FSUM6785 File or directory "/usr/lpp/IBM/cnj/IBM/node-*" is not found
Error: node version node: ./zowe-check-prereqs.sh 446: FSUM7351 not found is 
less than minimum level required
```
This happens because `/usr/lpp/IBM/cnj/IBM/node-*` is hard-coded in the script, but node is actually in `/usr/lpp/IBM/cnj/v8r0/IBM/node-v8.16.0-os390-s390x`.

Script `zowe-verify.sh` does a better job of this, so it could hold a solution.

**Comment by John-A-Davies** [comment]
Some other issues are related to `zowe-check-prereqs.sh`: #512 and #447.

**Comment by peterkendlbacher** [comment]
We are using version 1.4, after adding the following lines to /etc/profile /zowe-check-prereqs.sh gets ok for nodejs.

export PATH=$PATH:/usr/lpp/IBM/cnj/v8r0/IBM/node-latest-os390-s390x/bin 
export NODE_HOME=/usr/lpp/IBM/cnj/v8r0/IBM/node-latest-os390-s390x

**Comment by stevenhorsman** [comment]
From 1.9 dev build onwards we've streamlined and simplified zowe-check-prereqs.sh, so the code that caused this issue has been removed
