### ISSUE TITLE
zowe-install-apf-server.sh doesn't run from an SMPE install

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#587]
Found by @jackjia-ibm:
 
installing xmem server, after Zowe pax.Z is installed, I try to run `zowe-install-apf-server.sh` from `/tmp/usr/lpp/zowe/xmem-server`, but got these errors:

```
pax: ../zss.pax: EDC5129I No such file or directory.
chmod: FSUM6180 file "/zaas1/zowe-smpe-packaging-20190726145130/zowe/AZWE001/stage/scripts/internal/opercmd": EDC5129I No such file or directory.
chmod: FSUM6180 file "/zaas1/zowe-smpe-packaging-20190726145130/zowe/AZWE001/stage/xmem-server/scripts/*": EDC5129I No such file or directory.
.: ./zowe-install-apf-server.sh 47: /zaas1/zowe-smpe-packaging-20190726145130/zowe/AZWE001/stage/xmem-server/scripts/zowe-xmem-parse-yaml.sh: not found
```

the xmem server install script issue I think it’s related to run `zowe-install.sh -I` during packaging, the script will call `zowe-copy-xmem.sh` which will update SCRIPT_DIR, ZSS, OPERCMD location in `zowe-install-apf-server.sh` with the temp smpe packaging folder.

**Comment by stevenhorsman** [comment]
Just to clarify - this issue is nothing to do with the zowe-install -I install, but it is not working for the smpe install as the root directory doesn't match.

**Comment by stevenhorsman** [comment]
It looks like this is still an issues:
`.: ./zowe-install-apf-server.sh 47: /zaas1/zowe-smpe-packaging-20190726145130/zowe/AZWE001/stage/xmem-server/scripts/zowe-xmem-parse-yaml.sh: not found`

**Comment by stevenhorsman** [comment]
Hopefully this is fixed now. Awaiting the testing on smpe master #34

**Comment by stevenhorsman** [comment]
Fixed in zowe-install-test 99+
