### ISSUE TITLE
zowe-configure-explorer-ui.sh - nodejs codepage problem

### ISSUE THREAD

**Issue by peterkendlbacher** [zowe/zowe-install-packaging#596]
We just installed ZOWE. After going through several codepage issues we finally made it to start the started task.

In the startup log the following error message appears:

í408ù Error: /SYSTEM/var/zowe/1.4.0/zlux-app-server/deploy/instance/ZLUX/plugins/‹¨«‹¨«‹¨«K‹¨«‹¨«‹¨«‹¨«K‹¨«‹¨«‹¨«‹¨«‹¨«‹¨«‹¨«‹¨«`‹¨«‹¨«‹¨«.json is missing
 í408ù     at PluginLoader._readPluginDef (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/lib/plugin-loader.js:574:13)
 í408ù     at PluginLoader.readPluginDefs (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/lib/plugin-loader.js:618:29)
 í408ù     at PluginLoader.loadPlugins (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/lib/plugin-loader.js:631:23)
 í408ù     at Server.<anonymous> (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/lib/index.js:215:23)
 í408ù     at Generator.next (<anonymous>)
 í408ù     at Generator.tryCatcher (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)
 í408ù     at PromiseSpawn._promiseFulfilled (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/generators.js:97:49)
 í408ù     at Promise._settlePromise (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:579:26)
 í408ù     at Promise._settlePromise0 (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:619:10)
 í408ù     at Promise._settlePromises (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:699:18)
 í408ù     at _drainQueueStep (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:138:12)
 í408ù     at _drainQueue (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:131:9)
 í408ù     at Async._drainQueues (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:147:5)
 í408ù     at Immediate.Async.drainQueues (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:17:14)
 í408ù     at runCallback (timers.js:810:20)
 í408ù     at tryOnImmediate (timers.js:768:5)
 í408ù í2019-08-26 14:19:20.955 _zsf.bootstrap WARNINGù - Error: /SYSTEM/var/zowe/1.4.0/zlux-app-server/deploy/instance/ZLUX/plugins/‹¨«‹¨«‹¨«K‹¨«‹¨«‹¨«‹¨«K‹¨«‹¨«‹¨«‹¨«‹¨«‹¨«‹¨«‹¨«`‹¨«‹¨«‹¨«.json is missing
 í408ù     at PluginLoader._readPluginDef (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/lib/plugin-loader.js:574:13)
 í408ù     at PluginLoader.readPluginDefs (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/lib/plugin-loader.js:618:29)
 í408ù     at PluginLoader.loadPlugins (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/lib/plugin-loader.js:631:23)
 í408ù     at Server.<anonymous> (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/lib/index.js:215:23)
 í408ù     at Generator.next (<anonymous>)
 í408ù     at Generator.tryCatcher (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)
 í408ù     at PromiseSpawn._promiseFulfilled (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/generators.js:97:49)
 í408ù     at Promise._settlePromise (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:579:26)
 í408ù     at Promise._settlePromise0 (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:619:10)
 í408ù     at Promise._settlePromises (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:699:18)
 í408ù     at _drainQueueStep (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:138:12)
 í408ù     at _drainQueue (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:131:9)
 í408ù     at Async._drainQueues (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:147:5)
 í408ù     at Immediate.Async.drainQueues (/SYSTEM/var/zowe/1.4.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:17:14)
 í408ù     at runCallback (timers.js:810:20)
 í408ù     at tryOnImmediate (timers.js:768:5)

There are unexpected signs in the path so I understand this is not correct (pointing to nowhere).

I checked the installation folder and also found three strange looking folders:

drwxr-xr-x   3 BPXROOT  WSTCALLE    8192 Aug 26 16:06 ..
-rw-rw----   1 BPXROOT  IZUADMIN    2728 Aug 26 16:08 ZOWESVR.JCL
drwxrwx--x   6 BPXROOT  IZUADMIN    8192 Aug 26 16:07 api-mediation
drwxrwx--x   3 BPXROOT  IZUADMIN    8192 Aug 26 16:07 api_catalog
drwxrwxr-x   2 BPXROOT  IZUADMIN    8192 Aug 26 16:08 configure_log
drwxrwx--x   3 BPXROOT  IZUADMIN    8192 Aug 26 16:06 explorer-data-sets-api
drwxrwx--x   3 BPXROOT  IZUADMIN    8192 Aug 26 16:06 explorer-jobs-api
drwxrwx--x   2 BPXROOT  IZUADMIN    8192 Aug 26 16:06 install_log
drwxrwx--x   6 BPXROOT  IZUADMIN    8192 Aug 26 16:06 jes_explorer
-rw-r-----   1 BPXROOT  IZUADMIN    8107 Aug 26 16:06 manifest.json
drwxrwx--x   6 BPXROOT  IZUADMIN    8192 Aug 26 16:06 mvs_explorer
drwxrwx--x   7 BPXROOT  IZUADMIN    8192 Aug 26 16:06 sample-angular-app
drwxrwx--x   3 BPXROOT  IZUADMIN    8192 Aug 26 16:06 sample-iframe-app
drwxrwx--x   4 BPXROOT  IZUADMIN    8192 Aug 26 16:06 sample-react-app
drwxrwx--x   5 BPXROOT  IZUADMIN    8192 Aug 26 16:08 scripts
drwxr-x--x   4 BPXROOT  IZUADMIN    8192 Aug 26 16:07 tn3270-ng2
drwxrwx--x   6 BPXROOT  IZUADMIN    8192 Aug 26 16:06 uss_explorer
drwxr-x--x   4 BPXROOT  IZUADMIN    8192 Aug 26 16:07 vt-ng2
drwxrwx--x   3 BPXROOT  IZUADMIN    8192 Aug 26 16:06 xmem-server
dr-xr-x--x   5 BPXROOT  IZUADMIN    8192 Jul 18 16:44 zlux-app-manager
dr-xr-x--x  11 BPXROOT  IZUADMIN    8192 Aug 26 16:06 zlux-app-server
drwxr-x--x   2 BPXROOT  IZUADMIN    8192 Jul 18 16:44 zlux-build
drwxrwx--x   3 BPXROOT  IZUADMIN    8192 Aug 26 16:06 zlux-editor
drwxr-x--x   4 BPXROOT  IZUADMIN    8192 Jul 18 16:44 zlux-platform
dr-xr-x--x   7 BPXROOT  IZUADMIN    8192 Jul 18 16:44 zlux-server-framework
dr-xr-x--x   4 BPXROOT  IZUADMIN    8192 Jul 18 16:44 zlux-shared
drwxrwx--x   5 BPXROOT  IZUADMIN    8192 Aug 26 16:06 zlux-workflow
drwxrwx--x   4 BPXROOT  IZUADMIN    8192 Aug 26 16:06 zosmf-auth
drwxrwx--x   4 BPXROOT  IZUADMIN    8192 Aug 26 16:06 zss-auth
drwxrwx--x   3 BPXROOT  IZUADMIN    8192 Aug 26 16:07 ▒▒▒@ŧ▒▒▒▒▒▒
drwxrwx--x   3 BPXROOT  IZUADMIN    8192 Aug 26 16:07 ▒▒▒@ŧ▒▒▒▒▒▒
drwxrwx--x   3 BPXROOT  IZUADMIN    8192 Aug 26 16:07 ▒▒▒@ŧ▒▒▒▒▒▒

If I switsch to the /var/zowe/1.4.0/api-mediation/api-defs folder and try to check the content of any of the following files I get no useful content.

datasets.yml
jobs.yml    
uss.yml     
zosmf.yml   

I tried to convert the content from and to other codepages, but nothing helped. the content still is trash.

Does anybody have an idea what the problem could be, because I really am out of ideas?

**Comment by peterkendlbacher** [comment]
I have tracked down the problem to this script: 

zowe-configure-explorer-ui.sh

In this script the wrong codepage folders are created.

I will go on investigating.

**Comment by peterkendlbacher** [comment]
Found the following in the configuration log file:

<zowe-explorer-ui-configure.sh>
  Configuring Explorer UI: JES ...
    - plugin ID   : ���K����K��������`���
    - plugin name : ���@ŧ������
    - port        : 8546
    - base uri    : a��a��a��������`���
  JES Explorer UI configured.
  Configuring Explorer UI: MVS ...
    - plugin ID   : ���K����K��������`���
    - plugin name : ���@ŧ������
    - port        : 8548
    - base uri    : a��a��a��������`���
  MVS Explorer UI configured.
  Configuring Explorer UI: USS ...
    - plugin ID   : ���K����K��������`���
    - plugin name : ���@ŧ������
    - port        : 8550
    - base uri    : a��a��a��������`���
  USS Explorer UI configured.
</zowe-explorer-ui-configure.sh>

**Comment by peterkendlbacher** [comment]
The problem is in this command:

EXPLORER_PLUGIN_BASEURI=$($NODE_BIN -e "process.stdout.write(require('./package.json').config.baseuri)")

In the script I get the wrong codepage, but if I execute it manually  it returns the correct content:

/ui/v1/explorer-jesbash-4.3$

The question now is is the output of the node command wrong or do I have to change the codepage of the script??

**Comment by peterkendlbacher** [comment]
Sorry, the  result of course is /ui/v1/explorer-jes

Does anyone know how to fix this codepage issue?

**Comment by NakulManchanda** [comment]
hi one suggestion is to use iconv utility
if you have original file in 1047/ascii format you can convert that manually to 850 format and place it in api-defs folder
If you want to read content of yml file you can convert it to 1047 and read,
Just swap -t & -f based on your use case.
```
cd /u/zowe/ibmuser/1.4.0/sample-node-api
iconv -t IBM-850 -f IBM-1047 sample-node-api.yml.1047 > sample-node-api.yml
mv sample-node-api.yml ../api-mediation/api-defs/
```

**Comment by peterkendlbacher** [comment]
After upgrading to 1.5.0 the problem still exists.

As discussed with Joe-Winchester the problem has to do with the shell.

We are using bash 4.3.

I now did the following with bash:

cd /var/zowe/1.5.0/jes_explorer   --> install dir where zowe is installed
echo $(node -e "process.stdout.write(require('./package.json').config.baseuri)")

Result: a▒▒a▒▒a▒▒▒▒▒▒▒▒`▒▒▒

Next I exit bash and try the same in root nativ shell

cd /var/zowe/1.5.0/jes_explorer   --> install dir where zowe is installed
echo $(node -e "process.stdout.write(require('./package.json').config.baseuri)")

Result: /ui/v1/explorer-jes

This means the bash shell is not correctly converting the codepage in the script.
It also means, if I would run the configuration script without the bash the script should run correctly.

Joe advised me to export the following parameters befor running the script:

I now want test if I export the parameters in bash, if it also works:

Commands again run in bash:

bash
cd /var/zowe/1.5.0/jes_explorer
export _CEE_RUNOPTS=""
export _TAG_REDIR_IN=""
export _TAG_REDIR_ERR=""
export _TAG_REDIR_OUT=""
export _BPXK_AUTOCVT="OFF"
echo $(node -e "process.stdout.write(require('./package.json').config.baseuri)")

Result: a▒▒a▒▒a▒▒▒▒▒▒▒▒`▒▒▒

So the parameters are not effective for bash 4.3.

**Comment by peterkendlbacher** [comment]
Next I looked up the information of the zowe-configure-explorer-ui.sh:

chtag -p zowe-configure-explorer-ui.sh
- untagged    T=off zowe-configure-explorer-ui.sh
If I look into idz and open the script, it shows me Codepage Cp1047 for the content.

**Comment by peterkendlbacher** [comment]
As next test I made two scripts in the folder /var/zowe/1.5.0/jes_explorer.
The content of both is IBM1047.

1) test-IBM-1047.sh

echo "Running test-IBM-1047.sh" (This script is tagged and coded in IBM1047)

EXPLORER_PLUGIN_BASEURI=$(node -e "process.stdout.write(require('./package.json').config.baseuri)")
EXPLORER_PLUGIN_ID=$(node -e "process.stdout.write(require('./package.json').config.pluginId)")
EXPLORER_PLUGIN_NAME=$(node -e "process.stdout.write(require('./package.json').config.pluginName)")

echo "    - plugin ID   : ${EXPLORER_PLUGIN_ID}" 
echo "    - port        : ${EXPLORER_PLUGIN_PORT}" 
echo "    - base uri    : ${EXPLORER_PLUGIN_BASEURI}"

This script is tagged as IBM1047

chtag -p test-IBM1047.sh
t IBM-1047    T=on  test-IBM1047.sh

Script Result with bash:

Running test-IBM-1047.sh
    - plugin ID   : ▒▒▒K▒▒▒▒K▒▒▒▒▒▒▒▒`▒▒▒
    - port        :
    - base uri    : a▒▒a▒▒a▒▒▒▒▒▒▒▒`▒▒▒

Script Result without bash:

Running test-IBM-1047.sh
    - plugin ID   : org.zowe.explorer-jes
    - port        :
    - base uri    : /ui/v1/explorer-jes


2) test-untagged.sh (This script has the same configuration as zowe-configure-explorer-ui.sh)

echo "Running test-untagged.sh"

EXPLORER_PLUGIN_BASEURI=$(node -e "process.stdout.write(require('./package.json').config.baseuri)")
EXPLORER_PLUGIN_ID=$(node -e "process.stdout.write(require('./package.json').config.pluginId)")
EXPLORER_PLUGIN_NAME=$(node -e "process.stdout.write(require('./package.json').config.pluginName)")

echo "    - plugin ID   : ${EXPLORER_PLUGIN_ID}" 
echo "    - port        : ${EXPLORER_PLUGIN_PORT}" 
echo "    - base uri    : ${EXPLORER_PLUGIN_BASEURI}"

Script Result with bash: (result as expected)

Running test-untagged.sh
    - plugin ID   : ▒▒▒K▒▒▒▒K▒▒▒▒▒▒▒▒`▒▒▒
    - port        :
    - base uri    : a▒▒a▒▒a▒▒▒▒▒▒▒▒`▒▒▒

Script Result without bash:

Running test-untagged.sh
    - plugin ID   : org.zowe.explorer-jes
    - port        :
    - base uri    : /ui/v1/explorer-jes

A conclusion to this is, that if I run the script without bash everyting should be fine, But I still don't know what the differences between the shells is.

**Comment by peterkendlbacher** [comment]
Next deleted the complete zowe 1.5.0 installation and started from the beginning doing everything withot bash.

Finally the installation now looks fine.

If anyone knows why bash has this problem please comment.

**Comment by stevenhorsman** [comment]
I think given the lack of responses we can close this now. Note in v1.9 there are updated code-page settings for node 12 support, so hopefully things have got better, not worse
