### ISSUE TITLE
Remove the message ZOWE_INSTANCE not specified from the install log

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#599]
When installing Zowe if there isn't a ZOWE_INSTANCE specified it defaults to 1 which is correct.

It should not echo this to the console however as we want to keep the console very clean, so the message should be written to the install log instead

![image](https://user-images.githubusercontent.com/28100302/63843653-a30b4d80-c97e-11e9-9281-bd4c01b012f7.png)

In addition when zowe-start.sh is run the message JOBNAME-ZOWES{{zowe_instance}}SV is written to the log which is not the actual job name.

![image](https://user-images.githubusercontent.com/28100302/63844993-1c0ba480-c981-11e9-890b-99138e9b2fe3.png)

If we have introduced a new .yaml argument for the default instance number we should perhaps introduce it into the one we ship to make it clearer that there is something to change

**Comment by John-A-Davies** [comment]
This is a real error that we want the installer to see.  All such msgs are now echoed to the console and $LOG_FILE, fixed in #608.
