### ISSUE TITLE
Cupids Phase 2 scratchpad

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#615]
- Keystore changes - Rather than creating a new keystore in the install we can use an existing one the customer has/ provide doc to create a new one if they need, use keyrings, made keystore shared globally between zowe installs
- Containerisation - put all the node and java components in docker containers so they can be run off platform/in zCX - #793
- Lifecycle Managment - add the ability to restart components by issuing a console modify command - or using kube or similar in containers
- Launch multiple Zowe servers from the same binary (phase 1 or 2?)

**Comment by 1000TurquoisePogs** [comment]
On keyring changes, https://github.com/zowe/zowe-install-packaging/issues/3877
Rest already has tickets or has been handled.
