### ISSUE TITLE
Epic: Zowe Performance Test - Stage 1 (2020PI3)

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#617]
Epic to group tasks related to performance test in 2020PI2.

<img width="1075" alt="Screen Shot 2019-09-10 at 8 18 46 PM" src="https://user-images.githubusercontent.com/39711029/64639490-3bd2ac00-d408-11e9-8b3b-f0fe9c8c5762.png">

**Comment by jackjia-ibm** [comment]
A more close look of the hills for performance work: 
[2020PI3 - performance test.pdf](https://github.com/zowe/zowe-install-packaging/files/4898055/2020PI3.-.performance.test.pdf)

**Comment by jandadav** [comment]
Dear Systems squad

Please find our suggestions for possible initial test scenarios that would be interesting for API Mediation Layer (Apiml):

Tests for the UI would be interesting to benchmark user-perspective performance but we understand that at this point in time, they are out of scope. We plan to enhance the test suite even further with time, as we develop test cases in house. This is the initial set of cases that we would be looking to have:

### Pipeline tests:

- Zowe startup time
Measure time that it takes to start Zowe instance
Startup is when services homepages or API’s are reachable. We can provide more data on how to understand the status of Apiml.

- Registration of service performance
Register service with direct call to Discovery service: post `/eureka/apps/<someService>`
Call service through Gateway service: get `<gateway>/api/v1/<someService>/<someEndpoint>`. Measure how long it takes for the service endpoint to be available in the gateway.

_Let’s say that each following test is run with 100 concurrent users for 2 minutes_

- Home Page Load
Issue GET request to Gateway and API Catalog homepage.
measure average response time.
For Api Catalog, it would be nice if we can also measure full page load (also with the JS files through links)

- Login performance:
Call to `<gateway>/api/v1/gateway/auth/login` with credentials
Measure average time between request and response.

- Gateway routing performance:
Route service (preferably some fast or dummy endpoint) and measure average request metrics
`<gateway>/api/v1/<testService>/<testEndpoint>`
Issue the same requests directly against 
`<testService>/<testEndpoint>`
and measure average metrics
Calculate Gateway’s overhead and routing performance by comparing the different results


### Weekly tests:

- Apiml Core services cpu consumption at idle and with traffic.

We can provide information of what “traffic” means to us. It is a combination of logins, service routing, and using Apiml features like catalog.

Run Apiml without any load and measure consumption during time 0, then after startup (roughly 2 minutes) and then after 20 minutes.
Calculate startup cpu time and idle cpu time trend

Repeat the same but simulate Zowe traffic with a variable amount of concurrent users producing traffic after startup is complete. We can simulate 200/500/800

Calculate the same metrics

**Comment by jordanCain** [comment]
For the explorer API's (Jobs APIs and Data-sets and Unix files API's):
Each set of API's is accessible via two ports, the port of the service itself and the port of the API Gateway, both of these routes will need testing. 
Each API is also available in a v1 and a v2, the v1 APIs use basic authentication whereas the v2 APIs use the JWT provided by the api gateway auth service. 
All APIs are fulfilled on the backed by z/OSMF.

As a note we have seen wildly different response times on these api calls on the same system even on the same version of Zowe, this is down in part to z/OSMF and caching/JIT of the Java code, so there is some stabilizing time needed on startup before performance testing should commence.

Some of the provided APIs can fetch large volumes of data, for example requests can be made to get back all jobs that have run or are to be run on a system, this can be upwards of multiple thousands of jobs, similarly an endpoint is provided for getting the contents of a dataset, if the record length of the dataset is high and there are 10k lines this is a large volume of data to transfer.

We have 14 unix files and datasets apis and a further 12 jobs apis, each of which have 2 versions giving a total of 52 api endpoints. It may be difficult to test all fo these endpoints in a performance test suite (note that all fo these endpoints are currently tested using RestAssured in our integration tests).

As part of a performance test suite we should look at:

1. Startup time of the api services (When endpoints become usable via the service dedicated port)
2. Overall Zowe startup time (When endpoints become usable via the api gateway port)
3. Idle CPU usage
4. Selection of endpoints response times (Ensure any required JIT/stabilization is performed first) 
5. Selection of endpoints CPU load impact when under heavy load (sustained requests over a period of time)
6. Performance of endpoint when transferring large payloads (both response time and cpu load)

As for UI testing, there are 3 "explorer apps", JES, MVS and USS. These explorers make use of the APIs previously discussed. As the APIs would already be under performance testing the only aspect of the UIs that would not already be covered would be the initial page load time. There are two avenues to test the load time, the first being when the apps are in standalone mode and the second when the apps are accessed via the Zowe Desktop.

**Comment by jackjia-ibm** [comment]
Thanks Jordan! Currently the test framework can handle test cases listed as 3 ~ 6.

It's interesting point to test startup time. I will put this into a separated issue to investigate what's the best way to do it. Current all tests are assuming the server is already started, stabilized and ready for handling requests.

UI testing is another complicated part which we don't support yet. There is one possible way to evaluate from server side is we mimic real-world scenarios, testing with urls to the server with desired concurrency, like 500 users, and find the slow endpoints. To support this kind of test is in plan.

To test page loading time on browser is more complicated. If we just consider one user experience, we can use Chrome DevTools profiling to check the loading time and see if we can automate it. But if we are thinking of loading time for 500 concurrency, we need to find a way to start those browsers in different VMs to avoid client side bottleneck.

fyi @CaretCake

**Comment by jackjia-ibm** [comment]
Will substitute this epic with https://github.com/zowe/zowe-install-packaging/issues/1683 when we move to 2020PI4, all open tasks will be moved to the new epic.
