### ISSUE TITLE
Investigate Performance Metric Server Implementation

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#618]
Evaluate several ways of collecting server metrics and compare what's the best way.

Requirements:
- The tool should be able to provide metrics of CPU/Memory/IO consumption.
- The tool should be able to provide real-time metrics output.
- The tool should be able to process-level metrics along with overall.

Possible solutions:
- RMF Monitoring III
- CIM server
- SDSF

**Comment by jackjia-ibm** [comment]
Investigate how to read SMF data directly.

**Comment by MarkAckert** [comment]
Research status:
- SDSF works for metric data
- RMF works  for metric data
- CIM Tests ongoing
- SMF data prototype available. Starting to look at SMF30 records

**Comment by jackjia-ibm** [comment]
@NayerNajafi @jackjia-ibm after demo to the team, we also want to collect ZIIP CPU time from SDSF DA.

**Comment by NayerNajafi** [comment]
@jackjia-ibm The following two new metrics have been added to the REXX program for ZIIP CPU time:
1- zIIP-Time (CPU time consumed on zIIPs, in seconds)
2- zIIP-Use% (Percent of the total zIIP time used by the address space in the most recent interval)

You could find the program in TVT5003, _/u/ibmuser/pmetrics_

**Comment by jackjia-ibm** [comment]
Thanks Nayer, this has been imported to https://github.com/zowe/zowe-dependency-scan-pipeline/blob/master/performance/server/src/collectors/metrics/da.rexx

**Comment by jackjia-ibm** [comment]
My understanding is we have good idea on what metrics we can pull and how to pull for now, so will close this item. Please suggest otherwise.
