### ISSUE TITLE
Componentise the Data Set Explorer UI

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#624]
**As a** Zowe user,  
**I want** to be able to start the data-set UI services with the configuration passed in at runtime and have a separate user_directory/workspace for my instance data
**so that** I can make changes to my zowe config without having to reinstall and lose my config.

*Details/notes*
- We'll follow the pattern set out in #433 for launching a component and apply it to the Data set explorer ui service
- [ ] During configure we'll need to inject new properties into run-zowe.sh
ZOWE_EXPLORER_MVS_UI_PORT - rename this?
- Create a new start.sh script that is created in <zowe_root_dir>/components/<component-name>/bin based on explorer-mvs/scripts/start-explorer-mvs-ui-server.sh
- In  explorer-mvs/scripts/ create a new configure.sh script that is put in in <zowe_root_dir>/components/<component-name>/bin and does all the configure set-up - sed injecting the properties into config.json from shell variables (and others?) based on the logic in zowe-configure-explorer-ui.sh. It also needs to create the data set explorer ui static def yaml into the static definition config directory
- [ ] Add the new component id to the LAUNCH_COMPONENTS list and remove the old code

- We'll create a follow up story about doing component validation for Data set explorer similar to #445 after it is refactored to share logic

**Questions?**
- What is the component id for data-set explorer?
 - How do we validate that the dependencies are all in launch config - zosmf, api gateway & explorer APIs?

#### Acceptance Criteria

*Given* an run-zowe.sh forked script with defining all the require properties (listed above)
    *When* I run start ZOWE to drive the script
    *Then* ZOWE should start successfully
    *And* when I look at the zowe job address spaces through display active, I can see the data set explorer ui service active
    *And* The ui services should be available on ports <ZOWE_EXPLORER_MVS_UI_PORT>

**Comment by NakulManchanda** [comment]
merged in staging
