### ISSUE TITLE
Componentise USS Explorer UI

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#626]
Same as #624 for USS Explorer

**Questions?**
- What is the component id for uss explorer?

**Comment by 1000TurquoisePogs** [comment]
Question: If we're moving towards the explorer UI's being part of the ZAF server, then they wouldn't run without it, so at that point should the component IDs for the explorers be some subset of component IDs for ZAF plugins in general? And/or should the server-side have component IDs separate from the UI?
ZAF will have tooling to assist in install&removal of individual plugins, so things that can be packaged entirely as plugins can take advantage of that structure. We could also do more on having ZAF plugins know the lifecycle of server-side pieces that live elsewhere, like attached to the APIML.
