### ISSUE TITLE
Create performance test client framework

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#628]
**Summary**

The performance test client is a tool start test and collect test result. It

- can be started with one command line (later this command line will be encapsulated into Docker image,
- takes environment variables to adjust test behaviors,
- may have many test cases grouped into test suites,
- allows the user to run just one or many test suites (or test cases),
- can talk to metrics service to collect server metrics during the test,
- will generate JSON test report in pre-defined format.

**Programming Language**

Choices are:

- Python/PyTest
- Node.JS/Zowe CLI/imperative

**Sample Usage**

1. Start command

```shell
$ docker run —-rm \
    -e TARGET_SERVER=river.zowe.org \
    -e ZOWE_APIML_PORT=7554 \
    -e ZOWE_METRICS_SERVICE=https://river.zowe.org:7554/api/v1/metrics
    -v path/to/my/test:/test
    zowe-org/performance-test --concurrency 10 --duration 300 my-test-case-name
```

  - `zowe-org/performance-test` is official docker image.
  - change variable TARGET_SERVER to test any server,
  - ZOWE_METRICS_SERVICE is optional. If it's set, the test client will collect server metrics,
  - `--concurrency 10 --duration 5m` are test parameters. These parameters will also be saved in final report.
  - `path/to/my/test` is where test suite located.
  - `my-test-case-name` is the test suite/case we want to run

2. Sample output

```
> Test started at .....
> Testing apiml-zosmf-fetching-ds-content ...
    - sending request https://......
    - collecting server metrics ...             << optional if provide ZOWE_METRICS_SERVICE
> Testing explorer-fetching-ds-content ...
    - sending request https://......
    - collecting server metrics ...             << optional if provide ZOWE_METRICS_SERVICE
> Testing cli-fetching-ds-content ...
    - zowe cli...
> Done
```

3. Sample test report

```json
{
    "test": "",
    "start-at": "2019-07-31T01:23:45.789Z",
    "end-at": "2019-07-31T02:23:45.789Z",
    "test-cases": [{
        "name": "apiml-zosmf-fetching-ds-content",
        "environments": {
            "TARGET_SERVER": "river.zowe.org",
            "ZOWE_APIML_PORT": "7554",
            "ZOWE_METRICS_SERVICE": "https://river.zowe.org:7554/api/v1/metrics"
        },
        "parameters": {
            "concurrency": 10,
            "duration": "5m"
        },
        "result": {
            "average-response-time": "10",
            "error-rate": "0",
            "requests-per-seconds": "3"
        },
        "server-metrics": [{
            "timestamp": "2019-07-31T01:23:45.789Z",
            "name": "cpu.zowesv1",
            "value": "12"
        }]
    },]
}
```

  - `environments` and `parameters` are test context.
  - `result` section may vary based on type of test case.
  - `server-metrics` is server context which logs metrics before/during/after test.
  - We may extend for report in the future like `server-logs` etc.

**Key Classes**

- TestSuite
- BaseTestCase
  - IdleTestCase
  - WrkTestCase
  - SelleniumTestCase

`BaseTestCase` should allow to define test `parameters`, `metrics` should be collected, etc.

**Comment by MarkAckert** [comment]
Should we build this on imperative?

 Or make a zowe CLI plugin so users can run the same performance suite against their installation?
