### ISSUE TITLE
Create primary performance test suite

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#630]
**Summary**

This is the primitive test suite which will provide general view of Zowe performance. This test suite will run in scheduled pipeline defined at https://github.com/zowe/zowe-install-packaging/issues/631.

**Primitive Test Cases**

- Idle -  no traffic send to server, just collect CPU/memory usage of server.

**Note:** Below test cases should be re-evaluated, or pick from other dedicated test suites for APIML, Explorers APIs, CLI and Desktop.

- CLI
   - List datasets by pattern - list datasets that match a pattern in the data set name
- API
   - Datasets
      - get_datasets_content - reads content from a sequential data set or member of a partitioned data set
      - get_datasets_filter - returns a list of data sets according to a given filter
  - Jobs
     - get_zowe_job_jes_log_file - reads content from a specific job output file
  - USS
     - get_unix_files - gets a list of files and directories for a given path
     - get_unix_files_path_content - gets the contents of a Unix file
- UI
  - JES Explorer (jesExplorerMVD) - display zowe jes job log in content viewer
  - Dataset Explorer (mvsExplorerMVD) - display dataset information in content viewer
  - USS Explorer (ussExplorerMVD) - display uss file in content viewer

**Notes**

- We need to confirm with related squads if these tests are good enough to be used as primary test cases.
- Will need to define default concurrency, duration for each of the tests.
- The test cases below should allow the user to adjust traffic load bring to the server, like  concurrency. (This should be provided natively by the test framework.)

**Comment by CaretCake** [comment]
Based on discussions with the related squads, we've established a more comprehensive set of test cases which expand the set of "primitive" test cases of the past to cover a more general overview of Zowe performance and begun work on writing those test cases within the test framework.

We've also identified the following endpoints as a reasonable set for the automated weekly performance testing, subject to change based on feedback and on final actual runtime of automated run:

- [x] Idle
- [ ] /auth/login
- [ ] /auth/logout
- [ ] /server/
- [ ] /unixContents/
- [ ] /datasetContents/
- [ ] /plugins
- [ ] /auth
- [x] /api/v2/datasets/{filter}
- [x] /api/v2/datasets/{dataSetName}/content
- [x] /api/v2/unixfiles
- [x] /api/v2/unixfiles/{path}/**
- [x] /api/v2/jobs - DONE
- [x] /api/v2/jobs/{jobName}/{jobId}/files/{fileId}/content
- [x] /api/v2/jobs/{jobName}/{jobId}
- [ ] /eureka/apps/gateway


Upon completion of the above test cases, we'll expand coverage to also include the following component level test cases:

**APIML** #645
Dummy service for Gateway routing performance
/application
/application/health
/application/info
/eureka/apps
/eureka/apps/{service}
/eureka/apps/zlux

**Explorer APIs** #644 
/api/v1/datasets/{filter}
/api/v1/datasets/{filter}/list
/api/v1/datasets/{dataSetName}/content
/api/v1/datasets/username
/api/v1/datasets/{dataSetName}/members
/api/v2/datasets/{filter}/list
/api/v2/datasets/{dataSetName}/members
/api/v1/unixfiles/{path}/**
/api/v1/unixfiles
/api/v1/jobs/{jobName}/{jobId}/steps
/api/v1/jobs/username
/api/v1/jobs/{jobName}/{jobId}/files/content
/api/v1/jobs
/api/v1/jobs/{jobName}/{jobId}/files
/api/v1/jobs/{jobName}/{jobId}/files/{fileId}/content
/api/v1/jobs/{jobName}/{jobId}
/api/v2/jobs/{jobName}/{jobId}/steps
​/api​/v2​/jobs​/{jobName}​/{jobId}​/files
/api/v2/jobs/{jobName}/{jobId}/files/content

**Desktop** #643 
(all listed in the primary test suite)

**Comment by CaretCake** [comment]
I am working on changes according to Jack's review of the following pull request for the first set of test cases from the primary test suite. 

https://github.com/zowe/zowe-dependency-scan-pipeline/pull/33
