### ISSUE TITLE
Create performance test scheduled pipeline

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#631]
**Summary**

This pipeline will run after the most recent staging build is install and tested.

The test suite will be run is built from #630.

The test will be performed on our primary performance test server, Marist. Our current goal is to run it every Saturday early morning, but will need to confirm with Marist Support.

The test result will be published to Zowe Artifactory.

**Comment by MarkAckert** [comment]
Dependency on Marist college and infrastructure availibility/quiet periods

**Comment by jackjia-ibm** [comment]
Fulfilled with https://github.com/zowe/zowe-dependency-scan-pipeline/pull/21
