### ISSUE TITLE
Configuring ZOWE working with NAT address 

### ISSUE THREAD

**Issue by yann-59** [zowe/zowe-install-packaging#639]
Hello,

We had a ZOWE running on a LPAR with a DNS like "TITI.TOTO" resolving an address 172.16.x.x .
To access the ZLUX, we had to put an IP address (111.56.x.x) which is the NAT's adresse of our LPAR. The NAT address (111.56.x.x) isn't resolvd by the LPAR.

If we let the install script fixing the hostname "TITI.TOTO" , we can access to the Zlux , TN3270 and SSH ... but the JOB Explorer, USS Explorer wont' work because they try to access "TITI.TOTO" .

Is it a way to configure ZOWE working with NAT address ? Using the ZOWE_IPADDRESS 's variable ?

Cheers,

**Comment by vit-tomica** [comment]
Issue is possible to workaround by modification of `/api_catalog/web/index.html`
```
<!DOCTYPE html>
<html>
    <body>
        <iframe
            id="zluxIframe"
            src="https://TITI.TOTO:61418/ZLUX/plugins/org.zowe.zlux.auth.apiml/services/tokenInjector/1.0.0/ui/v1/apicatalog/";
            style="position:fixed; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:999999;">
            Your browser doesn't support iframes
        </iframe>
    </body>
</html>
```

Replace TITI.TOTO in html file with an ip address that is visible from your browser. The ZOWE_IPADDRESS variable can contain only an ip address of your LPAR.

There is a plan to optionally move zaf behind gateway so that there would be no hostname in the index.html file.

**Comment by yann-59** [comment]
Thks U ... we make this changement since the begining of our zowe's project ... it was a litlle bit boring to change any Iframe (api_catalog, uss_explorer, jes_explorer, ..) .. that's why I open this issue in order to have an improvement. If you have a plan to change this .. it was a good thing for us  👍

**Comment by stevenhorsman** [comment]
@yann-59 - sorry for the slow response - I wondered if - now in 1.8+ we have the instance.env which isn't overwritten on every install - you'd tried updating the properties in your instance.env from
```
ZOWE_EXPLORER_HOST=TITI.TOTO
ZOWE_IP_ADDRESS=<your ip>
``` 
to
```
ZOWE_IP_ADDRESS=<your ip>
ZOWE_EXPLORER_HOST=${ZOWE_IP_ADDRESS}
```
I'm not 100% sure, but that should help the issue for you and if so we might be able to follow that strategy if we can detect NAT being used?

**Comment by yann-59** [comment]
Thks @stevenhorsman  .. we are in 1.8 and migrate to 1.9 (since today).
We try :
ZOWE_IP_ADDRESS=<your ip>
ZOWE_EXPLORER_HOST=${ZOWE_IP_ADDRESS}

But the STC don't like this syntax :  
EZZ3111I Unknown host '${ZOWE_IP_ADDRESS}' 
Error 1: ZOWE_EXPLORER_HOST                
EZZ3111I Unknown host '${ZOWE_IP_ADDRESS}' 
Error 4: ZOWE_EXPLORER_HOST                
EZZ3111I Unknown host '${ZOWE_IP_ADDRESS}' 
Error 6: ZOWE_EXPLORER_HOST                

We fix the ZOWE_EXPLORER_HOST with the IP ADDRESS ... it seems to work but we had another error on our explorer (USS, JES, MVS) ... 

{"messages":[{"messageType":"ERROR","messageNumber":"ZWEAM104E","messageContent":"The endpoint you are looking for '/ui/v1/explorer-jes' could not be located","messageKey":"apiml.common.endPointNotFound"}]}

Maybe it caused by the IP Adresse instead of the HostName ?
We install the zowe 1.9 and we try new test.

**Comment by stevenhorsman** [comment]
Hi @yann-59 - apologies if my message wasn't clear - I just want to check that your settings are correct. I've tried updating my instance.env as follows:
![image](https://user-images.githubusercontent.com/35110159/75783095-e1336080-5d57-11ea-9933-d3e12803329c.png)
and it is working, without seeing any of the errors you mention. 
If I looking the in STDOUT of the job then I can see that the property has been copied across:
```
ZOWE_EXPLORER_HOST=9.20.5.48
...
ZOWE_IP_ADDRESS=9.20.5.48
```
What do you get for those parameters in the `Show Environment` section of the STDOUT?

**Comment by MarkAckert** [comment]
Closing this issue as stale.
