### ISSUE TITLE
zlux-app-server/log not writable after install

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#648]
After SMP/E install to target `/tmp/usr/lpp/zowe`, you have to . . .
     chmod a+x /tmp/usr
     chmod a+x /tmp/usr/lpp
     chmod a+x /tmp/usr/lpp/zowe

I also had to 
`chmod g+w /MV3B/tmp/usr/lpp/zowe/zlux-app-server/log/`

**Comment by stevenhorsman** [comment]
The chmod a+x is just dependent on where the customer picked to install SMPE to, so the only thing I think we can do is doc the requirement that the full path needs a+x permission

I tried an install of the convenience build and zlux-app-server/log/ has 771 permission, so I don't think there are any changes needed in Zowe-install-packaging

```ls -al /u/stevenh/staging/runtime/zlux-app-server/log/
total 16
drwxrwx--x   2 STEVENH  IZUADMIN       0 Sep 10 11:05 .
dr-xr-x--x  11 STEVENH  IZUADMIN    8192 Sep 10 11:05 ..```

```"build": {
    "branch": "staging",
    "number": "197",
    "commitHash": "f2bc6f4f4740c1e50e9ca6d3f5ce9014ad72c6b8",
    "timestamp": "1568000556507"
  },```
