### ISSUE TITLE
Research - Metrics Database and Hosting

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#649]
Research:

* Hosting for a performance metric historical database
  - Scale
  - Redundancy
* Database storage 
  - Does Promethus/Grafana or any similar technology cover this?
  - If not, think about our metric data structure and storage in another DB like Postgres / Cassandra
* Should DB persistence and operations be added to the metrics server if it runs off-platform?

**Comment by jackjia-ibm** [comment]
Current solution is we will not keep metrics history data but only keep the test reports into Artifactory.
