### ISSUE TITLE
Investigate possibilities of persisting performance test result

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#654]
**Data Will Be Persisted**

- test reports
- server metrics/context

**Candidate Tools**

Choices are:

- MongoDB
- ElasticSearch
- MapDB

Open question: should we request service from LF?

**Comment by MarkAckert** [comment]
Reports can be persisted in Artifactory

**Comment by jackjia-ibm** [comment]
Will use Artifactory to store the reports.
