### ISSUE TITLE
Update release/promote pipeline for S3

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#672]
We need to update our release and promotion pipeline to use the S3 bucket provided by the LF. 

We have successfully deployed to the S3 bucket manually already.

Pre-requisites:
- S3 credentials in LF Jenkins.
- Zowe promote / publish running in LF Jenkins

**Comment by jackjia-ibm** [comment]
John M. had move the contents located in S3 buckets to Zowe Artifactory, so will close this item.
