### ISSUE TITLE
Enhancement: Shared Pipeline Library has Docker Build/Deploy

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#675]
Add the capability to build and deploy docker images within the Zowe Shared Pipeline Library.

Exact implementation details TBD, but most options should be configurable with sensible defaults.

**Comment by jackjia-ibm** [comment]
Example pipeline created https://github.com/zowe/zowe-dockerfiles/blob/users/jack/pipeline/Jenkinsfile.zowe-dev
