### ISSUE TITLE
Enhancement: Support pipline.systemTest() with rules for PRs

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#685]
The shared pipeline library should be enhanced to support a "systemTest" stage which contains additional rules and behaviors for running Zowe system tests.

Functionality:
* PRs with protected labels (TBD) are able to run system tests
* Nightly trigger (or configurable trigger?)

**Comment by jackjia-ibm** [comment]
Will remove myself from this item as my role changed. We can try to find new owner for this item.

**Comment by jackjia-ibm** [comment]
Maybe we can check against https://github.com/zowe/community/blob/master/COMMITTERS.csv to automate build/test if the user is verified committer.

**Comment by FlappiTomic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PR Testing - Label PR Builds to run tests before merging](https://trello.com/c/E5BfDc9i/17-pr-testing-label-pr-builds-to-run-tests-before-merging)

**Comment by balhar-jakub** [comment]
Could you add me to the board you linked here? This is something I am interesting in at least knowing about.

**Comment by FlappiTomic** [comment]
> Could you add me to the board you linked here? This is something I am interesting in at least knowing about.

Sorry this comment was added by mistake, please ignore it.
