### ISSUE TITLE
Research/Implement: Merge Explorer Services Repositories

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#696]
This story includes:
* Modification of build pipeline
* Archival of old repositories

Proposed merged below:

| Grouping | Existing Repositories | Proposed New Repository | 
|--- | --- |  --- |
| Explorer Services | data-sets<br>jobs<br>explorer-api-common | zowe-explorer-rest-services |

**Comment by jackjia-ibm** [comment]
As suggested by OMP, mono repo is not suggested. Relevant discussion here https://github.com/zowe/community/issues/520#issuecomment-638214608.

Please re-open if this is still wanted.
