### ISSUE TITLE
Merge the zowe installation repositories

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#697]
The issues covers:
* Archival of old repositories 
* Modification of build pipeline to support new repository structure

Proposed Structure:

| Component | Existing Repositories | Proposed New Repository | 
|--- | --- |  --- |
| Zowe Install/Package | zowe-install-packaging<br>zowe-promote-publish<br>zowe-install-test<br>explorer-jes-fvt<br>release-management<br>zowe-cli-standalone-package<br>zowe-smpe-packaging | zowe-aggregate-artifact (name TDB) |

**Comment by jackjia-ibm** [comment]
progress updates, these repos are archived as of today:

- explorer-jes-fvt
- zowe-promote-publish
- zowe-smpe-packaging

**Comment by jackjia-ibm** [comment]
https://github.com/zowe/jenkins-library/issues/30 and https://github.com/zowe/jenkins-library/issues/31 are fulfilled in the work of merging zowe-promote-publish.

**Comment by jackjia-ibm** [comment]
I believe except for `zowe-cli-standalone-package`, all others had been merged into `zowe-install-packaging` and original repository had been archived.
