### ISSUE TITLE
Migrate CLI and Plugin Builds to LF Jenkins

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#705]
- Create JJB For CLI and all the plugins
- Requires pipeline updates to credential IDs and image names
- Requires `docker.inside` syntax in pipelines

**Comment by jackjia-ibm** [comment]
Will close the issue for now until we make decision on https://github.com/zowe/zowe-install-packaging/issues/1868. We can reopen if we decide to continue the path with LF Jenkins.
