### ISSUE TITLE
Migrate PAX builds to LF Jenkins

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#707]
This covers zowe-install-packaging, zowe-install-test, and zowe-promote-publish. This issue is dependent on all other component builds completing their migration to LF Jenkins first.

- Create JJB For All repos
- Requires pipeline updates to credential IDs and image names
- Requires `docker.inside` syntax in pipelines

**Comment by jackjia-ibm** [comment]
@Roavill2 @stevenhorsman this is one of the issue tracking LF Jenkins migration we discussed during work transfer.

**Comment by jackjia-ibm** [comment]
Will close the issue for now until we make decision on https://github.com/zowe/zowe-install-packaging/issues/1868. We can reopen if we decide to continue the path with LF Jenkins.
