### ISSUE TITLE
Review/Research: Other Migrations to LF Infrastructure

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#709]
Once all major builds have been moved to LF Infra (components + PAX builds), review any other builds leftover in private infrastructure and generate issues for them

**Comment by jackjia-ibm** [comment]
Will close the issue for now until we make decision on https://github.com/zowe/zowe-install-packaging/issues/1868. We can reopen if we decide to continue the path with LF Jenkins.
