### ISSUE TITLE
Validate Top Secret and ACF2 Installations

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#711]
Pre-requisite: TSS and ACF2 licenses for open infrastructure.

Once ACF2 and TSS are installed and configured on Marist infrastructure, do a manual installation / validation of Zowe and other ssoftware present on the current RACF LPAR.

**Comment by jackjia-ibm** [comment]
We have enabled ACF2/TS testing on nightly build, think we can close this item.
