### ISSUE TITLE
Create builds for zowe-install-test on TSS/ACF2

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#712]
Depends on #711

Fan-out the zowe-install-test build to also run against the TSS and ACF2 LPARs.

- Some tests will not work out of the box
- Security manager commands are the likely reasons for failure
- Investigate where security commands are run
  - ACF2 will require JCL
  - CUPIDS: is JCL the long-term plan for install security commands?

**Comment by jackjia-ibm** [comment]
We have enabled ACF2/TS tests on nightly build, think we can close this item.
