### ISSUE TITLE
Sonarqube Fail build on quality gate failure

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#723]
Research and implement a configurable option for failing builds when the sonarqube quality gate is a failure.

Note: Changes to files like Jenkinsfile triggers quality gate failures, research how to handle this as well.

**Comment by jackjia-ibm** [comment]
Related to https://github.com/zowe/jenkins-library/issues/11

**Comment by jackjia-ibm** [comment]
Interesting point from SonarSource blog: https://blog.sonarsource.com/why-you-shouldnt-use-build-breaker. We will implement with option to enable/disable, so should be ok.

**Comment by jackjia-ibm** [comment]
Implemented in https://github.com/zowe/jenkins-library/pull/37 and tests https://wash.zowe.org:8443/job/jenkins-library/job/staging/20/console passed.

Option is boolean `failBuild`.
