### ISSUE TITLE
Validate root and user directory permissions

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#724]
Vaidate 
rootDir
usrDir
have correct permissions.  
usrDir has to have X all the way up its stack and exact for W for STC user ID which is IZUSVR by default
rootDir has to have the same

scripts/utils

code already exists in api-mediation-layer    validateAPIMLVariables

call in run-zowe.sh

**Comment by stevenhorsman** [comment]
Slight complication with the design - if root_dir is not accessible then we can't run any of our scripts!
