### ISSUE TITLE
clarify install-apf-server.yaml STC group description 

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#737]
The comment in `zowe-install-apf-server.yaml` says
```
# STC user group (required if either STC user or profile doesn't exist)    
stcGroup=                                                                  
```
which implies that it can be left blank if STC user exists.  As I chose IZUSVR, which exists, I found
```
Define STC prefix ZWESIS with STC user IZUSVR and GROUP=STCGROUP (SAF=RACF)
```
So ZWESIS01 was started with a blank OWNER instead of IZUSVR.  

The doc says
```
users:stcGroup is the user group that the ZWESIS01 started task will be run under. Enter the same values as the
user group that is running ZOWESVR, so choose IZUADMIN.
``` 
which is fine but the comment in the yaml file could be clearer.

**Comment by Joe-Winchester** [comment]
Close issue as zowe-install-apf-server is removed from 1.8
