### ISSUE TITLE
Create PTF builds

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#738]
Currently smpe-packaging creates the initial AZWE001 FMID. This is a packaging of a convenience build and distribution as JCL APPLY and RECEIVE Jobs

This epic is to track the ability for us to create PTF builds that can be applied on top of the initial FMID that represent convenience builds created post initial FMID

1. Jenkins Pipeline to build PTF out of zowe.org. This needs information on old/new PTFs. Need to find a away for shell scripts to access this data, perhaps old PTF numbers need to be stored in a github file and pull/push by the packaging script
2. All PTFs supersede old previous ones and represent a rollup
3. Possible way to create an install that includes all PTFs so customers don't need to install initial FMID and apply PTF. (phase 2)
4. Should be able to create interim build at any point in middle of release, even when PTF is not finalized for intermin testing.

**Comment by OnnoVdT** [comment]
I would say this is as dup of https://github.com/zowe/zowe-install-packaging/issues/759. Can we merge and close one ?
