### ISSUE TITLE
zosmfServer log in wrong code page if _BPXK_AUTOCVT=OFF

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#739]
`/var/zosmf/data/logs/zosmfServer/logs/messages.log ` is tagged with CCSID=819 and convert=yes.  If you have `_BPXK_AUTOCVT=OFF`, the log file won't be converted to EBCDIC and so it will appear garbled when you read it with `grep`, `cat` and so on.  

Nowadays the `zowe-install.sh` will set  `_BPXK_AUTOCVT=OFF`, which will of course not persist after that shell script exits.  So the actions performed inside install are independent of the initial environment, but if that ends up having  `_BPXK_AUTOCVT=OFF`, you will see this error.

**Comment by John-A-Davies** [comment]
You need to EXPORT the shell variable for it to be in effect:
```
export _BPXK_AUTOCVT=ON
head /var/zosmf/data/logs/zosmfServer/logs/messages.log
```
The above should produce legible text.

For reference, 
```
ls -TE /var/zosmf/data/logs/zosmfServer/logs/messages.log
t ISO8859-1   T=on  -rw-rw----  --s-  1 IZUSVR   IZUADMIN  235746 Sep 19 22:13 /var/zosmf/data/logs/zosmfServer/logs/messages.log
```

**Comment by John-A-Davies** [comment]
The `zosmfserver` log should be 819 and tagged for convert, so it's reasonable to set  _BPXK_AUTOCVT=ON.  I'd assert that  _BPXK_AUTOCVT should always be set ON.

**Comment by stevenhorsman** [comment]
We don't need to use the z/OSMF log now, so closing
