### ISSUE TITLE
Create PDS for load module and PDS SAMPLIB at install time

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#740]
Add the following lines to zowe-install.yaml
```
install:    
  # High Level Qualifier of SZWE* data sets  
  datasetprefix={userid}.ZWE
```

When `zowe-instal.sh -I` is run the installer should

Check/create two data sets. One for the load library, one for the SAMPLIB content
Stick content into the two
```
{datasetprefix}.SZWEAUTH
     ZWESIS01          
{datasetprefix}.SZWESAMP
     ZWESISPRG (single RACF command to APF auth the LOADLIB ZWESIS01)
     ZWESIP00   (parmlib for x-mem)
     ZWESISCH
     ZWESISMS
     ZWESISTC   (proc for x-mem taken from zss.pax->SAMPLIB/ZWESIS01
     ZOWESVR    (this should be our proclib)
```

/xmem-server/zss.pax contains

SAMPLIB
   ZWESIP00  ZWESIS01  ZWESISCH  ZWESISMS
LOADLIB
   ZWESIS01
zssServer

ZWESIP00, ZWESISCH, ZWESISTC all come from zss.pax

**Comment by John-A-Davies** [comment]
Datasets named `hlq.ZWE.SZWEAUTH` and `hlq.ZWE.SZWESAMP` will be populated by the convenience build or SMP/E build.   It's then up to the customer to copy the contents of SZWE* to his live installation datasets.  
When we undo the install, RESTORE (in the SMP/E case) will undo those actions on those datasets.   It's up to the customer to restore their live datasets, if required.

**Comment by stevenhorsman** [comment]
@Joe-Winchester - why is the PDS creation only done if `zowe-install -I` is used? Why would we change the behaviour if you do install and config in two steps rather than one?

**Comment by OnnoVdT** [comment]
PDS creation should be done in every scenario, SMP/E vs non-SMP/E for install, and with or without immediate configuration.

**Comment by OnnoVdT** [comment]
see https://github.com/zowe/zowe-install-packaging/pull/763, it does the MVS artifact provisioning.
