### ISSUE TITLE
Move keystore out of api-mediation layer and refactor scripts into zowe-install-packaging

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#741]
**Update**: A new design has been discussed in the CUPIDS scrum. The picture describes certificates refactoring and how it fits to the overall installation rework effort. 

![zowe-certificates-refactoring](https://user-images.githubusercontent.com/55885025/69620474-bc836a80-103d-11ea-8021-b843f0e9e5dd.png)

An example of zowe-certificates.env output file:
```
TOMVI02:/a/tomvi02/zowe: >less ~/zow-keystore/keystore/zowe-certificates.env
  KEY_ALIAS=somealias
  KEYSTORE_PASSWORD=password
  KEYSTORE=/a/tomvi02/zow-keystore/keystore/somealias/somealias.keystore.p12
  TRUSTSTORE=/a/tomvi02/zow-keystore/keystore/somealias/somealias.truststore.p12
  KEYSTORE_KEY=/a/tomvi02/zow-keystore/keystore/somealias/somealias.keystore.key
  KEYSTORE_CERTIFICATE=/a/tomvi02/zow-keystore/keystore/somealias/somealias.keystore.cer-ebcdic
  ZOWE_APIM_VERIFY_CERTIFICATES=true
  ZOSMF_USERID=IZUSVR
  ZOSMF_KEYRING=IZUKeyring.IZUDFLT
```
_________________________________________________________________________________________________________
**Original description:** 
In the last 2 months as the design for install and configuration has changed we need to update this item:
- The current plan is to create a script <zowe-root-dir>/bin/zowe-setup-certificates.sh which is run once post install and creates the keystore. As we will no longer have the yaml any parameters that this needs will need to be passed in as arguments, or have a default values. This script will create the keystore directory and artifacts as before, but cannot be in the zowe-root-dir directory as this will be locked down and read-only, so we need a new default location for it.
  **Question** - what should the new default keystore directory location be /global/zowe/keystore?
At the end of the script if the defaults aren't used it should prompt the user with the correct setting to copy into their instance.env files. Something like:
```
The keystore has been created in /u/zoweuser/zowe/keystore. The use this in zowe instances, please replace the following entries in instance.env files in the zowe instance directory:
KEY_ALIAS=my_key
KEYSTORE_PASSWORD=passw0rd
KEYSTORE_DIRECTORY=/u/zoweuser/zowe/keystore
```
As part of this item the rest of the associated keystore entries in instance.env template should be reviewed to ensure they are kept up to date.
The existing code that calls the certificate setup in zowe-configure should be removed.

The documentation will need reviewing and update as part of this work also to explain the new flow.

As part of this - or split into a separate issue - we've heard reports from customers who are unhappy that the code that imports the zosmf keystore has to have permits to access the zosmf private key instead of the public key. The suggestion (Petr's I think) is that we connect to the HTTP server and get the public key that way, or document a RACF command that will do it (Onno's suggestion).

**Comment by VitekVlcek-Broadcom** [comment]
zosmf keystore
 * add --zosmf-host <zosmf_host:port>  (open ssl route)
* add --file  <file with z/osmf public key>  optionaly --dataset  <dataset with z/osmf public key>  (this is for Onno route)
* we can preserve former key tool aproch for back compatibility

Example how to extract zosfm cert using openssl
```
ZOSMF_CERT_FILE=$ZOWE_INSTALL_ROOT/components/api-mediation/keystore/localhost/zosmf.cer
ZOWE_P12_FILE=$ZOWE_INSTALL_ROOT/components/api-mediation/keystore/localhost/localhost.truststore.p12
echo "Downloading z/OSMF certificate from $ZOWE_ZOSMF_HOST:$ZOWE_ZOSMF_PORT to $ZOSMF_CERT_FILE"
echo -n | openssl s_client -connect $ZOWE_ZOSMF_HOST:$ZOWE_ZOSMF_PORT | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > $ZOSMF_CERT_FILE
echo "Importing z/OSMF certificate '$ZOSMF_CERT_FILE' into '$ZOWE_P12_FILE'"
keytool -importcert -trustcacerts -alias ZOSMF -keyalg RSA -keystore $ZOWE_P12_FILE -keypass password -storepass password -storetype PKCS12 -file $ZOSMF_CERT_FILE -noprompt
```

**Comment by nkocsis** [comment]
@VitekVlcek-Broadcom Vitek, will this be completed by v1.8.0 (Dec 17) ?
