### ISSUE TITLE
install-SMPE-PAX.sh is expecting AZWE001.readme.txt to be in ASCII form on zOS

### ISSUE THREAD

**Issue by kathysychan** [zowe/zowe-install-packaging#745]
The script install-SMPE-PAX.sh is expecting AZWE001.readme.txt to be in ASCII form on zOS and convert it to EBCDIC as one of it's steps. However, the documentation on 

https://docs.zowe.org/stable/user-guide/install-zowe-smpe.html#upload-the-download-package-to-the-host

tells user to "upload the AZWE001.readme.txt file in text format". When user upload it as text format, it will be changed from ASCII to EBCDIC causing the script to fail. The script should expect the readme file to be in EBCDIC on zOS and skip the convert to EBCDIC step to be consistent with user expectation.

**Comment by kathysychan** [comment]
@John-A-Davies for your awareness

**Comment by John-A-Davies** [comment]
@jackjia-ibm When the Jenkins pipeline copies text files from the build machine to River or Marist for testing, does it convert ASCII to EBCDIC?  If not could that be done, so that the `install-SMPE-PAX.sh` script can have an EBCDIC file just like the real customer would?

**Comment by jackjia-ibm** [comment]
@John-A-Davies yes the iconv step can put in `temp-fixes-before-install.sh` script to properly prepare for the install.

**Comment by stevenhorsman** [comment]
Issue moved to [zowe/zowe-install-test #173](https://github.com/zowe/zowe-install-test/issues/173) via [**ZenHub**](https://www.zenhub.com/)
