### ISSUE TITLE
Implement Organizational Diversity on Grimoire Lab Report

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#747]
Reference: https://chaoss.community/metric-organizational-diversity/

**Comment by GeorgLink** [comment]
Managing identities and affiliations with GrimoireLab is easiest done with Hatstall:
https://github.com/chaoss/grimoirelab-hatstall/blob/master/docs/README.md

**Comment by jackjia-ibm** [comment]
The report had been updated to break down by organizations. There are some committers I couldn't figure out which companies they are from, so we can still see some contributions are categorized as Unknown.

Please check and let me know how we can improve. Also feel free to message me if you need help on demo how Hatstall works.

**Comment by jackjia-ibm** [comment]
I will close this issue for now. Please feel free to re-open if there are improvements should be done.
