### ISSUE TITLE
Investigate Jenkins is not sending out email notifications

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#75]

**Comment by jackjia-ibm** [comment]
This issue turns to IBM internal email server issue. Had created an internal ticket and waited for progress update.

**Comment by MarkAckert** [comment]
@jackjia-ibm Is this still an issue? I believe e-mail is working now.

**Comment by jackjia-ibm** [comment]
@MarkAckert the issue still exists but looks like only me is affected. The support team said they white list the domain or email, but still didn't work for me. I setup alternative email to receive the notifications to solve the issue.
