### ISSUE TITLE
zowe-verify.sh is too restrictive in its checks.

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zowe-install-packaging#751]
zowe-install-packaging/scripts/zowe-verify.sh is too restrictIive in its checks. 
Checks are made on fixed values, such as user IZUSVR, group IZUADMIN, server names ZWESIS01/ICSF/CSF. 

At our site we have specific naming conventions for users, groups, server names, etc. that require us to assign different names to these items. Hence, the zowe-verify.sh is not helping us much in verifying the installation.
Is it possible to enable the script to accept customized values?

**Comment by John-A-Davies** [comment]
We're in the process of moving hard-coded user ids like IZUSVR into variables.  Some, like 
` zosmfUserid=IZUSVR`
` zosmfAdminGroup=IZUADMIN`
 were already in `.yaml` files, but `.yaml` files are being superseded by `.env` files.  When that's resolved, `zowe-verify.sh` will be updated.

**Comment by stevenhorsman** [comment]
@FreekCornelis - As of 1.8 the user and groups associated with starting zowe have changed and documentation state that zowe-verify is not updated to match, so from 1.9 it will be removed
