### ISSUE TITLE
zowe-install.sh requires installation ZFS to be mounted R/W

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zowe-install-packaging#752]
Running 'zowe-install.sh -I' from a Zowe installation ZFS in R/O mode shows:

mkdir: FSUM6404 directory "/SYSTEM/var/zowe/lpp/zowe-1.4.0-install/temp_2019-09-11": EDC5141I Read-only file system

where the Zowe ZFS is mounted on /SYSTEM/var/zowe/lpp/. 
Usually, ZFSes containing software are to be mounted in R/O mode in order to prevent corruption as much as possible. We would like Zowe installation to adhere to rule that as well.  

In order to temporarily bypass this, I modified the setting of the TEMP_DIR variable value in the script to:
export TEMP_DIR=/tmp/zowe_"`date +%Y-%m-%d`"_$(whoami)  
and remounted the ZFS in R/O mode. That works fine for us.
The user id of the invoker is added as a precaution to the directory name in order not to block some other user from invoking the install script.

We are running Zowe SMP/E Alpha, v1.4.0

**Comment by 1000TurquoisePogs** [comment]
Indeed - moving towards separating our config from our content so that we can have a clear list of directories to be made r/o.

**Comment by Joe-Winchester** [comment]
@OnnoVdT - for 1.8 with the 755 and the read only runtime directory I think this issue can be closed.  Do you agree ?

**Comment by OnnoVdT** [comment]
when 1.8 goes live I plan on running it on my system and will do so with the filesystem R/O to ensure this issue is done.

**Comment by FreekCornelis** [comment]
Hi @OnnoVdT 
I just installed 1.8.0 and I still needed to mount it R/W for the installation. That is, I installed the convenience build, extracted the pax contents into a ZFS that I then mounted R/O (similar to the situation when a SMP/E installation would be done). Running zowe-install.sh resulted in errors regarding the log location on a R/O ZFS.

In order to be able to run the install script with the ZFS in R/O mode , I adjusted the install script as follows:
Replace 
  export LOG_DIR=$INSTALL_DIR/log  
with
  export LOG_DIR=/var/zowe/log
(or some other location outside the ZFS, could be set using to a location in /tmp/ or via an environmental variable) and replace
  export TEMP_DIR=$INSTALL_DIR/temp_"`date +%Y-%m-%d`"  
with
  export TEMP_DIR=/tmp/zowe_"`date +%Y-%m-%d`"_$(whoami)
The suffix $(whoami) is useful to prevent errors when the TEMP_DIR is not cleaned up correctly afterwards. After making these adjustments, I was able to run to the install script without problems using the ZFS mounted in  R/O mode.

**Comment by FreekCornelis** [comment]
I suppose that the setting of INSTALL_DIR
> export INSTALL_DIR=$(cd $(dirname $0)/../;pwd) 
incorrectly assumes that that directory resides in a R/W environment. In our case, $INSTALL_DIR would point to 
> /var/zowe/lpp/zowe-1.8.0
containing
![image](https://user-images.githubusercontent.com/55885539/74420225-5ee80880-4e4b-11ea-9be5-3af29926a37f.png)
and IMHO this content should reside in a R/O ZFS. But as it is now, the install script still tries to create the TEMP_DIR AND LOG_DIR directories in this directory.

**Comment by OnnoVdT** [comment]
@stevenhorsman can you correct this as part of the other fixes you are doing?

**Comment by Joe-Winchester** [comment]
Maybe there should be an additional parm that allows the TEMP_DIR and LOG_DIR to be passed in, e.g. -l, or perhaps if it is detected that the install dir is R/O then given TEMP_DIR and LOG_DIR aren't mandatory, the installer could just choose ~/zowe-install-log/ and use these and just echo to the user what it's doing.

**Comment by stevenhorsman** [comment]
#1099 should have fixed this - available in nightly builds, or 1.9
