### ISSUE TITLE
Work out the best way to create the api-catalog iframe plugin

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#754]
Currently zowe-configure.sh does `. $CONFIG_DIR/zowe-install-iframe-plugin.sh $ZOWE_ROOT_DIR "org.zowe.api.catalog" "API Catalog" $CATALOG_GATEWAY_URL $ZOWE_ROOT_DIR"/components/api-mediation/api-catalog.png"` to create the api-catalog app

This needs moving to the configure step of the APIML and only run if the desktop component is in the launch config. It also might need refactoring to use the new install-app script to avoid the need for deploy.sh to run, so needs to wait for the zaf enhancements.

**Comment by 1000TurquoisePogs** [comment]
Alternatively: should this ability instead be pulled into the zaf repos so that various plugins can utilize it in the future?

**Comment by stevenhorsman** [comment]
Absolutely - I was hoping that the new way is - call the new installApp program that you've shown before and then we can remove the utils script (or longer term I'd love ZAF to ask the APIML what iframe UI plugins are registered and dynamically add them, but that's bit further in the future)
