### ISSUE TITLE
Create SMP/E PTF builds

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#759]
Currently smpe-packaging creates the initial AZWE001 FMID. This is a packaging of a convenience build and distribution as JCL APPLY and RECEIVE Jobs

This epic is to track the ability for us to create PTF builds that can be applied on top of the initial FMID that represent convenience builds created post initial FMID

Pipeline to build PTF out of zowe.org. This needs information on old/new PTFs. Need to find a away for shell scripts to access this data, perhaps old PTF numbers need to be stored in a github file and pull/push by the packaging script
All PTFs supersede old previous ones and represent a rollup
Possible way to create an install that includes all PTFs so customers don't need to install initial FMID and apply PTF.
Should be able to create interim build at any point in middle of release, even when PTF is not finalized for intermin testing.

This is a [copy of](https://github.com/zowe/zowe-smpe-packaging/issues/25) where the repo `smpe-install` has been archived

1. Make `zowe-install.sh` be able to be driven by `smpe.sh` and its subscripts

**Comment by mpanch59** [comment]
[Service flow(1).pptx](https://github.com/zowe/zowe-install-packaging/files/3680052/Service.flow.1.pptx)

**Comment by stevenhorsman** [comment]
Dup of #738
