### ISSUE TITLE
Change zowe-install.sh to allow parms to drive rootDir and datasetPrefix

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#765]
Add new function to `zowe-install.sh` 

`zowe-install.sh -i rootDir ` to install to a specific USS path (taks preference over the one specified in `install:rootDir` in the `zowe-install.yaml`

`zowe-install.sh -h datasetPrefix` to install the load lib and samplelib into a specific place (takes preference over the one specified in install:datasetPrefix in the zowe-install.yaml

**Comment by OnnoVdT** [comment]
provided as part of https://github.com/zowe/zowe-install-packaging/pull/763

**Comment by stevenhorsman** [comment]
Completed by #827
