### ISSUE TITLE
Convenience script to move ZWE.SZWESAMP(ZWESVSTC) to JES concatenation path

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#766]
Create a `/scripts/utils/zowe-install-proc.sh` that does JES concatenation path scanning and takes parameters of dsName and memberName, e.g.
1. `zowe-install-proc.sh {prefix}.SZWE.SZWESAMP auto` which copies from {prefix}.SZWESAMP(ZWESVSTC) to the JES contacentation path keeping the name ZWESVSTC
3. `zowe-install-proc.sh {prefix}.SZWE.SZWESAMP HLQ.PDS.ZWE` which copies from {prefix} into `HLQ.PDS.ZWE(ZWESVSTC)`   
   
Update the pipeline to use this script rather than running xmem install and zowe-copy-proc

For the doc create a new section `Scripted Zowe install` that will describe this.  This is part of a separate story.

**Comment by John-A-Davies** [comment]
`scripts/utils/zowe-install-proc.sh` won't create HLQ.PDS.ZWE if it does not exist.  It could easily be created if required.

**Comment by stevenhorsman** [comment]
From reading the description it doesn't look like the source HLQ is passed into the script, so I think it might need modifying to add an argument and not just copy from ZWE.SZWESAMP as specified?

**Comment by Joe-Winchester** [comment]
Yes - we should have a parm for where the source comes from for `zowe-install-proc.sh`, e.g. '-s WINCHJ.JCL.SZWE.ZOWESVR`, but we should also possibly update the default one when we do the install so that if the proc is renamed during install then we update it.

**Comment by John-A-Davies** [comment]
As per defect #853, the current script fails because the member name ZOWESVR has been changed to ZWESTC.  So the input DSN is now `${ZOWE_DSN_PREFIX}.SZWESAMP(ZWESTC)`.  But we also have the XMEM proc in SZWESAMP too - do we want to be able to handle that as well?

**Comment by John-A-Davies** [comment]
To enable this script to also copy the cross-memory server PROCLIB members, I propose pre-pending the name of the source member to be copied to the existing parameter list.  For example
`zowe-install-proc.sh ZWESVSTC HLQ.PDS.ZWE ZOWEXXX`
`zowe-install-proc.sh ZWEXMSTC HLQ.PDS.ZWE ZOWEXXX`
`zowe-install-proc.sh ZWEXASTC HLQ.PDS.ZWE ZOWEXXX`
So now the first parameter is the name of the member to be copied from `{datasetprefix}.SZWESAMP`.  If the specified member name is not in that PDS, the script will say so and terminate.

All other parameters remain as before.

@stevenhorsman Please comment.

**Comment by stevenhorsman** [comment]
As I mentioned above I still think we need to make sure the source HLQ is passed into the script otherwise it won't know where to find the pds members regardless of their names. I'm also not sure about  having to move the started tasks 1 at a time I think that the 'install' of all of the XMEM started tasks, loadlibs, parm entries etc should be done at the same time to stop a user having to run several different scripts.
I'm also not sure how ZWESECUR fits in to this. Are we expecting users to run it from the SAMPLIB data set directly, or to move it first? @OnnoVdT - do you have any thoughts?

**Comment by John-A-Davies** [comment]
My intended implementation of `zowe-install-proc.sh`  acquires the source DSN as `datasetPrefix` from `configure/zowe-install.yaml`.  

The problem I have is that the xmem server PROCs need tailoring to replace the LOADLIB and PARMLIB DSNs with the customer's choice.  (Script `install-xmem-server.sh` in `zowe-install-test` already does this.)  I could acquire those choices from `zowe-install-apf-server.yaml` like it does today.

The ZOWESVR PROC (now ZWESVSTC) is already parameterised with INSTANCE=, so it doesn't need tailoring.  

@stevenhorsman @OnnoVdT Please comment.

**Comment by stevenhorsman** [comment]
`configure/zowe-install.yaml` and `zowe-install-apf-server.yaml` will shortly be deleted, so you can't rely on that.
Could you have a separate script for configuring the xmem server that has parameters for PROCLIB, LOADLIB and PARMLIB?


> The ZOWESVR PROC (now ZWESVSTC) is already parameterised with INSTANCE=, so it doesn't need tailoring.

I'm not sure what you mean by this. There is not automatic parameter injection, but I don't know that it is needed?

**Comment by John-A-Davies** [comment]
I've placed 3 scripts to perform these tasks in https://github.com/zowe/zowe-install-packaging/tree/copy-PROCLIB-members/scripts/utils
You can test them on 3b by running
```
zowe-install-proc.sh zoe.smpe
zowe-install-xmem.sh zoe.smpe ZOE.ZIS.SZISLOAD ZOE.ZIS.PARMLIB
```
You will need
```
# Needs ../internal/opercmd to check JES concatenation
# Needs ./mcopyshr.clist to write to the target PDS
```
Script `opercmd ` is shipped in the `scripts` directory.
