### ISSUE TITLE
Add plugins to launch bar

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#79]
zlux has changed to only show plugins to the launch bar if they are in <zowe-install-dir>/zlux-example-server/pluginDefaults/com.rs.mvd.ng2desktop/ui/launchbar/plugins/pinnedPlugins.json
Decide what the default pinned apps should be and update the install so that they show up.

**Comment by 1000TurquoisePogs** [comment]
Note that the plugin's name has now become org.zowe.zlux.ng2desktop
