### ISSUE TITLE
Lifecycle Management - restart components using console modify command

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#790]
**Is your feature request related to a problem? Please describe.**
The STC ZOWESVR brings up all of the address spaces for the Zowe runtime stack.  Customers may wish to drop and recycle individual servers without rebooting the whole stack.  For example, just bounce the explorers, or bring up the explorers that weren't in the initial startup, without having to stop and start the entire STC.

**Describe the solution you'd like**
Lifecycle Managment - add the ability to restart components by issuing a console modify command

**Comment by ifakhrutdinov** [comment]
@Joe-Winchester I've implemented this in https://github.com/ifakhrutdinov/zowe-launcher.

For example, you can do
```
F ZLAUNCH,APPL=STOP(api-mediation)
F ZLAUNCH,APPL=START(api-mediation)
```

**Comment by 1000TurquoisePogs** [comment]
Implemented and documented here https://docs.zowe.org/stable/user-guide/start-zowe-zos
