### ISSUE TITLE
Containerise Zowe

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#793]
With (among other things) the introduction of z/OS Container Extensions customers have started asking about running bits of Zowe under zCX, or off platform in containers.
I think there are 2 potential drivers here:
 - Simplicity - rather than having to do SMPE install of the Java/Node microservices and mange HA environments, if we could install and lifecycle these via docker containers and something like kubernetes & helm to make it easier to get set up and simpler for us and customers to manage. This could also make development easier and attract new third parties as a result.
- Pricing - currently node is not ziip eligible, but zCX is, so allowing customers to run in zCX, or off platform would remove another hurdle for adoption of the zowe server.

@VitekVlcek-Broadcom has started some work under https://github.com/zowe/zowe-dockerfiles/blob/master/dockerfiles/zowe-1.5.0/README.md, but we'll probably need to break it down more and extend it going forward.

**Comment by 1000TurquoisePogs** [comment]
We've made good progress so far in getting a post-cupids docker image: https://github.com/zowe/zowe-dockerfiles/tree/master/dockerfiles/zowe-release/zowe-1.11.0

**Comment by 1000TurquoisePogs** [comment]
Unknown to me: Is kubernetes and helm and docker swarm technologies that can be used on top of any plain-old docker image, or do we need to carefully craft our docker image to be compatible?

**Comment by 1000TurquoisePogs** [comment]
Is docker swarm even the same concept as kubernetes?
Sounds like: 
- a swarm is a pool of hardware to dish out docker images to
- kubernetes is about orchestration of multiple images

**Comment by 1000TurquoisePogs** [comment]
Survey showed that Docker on intel linux was more desired (popularity contest) over zlinux, which also won over zcx. So, we'll start with intel linux first, and hopefully it will be easy to make the others work soon after.

**Comment by 1000TurquoisePogs** [comment]
"A fundamental difference between Kubernetes and Docker is that Kubernetes is meant to run across a cluster while Docker runs on a single node. Kubernetes is more extensive than Docker Swarm and is meant to coordinate clusters of nodes at scale in production in an efficient manner."

**Comment by 1000TurquoisePogs** [comment]
Initial end goal: Be able to take release code and make it available via Docker, on zowe.org, as a beta. Gather feedback, strive for simplicity of configuration.
Beta: AT-TLS for ZSS, because although it's extra configuration, trying to implement HTTPS within ZSS itself is a project of its own.

**Comment by 1000TurquoisePogs** [comment]
Open question: one docker image for all components, or docker images for each components?

**Comment by 1000TurquoisePogs** [comment]
UX question: what's the most elegant way to utilize plugins & static registrations without modifying the docker image?

**Comment by 1000TurquoisePogs** [comment]
Can we make a mock server for ZSS? One already partially exists for zosmf.
This would make it so that the docker image wouldnt even require zos for development.
This sounds like a stretch goal, but it would be excellent.

**Comment by jackjia-ibm** [comment]
Related High Availability topic https://github.com/zowe/zowe-install-packaging/issues/793

**Comment by 1000TurquoisePogs** [comment]
Completed in v2
