### ISSUE TITLE
zowe-install.sh -i <rootdir>

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#794]
*Customer content*

zowe-install.sh currently always relies on the content of the yaml file to decide where to install, which by default is the user's home directory. This is troublesome for automated install (for example to do the SMP/E packaging of Zowe), as here specific directories must be used to avoid concurrent install runs clashing with each other. Also adding code to the install automation to alter the yaml file adds another layer of complexity, as now that code must be kept in sync with the format of the yaml file.

**Describe the solution you'd like**
I propose that zowe-install.sh accepts a new startup argument, -i <rootdir>, that overrides the rootdir value in the yaml file. This way, automated install can simply specify the desired location as part of the zowe-install.sh invocation.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by OnnoVdT** [comment]
subset of issue https://github.com/zowe/zowe-install-packaging/issues/765

**Comment by stevenhorsman** [comment]
completed by #827
