### ISSUE TITLE
zowe-install.sh -h <high-level-qualifier>

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#796]
*Customer content*

**Is your feature request related to a problem? Please describe.**
Similar to issue 794 (zowe-install.sh -i <rootdir>)
Zowe-install.sh currently always relies on the content of the yaml file to decide where to install the MVS datasets, which by default is the user's userid. This is troublesome for automated install (for example to do the SMP/E packaging of Zowe), as here specific high level qualifiers must be used to avoid concurrent install runs clashing with each other. Also adding code to the install automation to alter the yaml file adds another layer of complexity, as now that code must be kept in sync with the format of the yaml file.

**Describe the solution you'd like**
I propose that zowe-install.sh accepts a new startup argument, -h , that overrides the datasetPrefix value in the yaml file. This way, automated install can simply specify the desired location as part of the zowe-install.sh invocation.

**Describe alternatives you've considered**
none

**Additional context**
none

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by OnnoVdT** [comment]
subset of issue 765, https://github.com/zowe/zowe-install-packaging/issues/765

**Comment by stevenhorsman** [comment]
Completed by #827
