### ISSUE TITLE
hardcoded /tmp usage

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#799]
**Describe the bug**
Several scripts hardcode the usage of /tmp. Some customer sites do not allow users to write to /tmp (reserved for system task to avoid a user filling up /tmp and impacting system tasks). These customers set USS system envvar TMPDIR to redirect temporary allocations elsewhere.

**To Reproduce**
See
install/zowe-check-prereqs.sh
scripts/zowe-verify.sh
apiml_cm.sh
zowe-copy-to-JES.sh

**Expected behavior**
All temporary files should either go to TEMP_DIR (defined for install scripts) or TMPDIR (used by USS itself). /tmp can be used as default if TMPDIR is not defined: ${TMPDIR:-/tmp}

**Comment by shivanshs9** [comment]
Hi, @OnnoVdT! I've opened a PR for this issue. Could you please check it out?
