### ISSUE TITLE
zowe-install.sh -f <logfile>

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#801]
*Customer content*

**Is your feature request related to a problem? Please describe.**
zowe-install.sh currently always decides how to name the log file which by default is LOG_FILE=$INSTALL_DIR/log/$(date +%Y-%m-%d-%H-%M-%S).log. This is troublesome for automated install to do the SMP/E packaging of Zowe, as now the install-log of the SMP/E-specific parts cannot be added, nor can the log be saved as part of the build output for future reference.

**Describe the solution you'd like**
I propose that zowe-install.sh accepts a new startup argument, -f , that overrides the default LOG_FILE definition. This way, automated install can simply specify the desired location as part of the zowe-install.sh invocation.

**Describe alternatives you've considered**
none

**Additional context**
none

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by OnnoVdT** [comment]
related to issue https://github.com/zowe/zowe-install-packaging/issues/752

**Comment by stevenhorsman** [comment]
Covered by #1154 which adds log directory parameter for all install/config scripts

**Comment by OnnoVdT** [comment]
Not exactly covered, as #1154 handles the log directory, not the log file name. I'll alter the smpe script to do a rename to a known name (and location).

**Comment by stevenhorsman** [comment]
Yep - sorry Onno, I should have been more specific - what I meant to say is that with -l for the directory being rolled out across all our scripts I'm not sure that -f specifying the file as well on zowe-install.sh makes much sense. It is worth noting that the zowe-install.sh actually has always moved it's log into the runtime installed environment at the end of the script, so it is accessible from the root directory, so an option is to grab it from there as needed?

**Comment by OnnoVdT** [comment]
Copying it to runtime is what we do NOT want for SMP/E, as it our install log, not SMP/E's. The smpe script trashes any log dirs it finds after install in the target staging area. The build logs are kept in a separate location that also goes to artifactory in case we need it for problem solving.
with -f smpe can tell zowe-install.sh which file to write logs too and be done with it. Even if the install fails we have the log up to that point tucked away for review.
