### ISSUE TITLE
zowe-install.sh misses error handling

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#802]
**Describe the bug**
zowe-install.sh continues processing when it encounters an error, wasting resources as the install must be done again after the root cause for the error is resolved. The additional messages that come from the continued processing also result in it being harder to spot the error message.

**To Reproduce**
There are lots of ways to introduce an error. This example makes the install directory read-only before install.
mkdir ~/zowe
chmod 555 ~/zowe
zowe-install.sh -I

**Expected behavior**
halt on first serious error

**Screenshots**
none

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
none

**Comment by OnnoVdT** [comment]
Issue with the v1.11 master build:
https://wash.zowe.org:8443/job/zowe-install-packaging/job/master/806/consoleFull
zowe-install.sh failed during build of SMPE package with `no space left on device` but kept on going and ended with RC 0, making the SMPE build script think everything was good. Luckily the MVS members were also victim of the no space, and the SMPE build trapped the error later on when it verified all SMPE-managed parts were present.

**Comment by OnnoVdT** [comment]
related issue: 
https://github.com/zowe/zowe-install-packaging/issues/803

**Comment by stevenhorsman** [comment]
#related to #1298

**Comment by Martin-Zeithaml** [comment]
Closing as V1 is out of support.
