### ISSUE TITLE
SAMPLIB members created have values set

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#808]
Raising on behalf of @Joe-Winchester, so I might have some of the details incorrect:

As a result of #749, when creating the SAMPLIB member entries:
- In ZOWESVR {{root_dir}} field is not filled in forcing customers to edit this to inject it. (I'm not sure the reasoning behind this decision though)
- In ZWESIPRG the DSNAME is hard coded to the SAMPLIB location, when we know that customer will need to move it to the JES2 proclib concatenation path, so this will be incorrect. I think we need to template this and then in the convenience script #766 should inject it.

**Comment by John-A-Davies** [comment]
1.  Script ` scripts/zowe-create-MVS-artefacts.sh` copies the ZOWESVR template into SAMPLIB unchanged.  SAMPLIB is shared by all instances of ZOWE, and the `{{root_dir}}` will be filled in for each instance under `${ZOWE_ROOT_DIR}` by #766 as required.  
2.  ZWESIPRG is a documentation member to show the systems programmer what manual commands to issue to authorise the SZWEAUTH PDS, which will be created at install time with `DSN=${ZOWE_DSN_PREFIX}.SZWEAUTH` by default.  Like SAMPLIB members, the SZWEAUTH member ZWESIS01 will need to be copied to a local authorised library by the systems programmer if the default `DSN=${ZOWE_DSN_PREFIX}.SZWEAUTH` is not suitable.
If #766 is extended to cover copying of ZWESIS01, then the manual instructions in ZWESIPRG would be edited at that point.  Only ZOWESVR should be moved to the JES concatenation.

**Comment by John-A-Davies** [comment]
This needs to tie up with ` zowe-install-packaging/install/zowe-install-apf-server.sh` which edits the PROC, parm and yaml for the XMEM server.

**Comment by OnnoVdT** [comment]
I have scripts to take SAMPLIB and create customized members in staging SAMPLIB, PROCLIB, & JCL datasets. They were in my last bulk drop, but I'm not sure they made it into github. Give a shout if you want a copy.

**Comment by John-A-Davies** [comment]
@OnnoVdT 
Do you mean these?
for creating customized libs, look at
https://github.com/zowe/zowe-install-packaging/blob/onno-reference/onno-reference/zowe-configure-jcllib.sh
https://github.com/zowe/zowe-install-packaging/blob/onno-reference/onno-reference/zowe-configure-parmlib.sh
https://github.com/zowe/zowe-install-packaging/blob/onno-reference/onno-reference/zowe-configure-proclib.sh

**Comment by OnnoVdT** [comment]
yes

**Comment by stevenhorsman** [comment]
I think this is out of date now
