### ISSUE TITLE
zowe-install-apf-server.sh msg has (zss/samplib/ZWESISCH) in wrong case

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#817]
**Describe the bug**

The script `zowe-install-apf-server.sh` issues a message which has (zss/samplib/ZWESISCH) in wrong case. 

**Expected behavior**
It should be `(zss/SAMPLIB/ZWESISCH)`

**Comment by John-A-Davies** [comment]
Review this error msg once #953 is resolved.

**Comment by stevenhorsman** [comment]
file now deleted (and problem copied to #1009 )
