### ISSUE TITLE
Node 8.16.1 breaks desktop as it treats untagged node files differently to 8.16.0

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#818]
**Describe the bug**
Launching the Zowe desktop with node 8.16.1 breaks the desktop - graphics that are untagged are not opened, .js files that are untagged are not opened (so the TN3270 crashes, ...)

**To Reproduce**
Run Zowe desktop with node 8.16.1 - screen shots of broken login screen and TN3270 shown below.
Reported in the [Node Github repo issue 142](https://github.com/ibmruntimes/node/issues/142)
Doc workaround suggested to warn users of 8.16.1 and ask them to use 8.16.0 in [docs-site](https://github.com/zowe/docs-site/issues/773)

**Expected behavior**
There is a workaround for 8.16.1 where the environment variable `__UNTAGGED_READ_MODE=V6` can be set.  

This issue is to modify the Zowe startup scripts to set this variable

**Screenshots**
![image](https://user-images.githubusercontent.com/28100302/67048908-fc952a80-f12c-11e9-8ce2-579801a3e30a.png)

![image](https://user-images.githubusercontent.com/28100302/67049238-aaa0d480-f12d-11e9-995d-79a911e0e1dc.png)

![image](https://user-images.githubusercontent.com/28100302/67049259-b42a3c80-f12d-11e9-8b01-9167142ae2cb.png)

**Comment by 1000TurquoisePogs** [comment]
So, it looks like the icons that do show up are because the build process embedded them into JS as base64 content, and the ones that fail were referenced by URL. Investigating the distinction.

**Comment by 1000TurquoisePogs** [comment]
I am working on this now by making a script for tagging all things node reads.

**Comment by stevenhorsman** [comment]
8.16.1 is no longer on the node team's website and we doc'd not to use it, so closing this
