### ISSUE TITLE
Perform node sanity check at component startup

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#833]
*Customer content*

**Is your feature request related to a problem? Please describe.**
If node.js is mis-configured, unavailable or badly installed, components will fail to start but the reason for failure may not be clear.

**Describe the solution you'd like**
A basic health check by each component that uses node.js would confirm that node.js can at least display its version.
Components that require node.js should issue `node --version` at startup and log the result.  

**Describe alternatives you've considered**
This is already checked in the zowe-verify script, but that's optional.

**Additional context**
This caused a blocking problem for a customer.

---
*Engineering team info https://github.com/zowe/community/issues/336*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by stevenhorsman** [comment]
There is already an validate-node.sh script that checks this for the explorer UIs, hopefully once the zlux componentisation is done that will check it, or we could make it go at the top of run-zowe.sh so that it is always run first (along with a java check)?
