### ISSUE TITLE
Node v12 breaking changes to install proccesses that use inline Node to extract values from package.json

### ISSUE THREAD

**Issue by jordanCain** [zowe/zowe-install-packaging#842]
During the install process when using Node version 12 any use of node to extract values from package.json files will now return in the wrong codepage resulting in directories and properties within files to be unreadable. 

**To Reproduce**
1. Run Zowe install script using the standard shell (/bin/sh) with node v12
2. See directories in zowe install directory with unreadable names

**Expected behavior**
When using Node v12 the install should process should complete without error, all directories and file properties should be the same as they are for node 6 and 8

**Additional context**
An example of a place where the install process uses node to extract values is https://github.com/zowe/zowe-install-packaging/blob/master/scripts/configure/zowe-configure-explorer-ui.sh#L55 

We've been informed by the node js team that version prior to v12 were converting output to stdout/stderr but will no longer. 

Suggestions from the nodejs team are:
Script tagged -t -c 1047 should  work without other environment variables.

OR

set 
export _TAG_REDIR_ERR=txt
export _TAG_REDIR_IN=txt
export _TAG_REDIR_OUT=txt

**Comment by stevenhorsman** [comment]
@jordanCain - after the changes we made yesterday I think this should be fixed - we get passing builds against node 12 on the jenkins pipeline - but I didn't know if there was any other validation you wanted to do?
