### ISSUE TITLE
Modify test pipeline to execute ZWESECUR, rather than run zowe-config-stc.sh

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#848]
Now we have the JCL we need to test it in our pipeline

**Comment by John-A-Davies** [comment]
#1003 and install-test/#151 are complete

**Comment by John-A-Davies** [comment]
The blocker #877 is closed.  And the pipeline now uses ZWESECUR.  So can this be closed?

**Comment by stevenhorsman** [comment]
We need to have passing builds before we can close this and the SMPE ones are not currently working

**Comment by John-A-Davies** [comment]
SMP/E build is failing.  Awaiting input from @OnnoVdT to help debug it.

**Comment by OnnoVdT** [comment]
John found mismatched  dates for the files, pulling in @jackjia-ibm as well.

**Comment by jackjia-ibm** [comment]
I think we figured out why ZWESECUR job was failing, which is picking up a temporary file located on the server, not from the SZWESAMP data set. Fix is on the way.

**Comment by John-A-Davies** [comment]
@stevenhorsman Can this issue now be closed, as PR-156 of `install-test` is complete?

**Comment by John-A-Davies** [comment]
For completeness, we should also insert ZWENOSEC into the pipeline.
