### ISSUE TITLE
Resolve SAMPLIB member names

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#864]
There seems to be some confusion about what the SAMPLIB member names should be. They currently are:

ZWE.SZWEAUTH:
 - ZWESAUX
 - ZWESIS01

ZWE.SZWESAMP:
- ZWESECUR
- ZWESVSTC
- ZWEXASTC           change to `ZWESASTC`
- ZWEXMPRG         change to `ZWESIPRG`
- ZWEXMP00          change to `ZWESIP00`
- ZWEXMSCH         change to `ZWESISCH`
- ZWEXMSTC          change to `ZWESISTC`

We should decided on the final names and use this issue to ensure that everything is matching in docs

**Comment by stevenhorsman** [comment]
No disagreements, so this naming finalised for this iteration of CUPIDS.

**Comment by stevenhorsman** [comment]
All changes merged and build passing: https://wash.zowe.org:8443/job/zowe-install-test/job/staging/505/

**Comment by John-A-Davies** [comment]
1.  The cross-memory PARMLIB member's prefix is hard-coded to be ZWESIP, so I propose reverting its name to ZWESIP00.
2.  The cross-memory PROCLIB member names originally clashed with their corresponding LOADLIB members, violating the uniqueness-of-object-names requirement in SMP/E, so that change will persist and they will be called ZWEXASTC and ZWEXMSTC.  These PROCs should ideally also have ZWEXASTC and ZWEXMSTC respectively as their PROC names internally on the JCL PROC statement name.

**Comment by ifakhrutdinov** [comment]
@John-A-Davies Since some customers (and developers) have already set up their SAF rules to assign the STC user to `ZWESIS01` and `ZWESAUX`, likely using mask `ZWES*.*`, I propose naming them `ZWESISJ` and `ZWESAUXJ`.

**Comment by OnnoVdT** [comment]
@John-A-Davies @stevenhorsman It would help customers if we keep naming logic in sync across PROCLIB and PARLMIB, so I advise to drop the XM/XA suffix idea all together and revert back to the SI (already in use) and SA I used initially. These are less obviously tied to cross memory server, but at least there's a common logic.

**Comment by John-A-Davies** [comment]
@Joe-Winchester and @John-A-Davies revised the naming of the SAMPLIB members, to be more consistent.

**Comment by John-A-Davies** [comment]
Test of the install here https://wash.zowe.org:8443/job/zowe-install-test/job/update-SAMPLIB-names/8/console shows that all SAMPLIB member names are now as required in the heading of this issue.  This test consumed `libs-snapshot-local/org/zowe/1.7.1-ZIP-928-1-/AZWE001-1.7.1-zip-928-1--13-20191218104502.pax.Z`
