### ISSUE TITLE
Epic - Fulfill CII Badge Requirements

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#87]
https://bestpractices.coreinfrastructure.org/en - needs to be achieved before 1.0 release. 

Current badge status: https://bestpractices.coreinfrastructure.org/en/projects/2226

__Related issues:__
#85 
zowe/zlc#38

__Related to release notes:__
parent of zowe/docs-site#91

__Related to code linter:__
parent of zowe/explorer-jes#6
parent of zowe/explorer-model#1
parent of zowe/explorer-mvs#7
parent of zowe/explorer-server#6
parent of zowe/explorer-uss#2
parent of zowe/imperative#23
parent of zowe/orion-editor-component#10
parent of zowe/zlux#25
_These issues current estimated size are **S**._

__Related to security mechanisms:__
parent of zowe/explorer-server-auth#2
parent of zowe/zss-auth#2
_These issues current estimated size are **S**._

__Related to static code analysis:__
parent of zowe/explorer-server-tests#1
parent of zowe/imperative#24
parent of zowe/zlux#26
parent of zowe/zowe-install-test#13
_These issues require more research and testing on pipeline changes, current estimated size are **M**._

**Comment by MarkAckert** [comment]
Hi Jack,
I agree with your sizing estimates, and would estimate the security mechanisms as an "S". I may break this into smaller sized epics as this reflects a large amount of total work.
Thanks

**Comment by stevenhorsman** [comment]
The IBM Security team has recommended a tool for OWASP dependency checking:
There is also a CLI interface which allows for integration into many kinds of builds, but plug-ins for jenkins and gradle exist.
https://github.com/jeremylong/DependencyCheck
https://jeremylong.github.io/DependencyCheck/general/dependency-check.pdf

**Comment by MarkAckert** [comment]
Removed dynamic analysis from this epic; will create a new epic to track compliance with higher level CII Badges
