### ISSUE TITLE
Finalise property names in instance.env

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#870]
https://github.com/zowe/zowe-install-packaging/blob/staging/scripts/instance.template.env has the latest copy of the properties required to start up zowe.

We need to finalised our naming scheme and up date these property names for the last time.
In order to avoid clashes I've heard suggestions of prepending the component id (from https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#configuration-variables), or ZWE to each property that don't have a component. Beyond this do we want any other naming conventions?

This will have quite a big effect and cause lots of other components to require changes at the same time.

**Comment by OnnoVdT** [comment]
Do not use ZOWE_JAVA_HOME / ZOWE_NODE_HOME but use the common names JAVA_HOME / NODE_HOME. This to ensure that the common names are available with correct values to Zowe / extenders.

**Comment by stevenhorsman** [comment]
> Do not use ZOWE_JAVA_HOME / ZOWE_NODE_HOME but use the common names JAVA_HOME / NODE_HOME. This to ensure that the common names are available with correct values to Zowe / extenders.

To be address in #1004

**Comment by stevenhorsman** [comment]
Should be superceded by the new yaml HA work

**Comment by 1000TurquoisePogs** [comment]
Basically accomplished in the v2 way of doing things.
