### ISSUE TITLE
Migrate other builds to use LF Artifactory

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#875]
Similar to https://github.com/zowe/zowe-install-packaging/issues/874, this task is for:

- migrating all other repos to use new Artifactory
- migrate promote release repo to use new Artifactory

**Comment by jackjia-ibm** [comment]
For Zlux pipelines, seems I couldn’t create PR because the pipeline code are defined in Jenkins:

- zlux-core
- zlux-core-cupids
- zlux-core-tagged
- zlux-plugins
- zlux-plugins-tagged

If so, I think you only need to change one line of code: `ARTIFACTORY_SERVER = "gizaArtifactory"` => `ARTIFACTORY_SERVER = "zoweArtifactory"`. I created a `zlux-core-jack-test` job to try out the configuration and seems working ok. This is the zlux-core published: https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/zlux/zlux-core/1.7.1-STAGING/zlux-core-1.7.1-20191217.202400.tar. From jFrog UI, you can find the result here: https://zowe.jfrog.io/zowe/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/org/zowe/zlux/zlux-core/1.7.1-STAGING

@dmitrynikolaev @struga0258 @1000TurquoisePogs Please let me know if you need any more helps on the migration.

**Comment by MarkAckert** [comment]
All PRs for Zowe CLI and APIML look good to me.

The failing builds under some CLI branches are from audit failures unrelated to the new artifactory, so we are good to merge.

**Comment by jackjia-ibm** [comment]
All migrations are done.
