### ISSUE TITLE
Finalise Zowe user id group/names

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#877]
Currently we run ZWESVSTC as IZUSVR and under group IZUADMIN and ZSS cross memory under IZUSVR.
We need to stop hijacking zosmf and create our own ids.

Do we want the ZSS cross memory started tasks to run under a different id? Assumption of no?

What the id/group names?
I think ZWESVR and ZWEADMIN were discussed. Are these final?

In order to be more flexible we've decided to default to having separate ids for XMEM and ZWESVR, as users can choose to combine them if they wish, therefore the proposed design is:
 - ZWESVUSR for the zowe server user
 - ZWEADMIN for the group
 - ZWESIUSR for the xmem server

**Comment by OnnoVdT** [comment]
There is also the name for ZSS userid.
personally I prefer USR instead of SVR for the userid, it makes it much more obvious in sample commands what the intent is.

**Comment by stevenhorsman** [comment]
Spoke to Irek and he said that he's thinks that either using the same id, or separate should be fine, there isn't particularly strong reasons for either.

**Comment by stevenhorsman** [comment]
One issue that I thought might come up with using different user ids for the XMEM and ZWESVSTC is if shops have a RDEFINE set up for ZWE* (like ours), but this is a minor consideration

**Comment by kathysychan** [comment]
@stevenhorsman Could you please confirm what's the final decision made for OWNER and GROUP name for Zowe server and xmem server?

**Comment by stevenhorsman** [comment]
ZWESVUSR for the zowe server user
ZWEADMIN for the group
ZWEXMUSR for the xmem server

as documented in the description

**Comment by stevenhorsman** [comment]
I've been advised that we need zlc approval to make this change. @Joe-Winchester as our zlc rep would you like to bring this up at the meeting, or do you want me to add the members as reviewers?
