### ISSUE TITLE
After installing NODE.js V8.161, facing issue when issuing npm commands

### ISSUE THREAD

**Issue by Rajeckum** [zowe/zowe-install-packaging#880]
**Describe the bug**
P752660:/usr/lpp/node-v6.14.4-os390-s390x/bin: >npm --version                   
-----ã/È/%-øÊ?ÄÁËË-||(-Ñ>-ÇÁ/ø-ËÁÈÍø----CEE5207E The signal SIGABRT was received
.                                                                               
CEE5207E The signal SIGABRT was received.                                       
Ý1¨ + Done(131) npm --version                                                   
  83890521      Abort   ./npm                                                                     

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
It is working as expected in another test environment. Looks like this is environment issue. Also I noticed it works only once when I relogin and for further attempts, it is failing with CEE5207E abend as above. Please advise.

**Comment by Joe-Winchester** [comment]
Node 8.16.1 included some issues that meant Zowe didn't function as expected, so the team released 8.16.2 with fixes and have removed 8.16.1 from the download site.  
https://docs.zowe.org/stable/user-guide/install-nodejs-zos.html#how-to-obtain-ibm-sdk-for-node-js-z-os
The documentation describes that only 8.16.0 or 8.16.2 + are supported
