### ISSUE TITLE
is there a variable indicating which branch is being built?

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#888]
*Customer content*

**Is your feature request related to a problem? Please describe.**
I see that variable ZOWE_VERSION is set during the build, so the SMPE build process can pick it and mention the related pax build in the FMID/PTF. For non-main build it can be good to document which branch was used. Is there a way for the SMPE build to know this?

**Describe the solution you'd like**
Preferably an environment variable that says which branch is used during the build

**Describe alternatives you've considered**
none

**Additional context**
none

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by jackjia-ibm** [comment]
If you don't have access to the `env.BUILD_BRANCH`, the `manifest.json` includes branch name: `build.branch`.

**Comment by OnnoVdT** [comment]
thanks
