### ISSUE TITLE
push SMPE PTF build result to Artifatory

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#889]
*Customer content*

**Is your feature request related to a problem? Please describe.**
The SMPE build now creates a USERMOD, APAR, or PTF, which must end up in Artifactory so it can be pulled for testing/publication on Zowe.org.

It will be 1 zip file, but the name is not a constant, not sure if that is a problem.
Also, since you already pick up other files from the SMPE build, I think it might be good to consolidate them in a single directory, as currently the files are in directories that are specific for that type of output. Since this implies moving the pick up location for files you already pick up, we need to discuss to ensure your and my updates are done in sync to ensure the build keeps running smooth.

**Describe the solution you'd like**
pick up everything in /ZOWE/tmp/zowe-packaging-###/zowe/ship

**Describe alternatives you've considered**
none

**Additional context**
none

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by jackjia-ibm** [comment]
@OnnoVdT I may still need to know the details what you want to put into /zowe/ship folder, also categorize them into 2 categories: for-release, not-for-release.

Everything categorized as for-release, will be published along with current ZOWE convenient build, like `AZWE001.pax.Z` and `AZWE001.readme.txt`. And everything not-for-release won't be published, but will be stored in Artifactory. Is that possible you can tar all not-for-release files into one tar ball so it's easier for download/upload?

**Comment by OnnoVdT** [comment]
a for-release / not-for-release split ties into https://github.com/zowe/zowe-install-packaging/issues/890, and will require the build to know whether the FMID or the PTF needs to be released.
I'm assumign that both will end up in artifactory. If so, then with our new Github-based metadata approach (https://github.com/zowe/zowe-install-packaging/issues/891), we can trigger the correct split based upon the presence of ptf-bucket. IF not present we're doing a FMID build, and thus that is published. If ptf-bucket is present, then we're doing a PTF build and I'll place the PTF in the for-release pile.

Do I need to tar the for-release as well?

**Comment by jackjia-ibm** [comment]
For the for-release artifacts, it's up to you how you want the end-user download from our website. Either way works ok to me. I just need to know the name patterns of the for-release artifacts.

The Zowe promote/release process will need to find and copy only the files for release to the target folder: https://github.com/zowe/zowe-install-packaging/blob/master/Jenkinsfile.release#L257.

Since on zowe.org, end-user can only download one file at a time, they actually put the 2 files (.pax.Z and .readme.txt) along with sha512 hashes, signatures into one zip file.

**Comment by jackjia-ibm** [comment]
@OnnoVdT since this is marked as v1.8 milestone, could you provide more details so I can proceed? Thanks!

**Comment by OnnoVdT** [comment]
Sorry, customer issues keep pulling me away from Zowe. Note that Stephen mainly marked this as 1.8 to simplify monitoring it in Zenhub (albeit it would be good to have it by then). 
As you requested I will separate the inputs by publish and not-publish, and place them as tar-balls in <basepath>/<fmid>/ship/publish.tar and <basepath>/<fmid>/ship/no-publish.tar.
**Will Artifactory hold the individual files inside the tar-balls, or the tar-balls themselves?**
I'm also assuming that zipping up the logs directory and placing it in Artificatory remains as is.

publish.tar will hold FMID pax & readme if there is no PTF-bucket is present, it will hold the PTF otherwise.

**Comment by jackjia-ibm** [comment]
Thanks a lot @OnnoVdT. Let me know when your changes are in, I will update the pipeline.

Artifactory will keep it as-is what we upload.

**Comment by OnnoVdT** [comment]
@jackjia-ibm, I implemented it slightly different than described above. Both PTF and FMID consist of multiple files. The PTF was already zipped up, and now I zipped up the FMID files as well. Both These zips can go straight to the website, no need to extract.
I also added a placeholder for the program directory that must be picked up by the doc pipeline.

You now have 4 files with fixed names to place in artifactory:
- smpe-build-logs.pax.Z
- no-publish.zip
- publish.zip
- pd.htm

Only publish.zip goes to zowe.org.
Only no-publish.zip and publish.zip need to be restored to the original name. However, since you must know which was which, I split rename-back.sh into 2 scripts, rename-back-no-publish.sh and rename-back-publish.sh.

**Comment by OnnoVdT** [comment]
Let me know if you prefer a tarball route instead of reusing the existing rename route.

**Comment by OnnoVdT** [comment]
@jackjia-ibm 
SMPE build & post-packaging.sh complete successfully, but the build is broken until the pipeline is adjusted to pick up the new output format.

[Pax.pack] done
Connection to zzow01.zowe.marist.cloud closed.
[Pipeline] sh
[we-install-packaging_PR-930-MX7SEZFPYDBQD4P52FIK2XZFSLVRJQREBDZUK7AAUD36MQKOINBA] Running shell script

+ SSHPASS=**** sshpass -e sftp -o BatchMode=no -o StrictHostKeyChecking=no -P 22 -b - ****@zzow01.zowe.marist.cloud

sftp> get /ZOWE/tmp/zowe-packaging-20191214203732/zowe.pax ./.pax

sftp> get /ZOWE/tmp/zowe-packaging-20191214203732/zowe-smpe.pax ./.pax
File "/ZOWE/tmp/zowe-packaging-20191214203732/zowe-smpe.pax" not found.

**Comment by OnnoVdT** [comment]
SMPE build is updated to create a tar file holding the zip that needs to be published. I kicked of build #19 to drive the SMPE build and ensure there are no typos
https://wash.zowe.org:8443/job/zowe-install-packaging/view/change-requests/job/PR-930/
the build is expected to fail since the pipeline does not yet now about the new filenames that must be picked up
# files to be uploaded to artifactory:
# ${CURR_PWD}/smpe-build-logs.pax.Z
# ${CURR_PWD}/publish.tar   -> holds zip that goes to zowe.org
# ${CURR_PWD}/fmid.zip
# ${CURR_PWD}/ptf.zip
# ${CURR_PWD}/pd.htm        -> can be a null file
the script to rename the zip files back to their original name is also in place
${CURR_PWD}/rename-back.sh

**Comment by jackjia-ibm** [comment]
@OnnoVdT I renamed publish.tar to zowe-smpe.tar. It should be better explain what the file is for. Hope it's ok.

https://github.com/zowe/zowe-install-test/issues/135 is created to use the new file format.

**Comment by OnnoVdT** [comment]
no problem for me, I just pulled that name out of mi hat.
