### ISSUE TITLE
conditional push of SMPE artifacts to Zowe.org

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#890]
*Customer content*

**Is your feature request related to a problem? Please describe.**
The SMPE build always builds a FMID and PTF that matches the current convenience build. However, we should not publish both on Zowe.org.
Wile in alpha/beta stage both can be published, but once the FMID GA's, then the FMID on Zowe.org no longer changes, and initially there is no PTF. With the first convenience build that follows, only the PTF is added to Zowe.org, the FMID remains. On the 2nd convenience build, the PTF that is on Zowe.org moves to 'old builds' page, and the new PTF goes to the main download page. This process will repeat until we stop building this branch of Zowe.

If we cannot put the publication logic after the build steps, then I will have to do a rewrite of the SMPE build, which I rather avoid.

**Describe the solution you'd like**
work out logic to not publish PTF when publishing FMID, and after that, no longer replace the published FMID but only publish PTF. 
Alpha/Beta programs can be an exception if that is easier, but I have no problem with a fixed beta FMID plus a more recent beta PTF.

**Describe alternatives you've considered**
update SMPE build to ensure only the desired output is created isntead of all

**Additional context**
none

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by jackjia-ibm** [comment]
@nannanli This task may need some helps from your side.

**Comment by OnnoVdT** [comment]
As mentioned in issue https://github.com/zowe/zowe-install-packaging/issues/889, with the new scheme for maintaining metadata, the build process has a way of identifying whether it is doing an FMID or PTF build, making this issue obsolete.
