### ISSUE TITLE
process to manually update SMPE logss zip in Artifactory

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#891]
*Customer content*

**Is your feature request related to a problem? Please describe.**
To fully automate the build process, the SMPE build relies on PTF numbers to be present in the logs.zip that is restored (from Artifactory) at the beginning of a build. This means that Nayer must be able to prime the logs.zip so it can be used during the next build.

To be self-documenting, I'm also adding here what is already in place
1. At beginning of a build, the logs.zip of the previous build of this branch is pulled from Artifactory, if any.
2. This zip is extracted to the location the SMPE build expects the logs dir, giving the SMPE build access to the data within.
3. The SMPE build process updates the logs directory during the build.
4. At the end of the build, the logs directory is zipped up and placed in Artifactory, together with other build artifacts that must be kept.

**Describe the solution you'd like**
1. Nayer needs a way to know which Artifactory entry to access (last official build)
2. Nayer must be able to copy the logs.zip from Artifactory to her desktop (not sure if this can be automated)
3. Nayer then extracts the zip locally, updates the PTF bucket file with new PTF numbers, and zips up the updated directory
4. Nayer pushes the updated zip back to Artifactory so that the next build can pick up the updated zip and act accordingly.

Note since we work with bucket files, these updates can be sporadic, as the SMP/E build process will know how to go through the bucket to find the correct entry.

Others will need to be able to do the same for testing and emergency APAR build

**Describe alternatives you've considered**
none

**Additional context**
none

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by jackjia-ibm** [comment]
@OnnoVdT This task concerns me. I think everything we put into release should come from GitHub, not manually updating a file on the Artifactory. There is no good way to track the changes on the Artifactory. This may also raise concerns from license point of view.

**Comment by OnnoVdT** [comment]
Jack and I discussed this, and came up with a solution that relies on the meta-data being stored in GitHub instead of logs.zip. This new process renders this issue obsolete. A new issue, https://github.com/zowe/zowe-install-packaging/issues/901, has been created.
