### ISSUE TITLE
update promote process to call script that manages PTF data

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#901]
*Customer content*

**Is your feature request related to a problem? Please describe.**

_Once the script of https://github.com/zowe/zowe-install-packaging/issues/900 is ready, the promote process must be updated to call it, passing in the name of the PTF file being promoted. When the script is done, smpe/bld/service/* will be updated, and this update must be committed so that the next SMPE build knows about the promote._

**Describe the solution you'd like**

After an RC build is vetted, it is promoted to be the official build. The promote process will be updated to invoke a script that updates the data in smpe/bld/service and then commits this to Github as starting point for the next build:
-    smpe/bld/service/ptf-bucket.txt : comment out the line holding the PTF that is being promoted
-    smpe/bld/service/current-apar.txt : remove if present (list of additional APARs)
-    smpe/bld/service/current-hold-*.txt : remove if present (additional hold info)
-    smpe/bld/service/promoted-apar.txt : add promoted APARs to list
-    smpe/bld/service/promoted-close.txt : add formatted closing info of this PTF
-    smpe/bld/service/promoted-hold.txt : add formatted ++HOLD info of this PTF
-    smpe/bld/service/promoted-apar.txt : add promoted PTFs to list

[Zowe PTF data management.docx](https://github.com/zowe/zowe-install-packaging/files/3928557/Zowe.PTF.data.management.docx)

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by OnnoVdT** [comment]
The script, smpe/bld/smpe-promote.sh is now available via pull request https://github.com/zowe/zowe-install-packaging/pull/946, so this task can continue.

**Comment by jackjia-ibm** [comment]
I believe this work is done and had been fully automated. Please re-open otherwise.
