### ISSUE TITLE
install-SMPE-PAX.sh fails to clean up dataset if using PREFIX=ZOE as default values when rerun the installation

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zowe-install-packaging#902]
Hi @John-A-Davies, 
cc @kathy-ca
When calling install-SMPE-PAX.sh using the default parameter values(like, PREFIX=ZOE.ZOWE), the installation is ok, the script generates the data set name like: ZOE.ZOWE.ZOWE.AZWE001.F1234 by default. But when running second time, installation will fail as complaining data set exists because there is no cleanup in the script to delete ZOE.ZOWE.ZOWE.AZWE001.F1234...

So to fix that, either use PREFIX=ZOE when calling install-SMPE-PAX.sh, or modify the install-SMPE-PAX.sh to cleanup DS by prefix
from
wrap_call tsocmd delete “‘${hlq}.ZOWE.${FMID}.Fx’”
to
wrap_call tsocmd delete “‘${PREFIX}.ZOWE.${FMID}.Fx’”

Please take a look the install script to keep consistent as the script suggests.

**Comment by John-A-Davies** [comment]
The `(un)install-SMPE-PAX.sh` scripts are in `zowe-install-test`.  I've created a PR with the fixes in https://github.com/zowe/zowe-install-test/pull/131.  

For future reference:
The DSN of the RELFILES is of the form
`${PREFIX}.ZOWE.${FMID}.Fn`
so you should have coded PREFIX (the 9th parameter) to be `ZOE`, not `ZOE.ZOWE` for the old script to work.

You can now choose any value for PREFIX and the script will cater for it.

**Comment by raymondyanli** [comment]
I will give it a try soon. thanks

**Comment by John-A-Davies** [comment]
@raymondyanli  Do you plan to try this at some point?

**Comment by raymondyanli** [comment]
@John-A-Davies 
The current SMPE install is using "ZOE" as PREFIX, it works ok. Thanks.
