### ISSUE TITLE
zowe-check-prereqs.sh - RACF assumption

### ISSUE THREAD

**Issue by gatogatogato** [zowe/zowe-install-packaging#903]
**Describe the bug**
zowe-check-prereqs.sh assumes that it runs on a RACF system.
E.g. 
```
"Check user has the basic auth to list the resources"
"Error: Unexpected response to RACF LISTUSER command"
```
 makes no sense on ACF2 systems

**To Reproduce**
Run zowe-check-prereqs.sh

**Expected behavior**
SAF resource check must work with ACF2 too or skip tests if RACF is not avalable.

**Comment by Joe-Winchester** [comment]
Tks @gatogatogato for reporting this.   The zowe-check-prereqs script was created early 2019 when Zowe was first released and we haven't kept it up to date.  We are planning to remove it and provide the same function in a different way and I have created Epic https://github.com/zowe/zowe-install-packaging/issues/923 to track the design and implementation of this, so what I'll do is assign of all your check-preqs issues as children of this so we can work on them together.

As a design question, if we provide an automated way to check the system pre-reqs, would you prefer a shell script (as we currently provide) or a JCL member ?  The latter would be easier for experienced sysprogs to edit, comment out, customize for their shop, ...    I'm thinking this would be a better approach but wanted to see if others (like you) agree.

**Comment by gatogatogato** [comment]
@Joe-Winchester Thank you for picking this up.
Regarding the design issue: personally I don't mind working in USS ans using shell scripts, I guess it all depends on the person installing ZOWE and their preferences. Classic JCL will surely find more acceptance among traditional mainframers.

**Comment by stevenhorsman** [comment]
@gatogatogato - Since 1.8 the users and groups that are associated with the zowe server have changed, and we've streamlined the zowe-check-prereqs.sh to remove some of the code that caused issue, so from 1.9 dev build onwards this issue won't happen. If any SAF checks get added in future they should support ACF2 and TSS as well as RACF
