### ISSUE TITLE
zowe-check-prereqs.sh - SDSF assumption

### ISSUE THREAD

**Issue by gatogatogato** [zowe/zowe-install-packaging#904]
**Describe the bug**
zowe-check-prereqs.sh assumes that it runs on a system with SDSF available.
E.g. 
```
"Check z/OSMF servers are up" 
```
wrongly states "Error: Job IZUANG1 is not executing"

**To Reproduce**
Run zowe-check-prereqs.sh

**Expected behavior**
Active tasks must be found with other methods than SDSF.

**Comment by stevenhorsman** [comment]
@gatogatogato - The check of z/OSMF has updated in 1.9 dev build, so you shouldn't see this anymore. There is still a ICFS check that requires opercmd (and in turn SDSF), but your issue #905 coverd this.
