### ISSUE TITLE
zowe-1.7.0/install/../scripts/opercmd - SDSF assumption

### ISSUE THREAD

**Issue by gatogatogato** [zowe/zowe-install-packaging#905]
**Describe the bug**
REXX opercmd assumes that it runs on a system with SDSF available.
Output is 
```
16 +++ rc=isfcalls('ON')
```
 --> isfcalls probably requires SDSF which we don't have

**To Reproduce**
Run zowe-check-prereqs.sh

**Comment by stevenhorsman** [comment]
Related to #1026

**Comment by MarkAckert** [comment]
Closing - will track in other issues.
