### ISSUE TITLE
zowe-verify.sh - returns empty version of z/OS

### ISSUE THREAD

**Issue by gatogatogato** [zowe/zowe-install-packaging#906]
**Describe the bug**
At one point zowe-verify.sh checks for the active z/OS version but returns an empy string on our system.

**To Reproduce**
Run zowe-verify.sh

**Expected behavior**
Get correct z/OS version

**Comment by stevenhorsman** [comment]
Hi @gatogatogato as of 1.8 documentation state that zowe-verify is deprecated and out of date and from 1.9 it will be removed, so closing this issue.
