### ISSUE TITLE
zowe-verify.sh - "Check SAF security settings are correct" on ACF2 systems

### ISSUE THREAD

**Issue by gatogatogato** [zowe/zowe-install-packaging#907]
**Describe the bug**
At one point zowe-verify.sh executes "Check SAF security settings are correct" but gets no or wrong results.

**To Reproduce**
Run zowe-verify.sh

**Expected behavior**
Check SAF security settings correctly on ACF2 systems.

**Comment by stevenhorsman** [comment]
Hi @gatogatogato as of 1.8 documentation state that zowe-verify is deprecated and out of date and from 1.9 it will be removed, so closing this issue.
