### ISSUE TITLE
zowe-verify.sh - "Check servers are up" on non-SDSF systems

### ISSUE THREAD

**Issue by gatogatogato** [zowe/zowe-install-packaging#908]
**Describe the bug**
At one point zowe-verify.sh executes "Check servers are up" but returns wrong results on non-SDSF systems

**To Reproduce**
Run zowe-verify.sh

**Expected behavior**
Check active servers with other methods than SDSF.

**Comment by jimmschlo89** [comment]
I'm not a Zowe developer or anything but our shop uses JES3. I had to modify the script to get it to work properly. Specifically for z/OSMF: `run zowe-verify.sh` looks for "S.izusvr.." (screen scraping) but in our JES3 environment, it should have been looking for "JOB(#########)". Hope that helps!

**Comment by stevenhorsman** [comment]
Hi @gatogatogato as of 1.8 documentation state that zowe-verify is deprecated and out of date and from 1.9 it will be removed, so closing this issue.
