### ISSUE TITLE
zowe-verify.sh - Checks wrong installation path of z/OSMF

### ISSUE THREAD

**Issue by gatogatogato** [zowe/zowe-install-packaging#909]
**Describe the bug**
At one point zowe-verify.sh checks for the installation path of z/OSMF ("Check zosmfServer is ready to run a smarter planet") but checks in wrong directory (Outdated: /var/zosmf/data/ instead of now recommended by IBM: /global/zosmf/data)

**To Reproduce**
Run zowe-verify.sh

**Expected behavior**
Multiple locations must be checked.

**Comment by bohns** [comment]
In z/OS 2.4, message logging is still done (by default) in /var/zosmf/data/logs/zosmfServer/logs/messages.log. Not in /global/zosmf/data.

However... z/OSMF 2.4 does not appear to write the "CWWKF0011I: The server zosmfServer is ready to run a smarter planet." to messages.log. This message only appears in the STC job log.

zowe-verify.sh incorrectly fails the validation check:
_Check zosmfServer is ready to run a smarter planet
Error: zosmfServer is not ready to run a smarter planet_

**Comment by stevenhorsman** [comment]
Hi @gatogatogato as of 1.8 documentation state that zowe-verify is deprecated and out of date and from 1.9 it will be removed, so closing this issue.
