### ISSUE TITLE
Convenience script to move X-MEM PROCLIB and LOADLIB

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#914]
Create a /scripts/utils/zowe-install-xmem.sh that can be used to copy the cross memory proclib and the load library from the install directory PCD members to execution PDS members

`zowe-install-xmem.sh {prefix}.SZWE auto` which copies from {prefix}.SZWE.SZWESAMP(ZWEXMSTC) to the JES contacentation path keeping the name ZWEXMSTC.  

`zowe-install-xmem.sh {prefix}.SZWE HLQ.PDS.ZWEPROC HLQ.PDS.ZWEAUTH` which copies from arg1 {prefix}.SZWE.SAMPLIB(ZWEXMSTC) into arg2 HLQ.PDS.ZWEPROC(ZWEXMSTC) for the JCL proclib, and also which copies from arg1 {prefix}.SZWE.SZWEAUTH into arg2 HLQ.PDS.ZWEAUTH(ZWESIS01) as well as HLQ.PDS.ZWEAUTH(ZWESAUX).

For the doc create a new section Scripted Zowe install that will describe this. This is part of a separate story.

**Comment by John-A-Davies** [comment]
As described in #864,
AUTHLIB  member names are
`ZWESAUX`
`ZWESIS01`

PARMLIB  member names are
`ZWESIP00`  for ZWESIS01

PROCLIB  member names are
`ZWESASTC` for ZWESAUX
`ZWESISTC`   for ZWESIS01

**Comment by John-A-Davies** [comment]
Script `zowe-install-xmem.sh` copies the xmem members, which is part of what `zowe-install-apf-server.sh` used to do.  But `zowe-install-apf-server.sh`  also edits the xmem members to insert the LOADLIB and PARMLIB names when in obtains them from the zss pax file.  For the purposes of the `zowe-install-test` stream,  `zowe-install-xmem.sh` needs to perform the same edit, at least in the interim.

**Comment by John-A-Davies** [comment]
The PROC JCL for ZWESISTC also needs its PARMLIB member ZWESIP00 so the script copies that too.
