### ISSUE TITLE
XMEM_PROFILE name is not set properly

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#941]
**Describe the bug**

The XMEM_PROFILE is set to a value of `{XMEM_ELEMENT_ID}.IS`, which caused errors during installing cross memory server.

Related logs:

```
00:44:40 ************************ Install step 'Security profile' start *****************
00:44:40 Check if profile {XMEM_ELEMENT_ID}.IS is defined in class FACILITY (SAF=RACF)
00:44:40 Error: SEARCH failed with the following errors
00:44:40 ICH31013I  INVALID LEADING CHARACTER IN FILTER STRING
00:44:40 SEARCH CLASS(FACILITY) FILTER({XMEM_ELEMENT_ID}.IS)
```

```
00:44:40 Security profile - Error
00:44:40 Please correct errors and re-run the following scripts:
00:44:40 sh /ZOWE/staging/usr/lpp/zowe/xmem-server/scripts/zowe-xmem-check-profile.sh RACF FACILITY {XMEM_ELEMENT_ID}.IS IZUSVR
00:44:40 sh /ZOWE/staging/usr/lpp/zowe/xmem-server/scripts/zowe-xmem-define-xmem-profile.sh RACF {XMEM_ELEMENT_ID}.IS ZOWEAD3
```

**To Reproduce**

1. run `zowe-install-apf-server.sh`

**Expected behavior**

Expected logs are:

```
************************ Install step 'Security profile' start *****************
Check if profile ZWES.IS is defined in class FACILITY (SAF=RACF)
Warning: profile ZWES.IS is not defined in class FACILITY
Define cross-memory server profile ZWES.IS (SAF=RACF)
Info:  profile has been defined
************************ Install step 'Security profile' end *******************
```

```
Security profile - Ok
```

**Additional context**

Related line of code: https://github.com/zowe/zowe-install-packaging/blob/staging/install/zowe-install-apf-server.sh#L32

zowe-install-test may need to delete the security profile during uninstallation. On marist server, even though `zowe-install-apf-server.sh` failed on `Security profile` step, cross memory server and Zowe are still started ok without error.

@kathysychan @NayerNajafi

**Comment by ifakhrutdinov** [comment]
This seems to have been introduced in https://github.com/zowe/zowe-install-packaging/commit/25b896062a2061b96c08f9ed966f81c01169f432#diff-dcccde91fb320cb4262b5069a603d3d4

**Comment by ifakhrutdinov** [comment]
@jackjia-ibm did the pull request resolve the issue?

**Comment by jackjia-ibm** [comment]
@ifakhrutdinov thanks for checking. The issue was first reported by another IBM team, I will check after they are back from holiday. I can not reproduce on the Marist server.

**Comment by John-A-Davies** [comment]
Looks OK now in `staging` from today's build:
https://wash.zowe.org:8443/job/zowe-install-test/job/staging/618/consoleFull
```
10:39:22 Check if profile ZWES.IS is defined in class FACILITY (SAF=RACF)
10:39:22 Info: profile ZWES.IS is defined in class FACILITY
```
```
10:39:22 Security profile - Ok
```

**Comment by jackjia-ibm** [comment]
Checked with Kathy and latest build fixed the issue.
