### ISSUE TITLE
Have the ability to run tests against all supported node environments

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#955]
Currently we support Node v6 and v8 and we are likely to add v12 in the future. As it stands our pipeline just tests against a version of v8, so it would be good to add tests for all supported node versions.

**Comment by jackjia-ibm** [comment]
@stevenhorsman do you think this change is good enough?

**Comment by stevenhorsman** [comment]
Yep - I think that it would be good to have testing of the latest of each supported version (ie 6,8,12) happen as part of the nightly, but that can wait until your ansible changes are in and is outside the scope of this issue
