### ISSUE TITLE
Create a default install log location and allow users to override this

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#956]
We currently have a few different scripts that each log during running:
- install, certificate setup, proclib copying...
these each write logs in a slightly different place (or different files in the home directory), making management annoying.

The logs folder instanceDir for ‘runtime’ logs, but we need to work out where that default unified install logs would be. One option is ~/zowe/logs, but a complication might be that different users run different bits, so maybe we should try /global/zowe/logs for install logs and fall back to the home directory  if we don’t have permissions.

For the pipeline (at least) adding a -l (lowercase L) parameter specifying the log directory for each step might be the best solution.

*Current proposal*
```
If a -l parameter is supplied to the script:
  LOG_DIR = -l parm
else:
  if /global/zowe/logs is writable:
     LOG_DIR = /global/zowe/logs
  else:
       LOG_DIR = ~/zowe/logs
if LOG_DIR not writable (ie -l parameter, or ~/zowe/logs doesn't have permission):
   echo an error explaining and directing the user to supply -l to a writable directory
   exit with non-zero code
```

- In all the scripts we should ensure that we echo out the log file created so that users can find it and any pipeline automation can as well

- Now zowe-support should take an optional -l parameter and do the same ordering to try and find the install logs and include them in the pax if possible

**Comment by 1000TurquoisePogs** [comment]
Completed in v2, there is a logsDirectory.
