### ISSUE TITLE
Ship runJob utility with Zowe build to help consumers to automate Zowe installation

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#977]
*Customer content*

**Is your feature request related to a problem? Please describe.**

Some consumers of Zowe doesn't have existing way to submit a job from JCL file. After we ship `ZWESECUR`, they will need a way to submit this job after install Zowe.

**Describe the solution you'd like**

Ship `runJob` defined in `zowe-install-test` https://github.com/zowe/zowe-install-test/blob/master/scripts/install-SMPE-PAX.sh#L142 as a shell script utility in `scripts/utils` folder.

@John-A-Davies @kathysychan

**Comment by MarkAckert** [comment]
Closing. We can run jobs from USS, and with Sean's recent PR more of the installation and configuration can be run through JCL in MVS datasets.
