### ISSUE TITLE
ZWESECUR started task names

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#978]
**Describe the bug**

There seems to be a misunderstanding about the started task names, resulting in incorrect default names in ZWESECUR.

Our SMPE packaging requires that all member names start with ZWE, and does not allow for duplicate part names. The Zowe server currently uses ZOWESVR as name, and thus does not meet rule 1, and the ZSS servers have the same name as the load module they run (ZWESIS01 and ZWESAUX), breaking rule 2.

So we are shipping the sample started task members with a different name:
ZWESVSTC
ZWESISTC
ZWESASTC

However. these member names are not ideal as actual started task names. 
* Unless explicitly told otherwise, ZSS assumes that ZSS AUX started task is named ZWESAUX, 
* For started tasks running USS processes, it's best to stick to names with 7 chars or less, as USS will slap on an additional digit for child-processes.
* server names now have a suffix that indicates what is running in the server (ZOWE_PREFIX + ZOWE_INSTANCE + type)

So during the config step where the sample started task JCL is copied from SAMPLIB to a customizable dataset, we (should) do a rename, especially for the ZWESAUX case.

ZWESECUR must follow whatever default names we use during this copy process, so that customer who use defaults don't need to update much.

**To Reproduce**

review files/jcl/ZWESECUR.jcl and the config copy script (not sure which one this is right now)

**Expected behavior**

ZWESECUR must follow whatever default names we use during the customization copy process.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Joe-Winchester** [comment]
@OnnoVdT - I'm wary to start changing names now as have gone back and forth, and the last time we did the forth (i.e. went back from ZWEXM to ZWESI it affected quite a lot of files, pipeline, doc, ...   

```
Unless explicitly told otherwise, ZSS assumes that ZSS AUX started task is named ZWESAUX,
```
I wasn't aware of this - is there an extra step that we need to do for ZSS to let it know that the Aux STC  is called ZWESASTC ?  Is this in the ZSS doc ?   

```
For started tasks running USS processes, it's best to stick to names with 7 chars or less, as USS will slap on an additional digit for child-processes.
server names now have a suffix that indicates what is running in the server (ZOWE_PREFIX + ZOWE_INSTANCE + type)
```
The address spaces are named based on each instance, so even if the PROCLIB is called ZWESVSTC then the address space names are chosen from the `ZOWE_PREFIX`, `ZOWE_INSTANCE` pair appended to with the address space IDs as described in https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#configuration-variables   Address Space Names.

**Comment by OnnoVdT** [comment]
Joe,
For your started task comment, it doesn't work that way. The name in PROCLIB MUST match the name you give on the start command, or JES will not be able to find it. This will also be the name you see in SDSF. (There are ways to fiddle with the name you see in SDSF, but that is making life difficult, so it should not be our default option.) The same is true for the RACF definition, The STARTED class in RACF MUST have a profile (can have wildcards) that matches the started task name, so RACF knows what userid to assign to the task (and by extension, which permits the task has).

For ZWESAUX, I do not know the name of the option or where it is documented, I just know Irek told me it exists (https://github.com/zowe/zss/issues/94#issuecomment-554288711).

**Comment by OnnoVdT** [comment]
@Joe-Winchester 
I now recall that Zowe server will run a script (run-zowe?) that will start the different servers as child tasks, using an environment variable to set their name. Since these are child processes, not individual started tasks, the PROCLIB rules do not apply to them. Similar for the RACF rules, the child processes automatically inherit the userid (and permits) from the parent.

The doc link you provided does mention that the main server is PREFIX+INSTANCE+SV. I'm assuming this is the name used on the START command (and thus must match PROCLIB and RACF definitions). That means that during the copy from SZWESAMP to elsewhere we must rename ZWESVSTC to ZWE1SV (to get the PROCLIB match) and use SET  ZOWESTC=ZWE1SV in ZWESECUR.

Similar, it documents name ZWE1SZ as default name for ZSS server, so copy and ZWESECUR should follow suit.

**Comment by John-A-Davies** [comment]
In `bin/zowe-start.sh`, Zowe is started like this
```
S \${ZOWE_SERVER_PROCLIB_MEMBER},INSTANCE=...,JOBNAME=\${ZOWE_PREFIX}\${ZOWE_INSTANCE}SV
```
and ZWESECUR defines the user and group that these jobs will use
```
//         SET  ZOWESTC=ZWESVSTC     * Zowe started task name
//         SET  XMEMSTC=ZWESISTC     * xmem started task name
//         SET   AUXSTC=ZWESASTC     * xmem AUX started task name
...
/* started task for ZOWE, main server                                */
  RLIST   STARTED &ZOWESTC..* ALL STDATA
  RDEFINE STARTED &ZOWESTC..* -
   STDATA(USER(&ZOWEUSER.) GROUP(&STCGROUP.) TRUSTED(NO)) -
   DATA('ZOWE MAIN SERVER')

/* started task for ZSS, cross memory server                         */
  RLIST   STARTED &ZSSSTC..* ALL STDATA
  RDEFINE STARTED &ZSSSTC..* -
   STDATA(USER(&ZSSUSER.) GROUP(&STCGROUP.) TRUSTED(NO)) -
   DATA('ZOWE ZSS CROSS MEMORY SERVER')

/* started task for ZSS auxilary cross memory server                 */
  RLIST   STARTED &AUXSTC..* ALL STDATA
  RDEFINE STARTED &AUXSTC..* -
   STDATA(USER(&AUXUSER.) GROUP(&STCGROUP.) TRUSTED(NO)) -
   DATA('ZOWE ZSS AUX CROSS MEMORY SERVER')
```
The STARTED profiles defined above will match the PROC name (because they're all coded as `procname.*`) not the jobname.  So the zowe server, xmem server and aux server will be assigned the USER and GROUP from the respective RDEFINEs.  

Tasks spawned by each job will inherit the jobname, USER and GROUP of the parent job.

Therefore I think that the values SET in the `SET keyword=value` JCL statements above are correct and we don't need to rename any of these PROCs.

**Comment by John-A-Davies** [comment]
@OnnoVdT is this waiting for you to test the AUX serve?

**Comment by OnnoVdT** [comment]
yes,
now that 1.8 is out I can install that one and get my head around what is really going on with the started tasks.

**Comment by OnnoVdT** [comment]
Closing this one. Opened 
https://github.com/zowe/zowe-install-packaging/issues/1137
to address the problem area.
