### ISSUE TITLE
Update ZWESECUR with TSS commands

### ISSUE THREAD

**Issue by vit-tomica** [zowe/zowe-install-packaging#980]
**Describe the bug**

Update ZWESECUR job with TSS commands so that the ZWESECUR job can create necessary security environment and permission for Zowe runtime. 
Make sure that Zowe runs fine under the created security environment.

**Comment by OnnoVdT** [comment]
ZWESECUR is being updated to include dataset protection, see PR https://github.com/zowe/zowe-install-packaging/pull/993

**Comment by OnnoVdT** [comment]
ZWENOSEC is created to undo security setup, see PR https://github.com/zowe/zowe-install-packaging/pull/994

**Comment by Joe-Winchester** [comment]
@vit-tomica - the two PRs are merged so does that mean this issue can be closed ?
