### ISSUE TITLE
Add keystore directory validation into run-zowe.sh

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#988]
With the change in processing a few people have struggled with not create the keystoredirectory upfront. As all components require this we should validate it at the start of run-zowe.sh along with java and node, rather than leave components to check it.
If it fails we could add direction to make sure they haven't missed the step.

**Comment by Joe-Winchester** [comment]
run-zowe.sh validation will appear in STDERR for the job,  what do you think in addition about validation in zowe-start.sh also which could be echo'd back to the user starting zowe in their unix shell (although that would still be under the starting user's ID and not the STC's ID) ?
