### ISSUE TITLE
Scripts in install folder not have .sh suffix

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#99]
The /scripts in the install folder contain files that are not meant to be run from that location, but instead are copied (and sed replaced with variables) into the runtime location.  To avoid confusion over which .sh can be run and which are template files, perhaps they should be renamed to not have the file suffix .zowe or something else (.template).

**Comment by MarkAckert** [comment]
@Joe-Winchester Does this still apply? I'm not sure which files you're referencing here exactly; we may have cleaned up the directory structure since this was opened.
